<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE,chrome=1" />
    <title>好看的连续剧-最新连续剧-经典连续剧--影视部落</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
<link rel="bookmark" href="favicon.ico" />
<link rel="icon" type="image/x-icon" href="favicon.ico" />
<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
<link href="/template/hc128www/css/home.css" rel="stylesheet" type="text/css" />
<link href="/template/hc128www/css/head.css" rel="stylesheet" type="text/css" />
<script>var SitePath='/',SiteAid='12',SiteTid='',SiteId='';</script>
<script src="/js/jquery.js" type="text/javascript" language="javascript"></script>
<script src="/js/jq/jquery.lazyload.js" type="text/javascript" language="javascript"></script>
<script src="/js/jq/jquery.autocomplete.js" type="text/javascript" language="javascript"></script>
<script src="/template/hc128www/js/home.js" type="text/javascript" language="javascript"></script>
<script src="/template/hc128www/js/Aknew.js" type="text/javascript" language="javascript"></script>
<script>
//var t;
//var urlj = location.search; 
//var urlnow = (location.pathname);
//document.write("m."+urlnow+urlj);
//var ua = navigator.userAgent.toLowerCase();
//var ua = navigator.userAgent.toLowerCase().match(/(ipod|iphone|android|coolpad|mmp|smartphone|midp|wap|xoom|symbian|j2me|blackberry|wince)/i) != null; 
//if(ua)
{
	//t=setTimeout("gomyurl()",1);
}
//function gomyurl()
{
	//clearTimeout(t);
	//location.href="/mmm"+urlnow+urlj;
}
//这个/ss/存手机端的页面，比如电脑是 www.xxx.com/55/1.html?s=1 那么会跳转到 www.xxx.com/SS/55/1.html?s=1
</script>
<link href="/template/hc128www/css/type.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="site_head">
    <div class="head_inner">
        <div class="site_logo"> <a href="http://www.maccms.com" title="影视部落" class="link_logo"><strong class="hidden">影视部落</strong></a>
        </div>
        <div class="mod_ad_head">
		<script language="JavaScript" type="text/javascript">
tips = new Array(9);
tips[0] = '<a href="" target="_blank"><img src="/template/hc128www/images/ads/1.gif" border="0" /></a>';
tips[1] = '<a href="" target="_blank"><img src="/template/hc128www/images/ads/2.gif" border="0" /></a>';
tips[2] = '<a href="" target="_blank"><img src="/template/hc128www/images/ads/3.gif" border="0" /></a>';
tips[3] = '<a href="" target="_blank"><img src="/template/hc128www/images/ads/4.gif" border="0" /></a>';
tips[4] = '<a href="" target="_blank"><img src="/template/hc128www/images/ads/5.gif" border="0" /></a>';
tips[5] = '<a href="" target="_blank"><img src="/template/hc128www/images/ads/6.gif" border="0" /></a>';
tips[6] = '<a href="" target="_blank"><img src="/template/hc128www/images/ads/7.gif" border="0" /></a>';
tips[7] = '<a href="" target="_blank"><img src="/template/hc128www/images/ads/8.gif" border="0" /></a>';
tips[8] = '<a href="" target="_blank"><img src="/template/hc128www/images/ads/9.gif" border="0" /></a>';
tips[9] = '<a href="" target="_blank"><img src="/template/hc128www/images/ads/10.gif" border="0" /></a>';
index = Math.floor(Math.random() * tips.length);
document.write(tips[index]);
</script>
        </div>
        <div class="mod_search">         
		    <form id="search_form" name="search_form" method="post" action="">
                <div class="search_inner"> <i class="ico_search"></i>
                    <label>
                        <input class="search_ipt" name="key" type="text" id="key" onBlur="if(this.value==''){this.value='请输入关键词';this.style.color='#aaa'};" onFocus="if(this.value=='请输入关键词'){this.value='';this.style.color='#aaa'};" value="请输入关键词"
                        style="color: rgb(170, 170, 170);" />
                    </label>
                    <label>
                        <select name="seachid" id="seachid" class="myselect f14">
						    <option value="kan">站内</option>
							<option value="baidu">百度</option>
							<option value="haosou">好搜</option>
                        </select>
                    </label>
                    <label>
                        <input class="search_btn" type="button" name="button" id="button" value="" onClick="subs();" /><span class="hidden">搜索</span>
                    </label>
                </div>
            </form>
        </div>
        <div class="mod_quick">
            <div class="quick_item">
                <a class="quick_history" href="#" id="history"> <i class="ico_history_26"></i>  <span class="quick_txt">看过</span>  <i class="divide"></i> 
                </a>
            </div>
            <div class="quick_item">
                <a class="quick_attention" href="javascript:MAC.Fav(MAC.Url,MAC.Title)"> <i class="ico_collect_26"></i>  <span class="quick_txt">关注</span>  <i class="divide"></i> 
                </a>
            </div>
            <div class="quick_item">
                <a class="quick_attention" href="/index.php?m=gbook-show.html"> <i class="ico_upload_26"></i>  <span class="quick_txt">留言</span>  <i class="divide"></i> 
                </a>
            </div>
            <div class="quick_item">
                <a class="quick_attention" href="javascript:void(0)" id="login">
                    <img  class="yj" src="http://imgcache.qq.com/tencentvideo_v1/vstyle/web/v3/style/images/default_avatar.png" alt="登陆" />
                </a>
            </div>
        </div>
    </div>
    <div class="site_navigation">
        <div class="navigation_main">
            <div class="navigation_top"></div>
            <div class="navigation_inner">
                <ul class="navigation_area">
                    </li>
					
                    <li class="list_item"> <a href="/?m=vod-type-id-1.html" class="link_nav"><span class="link_inner ft">电影</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-29931.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900957.jpg" alt="刺客信条" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29931.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">刺客信条</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29930.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900956.jpg" alt="五一小长假看什么 4部国产电影随你怎么选" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29930.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">五一小长假看什么</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29929.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900955.jpg" alt="《我的爸爸是国王》主题曲MV 开启冒险之旅" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29929.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">《我的爸爸是国王</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29928.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900954.jpg" alt="剧透师全家第三十九期：三分钟全息剧透《小姐》" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29928.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">剧透师全家第三十</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29927.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900953.jpg" alt="《电影恋爱学》第六十七期 《速度与激情》众帅哥撩妹技术哪家强" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29927.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">《电影恋爱学》第</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29926.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900952.jpg" alt="抗日奇侠速激8 全是光头顶呱呱" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29926.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">抗日奇侠速激8 </span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29925.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900951.jpg" alt="《微缩电影》第八期：《嫌疑人X的献身》" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29925.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">《微缩电影》第八</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29924.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149509009119.jpg" alt="剧透师全家第三十八期：三分钟全息剧透《伊甸湖》" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29924.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">剧透师全家第三十</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29923.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149509009118.jpg" alt="《越狱》第五季回归了，米帅再一次逃出监狱" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29923.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">《越狱》第五季回</span></a>
                                </li>
								
								</ul>
                        </div>
                    </li>
					
                    <li class="list_item"> <a href="/?m=vod-type-id-2.html" class="link_nav"><span class="link_inner ft">连续剧</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-29952.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900959.jpg" alt="人民的名义" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29952.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">人民的名义</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-7150.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950813849.jpg" alt="穿越火线" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-7150.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">穿越火线</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-6746.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950812523.jpg" alt="华丽一族" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-6746.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">华丽一族</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-317.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950872550.jpg" alt="神机妙算刘伯温" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-317.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">神机妙算刘伯温</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-7596.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950815361.jpg" alt="我可能不会爱你" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-7596.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">我可能不会爱你</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-5016.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950806962.jpg" alt="同窗那些事儿" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-5016.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">同窗那些事儿</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-5012.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508069217.jpg" alt="御姐归来" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-5012.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">御姐归来</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-42.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950898510.jpg" alt="苦咖啡" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-42.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">苦咖啡</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-4993.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508068719.jpg" alt="择天记 未删减版" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4993.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">择天记 未删减版</span></a>
                                </li>
								
								</ul>
                        </div>
                    </li>
					
                    <li class="list_item"> <a href="/?m=vod-type-id-3.html" class="link_nav"><span class="link_inner ft">综艺</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-4443.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/201705181495080345.jpg" alt="今晚80后脱口秀 2017" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4443.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">今晚80后脱口秀</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-4488.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/201705181495079702.jpg" alt="欢乐喜剧人 第三季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4488.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">欢乐喜剧人 第三</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29953.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900958.jpg" alt="新娱乐在线 2017 5月" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29953.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">新娱乐在线 20</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-25696.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950879389.jpg" alt="超人访问团 第一季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-25696.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">超人访问团 第一</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-25697.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508793810.jpg" alt="韩伴FUN 2017 5月" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-25697.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">韩伴FUN 20</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-25695.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950879388.jpg" alt="猪头传媒 2017 5月" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-25695.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">猪头传媒 201</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-31.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950899070.jpg" alt="娱乐乐翻天 2017 5月" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-31.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">娱乐乐翻天 20</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-28.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950899250.jpg" alt="音乐大师课 第三季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-28.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">音乐大师课 第三</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-10.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900510.jpg" alt="全娱乐早扒点 2017 5月" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-10.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">全娱乐早扒点 2</span></a>
                                </li>
								
								</ul>
                        </div>
                    </li>
					
                    <li class="list_item"> <a href="/?m=vod-type-id-4.html" class="link_nav"><span class="link_inner ft">动漫</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-5005.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508069210.jpg" alt="小伶玩具" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-5005.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">小伶玩具</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-4980.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950806876.jpg" alt="银魂 精选集" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4980.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">银魂 精选集</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-4961.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950806826.jpg" alt="博人传 火影忍者新时代" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4961.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">博人传 火影忍者</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-4931.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508067214.jpg" alt="爆兽猎人" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4931.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">爆兽猎人</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-4929.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508067212.jpg" alt="偶像大师 灰姑娘剧场 第一季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4929.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">偶像大师 灰姑娘</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-4928.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508067211.jpg" alt="偶像时间 美妙天堂" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4928.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">偶像时间 美妙天</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-4914.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508066816.jpg" alt="宝宝巴士儿歌 英文精选" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4914.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">宝宝巴士儿歌 英</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-4839.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508064518.jpg" alt="闯堂兔损友联萌 第三季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4839.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">闯堂兔损友联萌 </span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-4349.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508053317.jpg" alt="灵石茂险王" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4349.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">灵石茂险王</span></a>
                                </li>
								
								</ul>
                        </div>
                    </li>
					
					</ul>
                <ul class="navigation_area">
				
				 <li class="list_item"> <a href="/?m=vod-type-id-12.html" class="link_nav"><span class="link_inner ft">国产剧</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-29952.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900959.jpg" alt="人民的名义" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29952.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">人民的名义</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-7150.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950813849.jpg" alt="穿越火线" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-7150.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">穿越火线</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-6746.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950812523.jpg" alt="华丽一族" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-6746.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">华丽一族</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-317.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950872550.jpg" alt="神机妙算刘伯温" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-317.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">神机妙算刘伯温</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-5016.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950806962.jpg" alt="同窗那些事儿" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-5016.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">同窗那些事儿</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-5012.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508069217.jpg" alt="御姐归来" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-5012.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">御姐归来</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-42.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950898510.jpg" alt="苦咖啡" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-42.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">苦咖啡</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-4993.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508068719.jpg" alt="择天记 未删减版" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-4993.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">择天记 未删减版</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-389.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950866500.jpg" alt="伪装者" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-389.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">伪装者</span></a>
                                </li>
								
								</ul>
                        </div>
                    </li>
					
				 <li class="list_item"> <a href="/?m=vod-type-id-13.html" class="link_nav"><span class="link_inner ft">港台剧</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-7596.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950815361.jpg" alt="我可能不会爱你" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-7596.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">我可能不会爱你</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-8496.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950818378.jpg" alt="精武门" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-8496.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">精武门</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-7340.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508145011.jpg" alt="芙蓉镇" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-7340.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">芙蓉镇</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-7582.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950815316.jpg" alt="真爱遇到他" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-7582.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">真爱遇到他</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27238.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508921012.jpg" alt="滚石爱情故事" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27238.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">滚石爱情故事</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26774.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950887574.jpg" alt="鉴侦英雄" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26774.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">鉴侦英雄</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26775.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950887575.jpg" alt="天若有情II" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26775.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">天若有情II</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26609.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508862910.jpg" alt="台湾第一巡抚" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26609.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">台湾第一巡抚</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26529.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950885576.jpg" alt="聂小倩" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26529.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">聂小倩</span></a>
                                </li>
								
								</ul>
                        </div>
                    </li>
					
				 <li class="list_item"> <a href="/?m=vod-type-id-14.html" class="link_nav"><span class="link_inner ft">日韩剧</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-29789.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149509005617.jpg" alt="拥抱太阳的月亮" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29789.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">拥抱太阳的月亮</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-28024.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950893903.jpg" alt="我叫金三顺 未删减版" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-28024.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">我叫金三顺 未删</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-54.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950897890.jpg" alt="匹诺曹" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-54.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">匹诺曹</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27841.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950894608.jpg" alt="云画的月光" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27841.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">云画的月光</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27728.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950894259.jpg" alt="下女们" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27728.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">下女们</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27696.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508941115.jpg" alt="锥子" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27696.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">锥子</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27681.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508940719.jpg" alt="亲爱的恩东啊" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27681.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">亲爱的恩东啊</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27689.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950894118.jpg" alt="仙岩女高侦探团" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27689.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">仙岩女高侦探团</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27676.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508940714.jpg" alt="Last" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27676.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">Last</span></a>
                                </li>
								
								</ul>
                        </div>
                    </li>
					
				 <li class="list_item"> <a href="/?m=vod-type-id-15.html" class="link_nav"><span class="link_inner ft">欧美剧</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-27280.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508925416.jpg" alt="副总统第五季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27280.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">副总统第五季</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27281.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508925617.jpg" alt="球手们 第二季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27281.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">球手们 第二季</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27243.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508921417.jpg" alt="亿万 第1季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27243.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">亿万 第1季</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27202.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508917914.jpg" alt="黑吃黑 第四季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27202.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">黑吃黑 第四季</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27194.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950891676.jpg" alt="权力的游戏第七季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27194.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">权力的游戏第七季</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26749.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508873517.jpg" alt="硅谷第三季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26749.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">硅谷第三季</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26690.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508868815.jpg" alt="时尚烟云" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26690.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">时尚烟云</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26667.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508867111.jpg" alt="亿万 第一季" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26667.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">亿万 第一季</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26645.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950886578.jpg" alt="第74届金球奖" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26645.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">第74届金球奖</span></a>
                                </li>
								
								</ul>
                        </div>
                    </li>
					
				 <li class="list_item"> <a href="/?m=vod-type-id-26.html" class="link_nav"><span class="link_inner ft">其它剧</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-7807.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950816093.jpg" alt="笑傲江湖" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-7807.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">笑傲江湖</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-6429.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950811459.jpg" alt="千方百计" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-6429.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">千方百计</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27396.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508932118.jpg" alt="神雕侠侣[范文芳版]" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27396.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">神雕侠侣[范文芳</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27308.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950892876.jpg" alt="宫[泰国版][泰语]" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27308.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">宫[泰国版][泰</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27309.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950892887.jpg" alt="宫[泰国版][国语]" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27309.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">宫[泰国版][国</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26502.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508853617.jpg" alt="网红养成记[国语]" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26502.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">网红养成记[国语</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26299.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950883974.jpg" alt="奇葩海外剧合集" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26299.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">奇葩海外剧合集</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26054.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950882016.jpg" alt="超级巨星" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26054.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">超级巨星</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-25815.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508801114.jpg" alt="千方百计爱上你" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-25815.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">千方百计爱上你</span></a>
                                </li>
								
								</ul>
                        </div>
                    </li>
					
                   </ul>
                <ul class="navigation_area">
				
                 <li class="list_item"> <a href="/?m=vod-type-id-5.html" class="link_nav"><span class="link_inner ft">动作片</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-27311.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950892909.jpg" alt="生化危机：终章" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27311.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">生化危机：终章</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29914.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900919.jpg" alt="丐帮之千年打狗棒" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29914.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">丐帮之千年打狗棒</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26963.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950889343.jpg" alt="十字追杀令2" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26963.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">十字追杀令2</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26894.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508885510.jpg" alt="但丁密码" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26894.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">但丁密码</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29800.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900629.jpg" alt="钢铁侠3" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29800.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">钢铁侠3</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-22663.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508672916.jpg" alt="绝地逃亡" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-22663.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">绝地逃亡</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29798.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900627.jpg" alt="蚁人" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29798.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">蚁人</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29797.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900626.jpg" alt="钢铁侠2" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29797.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">钢铁侠2</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29793.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900602.jpg" alt="终结者：创世纪" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29793.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">终结者：创世纪</span></a>
                                </li>
								
                                </ul>
                        </div>
                    </li>
					
                 <li class="list_item"> <a href="/?m=vod-type-id-6.html" class="link_nav"><span class="link_inner ft">喜剧片</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-27307.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950892855.jpg" alt="玛格丽特的春天" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27307.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">玛格丽特的春天</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27303.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950892841.jpg" alt="疯岳撬佳人" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27303.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">疯岳撬佳人</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27227.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950892011.jpg" alt="合约男女" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27227.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">合约男女</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27159.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950891199.jpg" alt="你好，疯子！" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27159.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">你好，疯子！</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-26927.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950888865.jpg" alt="乔希" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-26927.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">乔希</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-25409.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950878447.jpg" alt="我不是潘金莲" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-25409.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">我不是潘金莲</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27123.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508908811.jpg" alt="新大头儿子小头爸爸2一日成才" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27123.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">新大头儿子小头爸</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29795.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900614.jpg" alt="恐龙当家" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29795.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">恐龙当家</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29794.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900613.jpg" alt="赏金猎人" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29794.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">赏金猎人</span></a>
                                </li>
								
                                </ul>
                        </div>
                    </li>
					
                 <li class="list_item"> <a href="/?m=vod-type-id-7.html" class="link_nav"><span class="link_inner ft">爱情片</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-29927.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900953.jpg" alt="《电影恋爱学》第六十七期 《速度与激情》众帅哥撩妹技术哪家强" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29927.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">《电影恋爱学》第</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29919.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149509009114.jpg" alt="《电影恋爱学》第六十六期 怎么给妹纸催眠，让她爱上你？" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29919.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">《电影恋爱学》第</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29915.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149509009110.jpg" alt="《电影恋爱学》第六十五期 女人这些信号，暗示你快来撩她" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29915.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">《电影恋爱学》第</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29913.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900918.jpg" alt="《电影恋爱学》第六十二期 最优雅的撩妹装逼方式" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29913.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">《电影恋爱学》第</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29899.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149509008513.jpg" alt="《电影恋爱学》第六十期 搭讪搭的好，妹纸跑不了！" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29899.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">《电影恋爱学》第</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-27169.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508912919.jpg" alt="那年夏天你去了哪里" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-27169.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">那年夏天你去了哪</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29880.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149509008113.jpg" alt="《电影恋爱学》第五十八期 让妹纸一见钟情的秘诀大揭秘" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29880.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">《电影恋爱学》第</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29869.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900812.jpg" alt="摆渡人 粤语版" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29869.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">摆渡人 粤语版</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29863.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149509007715.jpg" alt="《电影恋爱学》第五十七期 情人节暖化女人心全攻略" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29863.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">《电影恋爱学》第</span></a>
                                </li>
								
                                </ul>
                        </div>
                    </li>
					
                 <li class="list_item"> <a href="/?m=vod-type-id-8.html" class="link_nav"><span class="link_inner ft">科幻片</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-29931.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900957.jpg" alt="刺客信条" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29931.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">刺客信条</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-21267.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950861459.jpg" alt="变形金刚2" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-21267.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">变形金刚2</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-22507.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508663312.jpg" alt="美国队长3" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-22507.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">美国队长3</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-29796.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900615.jpg" alt="星球大战7：原力觉醒" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29796.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">星球大战7：原力</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-21229.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950861329.jpg" alt="无限复活" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-21229.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">无限复活</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-19655.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508553112.jpg" alt="卫斯理传奇" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-19655.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">卫斯理传奇</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-20010.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950856496.jpg" alt="卫斯理之蓝血人" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-20010.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">卫斯理之蓝血人</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-1291.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950808020.jpg" alt="末日迷踪" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-1291.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">末日迷踪</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-14786.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950839807.jpg" alt="珍爱泉源" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-14786.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">珍爱泉源</span></a>
                                </li>
								
                                </ul>
                        </div>
                    </li>
					
                 <li class="list_item"> <a href="/?m=vod-type-id-9.html" class="link_nav"><span class="link_inner ft">恐怖片</span><i class="nav_sign"></i></a>
                        <div class="navigation_sub">
                            <ul>
							
                                <li><a href="/?m=vod-detail-id-29792.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950900601.jpg" alt="金钱怪兽" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-29792.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">金钱怪兽</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-21860.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508638913.jpg" alt="我左眼见到鬼" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-21860.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">我左眼见到鬼</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-18825.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508526518.jpg" alt="风雨双流星" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-18825.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">风雨双流星</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-20828.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950859847.jpg" alt="Office有鬼" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-20828.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">Office有鬼</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-1497.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950795733.jpg" alt="魔宫魅影" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-1497.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">魔宫魅影</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-1429.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950800400.jpg" alt="荒野猎人" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-1429.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">荒野猎人</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-970.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950827910.jpg" alt="十亿韩元" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-970.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">十亿韩元</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-21629.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/149508627610.jpg" alt="我是证人" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-21629.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">我是证人</span></a>
                                </li>
								
                                <li><a href="/?m=vod-detail-id-20027.html" target="_blank">
                                    <img class="lazy yj" src="/upload/vod/2017-05-18/14950856544.jpg" alt="灵臆事件" width="120" height="142" />
                                    </a><a href="/?m=vod-detail-id-20027.html" target="_blank" class="link_nav_sub"><span class="link_innet f14">灵臆事件</span></a>
                                </li>
								
                                </ul>
                        </div>
                    </li>
					
					</ul>
                <ul class="navigation_none">
                    <li class="list_item"><a href="/index.php?m=label-tv.html" class="link_nav"><span class="link_inner">直播</span></a></li>
                    <li class="list_item"><a href="/index.php?m=label-new.html" class="link_nav"><span class="link_inner">最新</span></a></li>
                    <li class="list_item"><a href="/?m=vod-map.html" class="link_nav"><span class="link_inner">排行</span></a></li>
					<li class="list_item"><a href="/?m=vod-topicindex.html" class="link_nav"><span class="link_inner">专题</span><i class="ico_text_top_small"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
    <div class="warpper" style="padding-top: 110px;">
        <div class="qirebox">
            <div class="qirepic">
                <ul class="info">
				 
                    <li class="li_n" >
                        <div class="qirepic-silder-panel"><i class="userfav"><a href="javascript:void(0)" onclick="MAC.UserFav('29952');return false;"/>会员收藏</a></i>
                            <a class="qirepic-silder-img yj5 mt5" href="/?m=vod-detail-id-29952.html">
                                <img src="/upload/vod/2017-05-18/14950900959.jpg">
                            </a>
                            <div class="qirepic-silder-intro">
                                <div class="qirepic-silder-title">
                                    <h2><a target="_blank" href="/?m=vod-detail-id-29952.html" title="人民的名义">人民的名义</a></h2>
                                    <span>(52集全 )</span>
                                </div>
                                <ul class="qirepic-silder-info clearfix">
                                    <li class="long">
                                        <label>主演：</label><span>陆毅,柯蓝,张丰毅</span>
                                    </li>
                                    <li>类型：<span>[vod:classname]</span>
                                    </li>
                                    <li>导演：<span>李路</span>
                                    </li>
                                    <li>年份：<span>2017</span>
                                    </li>
                                    <li>时间：<span>15-09-01</span>
                                    </li>
                                </ul>
                                <p class="qirepic-silder-desc">剧情：<span>简介：一位国家部委的项目处长被人举报受贿千万，当最高人民检察院反贪总局侦查处处长侯亮平前来搜查时，看到的却是一位长相憨厚、衣着朴素的“老农民”在简陋破败的旧房里吃炸酱面。当这位腐败分子的面具被最终撕开的同时，与之案件牵连甚紧的汉东省京州市副市长丁义珍，却在一位</span>
                                </p> <a class="qirepic-silder-play" href="/?m=vod-detail-id-29952.html" target="_blank">立即观看</a>
                            </div>
                        </div>
                    </li>
					
                    <li class="li_n" >
                        <div class="qirepic-silder-panel"><i class="userfav"><a href="javascript:void(0)" onclick="MAC.UserFav('4488');return false;"/>会员收藏</a></i>
                            <a class="qirepic-silder-img yj5 mt5" href="/?m=vod-detail-id-4488.html">
                                <img src="/upload/vod/2017-05-18/201705181495079702.jpg">
                            </a>
                            <div class="qirepic-silder-intro">
                                <div class="qirepic-silder-title">
                                    <h2><a target="_blank" href="/?m=vod-detail-id-4488.html" title="欢乐喜剧人 第三季">欢乐喜剧人 第三季</a></h2>
                                    <span>(更新至04-09期)</span>
                                </div>
                                <ul class="qirepic-silder-info clearfix">
                                    <li class="long">
                                        <label>主演：</label><span>郭德纲</span>
                                    </li>
                                    <li>类型：<span>[vod:classname]</span>
                                    </li>
                                    <li>导演：<span>郭德纲</span>
                                    </li>
                                    <li>年份：<span>未知</span>
                                    </li>
                                    <li>时间：<span>15-09-01</span>
                                    </li>
                                </ul>
                                <p class="qirepic-silder-desc">剧情：<span>《欢乐喜剧人》是东方卫视打造的首档明星喜剧竞赛真人秀节目。节目中汇聚了中国当下最顶级的喜剧笑星，致力于呈现中国最顶级的喜剧盛宴。</span>
                                </p> <a class="qirepic-silder-play" href="/?m=vod-detail-id-4488.html" target="_blank">立即观看</a>
                            </div>
                        </div>
                    </li>
					
                    <li class="li_n" >
                        <div class="qirepic-silder-panel"><i class="userfav"><a href="javascript:void(0)" onclick="MAC.UserFav('4443');return false;"/>会员收藏</a></i>
                            <a class="qirepic-silder-img yj5 mt5" href="/?m=vod-detail-id-4443.html">
                                <img src="/upload/vod/2017-05-18/201705181495080345.jpg">
                            </a>
                            <div class="qirepic-silder-intro">
                                <div class="qirepic-silder-title">
                                    <h2><a target="_blank" href="/?m=vod-detail-id-4443.html" title="今晚80后脱口秀 2017">今晚80后脱口秀 2017</a></h2>
                                    <span>(更新至04-27期)</span>
                                </div>
                                <ul class="qirepic-silder-info clearfix">
                                    <li class="long">
                                        <label>主演：</label><span>王自健/百克力</span>
                                    </li>
                                    <li>类型：<span>[vod:classname]</span>
                                    </li>
                                    <li>导演：<span>王自健/百克力</span>
                                    </li>
                                    <li>年份：<span>未知</span>
                                    </li>
                                    <li>时间：<span>15-09-01</span>
                                    </li>
                                </ul>
                                <p class="qirepic-silder-desc">剧情：<span>《今晚80后脱口秀》是东方卫视打造的高端文化脱口秀，也是中国唯一一档欧美风格脱口秀节目，80后新锐相声演员王自健倾情加盟，每期通过脱口秀的形式，展现年轻人对社会热点、文化事件、时尚潮流的态度和思想，幽默风趣却又不失智慧与锐度。</span>
                                </p> <a class="qirepic-silder-play" href="/?m=vod-detail-id-4443.html" target="_blank">立即观看</a>
                            </div>
                        </div>
                    </li>
					
                    <li class="li_n" >
                        <div class="qirepic-silder-panel"><i class="userfav"><a href="javascript:void(0)" onclick="MAC.UserFav('29953');return false;"/>会员收藏</a></i>
                            <a class="qirepic-silder-img yj5 mt5" href="/?m=vod-detail-id-29953.html">
                                <img src="/upload/vod/2017-05-18/14950900958.jpg">
                            </a>
                            <div class="qirepic-silder-intro">
                                <div class="qirepic-silder-title">
                                    <h2><a target="_blank" href="/?m=vod-detail-id-29953.html" title="新娱乐在线 2017 5月">新娱乐在线 2017 5月</a></h2>
                                    <span>(更新至05-01期)</span>
                                </div>
                                <ul class="qirepic-silder-info clearfix">
                                    <li class="long">
                                        <label>主演：</label><span>万蒂妮</span>
                                    </li>
                                    <li>类型：<span>[vod:classname]</span>
                                    </li>
                                    <li>导演：<span>万蒂妮</span>
                                    </li>
                                    <li>年份：<span>未知</span>
                                    </li>
                                    <li>时间：<span>15-09-01</span>
                                    </li>
                                </ul>
                                <p class="qirepic-silder-desc">剧情：<span>《新娱乐在线》是一档娱乐资讯类节目。节目立足华人娱乐制高点，放眼世界，将全球娱乐盛事尽收眼底。盘点新鲜娱乐大事，评点天下娱乐人物，强调娱乐事件的点评和分析，发挥直播的互动性，以新闻视角看娱乐，以娱乐方式做新闻，并参与全球各大娱乐盛事及电影节的现场报道。《新娱乐</span>
                                </p> <a class="qirepic-silder-play" href="/?m=vod-detail-id-29953.html" target="_blank">立即观看</a>
                            </div>
                        </div>
                    </li>
					
                    <li class="li_n" >
                        <div class="qirepic-silder-panel"><i class="userfav"><a href="javascript:void(0)" onclick="MAC.UserFav('29931');return false;"/>会员收藏</a></i>
                            <a class="qirepic-silder-img yj5 mt5" href="/?m=vod-detail-id-29931.html">
                                <img src="/upload/vod/2017-05-18/14950900957.jpg">
                            </a>
                            <div class="qirepic-silder-intro">
                                <div class="qirepic-silder-title">
                                    <h2><a target="_blank" href="/?m=vod-detail-id-29931.html" title="刺客信条">刺客信条</a></h2>
                                    <span>()</span>
                                </div>
                                <ul class="qirepic-silder-info clearfix">
                                    <li class="long">
                                        <label>主演：</label><span>迈克尔·法斯宾德,玛丽昂·歌迪亚,杰瑞米·艾恩斯,布莱丹·格里森</span>
                                    </li>
                                    <li>类型：<span>[vod:classname]</span>
                                    </li>
                                    <li>导演：<span>贾斯汀·库泽尔</span>
                                    </li>
                                    <li>年份：<span>未知</span>
                                    </li>
                                    <li>时间：<span>15-09-01</span>
                                    </li>
                                </ul>
                                <p class="qirepic-silder-desc">剧情：<span>《刺客信条》根据育碧同名电子系列游戏改编，讲述了卡勒姆·林奇获得先祖阿圭拉超凡的知识和能力来对抗圣殿骑士组织的故事。</span>
                                </p> <a class="qirepic-silder-play" href="/?m=vod-detail-id-29931.html" target="_blank">立即观看</a>
                            </div>
                        </div>
                    </li>
					
                    <li class="li_n" >
                        <div class="qirepic-silder-panel"><i class="userfav"><a href="javascript:void(0)" onclick="MAC.UserFav('29930');return false;"/>会员收藏</a></i>
                            <a class="qirepic-silder-img yj5 mt5" href="/?m=vod-detail-id-29930.html">
                                <img src="/upload/vod/2017-05-18/14950900956.jpg">
                            </a>
                            <div class="qirepic-silder-intro">
                                <div class="qirepic-silder-title">
                                    <h2><a target="_blank" href="/?m=vod-detail-id-29930.html" title="五一小长假看什么 4部国产电影随你怎么选">五一小长假看什么 4部国产电影随你怎么选</a></h2>
                                    <span>()</span>
                                </div>
                                <ul class="qirepic-silder-info clearfix">
                                    <li class="long">
                                        <label>主演：</label><span></span>
                                    </li>
                                    <li>类型：<span>[vod:classname]</span>
                                    </li>
                                    <li>导演：<span></span>
                                    </li>
                                    <li>年份：<span>未知</span>
                                    </li>
                                    <li>时间：<span>15-09-01</span>
                                    </li>
                                </ul>
                                <p class="qirepic-silder-desc">剧情：<span>你见过屌的，更屌的在这里。</span>
                                </p> <a class="qirepic-silder-play" href="/?m=vod-detail-id-29930.html" target="_blank">立即观看</a>
                            </div>
                        </div>
                    </li>
					
                    <li class="li_n" >
                        <div class="qirepic-silder-panel"><i class="userfav"><a href="javascript:void(0)" onclick="MAC.UserFav('29929');return false;"/>会员收藏</a></i>
                            <a class="qirepic-silder-img yj5 mt5" href="/?m=vod-detail-id-29929.html">
                                <img src="/upload/vod/2017-05-18/14950900955.jpg">
                            </a>
                            <div class="qirepic-silder-intro">
                                <div class="qirepic-silder-title">
                                    <h2><a target="_blank" href="/?m=vod-detail-id-29929.html" title="《我的爸爸是国王》主题曲MV 开启冒险之旅">《我的爸爸是国王》主题曲MV 开启冒险之旅</a></h2>
                                    <span>()</span>
                                </div>
                                <ul class="qirepic-silder-info clearfix">
                                    <li class="long">
                                        <label>主演：</label><span></span>
                                    </li>
                                    <li>类型：<span>[vod:classname]</span>
                                    </li>
                                    <li>导演：<span></span>
                                    </li>
                                    <li>年份：<span>未知</span>
                                    </li>
                                    <li>时间：<span>15-09-01</span>
                                    </li>
                                </ul>
                                <p class="qirepic-silder-desc">剧情：<span>国内首档非主流纯得瑟自带弹幕解说磕巴的严肃娱乐星闻类BB，粉丝超爱，啪！</span>
                                </p> <a class="qirepic-silder-play" href="/?m=vod-detail-id-29929.html" target="_blank">立即观看</a>
                            </div>
                        </div>
                    </li>
					
                    <li class="li_n" >
                        <div class="qirepic-silder-panel"><i class="userfav"><a href="javascript:void(0)" onclick="MAC.UserFav('29928');return false;"/>会员收藏</a></i>
                            <a class="qirepic-silder-img yj5 mt5" href="/?m=vod-detail-id-29928.html">
                                <img src="/upload/vod/2017-05-18/14950900954.jpg">
                            </a>
                            <div class="qirepic-silder-intro">
                                <div class="qirepic-silder-title">
                                    <h2><a target="_blank" href="/?m=vod-detail-id-29928.html" title="剧透师全家第三十九期：三分钟全息剧透《小姐》">剧透师全家第三十九期：三分钟全息剧透《小姐》</a></h2>
                                    <span>()</span>
                                </div>
                                <ul class="qirepic-silder-info clearfix">
                                    <li class="long">
                                        <label>主演：</label><span></span>
                                    </li>
                                    <li>类型：<span>[vod:classname]</span>
                                    </li>
                                    <li>导演：<span></span>
                                    </li>
                                    <li>年份：<span>未知</span>
                                    </li>
                                    <li>时间：<span>15-09-01</span>
                                    </li>
                                </ul>
                                <p class="qirepic-silder-desc">剧情：<span>剧透师全家是一个剧透师大家庭，为您在电影上映前带来最完整的全息剧透。</span>
                                </p> <a class="qirepic-silder-play" href="/?m=vod-detail-id-29928.html" target="_blank">立即观看</a>
                            </div>
                        </div>
                    </li>
					
                    <li class="li_n" >
                        <div class="qirepic-silder-panel"><i class="userfav"><a href="javascript:void(0)" onclick="MAC.UserFav('29927');return false;"/>会员收藏</a></i>
                            <a class="qirepic-silder-img yj5 mt5" href="/?m=vod-detail-id-29927.html">
                                <img src="/upload/vod/2017-05-18/14950900953.jpg">
                            </a>
                            <div class="qirepic-silder-intro">
                                <div class="qirepic-silder-title">
                                    <h2><a target="_blank" href="/?m=vod-detail-id-29927.html" title="《电影恋爱学》第六十七期 《速度与激情》众帅哥撩妹技术哪家强">《电影恋爱学》第六十七期 《速度与激情》众帅哥撩妹技术哪家强</a></h2>
                                    <span>()</span>
                                </div>
                                <ul class="qirepic-silder-info clearfix">
                                    <li class="long">
                                        <label>主演：</label><span></span>
                                    </li>
                                    <li>类型：<span>[vod:classname]</span>
                                    </li>
                                    <li>导演：<span></span>
                                    </li>
                                    <li>年份：<span>未知</span>
                                    </li>
                                    <li>时间：<span>15-09-01</span>
                                    </li>
                                </ul>
                                <p class="qirepic-silder-desc">剧情：<span>爱对了是运气，爱错了是青春？可别再为自己的无知找借口了！数据统计发现，在中国有超过3/4的年轻人群情感知识匮乏，缺少对异性内心真实想法的了解，更不懂如何去学习和提升，只会盲目地等待。而那些沉迷于爱情甜蜜的，也只有在对方离去时，才意识到自己的情感能力需要！</span>
                                </p> <a class="qirepic-silder-play" href="/?m=vod-detail-id-29927.html" target="_blank">立即观看</a>
                            </div>
                        </div>
                    </li>
					
                    </ul>
            </div>
            <div class="set_num yj5">
                <ul>
				
                    <li >
                        <a class="yj" href="/?m=vod-detail-id-29952.html" target="_blank">
                            <img  class="yj" src="/upload/vod/2017-05-18/14950900959.jpg">
                        </a>
                    </li>
					
                    <li >
                        <a class="yj" href="/?m=vod-detail-id-4488.html" target="_blank">
                            <img  class="yj" src="/upload/vod/2017-05-18/201705181495079702.jpg">
                        </a>
                    </li>
					
                    <li >
                        <a class="yj" href="/?m=vod-detail-id-4443.html" target="_blank">
                            <img  class="yj" src="/upload/vod/2017-05-18/201705181495080345.jpg">
                        </a>
                    </li>
					
                    <li >
                        <a class="yj" href="/?m=vod-detail-id-29953.html" target="_blank">
                            <img  class="yj" src="/upload/vod/2017-05-18/14950900958.jpg">
                        </a>
                    </li>
					
                    <li >
                        <a class="yj" href="/?m=vod-detail-id-29931.html" target="_blank">
                            <img  class="yj" src="/upload/vod/2017-05-18/14950900957.jpg">
                        </a>
                    </li>
					
                    <li >
                        <a class="yj" href="/?m=vod-detail-id-29930.html" target="_blank">
                            <img  class="yj" src="/upload/vod/2017-05-18/14950900956.jpg">
                        </a>
                    </li>
					
                    <li >
                        <a class="yj" href="/?m=vod-detail-id-29929.html" target="_blank">
                            <img  class="yj" src="/upload/vod/2017-05-18/14950900955.jpg">
                        </a>
                    </li>
					
                    <li >
                        <a class="yj" href="/?m=vod-detail-id-29928.html" target="_blank">
                            <img  class="yj" src="/upload/vod/2017-05-18/14950900954.jpg">
                        </a>
                    </li>
					
                    <li >
                        <a class="yj" href="/?m=vod-detail-id-29927.html" target="_blank">
                            <img  class="yj" src="/upload/vod/2017-05-18/14950900953.jpg">
                        </a>
                    </li>
					
                   </ul>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(".qirebox").slide({
            titCell: ".set_num ul li",
            mainCell: ".qirepic ul.info",
            effect: "fold",
            autoPlay: true,
            delayTime: 300
        });
    </script>
    <div class="container">
        <div class="nvc bks blyj bryj">
            <dl>	<dt>
					<span>当前位置</span>
					<i class="arrow"><b class="a_outer"></b><b class="a_inner"></b></i>
				</dt>
                <dd><a href='/'>首页</a>&nbsp;&nbsp;&raquo;&nbsp;&nbsp;<a href='/?m=vod-type-id-2.html' >连续剧</a></dd>
            </dl>
        </div>
    </div>
    <div class="container">
        <div class="l">
            <div class="mod_tpy_Box mt5 mb10">
                <div class="hd">
                    <ul>
                        <li>日榜</li>
                        <li>月榜</li>
                        <li>总榜</li>
                        <li>推荐</li>
                    </ul>
                </div>
                <div class="bd mod_guess_video_list fl">
                    <ol>
					
			{if-A:1 = 1 }
                        <a href="/?m=vod-detail-id-28024.html" target="_blank" class="figure">
                            <img class="lazy" data-original="/upload/vod/2017-05-18/14950893903.jpg" src="/images/blank.png" alt="我叫金三顺 未删减版" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_1 f18">1</i>
                            </div>
                            <div class="figure_caption ftno"><strong>我叫金三顺 未删减版</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_1 yj">1</em>
                            <h6><a href="/?m=vod-detail-id-28024.html" title="我叫金三顺 未删减版">我叫金三顺 未删减版</a> </h6>
                            <en class="fr">10.0</en>
                        </li>
						{endif-A}
					
			{if-A:2 = 1 }
                        <a href="/?m=vod-detail-id-27281.html" target="_blank" class="figure">
                            <img class="lazy" data-original="/upload/vod/2017-05-18/149508925617.jpg" src="/images/blank.png" alt="球手们 第二季" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_2 f18">2</i>
                            </div>
                            <div class="figure_caption ftno"><strong>球手们 第二季</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_2 yj">2</em>
                            <h6><a href="/?m=vod-detail-id-27281.html" title="球手们 第二季">球手们 第二季</a> </h6>
                            <en class="fr">9.0</en>
                        </li>
						{endif-A}
					
			{if-A:3 = 1 }
                        <a href="/?m=vod-detail-id-26283.html" target="_blank" class="figure">
                            <img class="lazy" data-original="/upload/vod/2017-05-18/14950883857.jpg" src="/images/blank.png" alt="麻雀张鲁一CUT" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_3 f18">3</i>
                            </div>
                            <div class="figure_caption ftno"><strong>麻雀张鲁一CUT</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_3 yj">3</em>
                            <h6><a href="/?m=vod-detail-id-26283.html" title="麻雀张鲁一CUT">麻雀张鲁一CUT</a> </h6>
                            <en class="fr">3.0</en>
                        </li>
						{endif-A}
					
			{if-A:4 = 1 }
                        <a href="/?m=vod-detail-id-26018.html" target="_blank" class="figure">
                            <img class="lazy" data-original="/upload/vod/2017-05-18/14950881648.jpg" src="/images/blank.png" alt="无心法师2" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_4 f18">4</i>
                            </div>
                            <div class="figure_caption ftno"><strong>无心法师2</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_4 yj">4</em>
                            <h6><a href="/?m=vod-detail-id-26018.html" title="无心法师2">无心法师2</a> </h6>
                            <en class="fr">5.0</en>
                        </li>
						{endif-A}
					
			{if-A:5 = 1 }
                        <a href="/?m=vod-detail-id-26022.html" target="_blank" class="figure">
                            <img class="lazy" data-original="/upload/vod/2017-05-18/149508816812.jpg" src="/images/blank.png" alt="剃刀边缘" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_5 f18">5</i>
                            </div>
                            <div class="figure_caption ftno"><strong>剃刀边缘</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_5 yj">5</em>
                            <h6><a href="/?m=vod-detail-id-26022.html" title="剃刀边缘">剃刀边缘</a> </h6>
                            <en class="fr">7.0</en>
                        </li>
						{endif-A}
					
			{if-A:6 = 1 }
                        <a href="/?m=vod-detail-id-27391.html" target="_blank" class="figure">
                            <img class="lazy" data-original="/upload/vod/2017-05-18/149508931913.jpg" src="/images/blank.png" alt="神探狄仁杰" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_6 f18">6</i>
                            </div>
                            <div class="figure_caption ftno"><strong>神探狄仁杰</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_6 yj">6</em>
                            <h6><a href="/?m=vod-detail-id-27391.html" title="神探狄仁杰">神探狄仁杰</a> </h6>
                            <en class="fr">8.0</en>
                        </li>
						{endif-A}
					
			{if-A:7 = 1 }
                        <a href="/?m=vod-detail-id-25765.html" target="_blank" class="figure">
                            <img class="lazy" data-original="/upload/vod/2017-05-18/14950879892.jpg" src="/images/blank.png" alt="三十定律" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_7 f18">7</i>
                            </div>
                            <div class="figure_caption ftno"><strong>三十定律</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_7 yj">7</em>
                            <h6><a href="/?m=vod-detail-id-25765.html" title="三十定律">三十定律</a> </h6>
                            <en class="fr">4.0</en>
                        </li>
						{endif-A}
					
			{if-A:8 = 1 }
                        <a href="/?m=vod-detail-id-27854.html" target="_blank" class="figure">
                            <img class="lazy" data-original="/upload/vod/2017-05-18/14950894652.jpg" src="/images/blank.png" alt="红星照耀中国 未删减版" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_8 f18">8</i>
                            </div>
                            <div class="figure_caption ftno"><strong>红星照耀中国 未删减版</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_8 yj">8</em>
                            <h6><a href="/?m=vod-detail-id-27854.html" title="红星照耀中国 未删减版">红星照耀中国 未删减版</a> </h6>
                            <en class="fr">9.0</en>
                        </li>
						{endif-A}
					
			{if-A:9 = 1 }
                        <a href="/?m=vod-detail-id-27250.html" target="_blank" class="figure">
                            <img class="lazy" data-original="/upload/vod/2017-05-18/14950892255.jpg" src="/images/blank.png" alt="火线出击[下]" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_9 f18">9</i>
                            </div>
                            <div class="figure_caption ftno"><strong>火线出击[下]</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_9 yj">9</em>
                            <h6><a href="/?m=vod-detail-id-27250.html" title="火线出击[下]">火线出击[下]</a> </h6>
                            <en class="fr">6.0</en>
                        </li>
						{endif-A}
					
			{if-A:10 = 1 }
                        <a href="/?m=vod-detail-id-27478.html" target="_blank" class="figure">
                            <img class="lazy" data-original="/upload/vod/2017-05-18/14950893475.jpg" src="/images/blank.png" alt="隋唐英雄传3 未删减版" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_10 f18">10</i>
                            </div>
                            <div class="figure_caption ftno"><strong>隋唐英雄传3 未删减版</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_10 yj">10</em>
                            <h6><a href="/?m=vod-detail-id-27478.html" title="隋唐英雄传3 未删减版">隋唐英雄传3 未删减版</a> </h6>
                            <en class="fr">8.0</en>
                        </li>
						{endif-A}
					
                        </ol>
                    <ol>
					
			{if-A:1 = 1 }
                        <a href="/?m=vod-detail-id-27569.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950893751.jpg" alt="《离婚协议》" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_1">1</i>
                            </div>
                            <div class="figure_caption ftno"><strong>《离婚协议》</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_1 yj">1</em>
                            <h6><a href="/?m=vod-detail-id-27569.html" title="《离婚协议》">《离婚协议》</a> </h6>
                            <en class="fr">3.0</en>
                        </li>
						{endif-A}
					
			{if-A:2 = 1 }
                        <a href="/?m=vod-detail-id-7848.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950816236.jpg" alt="罪域" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_2">2</i>
                            </div>
                            <div class="figure_caption ftno"><strong>罪域</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_2 yj">2</em>
                            <h6><a href="/?m=vod-detail-id-7848.html" title="罪域">罪域</a> </h6>
                            <en class="fr">8.0</en>
                        </li>
						{endif-A}
					
			{if-A:3 = 1 }
                        <a href="/?m=vod-detail-id-7484.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950814993.jpg" alt="新四大名捕" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_3">3</i>
                            </div>
                            <div class="figure_caption ftno"><strong>新四大名捕</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_3 yj">3</em>
                            <h6><a href="/?m=vod-detail-id-7484.html" title="新四大名捕">新四大名捕</a> </h6>
                            <en class="fr">1.0</en>
                        </li>
						{endif-A}
					
			{if-A:4 = 1 }
                        <a href="/?m=vod-detail-id-6841.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950812844.jpg" alt="无盐女" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_4">4</i>
                            </div>
                            <div class="figure_caption ftno"><strong>无盐女</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_4 yj">4</em>
                            <h6><a href="/?m=vod-detail-id-6841.html" title="无盐女">无盐女</a> </h6>
                            <en class="fr">1.0</en>
                        </li>
						{endif-A}
					
			{if-A:5 = 1 }
                        <a href="/?m=vod-detail-id-5350.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/149508079713.jpg" alt="福禄双全" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_5">5</i>
                            </div>
                            <div class="figure_caption ftno"><strong>福禄双全</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_5 yj">5</em>
                            <h6><a href="/?m=vod-detail-id-5350.html" title="福禄双全">福禄双全</a> </h6>
                            <en class="fr">3.0</en>
                        </li>
						{endif-A}
					
			{if-A:6 = 1 }
                        <a href="/?m=vod-detail-id-847.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950835800.jpg" alt="恋爱SOS 第二季" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_6">6</i>
                            </div>
                            <div class="figure_caption ftno"><strong>恋爱SOS 第二季</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_6 yj">6</em>
                            <h6><a href="/?m=vod-detail-id-847.html" title="恋爱SOS 第二季">恋爱SOS 第二季</a> </h6>
                            <en class="fr">9.0</en>
                        </li>
						{endif-A}
					
			{if-A:7 = 1 }
                        <a href="/?m=vod-detail-id-7255.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950814242.jpg" alt="新方世玉" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_7">7</i>
                            </div>
                            <div class="figure_caption ftno"><strong>新方世玉</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_7 yj">7</em>
                            <h6><a href="/?m=vod-detail-id-7255.html" title="新方世玉">新方世玉</a> </h6>
                            <en class="fr">10.0</en>
                        </li>
						{endif-A}
					
			{if-A:8 = 1 }
                        <a href="/?m=vod-detail-id-6199.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950810707.jpg" alt="丁若镛" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_8">8</i>
                            </div>
                            <div class="figure_caption ftno"><strong>丁若镛</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_8 yj">8</em>
                            <h6><a href="/?m=vod-detail-id-6199.html" title="丁若镛">丁若镛</a> </h6>
                            <en class="fr">9.0</en>
                        </li>
						{endif-A}
					
			{if-A:9 = 1 }
                        <a href="/?m=vod-detail-id-4172.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950804942.jpg" alt="李氏家族" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_9">9</i>
                            </div>
                            <div class="figure_caption ftno"><strong>李氏家族</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_9 yj">9</em>
                            <h6><a href="/?m=vod-detail-id-4172.html" title="李氏家族">李氏家族</a> </h6>
                            <en class="fr">7.0</en>
                        </li>
						{endif-A}
					
			{if-A:10 = 1 }
                        <a href="/?m=vod-detail-id-240.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950878380.jpg" alt="壮丁也是兵" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_10">10</i>
                            </div>
                            <div class="figure_caption ftno"><strong>壮丁也是兵</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_10 yj">10</em>
                            <h6><a href="/?m=vod-detail-id-240.html" title="壮丁也是兵">壮丁也是兵</a> </h6>
                            <en class="fr">1.0</en>
                        </li>
						{endif-A}
					
                        </ol>
                    <ol> 
                    
			{if-A:1 = 1 }
                        <a href="/?m=vod-detail-id-8150.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950817224.jpg" alt="嘻哈四重奏 第一季" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_1">1</i>
                            </div>
                            <div class="figure_caption ftno"><strong>嘻哈四重奏 第一季</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_1 yj">1</em>
                            <h6><a href="/?m=vod-detail-id-8150.html" title="嘻哈四重奏 第一季">嘻哈四重奏 第一季</a> </h6>
                            <en class="fr">1.0</en>
                        </li>
						{endif-A}
					
			{if-A:2 = 1 }
                        <a href="/?m=vod-detail-id-7624.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/149508154510.jpg" alt="嘻哈四重奏 第三季" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_2">2</i>
                            </div>
                            <div class="figure_caption ftno"><strong>嘻哈四重奏 第三季</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_2 yj">2</em>
                            <h6><a href="/?m=vod-detail-id-7624.html" title="嘻哈四重奏 第三季">嘻哈四重奏 第三季</a> </h6>
                            <en class="fr">2.0</en>
                        </li>
						{endif-A}
					
			{if-A:3 = 1 }
                        <a href="/?m=vod-detail-id-6936.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950813164.jpg" alt="倚天屠龙记" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_3">3</i>
                            </div>
                            <div class="figure_caption ftno"><strong>倚天屠龙记</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_3 yj">3</em>
                            <h6><a href="/?m=vod-detail-id-6936.html" title="倚天屠龙记">倚天屠龙记</a> </h6>
                            <en class="fr">5.0</en>
                        </li>
						{endif-A}
					
			{if-A:4 = 1 }
                        <a href="/?m=vod-detail-id-224.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950879380.jpg" alt="圈里圈外" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_4">4</i>
                            </div>
                            <div class="figure_caption ftno"><strong>圈里圈外</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_4 yj">4</em>
                            <h6><a href="/?m=vod-detail-id-224.html" title="圈里圈外">圈里圈外</a> </h6>
                            <en class="fr">7.0</en>
                        </li>
						{endif-A}
					
			{if-A:5 = 1 }
                        <a href="/?m=vod-detail-id-26057.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950882039.jpg" alt="夜活儿" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_5">5</i>
                            </div>
                            <div class="figure_caption ftno"><strong>夜活儿</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_5 yj">5</em>
                            <h6><a href="/?m=vod-detail-id-26057.html" title="夜活儿">夜活儿</a> </h6>
                            <en class="fr">9.0</en>
                        </li>
						{endif-A}
					
			{if-A:6 = 1 }
                        <a href="/?m=vod-detail-id-7580.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950815314.jpg" alt="毛骗 第二季" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_6">6</i>
                            </div>
                            <div class="figure_caption ftno"><strong>毛骗 第二季</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_6 yj">6</em>
                            <h6><a href="/?m=vod-detail-id-7580.html" title="毛骗 第二季">毛骗 第二季</a> </h6>
                            <en class="fr">4.0</en>
                        </li>
						{endif-A}
					
			{if-A:7 = 1 }
                        <a href="/?m=vod-detail-id-5813.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950809461.jpg" alt="李宁 Shine动·穿越回去" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_7">7</i>
                            </div>
                            <div class="figure_caption ftno"><strong>李宁 Shine动·穿越回去</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_7 yj">7</em>
                            <h6><a href="/?m=vod-detail-id-5813.html" title="李宁 Shine动·穿越回去">李宁 Shine动·穿越回去</a> </h6>
                            <en class="fr">9.0</en>
                        </li>
						{endif-A}
					
			{if-A:8 = 1 }
                        <a href="/?m=vod-detail-id-5422.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950808219.jpg" alt="家和万事兴之在外过年" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_8">8</i>
                            </div>
                            <div class="figure_caption ftno"><strong>家和万事兴之在外过年</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_8 yj">8</em>
                            <h6><a href="/?m=vod-detail-id-5422.html" title="家和万事兴之在外过年">家和万事兴之在外过年</a> </h6>
                            <en class="fr">5.0</en>
                        </li>
						{endif-A}
					
			{if-A:9 = 1 }
                        <a href="/?m=vod-detail-id-691.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950846050.jpg" alt="密令1949" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_9">9</i>
                            </div>
                            <div class="figure_caption ftno"><strong>密令1949</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_9 yj">9</em>
                            <h6><a href="/?m=vod-detail-id-691.html" title="密令1949">密令1949</a> </h6>
                            <en class="fr">4.0</en>
                        </li>
						{endif-A}
					
			{if-A:10 = 1 }
                        <a href="/?m=vod-detail-id-151.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950890480.jpg" alt="ST 警视厅科学特搜班" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_10">10</i>
                            </div>
                            <div class="figure_caption ftno"><strong>ST 警视厅科学特搜班</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_10 yj">10</em>
                            <h6><a href="/?m=vod-detail-id-151.html" title="ST 警视厅科学特搜班">ST 警视厅科学特搜班</a> </h6>
                            <en class="fr">6.0</en>
                        </li>
						{endif-A}
					
					</ol>
                    <ol> 
                    
			{if-A:1 = 1 }
                        <a href="/?m=vod-detail-id-29789.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/149509005617.jpg" alt="拥抱太阳的月亮" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_1">1</i>
                            </div>
                            <div class="figure_caption ftno"><strong>拥抱太阳的月亮</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_1 yj">1</em>
                            <h6><a href="/?m=vod-detail-id-29789.html" title="拥抱太阳的月亮">拥抱太阳的月亮</a> </h6>
                            <en class="fr">1.0</en>
                        </li>
						{endif-A}
					
			{if-A:2 = 1 }
                        <a href="/?m=vod-detail-id-8202.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/149508173718.jpg" alt="我的土地我的家" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_2">2</i>
                            </div>
                            <div class="figure_caption ftno"><strong>我的土地我的家</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_2 yj">2</em>
                            <h6><a href="/?m=vod-detail-id-8202.html" title="我的土地我的家">我的土地我的家</a> </h6>
                            <en class="fr">9.0</en>
                        </li>
						{endif-A}
					
			{if-A:3 = 1 }
                        <a href="/?m=vod-detail-id-7423.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/149508147618.jpg" alt="肥猫寻亲记之明天会更好" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_3">3</i>
                            </div>
                            <div class="figure_caption ftno"><strong>肥猫寻亲记之明天会更好</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_3 yj">3</em>
                            <h6><a href="/?m=vod-detail-id-7423.html" title="肥猫寻亲记之明天会更好">肥猫寻亲记之明天会更好</a> </h6>
                            <en class="fr">9.0</en>
                        </li>
						{endif-A}
					
			{if-A:4 = 1 }
                        <a href="/?m=vod-detail-id-7197.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950814011.jpg" alt="私人公园" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_4">4</i>
                            </div>
                            <div class="figure_caption ftno"><strong>私人公园</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_4 yj">4</em>
                            <h6><a href="/?m=vod-detail-id-7197.html" title="私人公园">私人公园</a> </h6>
                            <en class="fr">4.0</en>
                        </li>
						{endif-A}
					
			{if-A:5 = 1 }
                        <a href="/?m=vod-detail-id-7148.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950813847.jpg" alt="风流唐伯虎" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_5">5</i>
                            </div>
                            <div class="figure_caption ftno"><strong>风流唐伯虎</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_5 yj">5</em>
                            <h6><a href="/?m=vod-detail-id-7148.html" title="风流唐伯虎">风流唐伯虎</a> </h6>
                            <en class="fr">10.0</en>
                        </li>
						{endif-A}
					
			{if-A:6 = 1 }
                        <a href="/?m=vod-detail-id-6546.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/149508118412.jpg" alt="惊险生活" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_6">6</i>
                            </div>
                            <div class="figure_caption ftno"><strong>惊险生活</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_6 yj">6</em>
                            <h6><a href="/?m=vod-detail-id-6546.html" title="惊险生活">惊险生活</a> </h6>
                            <en class="fr">10.0</en>
                        </li>
						{endif-A}
					
			{if-A:7 = 1 }
                        <a href="/?m=vod-detail-id-6019.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/149508101317.jpg" alt="风华绝代" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_7">7</i>
                            </div>
                            <div class="figure_caption ftno"><strong>风华绝代</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_7 yj">7</em>
                            <h6><a href="/?m=vod-detail-id-6019.html" title="风华绝代">风华绝代</a> </h6>
                            <en class="fr">6.0</en>
                        </li>
						{endif-A}
					
			{if-A:8 = 1 }
                        <a href="/?m=vod-detail-id-5545.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/149508085718.jpg" alt="这里没有冬季" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_8">8</i>
                            </div>
                            <div class="figure_caption ftno"><strong>这里没有冬季</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_8 yj">8</em>
                            <h6><a href="/?m=vod-detail-id-5545.html" title="这里没有冬季">这里没有冬季</a> </h6>
                            <en class="fr">2.0</en>
                        </li>
						{endif-A}
					
			{if-A:9 = 1 }
                        <a href="/?m=vod-detail-id-5342.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/14950807975.jpg" alt="梦想的天空" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_9">9</i>
                            </div>
                            <div class="figure_caption ftno"><strong>梦想的天空</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_9 yj">9</em>
                            <h6><a href="/?m=vod-detail-id-5342.html" title="梦想的天空">梦想的天空</a> </h6>
                            <en class="fr">8.0</en>
                        </li>
						{endif-A}
					
			{if-A:10 = 1 }
                        <a href="/?m=vod-detail-id-4016.html" target="_blank" class="figure">
                            <img class="lazy" src="/upload/vod/2017-05-18/149508045317.jpg" alt="秋去秋来" style="visibility: visible; " />
                            <div class="figure_sign yj"><i class="num num_10">10</i>
                            </div>
                            <div class="figure_caption ftno"><strong>秋去秋来</strong>
                            </div>
                        </a>
						{else-A}
                        <li> <em class="num num_10 yj">10</em>
                            <h6><a href="/?m=vod-detail-id-4016.html" title="秋去秋来">秋去秋来</a> </h6>
                            <en class="fr">8.0</en>
                        </li>
						{endif-A}
					
					</ol>
                </div>

            </div>
            <script type="text/javascript">
                jQuery(".mod_tpy_Box").slide();
            </script>
            <div class="mod_indexs mod_index_t">
                <div class="mod_cont">
                    <div class="h3">按类型看</div>
                    <ul>
                        <li {if-A:"0"="0"} class="current" {endif-A}><a href="{page:linktype}" title="全部">全部</a></li>
                        
                <li {if-A:"2"="12"} class="current" {endif-A}><a href="/index.php?m=vod-list-id-12-pg-1-order--by--class--year--letter--area--lang-.html" title="国产剧">国产剧</a>
                </li>
				
                <li {if-A:"2"="13"} class="current" {endif-A}><a href="/index.php?m=vod-list-id-13-pg-1-order--by--class--year--letter--area--lang-.html" title="港台剧">港台剧</a>
                </li>
				
                <li {if-A:"2"="14"} class="current" {endif-A}><a href="/index.php?m=vod-list-id-14-pg-1-order--by--class--year--letter--area--lang-.html" title="日韩剧">日韩剧</a>
                </li>
				
                <li {if-A:"2"="15"} class="current" {endif-A}><a href="/index.php?m=vod-list-id-15-pg-1-order--by--class--year--letter--area--lang-.html" title="欧美剧">欧美剧</a>
                </li>
				
                <li {if-A:"2"="26"} class="current" {endif-A}><a href="/index.php?m=vod-list-id-26-pg-1-order--by--class--year--letter--area--lang-.html" title="其它剧">其它剧</a>
                </li>
				
				</ul>
                </div>
                <div class="mod_cont">
                    <div class="h3">按年代看</div>
                    <ul>
					<li class="current"><a href="javascript:void(0)" title="全部">全部</a>
                    </li>
                    
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year-2017-letter--area--lang-.html" title="2017">2017</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year-2016-letter--area--lang-.html" title="2016">2016</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year-2015-letter--area--lang-.html" title="2015">2015</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year-2014-letter--area--lang-.html" title="2014">2014</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year-2013-letter--area--lang-.html" title="2013">2013</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year-2012-letter--area--lang-.html" title="2012">2012</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year-2011-letter--area--lang-.html" title="2011">2011</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year-2010-letter--area--lang-.html" title="2010">2010</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year-2009-letter--area--lang-.html" title="2009">2009</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year-2008-letter--area--lang-.html" title="2008">2008</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year-2007-letter--area--lang-.html" title="2007">2007</a>
                </li>
				
				</ul>
                </div>
                <div class="mod_cont">
                    <div class="h3">按地区看</div>
                    <ul>
                        <li class="current"><a href="javascript:void(0)" title="全部">全部</a>
                        </li>
                        
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E5%A4%A7%E9%99%86-lang-.html" title="大陆">大陆</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E9%A6%99%E6%B8%AF-lang-.html" title="香港">香港</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E5%8F%B0%E6%B9%BE-lang-.html" title="台湾">台湾</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E7%BE%8E%E5%9B%BD-lang-.html" title="美国">美国</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E9%9F%A9%E5%9B%BD-lang-.html" title="韩国">韩国</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E6%97%A5%E6%9C%AC-lang-.html" title="日本">日本</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E6%B3%B0%E5%9B%BD-lang-.html" title="泰国">泰国</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E6%96%B0%E5%8A%A0%E5%9D%A1-lang-.html" title="新加坡">新加坡</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E9%A9%AC%E6%9D%A5%E8%A5%BF%E4%BA%9A-lang-.html" title="马来西亚">马来西亚</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E5%8D%B0%E5%BA%A6-lang-.html" title="印度">印度</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E8%8B%B1%E5%9B%BD-lang-.html" title="英国">英国</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E6%B3%95%E5%9B%BD-lang-.html" title="法国">法国</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E5%8A%A0%E6%8B%BF%E5%A4%A7-lang-.html" title="加拿大">加拿大</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E8%A5%BF%E7%8F%AD%E7%89%99-lang-.html" title="西班牙">西班牙</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E4%BF%84%E7%BD%97%E6%96%AF-lang-.html" title="俄罗斯">俄罗斯</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter--area-%E5%85%B6%E5%AE%83-lang-.html" title="其它">其它</a>
                </li>
				
				</ul>
                </div>
                <div class="mod_cont">
                    <div class="h3">按剧情看</div>
                    <ul>
                        <li class="current"><a href="javascript:void(0)" title="全部">全部</a>
                        </li>
                        
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-15-year--letter--area--lang-.html" title="言情">言情</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-16-year--letter--area--lang-.html" title="都市">都市</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-17-year--letter--area--lang-.html" title="家庭">家庭</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-18-year--letter--area--lang-.html" title="生活">生活</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-19-year--letter--area--lang-.html" title="偶像">偶像</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-20-year--letter--area--lang-.html" title="喜剧">喜剧</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-21-year--letter--area--lang-.html" title="历史">历史</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-22-year--letter--area--lang-.html" title="古装">古装</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-23-year--letter--area--lang-.html" title="武侠">武侠</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-24-year--letter--area--lang-.html" title="刑侦">刑侦</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-25-year--letter--area--lang-.html" title="战争">战争</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-26-year--letter--area--lang-.html" title="神话">神话</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-27-year--letter--area--lang-.html" title="军旅">军旅</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-28-year--letter--area--lang-.html" title="谍战">谍战</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-29-year--letter--area--lang-.html" title="商战">商战</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-30-year--letter--area--lang-.html" title="校园">校园</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-31-year--letter--area--lang-.html" title="穿越">穿越</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-32-year--letter--area--lang-.html" title="悬疑">悬疑</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-33-year--letter--area--lang-.html" title="犯罪">犯罪</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-34-year--letter--area--lang-.html" title="科幻">科幻</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class-35-year--letter--area--lang-.html" title="预告片">预告片</a>
                </li>
				
				</ul>
                </div>
                <div class="mod_cont">
                    <div class="h3">按字母看</div>
                    <ul>
                        <li class="current"><a href="javascript:void(0)" title="全部">全部</a>
                        </li>
                        
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-A-area--lang-.html" title="A">A</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-B-area--lang-.html" title="B">B</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-C-area--lang-.html" title="C">C</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-D-area--lang-.html" title="D">D</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-E-area--lang-.html" title="E">E</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-F-area--lang-.html" title="F">F</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-G-area--lang-.html" title="G">G</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-H-area--lang-.html" title="H">H</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-I-area--lang-.html" title="I">I</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-J-area--lang-.html" title="J">J</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-K-area--lang-.html" title="K">K</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-L-area--lang-.html" title="L">L</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-M-area--lang-.html" title="M">M</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-N-area--lang-.html" title="N">N</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-O-area--lang-.html" title="O">O</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-P-area--lang-.html" title="P">P</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-Q-area--lang-.html" title="Q">Q</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-R-area--lang-.html" title="R">R</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-S-area--lang-.html" title="S">S</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-T-area--lang-.html" title="T">T</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-U-area--lang-.html" title="U">U</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-V-area--lang-.html" title="V">V</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-W-area--lang-.html" title="W">W</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-X-area--lang-.html" title="X">X</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-Y-area--lang-.html" title="Y">Y</a>
                </li>
				
                <li><a href="/index.php?m=vod-list-id-2-pg-1-order--by--class--year--letter-Z-area--lang-.html" title="Z">Z</a>
                </li>
				
				</ul>
                </div>
            </div>
            <div class="mod_gg"></div>
        </div>
        <div class="r ml10 mb10 mt5">
            <div class="mod_toolbar">
                <ul>
                    <li class="current"><a href="{page:linkbytime}">看最新更新</a>
                    </li>
                    <li><a href="{page:linkbyhits}">看最近热播</a>
                        </li>
                        <li><a href="{page:linkbyscore}">看最受好评</a>
                            </li>
                </ul>
            </div>
            <div class="mod_video_list">
                <ul>
				{maccms:vod pagesize=40 order=desc by=time}
                    <li>
						<i class="userfav"><a href="javascript:void(0)" onclick="MAC.UserFav('[vod:id]');return false;"/>会员收藏</a></i>
                        <a href="[vod:link]" target="_blank" class="mod_poster_170">
                            <img class="lazy yj5" data-original="[vod:pic]" src="/images/blank.png" alt="[vod:name]">
							<sup class="mark">[vod:remarks]</sup>
                            </a>
                        <h6 class="scores f14">
							<a href="[vod:link]" title="[vod:name]"target="_blank">[vod:name]</a>
							<strong>[vod:score]</strong>
						</h6>
                        <p>主演：[vod:starringlink]</p>
                    </li>
					{/maccms:vod}
					</ul>
               <div class="page" id="pager">{maccms:pages len=10}</div>
            </div>
        </div>
    </div>﻿<div class="footer" id="footer">
    <div class="footer_inner">
               <div class="mod_footer_l fl">
            <div class="footermenu">	<a href="#" rel="nofollow" target="_blank">关于我们</a> |	<a href="/index.php?m=map-baidu.html" rel="nofollow" target="_blank">百度地图</a> 	<a href="/index.php?m=gbook-show.html" rel="nofollow" target="_blank">留言求片</a> |	<a href="/index.php?m=map-google.html" rel="nofollow"
                target="_blank">谷歌地图</a> 	<a href="/index.php?m=gbook-show.html" rel="nofollow" target="_blank">客服中心</a> |	<a href="/index.php?m=gbook-show.html" rel="nofollow" target="_blank">客服中心</a>
				<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1260811733'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1260811733' type='text/javascript'%3E%3C/script%3E"));</script>
				</div>
        </div>
        <div class="mod_footer_r">
            <div class="copyrightzh">本网站所有资源均系互联网收集，本网站只提供web页面服务，并不提供影片资源存储，也不参与录制、上传
                <br />若本站收录的内容无意侵犯了贵司版权，请给123456@maccms.com邮箱地址来信或<a href="/index.php?m=gbook-show.html">留言</a>，我们将在第一时间处理与回复,谢谢</div>
            <div class="copyrighten">Copyright © <span>2016</span> All Rights Reserved<a> www.maccms.com  版权所有</a> 
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        $(window).scroll(function() {
            if ($(window).scrollTop() > 100) {
                $("#side-bar .gotop").fadeIn();
            } else {
                $("#side-bar .gotop").hide();
            }
        });
        $("#side-bar .gotop").click(function() {
            $('html,body').animate({
                'scrollTop': 0
            }, 500);
        });
    });
</script>
<ul id="side-bar" class="side-pannel side-bar">
    <a class="gotop" href="javascript:;" style="display:none;"> <s class="g-icon-top"></s>
    </a>
    <a class="survey" href="javascript:;"> <s class="g-icon-survey1"></s>
        <so>
            <form class="search_form" action="/index.php?m=vod-search" method="post">
                <div class="search_inner"> <i class="ico_search"></i>
                    <input type="text" class="search_ipt" id="wd" name="wd" onBlur="if(this.value==''){this.value='提醒您请输入您要搜索的关键字';this.style.color='#aaa'};" onFocus="if(this.value=='提醒您请输入您要搜索的关键字'){this.value='';this.style.color='#aaa'};" value="提醒您请输入您要搜索的关键字"
                    style="color: rgb(170, 170, 170);" />
                    <button type="submit" class="search_btn"><span class="hidden">搜索</span>
                    </button>
                </div>
            </form>
        </so>
    </a>
    <a class="liuyan" href="/index.php?m=gbook-show.html" target="_blank"> <s class="g-icon-liuyan1"></s>
    </a>
    <a class="weibo" href="#" target="_blank"> <s class="g-icon-weibo1"></s>
    </a>
</ul>
   </body>
</html>