(function(){function g(a){throw a;}var j=void 0,k=!0,m=null,n=!1,p,r=this;function aa(){}function ba(a){a.Oa=function(){return a.Nc?a.Nc:a.Nc=new a}}
function ca(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return a!==j}function u(a){return"array"==ca(a)}function v(a){var b=ca(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){return"string"==typeof a}function da(a){return"number"==typeof a}function ea(a){return"function"==ca(a)}function fa(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}function y(a){return a[ga]||(a[ga]=++ha)}var ga="closure_uid_"+(1E9*Math.random()>>>0),ha=0;
function ia(a,b,c){return a.call.apply(a.bind,arguments)}function ja(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function z(a,b,c){z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return z.apply(m,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var la=Date.now||function(){return+new Date};function ma(a,b){var c=a.split("."),d=r;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&t(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function B(a,b){function c(){}c.prototype=b.prototype;a.m=b.prototype;a.prototype=new c};function na(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function oa(a){if(!pa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ra,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(sa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ta,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ua,"&quot;"));return a}var ra=/&/g,sa=/</g,ta=/>/g,ua=/\"/g,pa=/[&<>\"]/;var va,wa,xa,ya;function za(){return r.navigator?r.navigator.userAgent:m}ya=xa=wa=va=n;var Aa;if(Aa=za()){var Ba=r.navigator;va=0==Aa.indexOf("Opera");wa=!va&&-1!=Aa.indexOf("MSIE");xa=!va&&-1!=Aa.indexOf("WebKit");ya=!va&&!xa&&"Gecko"==Ba.product}var Ca=va,C=wa,D=ya,E=xa,Da,Ea=r.navigator;Da=Ea&&Ea.platform||"";var Fa=-1!=Da.indexOf("Mac");function Ga(){var a=r.document;return a?a.documentMode:j}var Ha;
a:{var Ia="",Ja;if(Ca&&r.opera)var Ka=r.opera.version,Ia="function"==typeof Ka?Ka():Ka;else if(D?Ja=/rv\:([^\);]+)(\)|;)/:C?Ja=/MSIE\s+([^\);]+)(\)|;)/:E&&(Ja=/WebKit\/(\S+)/),Ja)var La=Ja.exec(za()),Ia=La?La[1]:"";if(C){var Ma=Ga();if(Ma>parseFloat(Ia)){Ha=String(Ma);break a}}Ha=Ia}var Na={};
function F(a){var b;if(!(b=Na[a])){b=0;for(var c=na(String(Ha)).split("."),d=na(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",l=d[f]||"",q=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var s=q.exec(h)||["","",""],A=w.exec(l)||["","",""];if(0==s[0].length&&0==A[0].length)break;b=((0==s[1].length?0:parseInt(s[1],10))<(0==A[1].length?0:parseInt(A[1],10))?-1:(0==s[1].length?0:parseInt(s[1],10))>(0==A[1].length?0:parseInt(A[1],10))?1:0)||((0==s[2].length)<
(0==A[2].length)?-1:(0==s[2].length)>(0==A[2].length)?1:0)||(s[2]<A[2]?-1:s[2]>A[2]?1:0)}while(0==b)}b=Na[a]=0<=b}return b}var Oa=r.document,Pa=!Oa||!C?j:Ga()||("CSS1Compat"==Oa.compatMode?parseInt(Ha,10):5);function G(){0!=Qa&&(this.Me=Error().stack,Ra[y(this)]=this)}var Qa=0,Ra={};G.prototype.hb=n;G.prototype.ta=function(){if(!this.hb&&(this.hb=k,this.g(),0!=Qa)){var a=y(this);delete Ra[a]}};G.prototype.g=function(){if(this.ad)for(;this.ad.length;)this.ad.shift()()};var Sa={};function H(a,b){this.type=a;this.currentTarget=this.target=b}p=H.prototype;p.g=function(){};p.ta=function(){};p.Aa=n;p.defaultPrevented=n;p.Cb=k;p.preventDefault=function(){this.defaultPrevented=k;this.Cb=n};var Ta=0;function Ua(){}p=Ua.prototype;p.key=0;p.ea=n;p.cb=n;p.ma=function(a,b,c,d,e,f){ea(a)?this.Pc=k:a&&a.handleEvent&&ea(a.handleEvent)?this.Pc=n:g(Error("Invalid listener argument"));this.Z=a;this.ed=b;this.src=c;this.type=d;this.capture=!!e;this.qb=f;this.cb=n;this.key=++Ta;this.ea=n};p.handleEvent=function(a){return this.Pc?this.Z.call(this.qb||this.src,a):this.Z.handleEvent.call(this.Z,a)};function Va(a,b){for(var c in a)b.call(j,a[c],c,a)}function Wa(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Xa(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Ya(a){for(var b in a)return n;return k}var Za="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function $a(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Za.length;f++)c=Za[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var ab=!C||C&&9<=Pa,bb=C&&!F("9");!E||F("528");D&&F("1.9b")||C&&F("8")||Ca&&F("9.5")||E&&F("528");D&&!F("8")||C&&F("9");function cb(a){Error.captureStackTrace?Error.captureStackTrace(this,cb):this.stack=Error().stack||"";a&&(this.message=String(a))}B(cb,Error);cb.prototype.name="CustomError";var I=Array.prototype,db=I.indexOf?function(a,b,c){return I.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(x(a))return!x(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},J=I.forEach?function(a,b,c){I.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},eb=I.filter?function(a,b,c){return I.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=x(a)?a.split(""):
a,l=0;l<d;l++)if(l in h){var q=h[l];b.call(c,q,l,a)&&(e[f++]=q)}return e},fb=I.some?function(a,b,c){return I.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return k;return n};function gb(a,b){return 0<=db(a,b)}function hb(a,b){var c=db(a,b),d;(d=0<=c)&&I.splice.call(a,c,1);return d}function ib(a){return I.concat.apply(I,arguments)}function jb(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function kb(a,b,c){return 2>=arguments.length?I.slice.call(a,b):I.slice.call(a,b,c)};function lb(a){lb[" "](a);return a}lb[" "]=aa;function mb(a,b){a&&this.ma(a,b)}B(mb,H);p=mb.prototype;p.target=m;p.relatedTarget=m;p.offsetX=0;p.offsetY=0;p.clientX=0;p.clientY=0;p.screenX=0;p.screenY=0;p.button=0;p.keyCode=0;p.charCode=0;p.ctrlKey=n;p.altKey=n;p.shiftKey=n;p.metaKey=n;p.te=n;p.Gc=m;
p.ma=function(a,b){var c=this.type=a.type;H.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(D){var e;a:{try{lb(d.nodeName);e=k;break a}catch(f){}e=n}e||(d=m)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=E||a.offsetX!==j?a.offsetX:a.layerX;this.offsetY=E||a.offsetY!==j?a.offsetY:a.layerY;this.clientX=a.clientX!==j?a.clientX:a.pageX;this.clientY=a.clientY!==j?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.te=Fa?a.metaKey:a.ctrlKey;this.state=a.state;this.Gc=a;a.defaultPrevented&&this.preventDefault();delete this.Aa};
p.preventDefault=function(){mb.m.preventDefault.call(this);var a=this.Gc;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,bb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};p.g=function(){};var nb={},K={},L={},ob={};
function M(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)M(a,b[f],c,d,e);return m}a:{b||g(Error("Invalid event type"));d=!!d;var h=K;b in h||(h[b]={a:0,r:0});h=h[b];d in h||(h[d]={a:0,r:0},h.a++);var h=h[d],f=y(a),l;h.r++;if(h[f]){l=h[f];for(var q=0;q<l.length;q++)if(h=l[q],h.Z==c&&h.qb==e){if(h.ea)break;l[q].cb=n;a=l[q];break a}}else l=h[f]=[],h.a++;var w=pb,s=ab?function(a){return w.call(s.src,s.Z,a)}:function(a){a=w.call(s.src,s.Z,a);if(!a)return a},q=s,h=new Ua;h.ma(c,q,a,b,d,e);h.cb=n;q.src=
a;q.Z=h;l.push(h);L[f]||(L[f]=[]);L[f].push(h);a.addEventListener?(a==r||!a.Ec)&&a.addEventListener(b,q,d):a.attachEvent(b in ob?ob[b]:ob[b]="on"+b,q);a=h}b=a.key;nb[b]=a;return b}function qb(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)qb(a,b[f],c,d,e);else if(d=!!d,a=rb(a,b,d))for(f=0;f<a.length;f++)if(a[f].Z==c&&a[f].capture==d&&a[f].qb==e){sb(a[f].key);break}}
function sb(a){var b=nb[a];if(!b||b.ea)return n;var c=b.src,d=b.type,e=b.ed,f=b.capture;c.removeEventListener?(c==r||!c.Ec)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in ob?ob[d]:ob[d]="on"+d,e);c=y(c);L[c]&&(e=L[c],hb(e,b),0==e.length&&delete L[c]);b.ea=k;if(b=K[d][f][c])b.Zc=k,tb(d,f,c,b);delete nb[a];return k}
function tb(a,b,c,d){if(!d.vb&&d.Zc){for(var e=0,f=0;e<d.length;e++)d[e].ea?d[e].ed.src=m:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.Zc=n;0==f&&(delete K[a][b][c],K[a][b].a--,0==K[a][b].a&&(delete K[a][b],K[a].a--),0==K[a].a&&delete K[a])}}function ub(a,b){var c=0,d=b==m;if(a!=m){var e=y(a);if(L[e])for(var e=L[e],f=e.length-1;0<=f;f--){var h=e[f];if(d||b==h.type)sb(h.key),c++}}else Va(nb,function(a,b){sb(b);c++})}function rb(a,b,c){var d=K;return b in d&&(d=d[b],c in d&&(d=d[c],a=y(a),d[a]))?d[a]:m}
function vb(a,b,c,d,e){var f=1;b=y(b);if(a[b]){var h=--a.r,l=a[b];l.vb?l.vb++:l.vb=1;try{for(var q=l.length,w=0;w<q;w++){var s=l[w];s&&!s.ea&&(f&=wb(s,e)!==n)}}finally{a.r=Math.max(h,a.r),l.vb--,tb(c,d,b,l)}}return Boolean(f)}function wb(a,b){a.cb&&sb(a.key);return a.handleEvent(b)}
function pb(a,b){if(a.ea)return k;var c=a.type,d=K;if(!(c in d))return k;var d=d[c],e,f;if(!ab){var h;if(!(h=b))a:{h=["window","event"];for(var l=r;e=h.shift();)if(l[e]!=m)l=l[e];else{h=m;break a}h=l}e=h;h=k in d;l=n in d;if(h){if(0>e.keyCode||e.returnValue!=j)return k;a:{var q=n;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(w){q=k}if(q||e.returnValue==j)e.returnValue=k}}q=new mb;q.ma(e,this);e=k;try{if(h){for(var s=[],A=q.currentTarget;A;A=A.parentNode)s.push(A);f=d[k];f.r=f.a;for(var P=s.length-
1;!q.Aa&&0<=P&&f.r;P--)q.currentTarget=s[P],e&=vb(f,s[P],c,k,q);if(l){f=d[n];f.r=f.a;for(P=0;!q.Aa&&P<s.length&&f.r;P++)q.currentTarget=s[P],e&=vb(f,s[P],c,n,q)}}else e=wb(a,q)}finally{s&&(s.length=0)}return e}c=new mb(b,this);return e=wb(a,c)};var xb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");var yb="StopIteration"in r?r.StopIteration:Error("StopIteration");function zb(){}zb.prototype.next=function(){g(yb)};zb.prototype.Ga=function(){return this};function Ab(a){if(a instanceof zb)return a;if("function"==typeof a.Ga)return a.Ga(n);if(v(a)){var b=0,c=new zb;c.next=function(){for(;;){b>=a.length&&g(yb);if(b in a)return a[b++];b++}};return c}g(Error("Not implemented"))};function Bb(a){if("function"==typeof a.L)return a.L();if(x(a))return a.split("");if(v(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Wa(a)};function Cb(a,b){this.F={};this.b=[];var c=arguments.length;if(1<c){c%2&&g(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Cb?(c=a.la(),d=a.L()):(c=Xa(a),d=Wa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}}p=Cb.prototype;p.a=0;p.Xa=0;p.L=function(){Db(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.F[this.b[b]]);return a};p.la=function(){Db(this);return this.b.concat()};p.ia=function(a){return Eb(this.F,a)};
p.clear=function(){this.F={};this.Xa=this.a=this.b.length=0};p.remove=function(a){return Eb(this.F,a)?(delete this.F[a],this.a--,this.Xa++,this.b.length>2*this.a&&Db(this),k):n};function Db(a){if(a.a!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];Eb(a.F,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.a!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],Eb(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}}p.get=function(a,b){return Eb(this.F,a)?this.F[a]:b};
p.set=function(a,b){Eb(this.F,a)||(this.a++,this.b.push(a),this.Xa++);this.F[a]=b};p.K=function(){return new Cb(this)};p.Ga=function(a){Db(this);var b=0,c=this.b,d=this.F,e=this.Xa,f=this,h=new zb;h.next=function(){for(;;){e!=f.Xa&&g(Error("The map has changed since the iterator was created"));b>=c.length&&g(yb);var h=c[b++];return a?h:d[h]}};return h};function Eb(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Fb(a,b){var c;if(a instanceof Fb)this.u=t(b)?b:a.u,Gb(this,a.fa),c=a.ra,N(this),this.ra=c,Hb(this,a.ja),Ib(this,a.za),Jb(this,a.da),Kb(this,a.H.K()),c=a.ka,N(this),this.ka=c;else if(a&&(c=String(a).match(xb))){this.u=!!b;Gb(this,c[1]||"",k);var d=c[2]||"";N(this);this.ra=d?decodeURIComponent(d):"";Hb(this,c[3]||"",k);Ib(this,c[4]);Jb(this,c[5]||"",k);Kb(this,c[6]||"",k);c=c[7]||"";N(this);this.ka=c?decodeURIComponent(c):""}else this.u=!!b,this.H=new Lb(m,0,this.u)}p=Fb.prototype;p.fa="";
p.ra="";p.ja="";p.za=m;p.da="";p.ka="";p.de=n;p.u=n;p.toString=function(){var a=[],b=this.fa;b&&a.push(Mb(b,Nb),":");if(b=this.ja){a.push("//");var c=this.ra;c&&a.push(Mb(c,Nb),"@");a.push(encodeURIComponent(String(b)));b=this.za;b!=m&&a.push(":",String(b))}if(b=this.da)this.ja&&"/"!=b.charAt(0)&&a.push("/"),a.push(Mb(b,"/"==b.charAt(0)?Pb:Qb));(b=this.H.toString())&&a.push("?",b);(b=this.ka)&&a.push("#",Mb(b,Rb));return a.join("")};
p.jd=function(a){var b=this.K(),c=!!a.fa;c?Gb(b,a.fa):c=!!a.ra;if(c){var d=a.ra;N(b);b.ra=d}else c=!!a.ja;c?Hb(b,a.ja):c=a.za!=m;var e=a.da;if(c)Ib(b,a.za);else if(c=!!a.da)if("/"!=e.charAt(0)&&(this.ja&&!this.da?e="/"+e:(d=b.da.lastIndexOf("/"),-1!=d&&(e=b.da.substr(0,d+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){for(var d=0==e.lastIndexOf("/",0),e=e.split("/"),f=[],h=0;h<e.length;){var l=e[h++];"."==l?d&&h==e.length&&f.push(""):".."==l?((1<f.length||1==f.length&&
""!=f[0])&&f.pop(),d&&h==e.length&&f.push("")):(f.push(l),d=k)}e=f.join("/")}c?Jb(b,e):c=""!==a.H.toString();c?Kb(b,a.H.toString()?decodeURIComponent(a.H.toString()):""):c=!!a.ka;c&&(a=a.ka,N(b),b.ka=a);return b};p.K=function(){return new Fb(this)};function Gb(a,b,c){N(a);a.fa=c?b?decodeURIComponent(b):"":b;a.fa&&(a.fa=a.fa.replace(/:$/,""))}function Hb(a,b,c){N(a);a.ja=c?b?decodeURIComponent(b):"":b}
function Ib(a,b){N(a);b?(b=Number(b),(isNaN(b)||0>b)&&g(Error("Bad port number "+b)),a.za=b):a.za=m}function Jb(a,b,c){N(a);a.da=c?b?decodeURIComponent(b):"":b}function Kb(a,b,c){N(a);b instanceof Lb?(a.H=b,a.H.oc(a.u)):(c||(b=Mb(b,Sb)),a.H=new Lb(b,0,a.u))}function Tb(a,b,c){N(a);u(c)||(c=[String(c)]);Ub(a.H,b,c)}function N(a){a.de&&g(Error("Tried to modify a read-only Uri"))}p.oc=function(a){this.u=a;this.H&&this.H.oc(a);return this};
function Vb(a,b){var c=new Fb(m,j);Gb(c,"http");Hb(c,"web.houyi.baofeng.net");a&&Jb(c,a);b&&Kb(c,b);return c}function Mb(a,b){return x(a)?encodeURI(a).replace(b,Wb):m}function Wb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Nb=/[#\/\?@]/g,Qb=/[\#\?:]/g,Pb=/[\#\?]/g,Sb=/[\#\?@]/g,Rb=/#/g;function Lb(a,b,c){this.t=a||m;this.u=!!c}
function Xb(a){if(!a.c&&(a.c=new Cb,a.a=0,a.t))for(var b=a.t.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=m,f=m;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=Yb(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}p=Lb.prototype;p.c=m;p.a=m;p.add=function(a,b){Xb(this);this.t=m;a=Yb(this,a);var c=this.c.get(a);c||this.c.set(a,c=[]);c.push(b);this.a++;return this};
p.remove=function(a){Xb(this);a=Yb(this,a);return this.c.ia(a)?(this.t=m,this.a-=this.c.get(a).length,this.c.remove(a)):n};p.clear=function(){this.c=this.t=m;this.a=0};p.ia=function(a){Xb(this);a=Yb(this,a);return this.c.ia(a)};p.la=function(){Xb(this);for(var a=this.c.L(),b=this.c.la(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
p.L=function(a){Xb(this);var b=[];if(a)this.ia(a)&&(b=ib(b,this.c.get(Yb(this,a))));else{a=this.c.L();for(var c=0;c<a.length;c++)b=ib(b,a[c])}return b};p.set=function(a,b){Xb(this);this.t=m;a=Yb(this,a);this.ia(a)&&(this.a-=this.c.get(a).length);this.c.set(a,[b]);this.a++;return this};p.get=function(a,b){var c=a?this.L(a):[];return 0<c.length?String(c[0]):b};function Ub(a,b,c){a.remove(b);0<c.length&&(a.t=m,a.c.set(Yb(a,b),jb(c)),a.a+=c.length)}
p.toString=function(){if(this.t)return this.t;if(!this.c)return"";for(var a=[],b=this.c.la(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.L(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}return this.t=a.join("&")};p.K=function(){var a=new Lb;a.t=this.t;this.c&&(a.c=this.c.K(),a.a=this.a);return a};function Yb(a,b){var c=String(b);a.u&&(c=c.toLowerCase());return c}
p.oc=function(a){if(a&&!this.u){Xb(this);this.t=m;var b=this.c,c=function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),Ub(this,c,a))};if("function"==typeof b.forEach)b.forEach(c,this);else if(v(b)||x(b))J(b,c,this);else{var d;if("function"==typeof b.la)d=b.la();else if("function"!=typeof b.L)if(v(b)||x(b)){d=[];for(var e=b.length,f=0;f<e;f++)d.push(f)}else d=Xa(b);else d=j;b=Bb(b);e=b.length;for(f=0;f<e;f++)c.call(this,b[f],d&&d[f])}}this.u=a};function Zb(a){this.D=a}var $b=/\s*;\s*/;p=Zb.prototype;p.set=function(a,b,c,d,e,f){/[;=\s]/.test(a)&&g(Error('Invalid cookie name "'+a+'"'));/[;\r\n]/.test(b)&&g(Error('Invalid cookie value "'+b+'"'));t(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(la()+1E3*c)).toUTCString();this.D.cookie=a+"="+b+e+d+c+f};
p.get=function(a,b){for(var c=a+"=",d=(this.D.cookie||"").split($b),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};p.remove=function(a,b,c){var d=this.ia(a);this.set(a,"",0,b,c);return d};p.la=function(){return ac(this).keys};p.L=function(){return ac(this).Ie};p.ia=function(a){return t(this.get(a))};p.clear=function(){for(var a=ac(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
function ac(a){a=(a.D.cookie||"").split($b);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,Ie:c}};function bc(){G.call(this)}B(bc,G);p=bc.prototype;p.Ec=k;p.zb=m;p.pc=function(a){this.zb=a};p.addEventListener=function(a,b,c,d){M(this,a,b,c,d)};p.removeEventListener=function(a,b,c,d){qb(this,a,b,c,d)};
p.dispatchEvent=function(a){var b=a.type||a,c=K;if(b in c){if(x(a))a=new H(a,this);else if(a instanceof H)a.target=a.target||this;else{var d=a;a=new H(b,this);$a(a,d)}var d=1,e,c=c[b],b=k in c,f;if(b){e=[];for(f=this;f;f=f.zb)e.push(f);f=c[k];f.r=f.a;for(var h=e.length-1;!a.Aa&&0<=h&&f.r;h--)a.currentTarget=e[h],d&=vb(f,e[h],a.type,k,a)&&a.Cb!=n}if(n in c)if(f=c[n],f.r=f.a,b)for(h=0;!a.Aa&&h<e.length&&f.r;h++)a.currentTarget=e[h],d&=vb(f,e[h],a.type,n,a)&&a.Cb!=n;else for(e=this;!a.Aa&&e&&f.r;e=e.zb)a.currentTarget=
e,d&=vb(f,e,a.type,n,a)&&a.Cb!=n;a=Boolean(d)}else a=k;return a};p.g=function(){bc.m.g.call(this);ub(this);this.zb=m};/*
 {@link www.baofeng.com}
*/
new Fb(r.location.href);var O=new bc,cc=m;function dc(a,b,c,d){var e=[];e.push("_trackEvent");e.push(a);e.push(b);c!=m&&e.push(c);d!=m&&e.push(d);try{r._hmt.push(e),r.ga&&r.ga("send","event",a,b)}catch(f){}}M(O,"log",function(a){var b=ec[a.data.key].name,c=ec[a.data.key].infor[a.data.value-1];a.data.other?dc(b,c,m,a.data.other):dc(b,c)});
M(O,"log",function(a){if(t(ec[a.data.key].bfinfo)&&t(r.baofeng.eventLog)){var b=ec[a.data.key].bfinfo[a.data.value-1];t(b)&&b!=m&&(t(a.data.other)&&(b.value&&(b.value=a.data.other),b.key&&(b[b.key]=a.data.other)),b.category=a.data.key,r.baofeng.eventLog(b))}});function fc(a,b){this.x=t(a)?a:0;this.y=t(b)?b:0}p=fc.prototype;p.K=function(){return new fc(this.x,this.y)};p.toString=function(){return"("+this.x+", "+this.y+")"};p.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};p.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};p.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function gc(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}p=gc.prototype;p.K=function(){return new gc(this.top,this.right,this.bottom,this.left)};p.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};p.contains=function(a){return!this||!a?n:a instanceof gc?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};
p.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};p.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};p.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function hc(a,b){this.width=a;this.height=b}p=hc.prototype;p.K=function(){return new hc(this.width,this.height)};p.toString=function(){return"("+this.width+" x "+this.height+")"};p.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};p.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};p.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function ic(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}p=ic.prototype;p.K=function(){return new ic(this.left,this.top,this.width,this.height)};p.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};p.contains=function(a){return a instanceof ic?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
p.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};p.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};p.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var jc;function kc(a){a=a.className;return x(a)&&a.match(/\S+/g)||[]}function Q(a,b){for(var c=kc(a),d=kb(arguments,1),e=c.length+d.length,f=c,h=0;h<d.length;h++)gb(f,d[h])||f.push(d[h]);a.className=c.join(" ");return c.length==e}function lc(a,b){var c=kc(a),d=kb(arguments,1),c=eb(c,function(a){return!gb(d,a)});a.className=c.join(" ")};var mc=!C||C&&9<=Pa,nc=!D&&!C||C&&C&&9<=Pa||D&&F("1.9.1"),oc=C&&!F("9");function pc(a){return a?new qc(rc(a)):jc||(jc=new qc)}function R(a){return x(a)?document.getElementById(a):a}function sc(a,b){var c=b||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):S("*",a,b)}function T(a,b){var c=b||document,d=m;return(d=c.querySelectorAll&&c.querySelector?c.querySelector("."+a):sc(a,b)[0])||m}
function S(a,b,c){var d=document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,f=0,h;h=c[f];f++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(f=e=0;h=c[f];f++)a=h.className,"function"==typeof a.split&&gb(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c}
function tc(a,b){Va(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in uc?a.setAttribute(uc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var uc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function vc(a){var b=!E&&"CSS1Compat"==a.compatMode?a.documentElement:a.body;a=a.parentWindow||a.defaultView;return new fc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}function wc(a,b,c){return xc(document,arguments)}
function xc(a,b){var c=b[0],d=b[1];if(!mc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',oa(d.name),'"');if(d.type){c.push(' type="',oa(d.type),'"');var e={};$a(e,d);delete e.type;d=e}c.push(">");c=c.join("")}var f=a.createElement(c);d&&(x(d)?f.className=d:u(d)?Q.apply(m,[f].concat(d)):tc(f,d));if(2<b.length){d=function(b){b&&f.appendChild(x(b)?a.createTextNode(b):b)};for(c=2;c<b.length;c++)if(e=b[c],v(e)&&!(fa(e)&&0<e.nodeType)){var h=J,l;a:{if((l=e)&&"number"==typeof l.length){if(fa(l)){l=
"function"==typeof l.item||"string"==typeof l.item;break a}if(ea(l)){l="function"==typeof l.item;break a}}l=n}h(l?jb(e):e,d)}else d(e)}return f}function yc(a){var b=document,c=b.createElement("div");C?(c.innerHTML="<br>"+a,c.removeChild(c.firstChild)):c.innerHTML=a;if(1==c.childNodes.length)return c.removeChild(c.firstChild);for(a=b.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);return a}function zc(a){a&&a.parentNode&&a.parentNode.removeChild(a)}
function Ac(a){return nc&&a.children!=j?a.children:eb(a.childNodes,function(a){return 1==a.nodeType})}function Bc(a){return fa(a)&&1==a.nodeType}function rc(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var Cc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Dc={IMG:" ",BR:"\n"};
function Ec(a){if(oc&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Fc(a,b,k);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");oc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Fc(a,b,c){if(!(a.nodeName in Cc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Dc)b.push(Dc[a.nodeName]);else for(a=a.firstChild;a;)Fc(a,b,c),a=a.nextSibling}function qc(a){this.D=a||r.document||document}p=qc.prototype;p.Jc=function(a){return x(a)?this.D.getElementById(a):a};p.Dc=function(a,b,c){return xc(this.D,arguments)};p.createElement=function(a){return this.D.createElement(a)};p.createTextNode=function(a){return this.D.createTextNode(String(a))};
p.appendChild=function(a,b){a.appendChild(b)};p.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function Gc(a,b){x(b)?Hc(a,j,b):Va(b,ka(Hc,a))}function Hc(a,b,c){var d;a:if(d=String(c).replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()}),a.style[d]===j){var e=E?"Webkit":D?"Moz":C?"ms":Ca?"O":m,f=x(j)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";c=c.replace(RegExp("(^"+(f?"|["+f+"]+":"")+")([a-z])","g"),function(a,b,c){return b+c.toUpperCase()});e+=c;if(a.style[e]!==j){d=e;break a}}d&&(a.style[d]=b)}
function Ic(a,b){var c=rc(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,m))?c[b]||c.getPropertyValue(b)||"":""}function Jc(a,b){return Ic(a,b)||(a.currentStyle?a.currentStyle[b]:m)||a.style&&a.style[b]}function Kc(a){var b=a.getBoundingClientRect();C&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Lc(a){if(C&&!(C&&8<=Pa))return a.offsetParent;var b=rc(a),c=Jc(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Jc(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return m}
function Mc(a){if("none"!=Jc(a,"display"))return Nc(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Nc(a);b.display=c;b.position=e;b.visibility=d;return a}function Nc(a){var b=a.offsetWidth,c=a.offsetHeight,d=E&&!b&&!c;return(!t(b)||d)&&a.getBoundingClientRect?(a=Kc(a),new hc(a.right-a.left,a.bottom-a.top)):new hc(b,c)}
function Oc(a){var b,c=rc(a),d=Jc(a,"position"),e=D&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),f=new fc(0,0),h;b=c?rc(c):document;if(h=C)if(h=!(C&&9<=Pa))h="CSS1Compat"!=pc(b).D.compatMode;h=h?b.body:b.documentElement;if(a!=h)if(a.getBoundingClientRect)b=Kc(a),c=pc(c),c=vc(c.D),f.x=b.left+c.x,f.y=b.top+c.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),c=c.getBoxObjectFor(h),f.x=b.screenX-c.screenX,f.y=b.screenY-c.screenY;
else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(E&&"fixed"==Jc(b,"position")){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(Ca||E&&"absolute"==d)f.y-=c.body.offsetTop;for(b=a;(b=Lc(b))&&b!=c.body&&b!=h;)if(f.x-=b.scrollLeft,!Ca||"TR"!=b.tagName)f.y-=b.scrollTop}a=Mc(a);return new ic(f.x,f.y,a.width,a.height)}function U(a,b){a.style.display=b?"":"none"}
function Pc(a,b){var c=a.currentStyle?a.currentStyle[b]:m,d;if(c)if(/^\d+px?$/.test(c))d=parseInt(c,10);else{d=a.style.left;var e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=d;a.runtimeStyle.left=e;d=c}else d=0;return d};function Qc(a){G.call(this);this.X=a;this.b=[]}B(Qc,G);var Rc=[];function Sc(a,b,c,d,e,f){if(u(c))for(var h=0;h<c.length;h++)Sc(a,b,c[h],d,e,f);else{a:{d=d||a;f=f||a.X||a;e=!!e;if(b=rb(b,c,e))for(c=0;c<b.length;c++)if(!b[c].ea&&b[c].Z==d&&b[c].capture==e&&b[c].qb==f){b=b[c];break a}b=m}b&&(b=b.key,sb(b),hb(a.b,b))}}Qc.prototype.g=function(){Qc.m.g.call(this);J(this.b,sb);this.b.length=0};Qc.prototype.handleEvent=function(){g(Error("EventHandler.handleEvent not implemented"))};function Tc(){}ba(Tc);Tc.prototype.pe=0;Tc.Oa();function V(a){G.call(this);this.ib=a||pc();this.ze=Uc}B(V,bc);V.prototype.$d=Tc.Oa();var Uc=m;p=V.prototype;p.N=m;p.wa=n;p.ba=m;p.ze=m;p.me=m;p.Q=m;p.fb=m;p.Ja=m;p.wd=n;p.Na=function(){return this.N||(this.N=":"+(this.$d.pe++).toString(36))};p.Jc=function(){return this.ba};p.pc=function(a){this.Q&&this.Q!=a&&g(Error("Method not supported"));V.m.pc.call(this,a)};p.Dc=function(){this.ba=this.ib.createElement("div")};
function W(a,b){a.wa&&g(Error("Component already rendered"));if(b){a.wd=k;if(!a.ib||a.ib.D!=rc(b))a.ib=pc(b);a.S(b);a.o()}else g(Error("Invalid element to decorate"))}p.S=function(a){this.ba=a};p.o=function(){this.wa=k;Vc(this,function(a){!a.wa&&a.Jc()&&a.o()})};function Wc(a){Vc(a,function(a){a.wa&&Wc(a)});if(a.pb){var b=a.pb;J(b.b,sb);b.b.length=0}a.wa=n}
p.g=function(){this.wa&&Wc(this);this.pb&&(this.pb.ta(),delete this.pb);Vc(this,function(a){a.ta()});!this.wd&&this.ba&&zc(this.ba);this.Q=this.me=this.ba=this.Ja=this.fb=m;V.m.g.call(this)};function Vc(a,b){a.fb&&J(a.fb,b,j)}
p.removeChild=function(a,b){if(a){var c=x(a)?a:a.Na();a=this.Ja&&c?(c in this.Ja?this.Ja[c]:j)||m:m;if(c&&a){var d=this.Ja;c in d&&delete d[c];hb(this.fb,a);b&&(Wc(a),a.ba&&zc(a.ba));c=a;c==m&&g(Error("Unable to set parent component"));c.Q=m;V.m.pc.call(c,m)}}a||g(Error("Child is not in parent component"));return a};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function Xc(a,b){this.Ca=[];this.Se=a;this.Nd=b||m}p=Xc.prototype;p.va=n;p.Pa=n;p.Nb=n;p.Dd=n;p.nd=n;p.Fd=0;p.Cc=function(a,b){this.Nb=n;Yc(this,a,b)};function Yc(a,b,c){a.va=k;a.mc=c;a.Pa=!b;Zc(a)}function $c(a){a.va&&(a.nd||g(new ad(a)),a.nd=n)}function bd(a){return fb(a.Ca,function(a){return ea(a[1])})}
function Zc(a){a.vc&&(a.va&&bd(a))&&(r.clearTimeout(a.vc),delete a.vc);a.Q&&(a.Q.Fd--,delete a.Q);for(var b=a.mc,c=n,d=n;a.Ca.length&&!a.Nb;){var e=a.Ca.shift(),f=e[0],h=e[1],e=e[2];if(f=a.Pa?h:f)try{var l=f.call(e||a.Nd,b);t(l)&&(a.Pa=a.Pa&&(l==b||l instanceof Error),a.mc=b=l);b instanceof Xc&&(d=k,a.Nb=k)}catch(q){b=q,a.Pa=k,bd(a)||(c=k)}}a.mc=b;d&&(d=b,l=z(a.Cc,a,k),f=z(a.Cc,a,n),d.Ca.push([l,f,j]),d.va&&Zc(d),b.Dd=k);c&&(a.vc=r.setTimeout(function(){g(b)},0))}
function ad(a){cb.call(this);this.Ne=a}B(ad,cb);ad.prototype.message="Deferred has already fired";ad.prototype.name="AlreadyCalledError";function cd(){if(this&&this.kd){var a=this.kd;a&&"SCRIPT"==a.tagName&&dd(a,k,this.Da)}}function dd(a,b,c){c!=m&&r.clearTimeout(c);a.onload=aa;a.onerror=aa;a.onreadystatechange=aa;b&&window.setTimeout(function(){zc(a)},0)}function ed(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);cb.call(this,c);this.code=a}B(ed,cb);function fd(a){this.G={id:0,Ib:m,name:m,Fe:0,fe:n,Td:0};$a(this.G,a);this.cd=0}fd.prototype.Na=function(){return this.G.id};fd.prototype.Lc=function(){return t(this.G.Ib)?this.G.Ib:n};fd.prototype.toString=function(){var a=this.Lc(),b=this.Na();(!t(a)||!a)&&g(Error("storm need wid"));(!t(b)||!b)&&g(Error("storm need id"));var c=["storm://"],d=[];c.push(9<a?a:"0"+a);c.push(this.cd);c.push("0000");c.push(b);d.push(c.join(""));return d.join("||")};
function gd(a){fd.call(this,{id:a.vid,name:a.vname,Fe:a.update_time,fe:a.ispay,Td:a.dzone,Pe:a.flash});this.cd=1;this.we(a)}B(gd,fd);gd.prototype.we=function(a){t(a.v_sub_title)&&(this.G.Ve=a.v_sub_title);t(a.video_time)&&(this.G.time=a.video_time);t(a.location)&&(this.G.location=a.location);t(a.publish_date)&&(this.G.Te=a.publish_date);this.G.Ib="wid"in a?a.wid:0};gd.prototype.Ic=function(){var a=this.G.Ad;return a?a:0};function id(a,b){function c(a){e.push(a)}var d={id:a,format:b},e=[],f=new Lb,h=["Consultation/web.php"],l;for(l in h)c.call(j,h[l]);Va(d,function(a,b){f.set(b,a)});f.set("_random","false");return new Vb(e.join("/"),f)};function jd(a,b){this.Ge=new Fb(a);this.Gd=b?b:"callback";this.Da=5E3}var kd=0;
jd.prototype.send=function(a,b,c,d){var e=a||m,f=d||"_"+(kd++).toString(36)+la().toString(36);r._callbacks_||(r._callbacks_={});a=this.Ge.K();if(e)for(var h in e)(!e.hasOwnProperty||e.hasOwnProperty(h))&&Tb(a,h,e[h]);b&&(r._callbacks_[f]=function(a){ld(f,k);b.apply(j,arguments)},Tb(a,this.Gd,"_callbacks_."+f));var l=a.toString(),q={timeout:this.Da,Jd:k};h=q.document||document;var w=document.createElement("SCRIPT");a={kd:w,Da:j};var s=new Xc(cd,a),A=m;d=q.timeout!=m?q.timeout:5E3;0<d&&(A=window.setTimeout(function(){dd(w,
k);var a=new ed(1,"Timeout reached for loading script "+l);$c(s);Yc(s,n,a)},d),a.Da=A);w.onload=w.onreadystatechange=function(){if(!w.readyState||"loaded"==w.readyState||"complete"==w.readyState)dd(w,q.Jd||n,A),$c(s),Yc(s,k,m)};w.onerror=function(){dd(w,k,A);var a=new ed(0,"Error while loading script "+l);$c(s);Yc(s,n,a)};tc(w,{type:"text/javascript",charset:"UTF-8",src:l});a=h.getElementsByTagName("HEAD");(!a||0==a.length?h.documentElement:a[0]).appendChild(w);s.Ca.push([m,function(){ld(f,n);c&&
c(e)},j]);s.va&&Zc(s);return{N:f,Od:s}};function ld(a,b){r._callbacks_[a]&&(b?delete r._callbacks_[a]:r._callbacks_[a]=aa)};/*
 {@link www.baofeng.com}
*/
function md(){this.i={wc:"Event_Billing",OPEN:"Event_Open",Ya:"Event_Complete",xc:"Event_Error"};this.Yb=n;this.bb="";this.Sb="json";this.height=this.width=0;this.A;this.Je=m}B(md,V);md.TIMEOUT=8E3;function nd(a,b,c,d){b&&(da(c)&&da(d))&&(a.width=c,a.height=d,a.bb=b)}p=md.prototype;
p.Bd=function(a){this.Yb=a.url?k:n;this.dispatchEvent({type:this.i.wc,target:this});if(this.Yb){var b=document.createElement("iframe");b.width=this.width;b.height=this.height;b.scrolling="no";b.frameBorder="no";b.align="center";b.marginHeight="0";b.marginWidth="0";b.src=a.url;M(b,"load",function(){this.dispatchEvent({type:this.i.Ya})},n,this);this.A.appendChild(b)}};p.Kc=function(){return this.Je};p.error=function(a){this.dispatchEvent({type:this.i.xc,target:this,error:a})};
p.S=function(a){this.A=a;if(this.bb&&this.width&&this.height){var b=z(this.Bd,this),c=z(this.error,this);a=md.TIMEOUT;var d=new id(this.bb,this.Sb),d=new jd(d),e=n;a&&(d.Da=a);a=d.send(m,function(a){e=k;b(a)},function(){c("\u8bf7\u6c42\u540e\u7fbf\u7cfb\u7edf\u5f02\u5e38")});C&&(a=a.Od,a.Ca.push([function(){e||c&&c("\u8bf7\u6c42\u540e\u7fbf\u7cfb\u7edf\u5f02\u5e38")},m,j]),a.va&&Zc(a));(new Image).src='http://log.houyi.baofeng.net/logger.php?ltype=wadaction&msg={"id":"'+this.bb+'","adpid":"2"}'}else this.error("\u4f20\u5165\u5e7f\u544a\u9700\u6c42\u53c2\u6570\u4e0d\u5b8c\u6574\u3002")};
p.o=function(){this.dispatchEvent({type:this.i.OPEN,target:this})};new function(){if((this.$a=r.ads)&&0<this.$a.length)for(var a=0,b=this.$a.length;a<b;a++){var c=this.$a[a],d=R(c.element);if(d){var e=new md;nd(e,c.id,c.width,c.height);W(e,d);M(e,e.i.wc,z(function(a,b){b.target.Yb&&U(a,k)},this,d))}}};/*
 {@link www.baofeng.com}
*/
function od(){this.sd=this.ud=this.A=this.Y=m;this.vd="menu";this.td="content";this.Ha="active";this.i="click";this.pa=[];this.M=[];this.pd=m;this.index=0;this.classList=[];this.ca=k}B(od,V);function pd(a,b){var c=jb(b.children),d=m,e;for(e in c)d=c[e],d.Kc=function(){return this},1==d.nodeType&&a.pa.push(c[e])}
od.prototype.Tc=function(a){var b=this;a.target!=this.Y&&("mouseover"==this.i?"mouseout"==a.type&&this.ca?clearTimeout(this.pd):this.ca?this.pd=setTimeout(function(){qd(b,a.target,n)},200):qd(this,a.target,n):qd(this,a.target,n))};od.prototype.Ae=function(a){a=a.index;t(a)&&(da(a)&&0<=a&&a<this.pa.length)&&qd(this,this.M[a],k)};
function qd(a,b,c){b!=a.Y&&(b.className=a.Ha+" "+a.classList[b.index],b.$b.style.display="block",a.dispatchEvent({type:"Event_UpPage",target:a,index:b.index,Le:c}),a.Y.className=""+a.classList[a.Y.index],a.Y.$b.style.display="none",a.Y=b,b.Ub&&(b.Ub=n,O.dispatchEvent({type:"Add_Display",element:b.$b})))}
od.prototype.S=function(a){var b=m;this.A=a;this.ud=sc(this.vd,this.A)[0];this.sd=sc(this.td,this.A)[0];this.M=jb(this.ud.children);a=document.createDocumentFragment();for(var c=0,d=this.pa.length;c<d;c++){b=this.pa[c].Kc();-1==this.M[c].className.indexOf(this.Ha)?(b.style.display="none",this.M[c].Ub=k):(this.index=c,this.Y=this.M[c],this.Y.index=c,this.Y.Ub=n);this.M[c].$b=b;var e=this.M[c].index=c,f=this.M[c].className;RegExp(this.Ha).test(f)&&(f=f.substr(this.Ha.length));this.classList[e]=f;this.classList[c]||
(this.classList[c]="");a.appendChild(b)}this.sd.appendChild(a)};od.prototype.o=function(){for(var a=0,b=this.pa.length;a<b;a++)M(this.M[a],this.i,z(this.Tc,this)),"mouseover"==this.i&&M(this.M[a],"mouseout",z(this.Tc,this));0!=this.pa.length&&(M(this,"Event_SetIndex",z(this.Ae,this)),this.dispatchEvent({type:"Event_Open",target:this}))};function rd(a,b,c){G.call(this);this.cc=a;this.be=b||0;this.X=c;this.Hd=z(this.Sd,this)}B(rd,G);p=rd.prototype;p.N=0;p.g=function(){rd.m.g.call(this);this.stop();delete this.cc;delete this.X};p.start=function(a){this.stop();var b=this.Hd;a=t(a)?a:this.be;ea(b)||(b&&"function"==typeof b.handleEvent?b=z(b.handleEvent,b):g(Error("Invalid listener argument")));this.N=2147483647<a?-1:r.setTimeout(b,a||0)};p.stop=function(){0!=this.N&&r.clearTimeout(this.N);this.N=0};p.Sd=function(){this.N=0;this.cc&&this.cc.call(this.X)};var sd={},td=m;function ud(a){a=y(a);delete sd[a];Ya(sd)&&td&&td.stop()}function vd(){td||(td=new rd(function(){var a=la();Va(sd,function(c){wd(c,a)});Ya(sd)||vd()},20));var a=td;0!=a.N||a.start()};function xd(){G.call(this);this.d=X;this.La=this.startTime=m}B(xd,bc);var X=0;xd.prototype.yb=function(){this.s("begin")};xd.prototype.ya=function(){this.s("end")};xd.prototype.s=function(a){this.dispatchEvent(a)};function yd(a,b,c,d){xd.call(this);(!u(a)||!u(b))&&g(Error("Start and end parameters must be arrays"));a.length!=b.length&&g(Error("Start and end points must be the same length"));this.Va=a;this.Ud=b;this.duration=c;this.Ac=d;this.coords=[];this.We=n}B(yd,xd);p=yd.prototype;p.Hc=0;p.w=0;p.bc=m;
p.play=function(a){if(a||this.d==X)this.w=0,this.coords=this.Va;else if(1==this.d)return n;ud(this);this.startTime=a=la();-1==this.d&&(this.startTime-=this.duration*this.w);this.La=this.startTime+this.duration;this.bc=this.startTime;this.w||this.yb();this.s("play");-1==this.d&&this.s("resume");this.d=1;var b=y(this);b in sd||(sd[b]=this);vd();wd(this,a);return k};p.stop=function(a){ud(this);this.d=X;a&&(this.w=1);zd(this,this.w);this.s("stop");this.ya()};
p.g=function(){this.d==X||this.stop(n);this.s("destroy");yd.m.g.call(this)};function wd(a,b){a.w=(b-a.startTime)/(a.La-a.startTime);1<=a.w&&(a.w=1);a.Hc=1E3/(b-a.bc);a.bc=b;zd(a,a.w);1==a.w?(a.d=X,ud(a),a.s("finish"),a.ya()):1==a.d&&a.hc()}function zd(a,b){ea(a.Ac)&&(b=a.Ac(b));a.coords=Array(a.Va.length);for(var c=0;c<a.Va.length;c++)a.coords[c]=(a.Ud[c]-a.Va[c])*b+a.Va[c]}p.hc=function(){this.s("animate")};p.s=function(a){this.dispatchEvent(new Ad(a,this))};
function Ad(a,b){H.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.Xe=b.coords[2];this.duration=b.duration;this.w=b.w;this.Qe=b.Hc;this.state=b.d;this.Ke=b}B(Ad,H);function Y(a,b,c,d,e){yd.call(this,b,c,d,e);this.element=a}B(Y,yd);Y.prototype.Hb=aa;Y.prototype.hc=function(){this.Hb();Y.m.hc.call(this)};Y.prototype.ya=function(){this.Hb();Y.m.ya.call(this)};Y.prototype.yb=function(){this.Hb();Y.m.yb.call(this)};function Bd(a,b,c,d,e){da(b)&&(b=[b]);da(c)&&(c=[c]);Y.call(this,a,b,c,d,e);(1!=b.length||1!=c.length)&&g(Error("Start and end points must be 1D"))}B(Bd,Y);
Bd.prototype.Hb=function(){var a=this.coords[0],b=this.element.style;"opacity"in b?b.opacity=a:"MozOpacity"in b?b.MozOpacity=a:"filter"in b&&(b.filter=""===a?"":"alpha(opacity="+100*a+")")};Bd.prototype.show=function(){this.element.style.display=""};Bd.prototype.p=function(){this.element.style.display="none"};function Cd(){xd.call(this);this.l=[]}B(Cd,xd);Cd.prototype.add=function(a){gb(this.l,a)||(this.l.push(a),M(a,"finish",this.$c,n,this))};Cd.prototype.remove=function(a){hb(this.l,a)&&qb(a,"finish",this.$c,n,this)};Cd.prototype.g=function(){J(this.l,function(a){a.ta()});this.l.length=0;Cd.m.g.call(this)};function Dd(){Cd.call(this);this.C=0}B(Dd,Cd);
Dd.prototype.play=function(a){if(0==this.l.length)return n;if(a||this.d==X)this.C<this.l.length&&this.l[this.C].d!=X&&this.l[this.C].stop(n),this.C=0,this.yb();else if(1==this.d)return n;this.s("play");-1==this.d&&this.s("resume");this.startTime=la();this.La=m;this.d=1;this.l[this.C].play(a);return k};
Dd.prototype.stop=function(a){this.d=X;this.La=la();if(a)for(a=this.C;a<this.l.length;++a){var b=this.l[a];b.d==X&&b.play();b.d==X||b.stop(k)}else this.C<this.l.length&&this.l[this.C].stop(n);this.s("stop");this.ya()};Dd.prototype.$c=function(){1==this.d&&(this.C++,this.C<this.l.length?this.l[this.C].play():(this.La=la(),this.d=X,this.s("finish"),this.ya()))};var Ed={Ue:k};C&&F(8);function Z(a){return a&&a.Ld&&a.Ld===Ed?a.content:String(a).replace(Fd,Gd)}var Hd={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Gd(a){return Hd[a]}var Fd=/[\x00\x22\x26\x27\x3c\x3e]/g;function Id(a){var b="";a=a.kc;for(var c=a.length,d=0;d<c;d++)var e=a[d],b=b+('<a href="'+Z(e.href)+'" target="_blank">'+Z(e.value)+"</a>");return b};function Jd(a){G.call(this);this.Sa={};this.Ra={};this.X=new Qc(this);this.Q=a}B(Jd,bc);var Kd=[C?"readystatechange":"load","abort","error"];Jd.prototype.start=function(){var a=this.Sa;J(Xa(a),function(b){var c=a[b];if(c&&(delete a[b],!this.hb)){var d;d=this.Q?pc(this.Q).Dc("img"):new Image;var e=this.X,f=this.bd,h=Kd;u(h)||(Rc[0]=h,h=Rc);for(var l=0;l<h.length;l++){var q=M(d,h[l],f||e,n,e.X||e);e.b.push(q)}this.Ra[b]=d;d.id=b;d.src=c}},this)};
Jd.prototype.bd=function(a){var b=a.currentTarget;if(b){if("readystatechange"==a.type)if("complete"==b.readyState)a.type="load";else return;"undefined"==typeof b.naturalWidth&&("load"==a.type?(b.naturalWidth=b.width,b.naturalHeight=b.height):(b.naturalWidth=0,b.naturalHeight=0));this.dispatchEvent({type:a.type,target:b});if(!this.hb&&(a=b.id,delete this.Sa[a],b=this.Ra[a]))delete this.Ra[a],Sc(this.X,b,Kd,this.bd),Ya(this.Ra)&&Ya(this.Sa)&&this.dispatchEvent("complete")}};
Jd.prototype.g=function(){delete this.Sa;delete this.Ra;var a=this.X;a&&"function"==typeof a.ta&&a.ta();Jd.m.g.call(this)};var Ld=m,Md=D||E||Ca||"function"==typeof r.atob;
function Nd(a){var b;if(Md)b=r.btoa(a);else{b=[];for(var c=0,d=0;d<a.length;d++){for(var e=a.charCodeAt(d);255<e;)b[c++]=e&255,e>>=8;b[c++]=e}v(b)||g(Error("encodeByteArray takes an array as a parameter"));if(!Ld){Ld={};for(a=0;65>a;a++)Ld[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}a=Ld;c=[];for(d=0;d<b.length;d+=3){var f=b[d],h=(e=d+1<b.length)?b[d+1]:0,l=d+2<b.length,q=l?b[d+2]:0,w=f>>2,f=(f&3)<<4|h>>4,h=(h&15)<<2|q>>6,q=q&63;l||(q=64,e||(h=64));c.push(a[w],
a[f],a[h],a[q])}b=c.join("")}return b};function Od(a){return 1-Math.pow(1-a,3)};function Pd(){this.rc=m;this.links=[];this.gc=this.gd=this.hd=this.Wa=this.Ia=this.uc=this.tc=this.I=this.J=this.B=this.R=m;this.wb=this.index=0;this.$=[];this.he="change-pic-l";this.ve="change-pic-r";this.Id="change-pic-list";this.le="linksVideo";this.Wc="art-pic-big";this.time=6E3;this.Ee=300;this.qa=6;this.qc=this.page=0;this.Vb=this.Rc=k;this.Gb=this.Ce;this.Ua=new Dd;this.i={OPEN:"Event_Open",xc:"Event_Error",Fa:"Event_Switch"};this.ic="q_"}B(Pd,V);
function Qd(a,b){var c=m,d=a.$[b];a.Wa.className="";for(var e=0,f=a.links.length;e<f;e++)c=a.links[e],c.href=d.href,c.title=d.title,1==e&&(c.innerHTML=a.Gb(d));a.A.style.backgroundColor=d.color;a.rc.style.backgroundImage=d.Sc?"":"url("+d.dd+")";a.R[b].className="cur";a.Wa=a.R[b];a.index++;a.page=Math.ceil(a.index/a.qa)-1;a.dispatchEvent({type:"click",Md:a});a.index>=a.R.length&&(a.index=0);a.Ua.d==X||a.Ua.stop();a.Ua.g();a.Ua.add(new Bd(a.rc,0,1,2E3,Od));a.Ua.play()}p=Pd.prototype;
p.Ce=function(a){return a.title?'<em class="icon-view"></em><span class="tip">'+Z(a.title)+"</span><span>"+Z(a.value)+"</span>":""};
p.De=function(a){return'<p class="tit"><a href="'+Z(a.href)+'" target="_blank">'+Z(a.title)+'</a></p><p class="newest"><a href="'+Z(a.href)+'" target="_blank">'+Z(a.status)+'</a></p><p class="info">\u7c7b\u578b\uff1a'+Id({kc:a.oe})+'</p><p class="info">\u5bfc\u6f14\uff1a'+Id({kc:a.Qd})+'</p><p class="info">\u4e3b\u6f14\uff1a'+Id({kc:a.zd})+'</p><p class="info">\u7b80\u4ecb\uff1a'+Z(a.value)+'</p><p class="mark"><em class="'+Z(a.Sb)+'"></em></p><p class="view"><a href="'+Z(a.href)+'" class="icon-play-btn" target="_blank">\u9a6c\u4e0a\u89c2\u770b</a></p>'};
function Rd(a,b,c,d){var e="";if(a&&b)return e=a.getAttribute(b)||d||"",c&&(e=c(e)),e}p.Pd=function(a){return a.replace(/(^\s+)|(\s+$)/g,"")};function Sd(a,b,c){var d=[],e=m,f=m,h=m;if(!b)return d;h=b.split("|");b=0;for(var l=h.length;b<l;b++)e={},c?(e.value=h[b],e.href=a.ic+Nd(encodeURIComponent(h[b]))):(f=h[b].split("="),e.value=f[0],e.href=f[1]),d.push(e);return d}
p.fc=function(a){switch(a.Md||a.currentTarget){case this.B:0<this.page&&(this.page--,this.I.style.left=-this.page*this.wb+"px",Td(this,this.page*this.qa));break;case this.J:this.page<this.qc&&(this.page++,this.I.style.left=-(this.page*this.wb)+"px",Td(this,this.page*this.qa));break;case this:this.I.style.left=-(this.page*this.wb)+"px"}this.B.Qc=0==this.page?n:k;this.J.Qc=this.page==this.qc?n:k;this.sa({target:this.B,type:Sa.xd});this.sa({target:this.J,type:Sa.xd})};
p.V=function(a){var b=Oc(a),c;if(C){c=Pc(a,"marginLeft");var d=Pc(a,"marginRight"),e=Pc(a,"marginTop");a=Pc(a,"marginBottom");c=new gc(e,d,a,c)}else c=Ic(a,"marginLeft"),d=Ic(a,"marginRight"),e=Ic(a,"marginTop"),a=Ic(a,"marginBottom"),c=new gc(parseFloat(e),parseFloat(d),parseFloat(a),parseFloat(c));b.height+=c.top+c.bottom;b.width+=c.left+c.right;return b};p.ne=function(){var a=this.$[this.index];a.aa?this.Kb():Ud(this,a,this.Kb,this.index)};
p.Kb=function(a){this.Rc&&this.Vb&&(clearTimeout(this.tc),Wd(this));a&&"error"==a.type&&(this.$[a.index].Sc=k);this.$[this.index].aa=k;Qd(this,this.index)};p.re=function(a){a&&"error"==a.type&&(this.$[a.index].Sc=k);this.$[a.index].aa=k;a.index==this.index&&Qd(this,this.index)};
function Ud(a,b,c,d){var e=new Image;e.index=d;C?e.onreadystatechange=function(){if("complete"==this.readyState||"loaded"==this.readyState)c.call(a,{type:"load",index:this.index}),this.onreadystatechange=m}:e.onload=function(){c.call(a,{type:"load",index:this.index})};e.onerror=function(){c.call(a,{type:"error",index:this.index})};e.src=b.dd}function Wd(a){a.tc=setTimeout(function(){a.dispatchEvent({type:a.i.Fa})},a.time)}
function Td(a,b){var c=a.$[b];a.Wa.className="";a.R[b].className="cur";a.Wa=a.R[b];a.index=b;c.aa?a.Kb():Ud(a,c,a.re,a.index)}p.Oc=function(a){var b=a.target,c=this;if("mouseover"==a.type){if("SPAN"==b.nodeName.toUpperCase()||"IMG"==b.nodeName.toUpperCase())clearTimeout(this.tc),clearTimeout(this.uc),this.Vb=n,this.uc=setTimeout(function(){Td(c,b.index)},this.Ee)}else"mouseout"==a.type&&this.U(a,this.Ia)&&(clearTimeout(this.uc),this.Vb=k,Wd(this))};
p.sa=function(a){var b=a.target;a=a.type;var c="change-pic-",c=b==this.B?c+"l":c+"r";b.Qc&&(c="mouseover"==a?c+"02":c+"03");b.className=c};p.U=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement;else if("mouseout"==c)c=a.relatedTarget||a.toElement;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};p.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};p.start=function(a){W(this,R(a))};
p.S=function(a){this.A=a;this.I=T(this.Id,this.A);this.Ia=this.I.parentNode;this.links=sc(this.le,this.A);this.rc=R("switchB");var b=a=m,c=S("a",m,this.I),d=S("img",m,this.I);this.R=S("span",m,this.I);this.gc=this.I.children;this.hd=this.gc[0];this.gd=this.V(this.hd);this.qc=Math.ceil(this.gc.length/this.qa)-1;this.wb=this.gd.width*this.qa;for(var e=0,f=c.length;e<f;e++)b=c[e],a={},a.dd=Rd(b,"data-pic",m,m),a.value=Rd(b,"data-value",m,m),a.color=Rd(b,"data-color",this.Pd,m),a.title=Rd(b,"title",m,
m),a.href=Rd(b,"data-href",m,"http://hd.baofeng.com"),a.status=Rd(b,"data-status",m,m),a.Sb=Rd(b,"data-format",m,m),a.oe=Sd(this,b.getAttribute("data-type")),a.Qd=Sd(this,b.getAttribute("data-director"),this.ic),a.zd=Sd(this,b.getAttribute("data-actor"),this.ic),a.index=e,this.$.push(a),d[e].index=this.R[e].index=e;this.R=c;this.B=T(this.he,this.A);this.J=T(this.ve,this.A);this.Wa=this.R[0]};
p.o=function(){this.R.length<=this.qa?(this.B.style.display="none",this.J.style.display="none",this.Wc&&Q(this.Ia,this.Wc)):this.B&&this.J&&(this.B.style.display="block",this.J.style.display="block",M(this.B,"click",z(this.fc,this)),M(this.J,"click",z(this.fc,this)),M(this.B,"mouseout",z(this.sa,this)),M(this.J,"mouseout",z(this.sa,this)),M(this.B,"mouseover",z(this.sa,this)),M(this.J,"mouseover",z(this.sa,this)));this.I&&(M(this.Ia,"mouseout",z(this.Oc,this)),M(this.Ia,"mouseover",z(this.Oc,this)));
this.dispatchEvent({type:this.i.OPEN,target:this});this.Rc&&(M(this,this.i.Fa,z(this.ne,this)),M(this,"click",z(this.fc,this)),Qd(this,0),Wd(this))};ma("baofeng.component.FocusMap",Pd);Pd.prototype.start=Pd.prototype.start;/*
 {@link www.baofeng.com}
*/
function Xd(){this.ue="data-qusrc";this.Wd="data-ersrc";this.ke="data-level";this.qe="data-none";this.xa=[];this.Fc=[];this.Zb=n;this.od=m;this.index=0;this.aa=200;this.ee=this.ce=n;this.xe="http://box.bfimg.com";this.Vc=0;this.exp=RegExp(this.xe);this.na={zc:"queue",Jb:"erup",Fa:"switch"};this.He=["http://box1.bfimg.com","http://box2.bfimg.com","http://box3.bfimg.com","http://box4.bfimg.com","http://box5.bfimg.com"]}B(Xd,V);p=Xd.prototype;p.start=function(){W(this,document)};
p.eb=function(){for(var a=Yd(),b=a.y+a.height,c=m,d=[],e=this.xa.length-1;-1<e;e--)if(c=this.xa[e],c.top<=b&&c.top+c.height>=a.y)switch(c.type){case this.na.Jb:this.xa.splice(e,1);c.je?(this.Zb=k,c.oa.src=c.src):d.push(c);break;case this.na.zc:this.xa.splice(e,1);Zd(this,c.oa);break;case this.na.Fa:c.Wb||(c.Wb=k)}else c.Wb&&c.type==this.na.Fa&&(c.Wb=n,c.Re.pa.push(j));d.length&&(this.Zb?(this.Fc.push(d),this.Zb=n,setTimeout(z(this.Xc,this),1E3)):this.Xc(d))};
p.Xc=function(a){a=a||this.Fc.shift();for(var b=m,c=0,d=a.length;c<d;c++)b=a[c],b.oa.onerror=function(){this.src=b.url;this.onerror=m;C&&(this.onreadystatechange=m);this.onload=m},C?b.oa.onreadystatechange=function(){if("complete"==this.readyState||"loaded"==this.readyState)this.onreadystatechange=this.onerror=m}:b.oa.onload=function(){this.onload=this.onerror=m},b.oa.src=b.src;a.length=0;a=m};
function Zd(a,b){var c=new Jd,d=$d(a,a.na.zc,a.ue,b);M(c,"complete",function(){for(var a in d)d[a].oa.src=d[a].src;c.g();ub(c,"complete");ub(c,"error");d.length=0;c=d=m});M(c,"error",function(a){d.splice(a.target.id,1)});for(var e in d){var f=d[e].src;(f=x(f)?f:f.src)&&(c.Sa[e]=f)}c.start()}p.ld=function(a){var b;this.ce?(clearTimeout(this.od),this.od=setTimeout(z(this.eb,this),this.aa)):(b=Yd().y,"scroll"==a.type&&50>=Math.abs(b-this.Vc)||(this.Vc=b,this.eb()))};
p.Rd=function(a){a=$d(this,this.na.Jb,this.qe,a.element);Array.prototype.push.apply(this.xa,a);this.eb()};p.V=function(a){var b=a.getBoundingClientRect(),c=Oc(a),d=a.ownerDocument;a=d.body;var e=d.documentElement,d=b.top+(self.pageYOffset||e.scrollTop||a.scrollTop)-(e.clientTop||a.clientTop||0),b=b.left+(self.pageXOffset||e.scrollLeft||a.scrollLeft)-(e.clientLeft||a.clientLeft||0);return{top:0>d?0:d,left:b,width:c.width,height:c.height}};
function Yd(){var a=vc(document),b;b=window.document;b="CSS1Compat"==b.compatMode?b.documentElement:b.body;b=new hc(b.clientWidth,b.clientHeight);return{x:a.x,y:a.y,width:b.width,height:b.height}}function $d(a,b,c,d){var e=[],f=m,h=m,l=m,q=m,w=m;d=d||document;d=S("img",m,d);for(var s=0,A=d.length;s<A;s++)l=d[s],w=l.getAttribute("src"),f=l.getAttribute(c),q=l.getAttribute(a.ke),f&&(a.ee&&(f=ae(a,f)),h=a.V(d[s]),h.src=f,h.url=w,h.oa=l,h.je=q,h.type=b,e.push(h));return e}
function ae(a,b){a.index++;return b.replace(a.exp,function(){return a.He[a.index%5]})}p.S=function(a){a=$d(this,this.na.Jb,this.Wd,a);Array.prototype.push.apply(this.xa,a);this.eb()};p.o=function(){M(r,"scroll",z(this.ld,this));M(r,"resize",z(this.ld,this));M(O,"Add_Display",z(this.Rd,this))};function be(){if((this.id=this.Na())&&0<this.id.length&&1240<=r.screen.width)this.left=yc('<div class="ad-bar-l" style="display: none;"><div class="ad-bar-close"><a href="javascript:void(0)">\u5173\u95ed</a></div></div>'),r.document.body.appendChild(this.left),this.sb=new md,nd(this.sb,this.id,120,270),W(this.sb,this.left),M(this.sb,this.sb.i.Ya,this.ie,n,this),this.right=yc('<div class="ad-bar-r" style="display: none;"><div class="ad-bar-close"><a href="javascript:void(0)">\u5173\u95ed</a></div></div>'),
r.document.body.appendChild(this.right),this.Db=new md,nd(this.Db,this.id,120,270),W(this.Db,this.right),M(this.Db,this.Db.i.Ya,this.ye,n,this),M(r,"resize",this.lc,n,this),"hddl"==this.id&&(Q(this.left,"ad-bar-bottom"),Q(this.right,"ad-bar-bottom"))}be.prototype.Na=function(){return r.ad_dl_id};be.prototype.ie=function(){this.lc();M(this.left,"click",function(a){"A"===a.target.nodeName&&zc(this.left)},n,this);setTimeout(z(function(){U(this.left,k)},this),500)};
be.prototype.ye=function(){this.lc();M(this.right,"click",function(a){"A"===a.target.nodeName&&zc(this.right)},n,this);setTimeout(z(function(){U(this.right,k);var a=document,b={type:"showRightBannerAd",target:document},c=K;"showRightBannerAd"in c&&(c=c.showRightBannerAd,n in c&&vb(c[n],a,"showRightBannerAd",n,b))},this),500)};
be.prototype.lc=function(){var a=Mc(r.document.body);1240<a.width?(Gc(this.left,{left:(a.width-1220)/2+"px"}),Gc(this.right,{right:(a.width-1220)/2+"px"})):(Gc(this.left,{left:"10px"}),Gc(this.right,{right:"10px"}))};new be;function ce(){this.ab=new md;this.element=yc('<div class="ad-pop-wrap" style="display: none;"><div class="ad-pop-close"><a href="javascript:void(0)">\u5173\u95ed</a></div></div>');r.document.body.appendChild(this.element);nd(this.ab,"hdtips",300,250);W(this.ab,this.element);M(this.ab,this.ab.i.Ya,this.Be,n,this)}ce.prototype.Be=function(){M(this.element,"click",function(a){"A"===a.target.nodeName&&zc(this.element)},n,this);setTimeout(z(function(){U(this.element,k)},this),500)};new ce;function de(){};function ee(){}B(ee,de);ee.prototype.clear=function(){var a;a=this.Ga(k);if(v(a))a=jb(a);else{a=Ab(a);var b=[],c=function(a){b.push(a)};if(v(a))try{J(a,c,j)}catch(d){d!==yb&&g(d)}else{a=Ab(a);try{for(;;)c.call(j,a.next())}catch(e){e!==yb&&g(e)}}a=b}var f=this;J(a,function(a){f.remove(a)})};function fe(a){this.z=a}B(fe,ee);p=fe.prototype;p.set=function(a,b){try{this.z.setItem(a,b)}catch(c){0==this.z.length&&g("Storage mechanism: Storage disabled"),g("Storage mechanism: Quota exceeded")}};p.get=function(a){a=this.z.getItem(a);!x(a)&&a!==m&&g("Storage mechanism: Invalid value was encountered");return a};p.remove=function(a){this.z.removeItem(a)};
p.Ga=function(a){var b=0,c=this.z,d=new zb;d.next=function(){b>=c.length&&g(yb);var d=c.key(b++);if(a)return d;d=c.getItem(d);x(d)||g("Storage mechanism: Invalid value was encountered");return d};return d};p.clear=function(){this.z.clear()};p.key=function(a){return this.z.key(a)};function ge(){var a=m;try{a=window.localStorage||m}catch(b){}this.z=a}B(ge,fe);function he(){var a=m;try{a=window.sessionStorage||m}catch(b){}this.z=a}B(he,fe);function ie(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))}function je(a){return ke(new le(j),a)}function le(a){this.Bb=a}function ke(a,b){var c=[];me(a,b,c);return c.join("")}
function me(a,b,c){switch(typeof b){case "string":ne(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if(u(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],me(a,a.Bb?a.Bb.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),ne(f,c),c.push(":"),
me(a,a.Bb?a.Bb.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}}var oe={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},pe=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function ne(a,b){b.push('"',a.replace(pe,function(a){if(a in oe)return oe[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return oe[a]=e+b.toString(16)}),'"')};function qe(a){this.Ta=a;this.md=new le}p=qe.prototype;p.Ta=m;p.md=m;p.set=function(a,b){t(b)?this.Ta.set(a,ke(this.md,b)):this.Ta.remove(a)};p.get=function(a){a=this.Ta.get(a);if(a!==m)try{return ie(a)}catch(b){g("Storage: Invalid value was encountered")}};p.remove=function(a){this.Ta.remove(a)};function re(a){qe.call(this,a)}B(re,qe);function se(a){this.data=a}re.prototype.set=function(a,b){re.m.set.call(this,a,!t(b)||b instanceof se?b:new se(b))};re.prototype.get=function(a){var b;a=re.m.get.call(this,a);!t(a)||a instanceof Object?b=a:g("Storage: Invalid value was encountered");b?(b=b.data,t(b)||g("Storage: Invalid value was encountered")):b=j;return b};function te(a){if(ue)return ue;a=a?new he:new ge;this.cookie=new Zb(r.document);var b;if(a.z)try{a.z.setItem("__sak","1"),a.z.removeItem("__sak"),b=k}catch(c){b=n}else b=n;b?(this.T=new re(a),this.Xb=k):this.T=this.cookie;ue=this}var ue;te.prototype.set=function(a,b){a&&this.T.set.apply(this.T,kb(arguments,0))};te.prototype.get=function(a){if(a)return this.T.get.apply(this.T,kb(arguments,0))};
te.prototype.clear=function(){this.Xb&&this.T.remove.apply(this.T,kb(arguments,0));this.cookie.set.apply(this.cookie,kb(arguments,0))};te.prototype.remove=function(a){a&&this.T.remove.apply(this.T,kb(arguments,0))};function ve(a){this.dc=a||15;this.key="bfViewRecords";this.O=7776E3;this.path="/";this.domain=".baofeng.com";this.h=ue?ue:new te(j);if(this.h.Xb){a=0;for(var b=we(this.h.cookie.get(this.key));a<b.length;a++)this.add(b[a])}}ba(ve);function xe(a){var b="",c;for(c in a)b+=c+"="+encodeURIComponent(a[c])+"&";return b=b.substring(0,b.length-1)}p=ve.prototype;p.list=function(){return we(this.h.get(this.key))};p.W=function(){return this.h.get(this.key)};
p.map=function(){for(var a=this.list(),b={},c=0,d=a.length;c<d;c++)b[a[c].id]=a[c];return b};function we(a){var b=[];a=a||"";if(0===a.length)return b;a=a.split(",");for(var c=0,d=a.length;c<d;c++){for(var e={},f=a[c].split("&"),h=0,l=f.length;h<l;h++){var q=f[h].split("=");e[q[0]]=2==q.length?decodeURIComponent(q[1]):m}b.push(e)}return b}p.Tb=function(a){for(var b=0,c=this.list();b<c.length;b++)if(c[b].id==a)return c[b];return m};
p.add=function(a){for(var b=this.list(),c="",d=n,e=0,f=b.length;e<f;e++)b[e].id==a.id?d=k:c+=xe(b[e])+",";b.length>=this.dc&&d===n&&(c=c.substring(c.indexOf(",")+1));c+=xe(a);this.h.set(this.key,c,this.O,this.path,this.domain);d||this.n("Event_Record","ADD",a.id)};p.Rb=function(a){for(var b=this.list(),c=n,d="",e=0,f=b.length;e<f;e++)b[e].id==a?c=k:d+=xe(b[e])+",";c&&(d=d.substr(0,d.length-1),this.h.set(this.key,d,this.O,this.path,this.domain),this.n("Event_Record","DEL",a))};
p.remove=function(){this.h.clear(this.key,"",this.O,this.path,this.domain)};p.clear=function(){this.h.clear(this.key,"",this.O,this.path,this.domain);this.n("Event_Record","DEL","")};p.n=function(a,b,c){O.dispatchEvent({type:a,kind:b,id:c})};function ye(a,b){this.anchor=a;this.k=b;this.Lb="expd";this.ha=[]}B(ye,V);p=ye.prototype;p.nc=function(a){this.anchor=a};p.Za=function(a){this.ha.push(a)};p.o=function(){M(this.anchor,"mouseover",z(this.show,this,k));M(this.anchor,"mouseout",z(this.p,this,50));M(this.k,"mouseover",z(this.show,this));M(this.k,"mouseout",z(this.p,this,50))};p.show=function(){this.f&&(clearTimeout(this.f),this.f=m);for(var a=0,b=this.ha.length;a<b;a++)U(this.ha[a],n);U(this.k,k);Q(this.anchor,this.Lb)};
p.p=function(a){this.f&&(clearTimeout(this.f),this.f=m);a&&0<a?this.f=setTimeout(z(this.p,this),a):(U(this.k,n),lc(this.anchor,this.Lb))};var ec={active:{name:"\u64ad\u653e\u63a7\u4ef6\u76f8\u5173",infor:"\u6709\u7f51\u9875\u64ad\u653e\u7ec4\u4ef6 \u65e0\u7f51\u9875\u64ad\u653e\u7ec4\u4ef6 \u6709\u5c0f\u5305 \u65e0\u5c0f\u5305 \u7406\u8bba\u5f39\u51fa\u9ec4\u6761\u6570 \u4e2d\u5305\u5c1d\u8bd5\u4e0b\u8f7d \u4e2d\u5305\u5f00\u59cb\u4e0b\u8f7d \u4e2d\u5305\u4e0b\u8f7d\u5931\u8d25 \u4e2d\u5305\u4e0b\u8f7d\u6210\u529f \u4e2d\u5305\u5b89\u88c5\u6210\u529f \u4e2d\u5305\u5b89\u88c5\u5931\u8d25 \u64ad\u653e\u5668\u4e0b\u65b9\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570clickonce\u4e0b\u8f7d \u64ad\u653e\u5668\u4e2d\u592e\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570clickonce\u4e0b\u8f7d \u64ad\u653e\u5668\u5e95\u90e8\u6587\u5b57\u94fe\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570clickonce\u4e0b\u8f7d \u975eie\u64ad\u653e\u5668\u4e0b\u65b9\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570 \u975eIE\u64ad\u653e\u5668\u5e95\u90e8\u6587\u5b57\u94fe\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570 \u64ad\u653e\u5668\u4e0b\u65b9\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570GUI\u4e0b\u8f7d \u64ad\u653e\u5668\u4e2d\u592e\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570GUI\u4e0b\u8f7d \u64ad\u653e\u5668\u5e95\u90e8\u6587\u5b57\u94fe\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570GUI\u4e0b\u8f7d".split(" "),
bfinfo:[{pagesstate:1},{pagesstate:2},{lbstate:1},{lbstate:2},{yellowpop:1},{mbtry:1},{mbbegin:1},{mbfail:1,value:1},{mbsuccess:1},{mbsetup:1},{mbsetup:1,value:1},{linkdownload:2},{setupdownload:2},{linkdownload:2},m,m,{linkdownload:1},{setupdownload:1},{linkdownload:1}]},webplayer:{name:"\u64ad\u653e\u76f8\u5173",infor:"onPlayerOpen onPlayerPlay onPlayerPause OnPlayerPlayStart onPlayerFinish onPlayerOpenFail onPlayerClose onPlayerStop".split(" ")},flashplayer:{name:"flash\u64ad\u653e\u76f8\u5173",
infor:"\u5f00\u59cb\u64ad\u653eclickonce\u4e0b\u8f7d \u5c1d\u8bd5\u64ad\u653e \u64ad\u653e\u6210\u529f \u7f13\u51b2\u65f6\u95f4 \u9519\u8bef \u64ad\u653e\u6682\u505c \u5931\u8d25FLASH\u7684\u4e0b\u8f7d\u6309\u94aeclickonce\u4e0b\u8f7d \u64ad\u653e\u5b8c\u6210 flash\u52a0\u8f7d\u8d85\u65f6\u5931\u8d25 flash\u52a0\u8f7d\u8d85\u65f6\u5931\u8d25 \u5931\u8d25FLASH\u7684\u4e0b\u8f7d\u6309\u94aeGUI\u4e0b\u8f7d \u5f00\u59cb\u64ad\u653eGUI\u4e0b\u8f7d \u89c6\u9891cid \u7248\u672c\u53f7 flash\u89c2\u770b\u65f6\u957f \u5361\u987f\u6b21\u6570 flash\u64ad\u653e\u5668\u7248\u672c\u53f7".split(" "),
bfinfo:[{playdownload:2},{flshtry:1},{flashsuccess:1,key:"flashsuccess"},{flashloadtime:1,key:"flashloadtime"},{flasherr:1,key:"flasherr"},m,{faildownload:2},m,m,m,{faildownload:1},{playdownload:1},{flashiid:1,key:"flashiid"},{flashver:1,key:"flashver"},{flashtime:1,key:"flashtime"},{flashbuffrtempty:1,key:"flashbuffrtempty"}]},houyi:{name:"\u540e\u7fbf\u5e7f\u544a",infor:"\u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u603b\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u6210\u529f \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u5931\u8d25 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u6210\u529f\u6709\u5e7f\u544a \u64ad\u653e\u5668\u53f3\u4fa7\u5e7f\u544a\u88ab\u52a8\u5c55\u73b0\u6b21\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u5e7f\u544a\u4e3b\u52a8\u5c55\u73b0\u6b21\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u5c1d\u8bd5\u8bf7\u6c42\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u6210\u529f\u65e0\u5e7f\u544aURL".split(" "),
bfinfo:[m,{hyrequest:1},m,{hyadrequest:1},{addisplay:2},{addisplay:1},m,{hyadrequest:0,value:0}]},b3:{name:"B3\u5224\u65ad",infor:"B3\u5c1d\u8bd5\u8bf7\u6c42\u603b\u6570 B3\u8bf7\u6c42\u6210\u529f\u6570 B3\u8bf7\u6c42\u5931\u8d25\u6570 B3\u5224\u65ad\u6b63\u7247\u53ef\u64ad B3\u5224\u65ad\u6b63\u7247\u4e0d\u53ef\u64ad\u64ad\u7247\u82b1 \u64ad\u653e\u9884\u544a\u7247 B3\u5224\u65ad\u5f71\u7247\u8d44\u6e90\u4e0d\u5b58\u5728".split(" "),bfinfo:[{b3request:1,value:0},{b3state:1,value:0},{b3state:2,value:0},
{b3judge:1,value:0},{b3judge:2,value:0},m,{b3fail:1,value:0}]},noIE:{name:"\u975eIE\u6d4f\u89c8\u5668",infor:["\u4f7f\u7528ie\u6d4f\u89c8\u5668\u6dfb\u52a0\u6536\u85cf","\u4f7f\u7528\u975eie\u6d4f\u89c8\u5668\u6dfb\u52a0\u6536\u85cf","IE\u6d4f\u89c8\u5668","\u975eIE\u6d4f\u89c8\u5668"],bfinfo:[{exfav:0},{exfav:1}]},other:{name:"\u76f8\u5173\u63a5\u53e3",infor:"\u8bc4\u8bba\u8bf7\u6c42\u603b\u6570 \u8bc4\u8bba\u6210\u529f\u5c55\u73b0\u6570 \u8bc4\u8bba\u8bf7\u6c42\u5931\u8d25\u6570 MINFO\u8bf7\u6c42\u603b\u6570 MINFO\u8bf7\u6c42\u6210\u529f MINFO\u8bf7\u6c42\u5931\u8d25".split(" "),
bfinfo:[{comrequest:1},{comstate:1},{comstate:2},{minforequest:1},{minfostate:1},{minfostate:2}]},buttonClick:{name:"\u6309\u94ae\u70b9\u51fb",infor:"\u89c2\u770b\u8bb0\u5f55\u6d6e\u5c42\u5c55\u73b0\u6b21\u6570 \u89c2\u770b\u8bb0\u5f55\u70b9\u51fb\u6570 \u6dfb\u52a0\u5feb\u6377\u65b9\u5f0f\u6309\u94ae\u70b9\u51fb\u6570 \u5267\u96c6\u6309\u94ae\u70b9\u51fb\u6570 \u5267\u96c6\u533a\u95f4\u70b9\u51fb\u6570 \u5267\u96c6\u683c\u5f0f\u5207\u6362\u70b9\u51fb\u6570 \u5267\u96c6\u5c55\u5f00\u70b9\u51fb\u6570 \u5267\u96c6\u6536\u8d77\u70b9\u51fb\u6570 \u64ad\u653e\u5668\u4e0b\u65b9\u76f8\u5173\u63a8\u8350\u70b9\u51fb\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u76f8\u5173\u63a8\u8350\u70b9\u51fb\u6570".split(" ")},
tyg:{name:"\u4f53\u9a8c\u9986",infor:["\u4f53\u9a8c\u99863D\u5f71\u7247\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570","\u4f53\u9a8c\u9986\u5de6\u773c\u5f71\u7247\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570","\u4f53\u9a8c\u9986\u5b89\u88c5\u66b4\u98ce\u7ec4\u4ef6\u70b9\u51fb\u6570clickOnce","\u4f53\u9a8c\u9986\u540e\u64ad\u63a8\u8350\u70b9\u51fb\u6570","\u4f53\u9a8c\u9986\u5b89\u88c5\u66b4\u98ce\u7ec4\u4ef6\u70b9\u51fb\u6570GUI"],bfinfo:[m,m,{testsetup:2},m,{testsetup:1}]},jizhi:{name:"\u6781\u81f4\u529f\u80fd\u6309\u94ae\u4f7f\u7528",
infor:["3D\u6309\u94ae\u70b9\u51fb\u6570","\u5de6\u773c\u6309\u94ae\u70b9\u51fb\u6570","\u53f3\u8033\u6309\u94ae\u70b9\u51fb\u6570","IE\u4e0d\u652f\u6301\u6781\u81f4\u529f\u80fd","\u975eIE\u4e0d\u652f\u6301\u6781\u81f4\u529f\u80fd"],bfinfo:[{acmestate:1},{acmestate:2},{acmestate:3},{acmestate:4},{acmestate:5}]},search:{name:"\u641c\u7d22\u76f8\u5173\u62a5\u6570",infor:["\u70b9\u51fb\u641c\u7d22\u6309\u94ae","\u5c1d\u8bd5\u641c\u7d22"],bfinfo:[{tsearch:1},{tsearch:1}]},detail:{name:"\u8be6\u60c5\u9875\u76f8\u5173\u6570",
infor:["\u8be6\u60c5\u9875\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570","\u8be6\u60c5\u9875\u5408\u4f5c\u65b9\u89c6\u9891\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570"],bfinfo:[{playstate:1},{playstate:2}]},movie:{name:"\u5f71\u7247\u64ad\u653e",infor:["\u901a\u8fc7\u5ba2\u6237\u7aef\u64ad\u653e","\u901a\u8fc7\u7f51\u9875\u64ad\u653e"],bfinfo:[{playstate:2},{playstate:1}]},micvideo:{name:"\u5fae\u89c6\u9891\u9996\u9875",infor:["\u4eca\u65e5\u5173\u6ce8","\u5a31\u4e50\u661f\u95fb","\u7f51\u7edc\u70ed\u8bae",
"\u5c4c\u4e1d\u5b85\u7537","\u7206\u7b11\u63a8\u8350"],bfinfo:[{"\u4eca\u65e5\u5173\u6ce8":2},{"\u5a31\u4e50\u661f\u95fb":2},{"\u7f51\u7edc\u70ed\u8bae":2},{"\u5c4c\u4e1d\u5b85\u7537":2},{"\u7206\u7b11\u63a8\u8350":2}]},baiduvip:{name:"\u767e\u5ea6VIP",infor:["\u767e\u5ea6VIP\u7528\u6237"],bfinfo:[{baiduvip:1}]}};function ze(){this.ha=[]}B(ze,V);p=ze.prototype;p.nc=function(a){this.anchor=a};p.Za=function(a){this.ha.push(a)};p.S=function(a){this.k=a;this.ae=T("innerBox",this.k);this.Yc=T("menuHolder",this.ae);this.Mc=S("iframe",j,this.Yc)[0];this.ob=T("frame",this.Yc);this.Kd=T("empty",this.ob);this.xb=T("his-none",this.ob);this.tb=T("his-cont",this.ob);this.list=S("ul",j,this.ob)[0]};
p.o=function(){M(this.k,"mouseover",z(this.show,this));M(this.k,"mouseout",z(this.p,this,50));M(this.anchor,"mouseover",z(this.show,this,k));M(this.anchor,"mouseout",z(this.p,this,50));M(this.Kd,"click",z(this.clear,this));M(this.list,"click",z(this.Zd,this))};p.log=function(a,b,c){O.dispatchEvent({type:"log",data:{key:a,value:b,other:c}})};
p.show=function(a){this.f?(clearTimeout(this.f),this.f=m):this.log("buttonClick",1);for(var b=0,c=this.ha.length;b<c;b++)U(this.ha[0],n);U(this.k,k);Q(this.anchor,"expd");if(a===k)if(a=this.Ea.list().reverse(),0>=a.length)U(this.xb,k),U(this.tb,n);else{U(this.xb,n);U(this.tb,k);var d="",e=0,f=a.length;for(template='<li  id="${recordId}"><a title=${title} class="his-reco">${recordName}</a><a class="continueButton">\u7ee7\u7eed\u89c2\u770b</a><span class="closed"></span></li>';e<f;e++){b=a[e];c=b.name;
recordId=b.id;if(!b.type||!("5"===b.type||"1"===b.type))"undefined"!==typeof b.loc&&"null"!=b.loc?c+=" \u7b2c"+b.loc+"\u671f":"undefined"!==typeof b.drama&&"null"!=b.drama&&(c+=" \u7b2c"+b.drama+"\u96c6");d+=template.replace("${title}",c).replace("${recordName}",c).replace("${recordId}","record-"+recordId)}this.list.innerHTML=d;this.Mb()}};p.Qa=function(a){console.log(a.target)};p.p=function(a){a&&0<a?this.f=setTimeout(z(this.p,this),a):(U(this.k,n),lc(this.anchor,"expd"))};
p.Mb=function(){for(var a=0,b=this.list.children.length;a<b;a++){var c=this.list.children[a];M(c,"mouseover",z(this.Ka,this));M(c,"mouseout",z(this.Ka,this))}};p.Ka=function(a){var b=a.currentTarget;"mouseover"==a.type&&this.U(a,b)?b.className="cur":"mouseout"==a.type&&this.U(a,b)&&(b.className="")};
p.U=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement||k;else if("mouseout"==c)c=a.relatedTarget||a.toElement||k;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};p.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};
p.Zd=function(a){a.preventDefault();a=a.target;var b;if("continueButton"===a.className||"his-reco"===a.className){b=this.Ea.Tb(a.parentNode.id.split("-")[1]);var c="/play/"+b.id%500+"/play-"+b.id;"5"===(b.type||"-1")?(c="",b.wid&&"13"!=b.wid&&(c="-"+b.wid),c="/micv/"+b.id%500+"/micv-"+b.id+c+"-vid-"+b.vid+".html"):("undefined"!==typeof b.drama&&"null"!=b.drama&&(c+="-drama-"+b.drama),"undefined"!==typeof b.format&&"null"!=b.format&&(c+="-format-"+b.format),"undefined"!==typeof b.trailer&&"null"!=
b.trailer&&(c+="-trailer-"+b.trailer),c+=".html");b=c;U(this.k,n);r.open(b,"_blank");this.log("buttonClick",2)}"closed"==a.className&&(b=this.Ea.Tb(a.parentNode.id.split("-")[1]),(b=b.id)&&this.Ea.Rb(b),0==this.Ea.list().length&&(U(this.tb,n),U(this.xb,k)),a.parentNode.parentNode.removeChild(a.parentNode))};p.clear=function(){this.Ea.clear();U(this.tb,n);U(this.xb,k)};function Ae(a){a=a||{};var b=this.j={jb:"hd-load-text-on",aa:50},c;for(c in a)b[c]=a[c];(!this.j.anchor||!this.j.content)&&this.dispatchEvent({type:"error",message:"hd.component.Popup params must contains anchor and content"})}B(Ae,V);
Ae.prototype.o=function(){try{M(this.j.anchor,"mouseover",this.show,n,this),M(this.j.anchor,"mouseout",z(this.p,this,this.j.aa)),M(this.j.content,"mouseover",this.show,n,this),M(this.j.content,"mouseout",z(this.p,this,this.j.aa))}catch(a){this.dispatchEvent({type:"error",message:"enterDocument method error"})}};Ae.prototype.show=function(){this.f&&(clearTimeout(this.f),this.f=m);this.j.jb&&Q(this.j.anchor,this.j.jb);U(this.j.content,k);this.dispatchEvent("show")};
Ae.prototype.p=function(a){this.f&&(clearTimeout(this.f),this.f=m);a&&0<a?this.f=setTimeout(z(this.p,this),a):(this.j.jb&&lc(this.j.anchor,this.j.jb),U(this.j.content,n),this.dispatchEvent("hide"))};function Be(a,b){O.dispatchEvent({type:"log",data:{key:"movie",value:a,other:b}})};function Ce(){this.Eb="\u8bf7\u8f93\u5165\u5f71\u7247\u540d\u3001\u5173\u952e\u5b57";this.Uc=r.static_keyword||""}B(Ce,V);p=Ce.prototype;p.S=function(a){this.k=a;this.form=S("form",j,this.k)[0];a=S("input",j,this.form);this.input=a[0];this.button=a[1];this.q=S("div",j,this.k)[1];this.Mc=S("iframe",j,this.q)[0];this.Ab=S("div",j,this.q)[0]};p.log=function(a,b,c){O.dispatchEvent({type:"log",data:{key:a,value:b,other:c}})};
p.ge=function(a){a=a.keyCode;var b=this.input.value;if(0>=b.length)U(this.q,n);else if(("38"==a||"40"==a)&&"none"!=this.Ab.style.display){var c=Ac(this.Ab),d=c.length;if(0<d)if("none"!=this.q.style.display===n)U(this.q,k);else{for(var e=-1,d=c.length,f=0;f<d;f++){var h=c[f];gb(kc(h),"selected")&&(e=f);lc(h,"selected")}e="38"==a?e-1:e+1;0>e&&(e=d-1);e>d-1&&(e=0);Q(c[e],"selected")}}else{var l=z(function(a){var c=this.input.value;if(c===b)if(0<c.length&&0<a.length){for(var c="",d=["\u7535\u5f71","\u7535\u89c6\u5267",
"\u52a8\u6f2b","\u7efc\u827a"],e=0,f=a.length;e<f;e++){var h=a[e],l=h.name,Ob="\u7535\u5f71",qa=parseInt(h.channel);isNaN(qa)===n&&(1<qa&&5>qa)&&(Ob=d[qa-1]);c+='<a href="javascript:void(0);" onclick="return false;">'+l+"<span>("+Ob+")</span></a>";if(0===e&&"\u7535\u5f71"!==Ob&&"undefined"!==typeof h.drama){var qa=h.id,Oe=h.wid,Pe=h.aid,Qe=h.vid,Vd=h.drama;(h=h.sub_title)||(h=Vd);c+='<a href="javascript:void(0);" onclick="return false;" class="search-suggest-detail"';c+=' m-id="'+qa+'"';c+=' m-wid="'+
Oe+'"';c+=' m-aId="'+Pe+'"';c+=' m-vId="'+Qe+'"';c+=' m-drama="'+Vd+'"';c="\u7efc\u827a"===Ob?c+(">\u6700\u65b0\u4e00\u671f("+h+")</a>"):c+(">\u6700\u65b0\u4e00\u96c6("+h+")</a>");c+='<a href="javascript:void(0);" onclick="return false;" class="search-suggest-info" m-id="'+qa+'">'+l+"\u8be6\u60c5</a>";f=Math.min(f,6)}}0<c.length?(this.Ab.innerHTML=c,U(this.q,k),c=Mc(this.q).height,a=this.Mc.style,"number"==typeof c&&(c=Math.round(c)+"px"),a.height=c):U(this.q,n)}else U(this.q,n)},this);a="http://search.hd.baofeng.com/prompt.php?query=${keyword}&start=0&limit=8".replace("${keyword}",
encodeURIComponent(b));a=new jd(a);a.Da=8E3;a.send(m,function(a){a?l(a.results):l(m)},function(){l(m)})}};
function De(a,b){if(b)if(gb(kc(b),"search-suggest-detail")){var c=b.getAttribute("m-id"),d=b.getAttribute("m-wid"),e=b.getAttribute("m-aid"),f=b.getAttribute("m-vid"),h=b.getAttribute("m-drama");if("13"==d){var l=c;Be(2,l);l="/play/"+l%500+"/play-"+l;h&&(l+="-drama-"+h);r.open(l+".html","_blank")}else{h=new gd({id:f,Ib:d});h.G.Ad=Number(e);var q="";fa(h)?(Be(1,h.Lc()),q=h.toString(),h.Ic&&(h=h.Ic())&&0!==h&&(q+="||aid="+h)):q=h;h=function(){var a=document.createElement("iframe");U(a,n);tc(a,{src:q});
document.writeln(" ");
document.body.appendChild(a)};e=function(){alert("\u672c\u7247\u9700\u8981\u4f7f\u7528\u66b4\u98ce\u5ba2\u6237\u7aef\u64ad\u653e\uff0c\u5982\u679c\u60a8\u5df2\u5b89\u88c5\uff0c\u60a8\u5c06\u4f7f\u7528\u5ba2\u6237\u7aef\u64ad\u653e\uff0c\u5982\u679c\u6ca1\u6709\uff0c\u8bf7\u5230\u5b98\u7f51www.baofeng.com\u4e0b\u8f7d\u3002")};if(C)try{l=new ActiveXObject("StormAxPlayer.Player"),/8\d$/.test(l.Version)?e():setTimeout(h,100)}catch(w){e()}else setTimeout(h,100),setTimeout(e,200)}}else gb(kc(b),"search-suggest-info")?
(c=b.getAttribute("m-id"),r.open("/detail/"+c%500+"/detail-"+c+".html","_blank")):(l=Ec(b),l=l.substring(0,l.lastIndexOf("(")),a.search(l));else a.search()}p.search=function(a){"undefined"===typeof a&&(a=this.input.value);a=encodeURIComponent(na(a));if(0<a.length){U(this.q,n);var b="_blank";0<=r.location.href.indexOf("q_")&&(b="_self");r.open("/q_"+Nd(a),b)}};/*
 {@link www.baofeng.com}
*/
function Ee(){this.name=this.id=m;this.Ma=0;this.title=this.v=this.element=m;this.mb="";this.ca=k;this.Fb=[" fv-add"," shadow-cut"];this.kb=""}B(Ee,V);p=Ee.prototype;p.U=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement;else if("mouseout"==c)c=a.relatedTarget||a.toElement;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};p.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};
p.start=function(a){var b=this;this.element=a;this.v=T("fv-add-no",a);this.id=a.getAttribute("data-id");this.kb=a.getAttribute("data-farther")||"";this.id&&this.v&&(this.mb=a.className.replace(/fv-cut|shadow-cut/gi,function(a){"fv-cut"==a&&(b.Fb[1]=" fv-cut");return""}),W(this,a))};
p.ec=function(a){var b;switch(a.type){case "mouseover":Fe(this,a.target,1);this.ca&&(this.ca=n,this.element.className=this.mb+this.Fb[0]);break;case "mouseout":Fe(this,a.target,0);!this.ca&&this.U(a,this.element)&&(this.ca=k,this.element.className=this.mb+this.Fb[1]);break;case "click":a=a.target,a==this.v?(this.Ma?(a={type:"Event_Collect",kind:"DEL",id:this.id},b=0):(a={type:"Event_Collect",kind:"ADD",data:{id:this.id,name:this.name,element:this.v}},b=1),Ge(this,b),this.dispatchEvent(a)):"IMG"==
a.tagName.toUpperCase()&&"A"==a.parentNode.tagName.toUpperCase()&&(this.ca=k,this.element.className=this.mb+this.Fb[1])}};function Fe(a,b,c){!a.Ma&&b==a.v&&(a.v.className=c?"fv-add-Keep "+a.kb:"fv-add-no")}function Ge(a,b){a.Ma=b;a.Ma?(a.v.title="\u53d6\u6d88\u6536\u85cf",a.kb&&(a.v.innerHTML="\u5df2\u6536\u85cf"),a.v.className="fv-add-Keep"):(a.v.title="\u6536\u85cf",a.kb&&(a.v.innerHTML="\u6536\u85cf"),a.v.className="fv-add-no")}p.S=function(a){this.name=a.getAttribute("data-name")};
p.o=function(){M(this.element,"mouseout",z(this.ec,this));M(this.element,"mouseover",z(this.ec,this));M(this.element,"click",z(this.ec,this))};function He(a){this.dc=a||15;this.key="bfCollects";this.O=7776E3;this.path="/";this.domain=".baofeng.com";this.h=ue?ue:new te(j);if(this.h.Xb){var b=this.h.cookie.get(this.key)||"[]";a=0;for(b=ie(b);a<b.length;a++)this.add(b[a])}}ba(He);p=He.prototype;p.list=function(){var a=this.h.get(this.key)||"[]";return ie(a)};p.W=function(){return this.h.get(this.key)};p.map=function(){for(var a=this.list(),b={},c=0,d=a.length;c<d;c++)b[a[c].id]=a[c];return b};
p.Tb=function(a){for(var b=0,c=this.list();b<c.length;b++)if(c[b].id==a)return c[b];return m};p.add=function(a){var b=this.list(),c=0;b.length>=this.dc&&(c=b.shift().id);b.push(a);this.h.set(this.key,je(b),this.O,this.path,this.domain);return c};function Ie(a,b,c){for(var d=a.list(),e=n,f=0,h=d.length;f<h;f++)if(d[f].id==b){e=k;d[f].lb=c;break}e&&a.h.set(a.key,je(d),a.O,a.path,a.domain)}
p.Rb=function(a){for(var b=this.list(),c=n,d=0,e=b.length;d<e;d++)if(b[d].id==a){b.splice(d,1);c=k;break}c&&this.h.set(this.key,je(b),this.O,this.path,this.domain)};p.clear=function(){this.h.clear(this.key,"",this.O,this.path,this.domain)};p.n=function(a,b,c){O.dispatchEvent({type:a,kind:b,id:c})};function Je(a){a&&(this.Vd=parseInt(this.V(a).left),this.Oe=parseInt(this.V(a).top))}Je.prototype.Qb=function(a,b,c){switch(arguments.length){case 2:if("object"==typeof b)for(var d in b)"opacity"==d?(a.style.filter="alpha(opacity="+b[d]+")",a.style[d]=b[d]/100):a.style[d]=b[d];else return a.currentStyle?a.currentStyle[b]:getComputedStyle(a,document)[b];break;case 3:"opacity"==b?(a.style.filter="alpha(opacity="+c+")",a.style[b]=c/100):a.style[b]=c}};
Je.prototype.V=function(a){var b=a.getBoundingClientRect(),c=Oc(a),d=a.ownerDocument;a=d.body;var e=d.documentElement,d=b.top+(self.pageYOffset||e.scrollTop||a.scrollTop)-(e.clientTop||a.clientTop||0),b=b.left+(self.pageXOffset||e.scrollLeft||a.scrollLeft)-(e.clientLeft||a.clientLeft||0);return{top:0>d?0:d,left:b,width:c.width,height:c.height}};function $(){this.time=this.fd=this.Bc=m;this.P={};this.e=He.Oa();this.Ba=ve.Oa();Ke(this);this.Ob=this.e.W();this.jc=this.Ba.W();this.nb=wc("div",{id:"fly"});U(this.nb,n);document.body.appendChild(this.nb);this.rd=R("viewFavoriteButton");this.n("Event_Collect","UP",this.e.list());this.Cd=new Je(this.rd)}B($,V);
$.prototype.yc=function(a){switch(a.kind){case "ADD":U(this.nb,k);var b=this.Cd,c=this.nb,d=a.data.element,e=this.rd,f=b.V(d).left,d=b.V(d).top,e=Math.max(parseInt(b.V(e).left),b.Vd),h=document.documentElement.scrollTop||document.body.scrollTop,l=30/Math.tan(Math.atan2(h-d,e-f)),d=d-30;b.Qb(c,"left",f-l+"px");b.Qb(c,"top",d+"px");var q={left:e-l,top:h-30},w=function(){U(c,n)};clearInterval(c.f);var s=b.Qb;c.f=setInterval(function(){var a=k,b,d;for(d in q){b="opacity"==d?100*parseFloat(s(c,d)):Math.round(parseInt(s(c,
d)));var e=(q[d]-b)/12,e=0<e?Math.ceil(e):Math.floor(e);"opacity"==d?s(c,d,b+e):s(c,d,b+e+"px");20<Math.abs(q[d]-b)&&(a=n)}a==k&&(clearInterval(c.f),w&&w())},30);a=a.data;b=this.Ba.list();a={id:a.id,name:a.name,lb:0};f=0;for(d=b.length;f<d;f++)b[f].id==a.id&&(a.lb=1);b=this.e.add(a);Le(this.P[a.id],1);b&&Le(this.P[b],0);this.n("Event_Collect","UP",this.e.list());break;case "DEL":if(a=a.id)this.e.Rb(a),Le(this.P[a],0);else for(b in this.e.clear(),this.P)Le(this.P[b],0);this.n("Event_Collect","UP",
this.e.list());break;case "UP":this.Ob=this.e.W(),this.jc=this.Ba.W()}};$.prototype.yd=function(a){var b=a.id;switch(a.kind){case "ADD":b&&(Ie(this.e,a.id,1),this.n("Event_Collect","UP",this.e.list()));break;case "DEL":if(b)Ie(this.e,a.id,0);else{a=this.e;for(var b=a.list(),c=0,d=b.length;c<d;c++)b[c].lb=0;a.h.set(a.key,je(b),a.O,a.path,a.domain)}Ke(this);this.n("Event_Collect","UP",this.e.list())}};
$.prototype.qd=function(){var a=n,b=this.e.W(),c=this.Ba.W(),d;clearTimeout(this.time);if(this.Ob!=b){var a=k,b=this.e.map(),e;for(e in this.P)d=this.P[e],b[e]?Le(d,1):Le(d,0);this.Ob=this.e.W()}this.jc!=c&&(a=k,Ke(this),this.jc=this.Ba.W());a&&this.n("Event_Collect","UP",this.e.list());this.time=setTimeout(z(this.qd,this),1E3)};function Le(a,b){var c;if(a)for(var d=0,e=a.length;d<e;d++)(c=a[d])&&c.Ma!=b&&Ge(c,b)}
function Ke(a){var b=a.e.list(),c,d;a.fd=a.Ba.map();for(var e=0,f=b.length;e<f;e++)c=b[e].id,d=0,a.fd[c]&&(d=1),Ie(a.e,c,d)}$.prototype.n=function(a,b,c){O.dispatchEvent({type:a,kind:b,data:c})};$.ma=function(){var a=new $;M(O,"Event_Record",z(a.yd,a));M(O,"Event_Collect",z(a.yc,a));var b,c=sc("js-collect");a.Bc=a.e.map();for(var d=0;d<c.length;d++)b=new Ee,b.start(c[d]),a.P[b.id]?a.P[b.id].push(b):a.P[b.id]=[b],a.Bc[b.id]&&Ge(b,1),M(b,"Event_Collect",z(a.yc,a));a.time=setTimeout(z(a.qd,a),1E3)};
ma("baofeng.menu.init",$.ma);function Me(){this.gb=[];this.ub="";this.rb=0;this.sc=this.anchor=this.ua=this.list=this.defaultView=this.Pb=this.ac=m;this.Gb='<li id="fav-{id}"><a title={title} class="his-reco" href="javascript:void(0);">{name}</a><a href="javascript:void(0);" class="{view} state">{lb}</a><span class="closed">\u5173\u95ed</span></li>'}B(Me,V);p=Me.prototype;p.S=function(a){this.ua=a;this.Pb=T("his-cont");this.list=S("ul",j,this.Pb)[0];this.ac=R("favoriteR");this.defaultView=T("his-none")};
p.o=function(){M(this.ua,"click",z(this.Yd,this));M(O,"Event_Collect",z(this.se,this));M(this.anchor,"mouseover",z(this.Qa,this));M(this.anchor,"mouseout",z(this.Qa,this));M(this.ua,"mouseover",z(this.Qa,this));M(this.ua,"mouseout",z(this.Qa,this))};p.Qa=function(a){this.sc&&clearTimeout(this.sc);"mouseover"==a.type?this.show():this.sc=setTimeout(z(this.p,this),80)};p.show=function(){for(var a=0;a<this.gb.length;a++)U(this.gb[a],n);U(this.ua,k)};p.p=function(){U(this.ua,n)};
p.Yd=function(a){var b=a.target.nodeName;if("SPAN"==b&&"closed"==a.target.className){var c=a.target.parentNode.id.replace("fav-","");this.n("Event_Collect","DEL",c)}if("A"==b&&(-1!=a.target.className.indexOf("empty")&&this.n("Event_Collect","DEL",""),-1!=a.target.className.indexOf("his-reco")||-1!=a.target.className.indexOf("state")))c=a.target.parentNode.id.replace("fav-",""),r.open("/play/"+c%500+"/play-"+c+".html","_blank")};
p.se=function(a){var b=a.data;"UP"==a.kind&&(this.jd(b),U(this.ac,0<this.rb?k:n),this.ac.innerHTML=this.rb+"",this.list.innerHTML=this.ub,U(this.defaultView,0==this.list.children.length?k:n),U(this.Pb,0==this.list.children.length?n:k),this.Mb())};p.Mb=function(){for(var a=0,b=this.list.children.length;a<b;a++){var c=this.list.children[a];M(c,"mouseover",z(this.Ka,this));M(c,"mouseout",z(this.Ka,this))}};
p.Ka=function(a){var b=a.currentTarget;"mouseover"==a.type&&this.U(a,b)?b.className="cur":"mouseout"==a.type&&this.U(a,b)&&(b.className="")};p.U=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement;else if("mouseout"==c)c=a.relatedTarget||a.toElement;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};p.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};
p.n=function(a,b,c){O.dispatchEvent({type:a,kind:b,id:c})};p.jd=function(a){this.ub="";this.rb=0;for(var b=a.length-1;0<=b;b--){var c=a[b],d=this.Gb,e;for(e in c){var f=c[e];"lb"==e&&(d=d.replace("{view}",1==f?"old":"new"),f=1==f?"\u5df2\u770b":"\u672a\u89c2\u770b");d=d.replace("{"+e+"}",f)}d=d.replace("{title}",c.name);this.ub+=d;0==c.lb&&this.rb++}};function Ne(a){try{var b;if(!cc&&!("Win64"==Da||-1!=za().indexOf("Trident")&&/11\.(.)*/.test(Ha))){var c,d=r.navigator.plugins;if(d&&0<d.length)for(var e=0;e<d.length;e++){if(d[e][0].type.match("application/baofengwebplayer-plugin")){c=document.createElement("embed");c.type="application/baofengwebplayer-plugin";c.width="1";c.height="1";document.body.appendChild(c);cc=c;break}}else try{cc=new ActiveXObject("StormAxPlayer.Player")}catch(f){}}b=cc;if(b)var h=b.GetUserId();else g(Error());if(t(h)&&"undefined"!=
h&&(h=h.substr(1).substr(0,h.length-2),t(h)&&"undefined"!=h)){var l=new Zb(r.document);l.set("uid",h,7776E3,"/",".baofeng.com")}}catch(q){l=new Zb(r.document),h=l.get("uid"),t(h)&&("undefined"!=h&&""!=h)&&l.get("uid")}W(new Ce,R("searchPane"));b=new Me;b.anchor=R("viewFavoriteButton");c=R("searchRecommend");Bc(c)&&b.gb.push(c);c=R("viewRecordPane");Bc(c)&&b.gb.push(c);W(b,R("viewFavoritePanel"));b=new ze;c=ve.Oa();b.Ea=c;b.nc(R("viewRecordButton"));b.Za(R("searchRecommend"));b.Za(R("viewFavoritePanel"));
W(b,R("viewRecordPane"));b=T("play-nave-guide");var w=T("play-nave-list");Bc(b)&&Bc(w)&&(c=new ye,c.nc(b),c.k=w,c.Lb="play-nave-guide-on",c.Za(R("searchRecommend")),c.o());b=T("hd-load-text");c=T("hd-load-con");Bc(b)&&Bc(c)&&(new Ae({anchor:b,content:c,expandAnchorClass:"hd-load-text-on"})).o();$.ma();if(a&&42<a){var s=T("play-page"),A=R("viewRecordPane"),P=R("searchRecommend");M(r,"scroll",function(){var a=r.document.documentElement.scrollTop||r.document.body.scrollTop;42<a&&650>a?(Bc(w)&&U(w,n),
U(A,n),U(P,n),U(s,n)):U(s,k)},n,this)}}ma("baofeng.header.init",Ne);ma("hd.channel",function(a,b){function c(){0<(document.documentElement.scrollTop||document.body.scrollTop)?U(e,k):U(e,n)}var d=b||[];Ne();var e=R("goTop");M(r,"scroll",c);c();var f=new Pd;f.qa=a;f.Gb=f.De;W(f,R("FocusMap"));for(f=0;f<d.length;f++){var h=new od,l=R(d[f][3]);h.vd=d[f][0];h.td=d[f][1];h.Ha=d[f][2];h.i="mouseover";pd(h,T(d[f][1],l));W(h,l)}(new Xd).start()});})();
