(function(){function g(a){throw a;}var j=void 0,k=!0,m=null,p=!1;function aa(a){return function(b){this[a]=b}}var q,r=this;function ba(a,b){var c=a.split("."),d=r;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&t(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function ca(){}function da(a){a.qa=function(){return a.Qb?a.Qb:a.Qb=new a}}
function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return a!==j}function u(a){return"array"==ea(a)}function v(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){return"string"==typeof a}function fa(a){return"function"==ea(a)}function ha(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}function y(a){return a[ia]||(a[ia]=++ja)}var ia="closure_uid_"+(1E9*Math.random()>>>0),ja=0;
function ka(a,b,c){return a.call.apply(a.bind,arguments)}function la(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function z(a,b,c){z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ka:la;return z.apply(m,arguments)}
function ma(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var na=Date.now||function(){return+new Date};function B(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c};function oa(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function pa(a){if(!qa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ra,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(sa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ta,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ua,"&quot;"));return a}var ra=/&/g,sa=/</g,ta=/>/g,ua=/\"/g,qa=/[&<>\"]/;var va,wa,xa,ya;function za(){return r.navigator?r.navigator.userAgent:m}ya=xa=wa=va=p;var Aa;if(Aa=za()){var Ba=r.navigator;va=0==Aa.indexOf("Opera");wa=!va&&-1!=Aa.indexOf("MSIE");xa=!va&&-1!=Aa.indexOf("WebKit");ya=!va&&!xa&&"Gecko"==Ba.product}var Ca=va,C=wa,D=ya,E=xa,Da,Ea=r.navigator;Da=Ea&&Ea.platform||"";var Fa=-1!=Da.indexOf("Mac");function Ga(){var a=r.document;return a?a.documentMode:j}var Ha;
a:{var Ia="",Ja;if(Ca&&r.opera)var Ka=r.opera.version,Ia="function"==typeof Ka?Ka():Ka;else if(D?Ja=/rv\:([^\);]+)(\)|;)/:C?Ja=/MSIE\s+([^\);]+)(\)|;)/:E&&(Ja=/WebKit\/(\S+)/),Ja)var La=Ja.exec(za()),Ia=La?La[1]:"";if(C){var Ma=Ga();if(Ma>parseFloat(Ia)){Ha=String(Ma);break a}}Ha=Ia}var Na={};
function F(a){var b;if(!(b=Na[a])){b=0;for(var c=oa(String(Ha)).split("."),d=oa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",l=d[f]||"",n=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var s=n.exec(h)||["","",""],A=w.exec(l)||["","",""];if(0==s[0].length&&0==A[0].length)break;b=((0==s[1].length?0:parseInt(s[1],10))<(0==A[1].length?0:parseInt(A[1],10))?-1:(0==s[1].length?0:parseInt(s[1],10))>(0==A[1].length?0:parseInt(A[1],10))?1:0)||((0==s[2].length)<
(0==A[2].length)?-1:(0==s[2].length)>(0==A[2].length)?1:0)||(s[2]<A[2]?-1:s[2]>A[2]?1:0)}while(0==b)}b=Na[a]=0<=b}return b}var Oa=r.document,Pa=!Oa||!C?j:Ga()||("CSS1Compat"==Oa.compatMode?parseInt(Ha,10):5);function Qa(a,b){for(var c in a)b.call(j,a[c],c,a)}function Ra(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Sa(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Ta(a){for(var b in a)return p;return k}var Ua="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Va(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ua.length;f++)c=Ua[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function G(a){Error.captureStackTrace?Error.captureStackTrace(this,G):this.stack=Error().stack||"";a&&(this.message=String(a))}B(G,Error);G.prototype.name="CustomError";var H=Array.prototype,Wa=H.indexOf?function(a,b,c){return H.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(x(a))return!x(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},I=H.forEach?function(a,b,c){H.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Xa=H.filter?function(a,b,c){return H.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=x(a)?a.split(""):
a,l=0;l<d;l++)if(l in h){var n=h[l];b.call(c,n,l,a)&&(e[f++]=n)}return e},Ya=H.some?function(a,b,c){return H.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return k;return p};function Za(a,b){return 0<=Wa(a,b)}function $a(a,b){var c=Wa(a,b);0<=c&&H.splice.call(a,c,1)}function ab(a){return H.concat.apply(H,arguments)}function bb(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function J(a,b,c){return 2>=arguments.length?H.slice.call(a,b):H.slice.call(a,b,c)};function cb(a,b){this.x=t(a)?a:0;this.y=t(b)?b:0}q=cb.prototype;q.C=function(){return new cb(this.x,this.y)};q.toString=function(){return"("+this.x+", "+this.y+")"};q.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};q.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};q.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function db(a,b){this.width=a;this.height=b}q=db.prototype;q.C=function(){return new db(this.width,this.height)};q.toString=function(){return"("+this.width+" x "+this.height+")"};q.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};q.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};q.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function eb(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}q=eb.prototype;q.C=function(){return new eb(this.left,this.top,this.width,this.height)};q.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};q.contains=function(a){return a instanceof eb?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
q.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};q.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};q.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var fb;function gb(a){a=a.className;return x(a)&&a.match(/\S+/g)||[]}function K(a,b){for(var c=gb(a),d=J(arguments,1),e=c.length+d.length,f=c,h=0;h<d.length;h++)Za(f,d[h])||f.push(d[h]);a.className=c.join(" ");return c.length==e}function M(a,b){var c=gb(a),d=J(arguments,1),c=Xa(c,function(a){return!Za(d,a)});a.className=c.join(" ")};var hb=!C||C&&9<=Pa,ib=!D&&!C||C&&C&&9<=Pa||D&&F("1.9.1"),jb=C&&!F("9");function kb(a){return a?new lb(mb(a)):fb||(fb=new lb)}function N(a){return x(a)?document.getElementById(a):a}function nb(a,b){var c=b||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):O("*",a,b)}function P(a,b){var c=b||document,d=m;return(d=c.querySelectorAll&&c.querySelector?c.querySelector("."+a):nb(a,b)[0])||m}
function O(a,b,c){var d=document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,f=0,h;h=c[f];f++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(f=e=0;h=c[f];f++)a=h.className,"function"==typeof a.split&&Za(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c}
function ob(a,b){Qa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in qb?a.setAttribute(qb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var qb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function rb(a){var b=!E&&"CSS1Compat"==a.compatMode?a.documentElement:a.body;a=a.parentWindow||a.defaultView;return new cb(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}function sb(a,b,c){return tb(document,arguments)}
function tb(a,b){var c=b[0],d=b[1];if(!hb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',pa(d.name),'"');if(d.type){c.push(' type="',pa(d.type),'"');var e={};Va(e,d);delete e.type;d=e}c.push(">");c=c.join("")}var f=a.createElement(c);d&&(x(d)?f.className=d:u(d)?K.apply(m,[f].concat(d)):ob(f,d));if(2<b.length){d=function(b){b&&f.appendChild(x(b)?a.createTextNode(b):b)};for(c=2;c<b.length;c++)if(e=b[c],v(e)&&!(ha(e)&&0<e.nodeType)){var h=I,l;a:{if((l=e)&&"number"==typeof l.length){if(ha(l)){l=
"function"==typeof l.item||"string"==typeof l.item;break a}if(fa(l)){l="function"==typeof l.item;break a}}l=p}h(l?bb(e):e,d)}else d(e)}return f}function ub(a){var b=document,c=b.createElement("div");C?(c.innerHTML="<br>"+a,c.removeChild(c.firstChild)):c.innerHTML=a;if(1==c.childNodes.length)return c.removeChild(c.firstChild);for(a=b.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);return a}function vb(a){a&&a.parentNode&&a.parentNode.removeChild(a)}
function wb(a){return ib&&a.children!=j?a.children:Xa(a.childNodes,function(a){return 1==a.nodeType})}function xb(a){return ha(a)&&1==a.nodeType}function mb(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var yb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},zb={IMG:" ",BR:"\n"};
function Ab(a){if(jb&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Bb(a,b,k);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");jb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Bb(a,b,c){if(!(a.nodeName in yb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in zb)b.push(zb[a.nodeName]);else for(a=a.firstChild;a;)Bb(a,b,c),a=a.nextSibling}function lb(a){this.s=a||r.document||document}q=lb.prototype;q.Nb=function(a){return x(a)?this.s.getElementById(a):a};q.Ib=function(a,b,c){return tb(this.s,arguments)};q.createElement=function(a){return this.s.createElement(a)};q.createTextNode=function(a){return this.s.createTextNode(String(a))};
q.appendChild=function(a,b){a.appendChild(b)};q.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function Cb(a,b){x(b)?Db(a,j,b):Qa(b,ma(Db,a))}function Db(a,b,c){var d;a:if(d=String(c).replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()}),a.style[d]===j){var e=E?"Webkit":D?"Moz":C?"ms":Ca?"O":m,f=x(j)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";c=c.replace(RegExp("(^"+(f?"|["+f+"]+":"")+")([a-z])","g"),function(a,b,c){return b+c.toUpperCase()});e+=c;if(a.style[e]!==j){d=e;break a}}d&&(a.style[d]=b)}
function Eb(a,b){var c;a:{c=mb(a);if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,m))){c=c[b]||c.getPropertyValue(b)||"";break a}c=""}return c||(a.currentStyle?a.currentStyle[b]:m)||a.style&&a.style[b]}function Fb(a){var b=a.getBoundingClientRect();C&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Gb(a){if(C&&!(C&&8<=Pa))return a.offsetParent;var b=mb(a),c=Eb(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Eb(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return m}
function Hb(a){if("none"!=Eb(a,"display"))return Ib(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Ib(a);b.display=c;b.position=e;b.visibility=d;return a}function Ib(a){var b=a.offsetWidth,c=a.offsetHeight,d=E&&!b&&!c;return(!t(b)||d)&&a.getBoundingClientRect?(a=Fb(a),new db(a.right-a.left,a.bottom-a.top)):new db(b,c)}
function Jb(a){var b,c=mb(a),d=Eb(a,"position"),e=D&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),f=new cb(0,0),h;b=c?mb(c):document;if(h=C)if(h=!(C&&9<=Pa))h="CSS1Compat"!=kb(b).s.compatMode;h=h?b.body:b.documentElement;if(a!=h)if(a.getBoundingClientRect)b=Fb(a),c=kb(c),c=rb(c.s),f.x=b.left+c.x,f.y=b.top+c.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),c=c.getBoxObjectFor(h),f.x=b.screenX-c.screenX,f.y=b.screenY-c.screenY;
else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(E&&"fixed"==Eb(b,"position")){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(Ca||E&&"absolute"==d)f.y-=c.body.offsetTop;for(b=a;(b=Gb(b))&&b!=c.body&&b!=h;)if(f.x-=b.scrollLeft,!Ca||"TR"!=b.tagName)f.y-=b.scrollTop}a=Hb(a);return new eb(f.x,f.y,a.width,a.height)}function Q(a,b){a.style.display=b?"":"none"};function R(){0!=Kb&&(this.hd=Error().stack,Lb[y(this)]=this)}var Kb=0,Lb={};R.prototype.Ha=p;R.prototype.na=function(){if(!this.Ha&&(this.Ha=k,this.n(),0!=Kb)){var a=y(this);delete Lb[a]}};R.prototype.n=function(){if(this.Yb)for(;this.Yb.length;)this.Yb.shift()()};function Mb(a,b){this.type=a;this.currentTarget=this.target=b}q=Mb.prototype;q.n=function(){};q.na=function(){};q.ea=p;q.defaultPrevented=p;q.Za=k;q.preventDefault=function(){this.defaultPrevented=k;this.Za=p};var Nb=0;function Ob(){}q=Ob.prototype;q.key=0;q.K=p;q.Ca=p;q.V=function(a,b,c,d,e,f){fa(a)?this.Rb=k:a&&a.handleEvent&&fa(a.handleEvent)?this.Rb=p:g(Error("Invalid listener argument"));this.G=a;this.ac=b;this.src=c;this.type=d;this.capture=!!e;this.Pa=f;this.Ca=p;this.key=++Nb;this.K=p};q.handleEvent=function(a){return this.Rb?this.G.call(this.Pa||this.src,a):this.G.handleEvent.call(this.G,a)};var Pb=!C||C&&9<=Pa,Qb=C&&!F("9");!E||F("528");D&&F("1.9b")||C&&F("8")||Ca&&F("9.5")||E&&F("528");D&&!F("8")||C&&F("9");function Rb(a){Rb[" "](a);return a}Rb[" "]=ca;function Sb(a,b){a&&this.V(a,b)}B(Sb,Mb);q=Sb.prototype;q.target=m;q.relatedTarget=m;q.offsetX=0;q.offsetY=0;q.clientX=0;q.clientY=0;q.screenX=0;q.screenY=0;q.button=0;q.keyCode=0;q.charCode=0;q.ctrlKey=p;q.altKey=p;q.shiftKey=p;q.metaKey=p;q.Wc=p;q.Lb=m;
q.V=function(a,b){var c=this.type=a.type;Mb.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(D){var e;a:{try{Rb(d.nodeName);e=k;break a}catch(f){}e=p}e||(d=m)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=E||a.offsetX!==j?a.offsetX:a.layerX;this.offsetY=E||a.offsetY!==j?a.offsetY:a.layerY;this.clientX=a.clientX!==j?a.clientX:a.pageX;this.clientY=a.clientY!==j?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Wc=Fa?a.metaKey:a.ctrlKey;this.state=a.state;this.Lb=a;a.defaultPrevented&&this.preventDefault();delete this.ea};
q.preventDefault=function(){Sb.H.preventDefault.call(this);var a=this.Lb;if(a.preventDefault)a.preventDefault();else if(a.returnValue=p,Qb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};q.n=function(){};var Tb={},S={},T={},Ub={};
function U(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)U(a,b[f],c,d,e);return m}a:{b||g(Error("Invalid event type"));d=!!d;var h=S;b in h||(h[b]={a:0,k:0});h=h[b];d in h||(h[d]={a:0,k:0},h.a++);var h=h[d],f=y(a),l;h.k++;if(h[f]){l=h[f];for(var n=0;n<l.length;n++)if(h=l[n],h.G==c&&h.Pa==e){if(h.K)break;l[n].Ca=p;a=l[n];break a}}else l=h[f]=[],h.a++;var w=Vb,s=Pb?function(a){return w.call(s.src,s.G,a)}:function(a){a=w.call(s.src,s.G,a);if(!a)return a},n=s,h=new Ob;h.V(c,n,a,b,d,e);h.Ca=p;n.src=a;
n.G=h;l.push(h);T[f]||(T[f]=[]);T[f].push(h);a.addEventListener?(a==r||!a.Jb)&&a.addEventListener(b,n,d):a.attachEvent(b in Ub?Ub[b]:Ub[b]="on"+b,n);a=h}b=a.key;Tb[b]=a;return b}function Wb(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)Wb(a,b[f],c,d,e);else if(d=!!d,a=Xb(a,b,d))for(f=0;f<a.length;f++)if(a[f].G==c&&a[f].capture==d&&a[f].Pa==e){Yb(a[f].key);break}}
function Yb(a){var b=Tb[a];if(!b||b.K)return p;var c=b.src,d=b.type,e=b.ac,f=b.capture;c.removeEventListener?(c==r||!c.Jb)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in Ub?Ub[d]:Ub[d]="on"+d,e);c=y(c);T[c]&&(e=T[c],$a(e,b),0==e.length&&delete T[c]);b.K=k;if(b=S[d][f][c])b.Xb=k,Zb(d,f,c,b);delete Tb[a];return k}
function Zb(a,b,c,d){if(!d.Ua&&d.Xb){for(var e=0,f=0;e<d.length;e++)d[e].K?d[e].ac.src=m:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.Xb=p;0==f&&(delete S[a][b][c],S[a][b].a--,0==S[a][b].a&&(delete S[a][b],S[a].a--),0==S[a].a&&delete S[a])}}function $b(a,b){var c=0,d=b==m;if(a!=m){var e=y(a);if(T[e])for(var e=T[e],f=e.length-1;0<=f;f--){var h=e[f];if(d||b==h.type)Yb(h.key),c++}}else Qa(Tb,function(a,b){Yb(b);c++})}function Xb(a,b,c){var d=S;return b in d&&(d=d[b],c in d&&(d=d[c],a=y(a),d[a]))?d[a]:m}
function ac(a,b,c,d,e){var f=1;b=y(b);if(a[b]){var h=--a.k,l=a[b];l.Ua?l.Ua++:l.Ua=1;try{for(var n=l.length,w=0;w<n;w++){var s=l[w];s&&!s.K&&(f&=bc(s,e)!==p)}}finally{a.k=Math.max(h,a.k),l.Ua--,Zb(c,d,b,l)}}return Boolean(f)}function bc(a,b){a.Ca&&Yb(a.key);return a.handleEvent(b)}
function Vb(a,b){if(a.K)return k;var c=a.type,d=S;if(!(c in d))return k;var d=d[c],e,f;if(!Pb){var h;if(!(h=b))a:{h=["window","event"];for(var l=r;e=h.shift();)if(l[e]!=m)l=l[e];else{h=m;break a}h=l}e=h;h=k in d;l=p in d;if(h){if(0>e.keyCode||e.returnValue!=j)return k;a:{var n=p;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(w){n=k}if(n||e.returnValue==j)e.returnValue=k}}n=new Sb;n.V(e,this);e=k;try{if(h){for(var s=[],A=n.currentTarget;A;A=A.parentNode)s.push(A);f=d[k];f.k=f.a;for(var L=s.length-
1;!n.ea&&0<=L&&f.k;L--)n.currentTarget=s[L],e&=ac(f,s[L],c,k,n);if(l){f=d[p];f.k=f.a;for(L=0;!n.ea&&L<s.length&&f.k;L++)n.currentTarget=s[L],e&=ac(f,s[L],c,p,n)}}else e=bc(a,n)}finally{s&&(s.length=0)}return e}c=new Sb(b,this);return e=bc(a,c)};function cc(a){R.call(this);this.aa=a;this.b=[]}B(cc,R);var dc=[];function ec(a,b,c,d,e,f){if(u(c))for(var h=0;h<c.length;h++)ec(a,b,c[h],d,e,f);else{a:{d=d||a;f=f||a.aa||a;e=!!e;if(b=Xb(b,c,e))for(c=0;c<b.length;c++)if(!b[c].K&&b[c].G==d&&b[c].capture==e&&b[c].Pa==f){b=b[c];break a}b=m}b&&(b=b.key,Yb(b),$a(a.b,b))}}cc.prototype.n=function(){cc.H.n.call(this);I(this.b,Yb);this.b.length=0};cc.prototype.handleEvent=function(){g(Error("EventHandler.handleEvent not implemented"))};function fc(){}da(fc);fc.prototype.Tc=0;fc.qa();function gc(){R.call(this)}B(gc,R);q=gc.prototype;q.Jb=k;q.Wa=m;q.Ab=aa("Wa");q.addEventListener=function(a,b,c,d){U(this,a,b,c,d)};q.removeEventListener=function(a,b,c,d){Wb(this,a,b,c,d)};
q.dispatchEvent=function(a){var b=a.type||a,c=S;if(b in c){if(x(a))a=new Mb(a,this);else if(a instanceof Mb)a.target=a.target||this;else{var d=a;a=new Mb(b,this);Va(a,d)}var d=1,e,c=c[b],b=k in c,f;if(b){e=[];for(f=this;f;f=f.Wa)e.push(f);f=c[k];f.k=f.a;for(var h=e.length-1;!a.ea&&0<=h&&f.k;h--)a.currentTarget=e[h],d&=ac(f,e[h],a.type,k,a)&&a.Za!=p}if(p in c)if(f=c[p],f.k=f.a,b)for(h=0;!a.ea&&h<e.length&&f.k;h++)a.currentTarget=e[h],d&=ac(f,e[h],a.type,p,a)&&a.Za!=p;else for(e=this;!a.ea&&e&&f.k;e=
e.Wa)a.currentTarget=e,d&=ac(f,e,a.type,p,a)&&a.Za!=p;a=Boolean(d)}else a=k;return a};q.n=function(){gc.H.n.call(this);$b(this);this.Wa=m};function V(a){R.call(this);this.Ia=a||kb();this.ad=hc}B(V,gc);V.prototype.Ic=fc.qa();var hc=m;q=V.prototype;q.ob=m;q.ba=p;q.I=m;q.ad=m;q.Sc=m;q.B=m;q.Ea=m;q.la=m;q.lc=p;q.pa=function(){return this.ob||(this.ob=":"+(this.Ic.Tc++).toString(36))};q.Nb=function(){return this.I};q.Ab=function(a){this.B&&this.B!=a&&g(Error("Method not supported"));V.H.Ab.call(this,a)};q.Ib=function(){this.I=this.Ia.createElement("div")};
function W(a,b){a.ba&&g(Error("Component already rendered"));if(b){a.lc=k;if(!a.Ia||a.Ia.s!=mb(b))a.Ia=kb(b);a.P(b);a.o()}else g(Error("Invalid element to decorate"))}q.P=aa("I");q.o=function(){this.ba=k;ic(this,function(a){!a.ba&&a.Nb()&&a.o()})};function jc(a){ic(a,function(a){a.ba&&jc(a)});if(a.Oa){var b=a.Oa;I(b.b,Yb);b.b.length=0}a.ba=p}
q.n=function(){this.ba&&jc(this);this.Oa&&(this.Oa.na(),delete this.Oa);ic(this,function(a){a.na()});!this.lc&&this.I&&vb(this.I);this.B=this.Sc=this.I=this.la=this.Ea=m;V.H.n.call(this)};function ic(a,b){a.Ea&&I(a.Ea,b,j)}
q.removeChild=function(a,b){if(a){var c=x(a)?a:a.pa();a=this.la&&c?(c in this.la?this.la[c]:j)||m:m;if(c&&a){var d=this.la;c in d&&delete d[c];$a(this.Ea,a);b&&(jc(a),a.I&&vb(a.I));c=a;c==m&&g(Error("Unable to set parent component"));c.B=m;V.H.Ab.call(c,m)}}a||g(Error("Child is not in parent component"));return a};var kc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");var lc="StopIteration"in r?r.StopIteration:Error("StopIteration");function mc(){}mc.prototype.next=function(){g(lc)};mc.prototype.ka=function(){return this};function nc(a){if(a instanceof mc)return a;if("function"==typeof a.ka)return a.ka(p);if(v(a)){var b=0,c=new mc;c.next=function(){for(;;){b>=a.length&&g(lc);if(b in a)return a[b++];b++}};return c}g(Error("Not implemented"))};function oc(a){if("function"==typeof a.w)return a.w();if(x(a))return a.split("");if(v(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ra(a)};function pc(a,b){this.t={};this.b=[];var c=arguments.length;if(1<c){c%2&&g(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof pc?(c=a.T(),d=a.w()):(c=Sa(a),d=Ra(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}}q=pc.prototype;q.a=0;q.xa=0;q.w=function(){qc(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.t[this.b[b]]);return a};q.T=function(){qc(this);return this.b.concat()};q.O=function(a){return rc(this.t,a)};
q.clear=function(){this.t={};this.xa=this.a=this.b.length=0};q.remove=function(a){return rc(this.t,a)?(delete this.t[a],this.a--,this.xa++,this.b.length>2*this.a&&qc(this),k):p};function qc(a){if(a.a!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];rc(a.t,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.a!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],rc(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}}q.get=function(a,b){return rc(this.t,a)?this.t[a]:b};
q.set=function(a,b){rc(this.t,a)||(this.a++,this.b.push(a),this.xa++);this.t[a]=b};q.C=function(){return new pc(this)};q.ka=function(a){qc(this);var b=0,c=this.b,d=this.t,e=this.xa,f=this,h=new mc;h.next=function(){for(;;){e!=f.xa&&g(Error("The map has changed since the iterator was created"));b>=c.length&&g(lc);var h=c[b++];return a?h:d[h]}};return h};function rc(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function sc(a,b){var c;if(a instanceof sc)this.p=t(b)?b:a.p,tc(this,a.L),c=a.Y,X(this),this.Y=c,uc(this,a.Q),vc(this,a.da),wc(this,a.J),xc(this,a.v.C()),c=a.S,X(this),this.S=c;else if(a&&(c=String(a).match(kc))){this.p=!!b;tc(this,c[1]||"",k);var d=c[2]||"";X(this);this.Y=d?decodeURIComponent(d):"";uc(this,c[3]||"",k);vc(this,c[4]);wc(this,c[5]||"",k);xc(this,c[6]||"",k);c=c[7]||"";X(this);this.S=c?decodeURIComponent(c):""}else this.p=!!b,this.v=new yc(m,0,this.p)}q=sc.prototype;q.L="";q.Y="";
q.Q="";q.da=m;q.J="";q.S="";q.Lc=p;q.p=p;q.toString=function(){var a=[],b=this.L;b&&a.push(zc(b,Ac),":");if(b=this.Q){a.push("//");var c=this.Y;c&&a.push(zc(c,Ac),"@");a.push(encodeURIComponent(String(b)));b=this.da;b!=m&&a.push(":",String(b))}if(b=this.J)this.Q&&"/"!=b.charAt(0)&&a.push("/"),a.push(zc(b,"/"==b.charAt(0)?Bc:Cc));(b=this.v.toString())&&a.push("?",b);(b=this.S)&&a.push("#",zc(b,Dc));return a.join("")};
q.cc=function(a){var b=this.C(),c=!!a.L;c?tc(b,a.L):c=!!a.Y;if(c){var d=a.Y;X(b);b.Y=d}else c=!!a.Q;c?uc(b,a.Q):c=a.da!=m;var e=a.J;if(c)vc(b,a.da);else if(c=!!a.J)if("/"!=e.charAt(0)&&(this.Q&&!this.J?e="/"+e:(d=b.J.lastIndexOf("/"),-1!=d&&(e=b.J.substr(0,d+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){for(var d=0==e.lastIndexOf("/",0),e=e.split("/"),f=[],h=0;h<e.length;){var l=e[h++];"."==l?d&&h==e.length&&f.push(""):".."==l?((1<f.length||1==f.length&&""!=f[0])&&
f.pop(),d&&h==e.length&&f.push("")):(f.push(l),d=k)}e=f.join("/")}c?wc(b,e):c=""!==a.v.toString();c?xc(b,a.v.toString()?decodeURIComponent(a.v.toString()):""):c=!!a.S;c&&(a=a.S,X(b),b.S=a);return b};q.C=function(){return new sc(this)};function tc(a,b,c){X(a);a.L=c?b?decodeURIComponent(b):"":b;a.L&&(a.L=a.L.replace(/:$/,""))}function uc(a,b,c){X(a);a.Q=c?b?decodeURIComponent(b):"":b}function vc(a,b){X(a);b?(b=Number(b),(isNaN(b)||0>b)&&g(Error("Bad port number "+b)),a.da=b):a.da=m}
function wc(a,b,c){X(a);a.J=c?b?decodeURIComponent(b):"":b}function xc(a,b,c){X(a);b instanceof yc?(a.v=b,a.v.zb(a.p)):(c||(b=zc(b,Ec)),a.v=new yc(b,0,a.p))}function Fc(a,b,c){X(a);u(c)||(c=[String(c)]);Gc(a.v,b,c)}function X(a){a.Lc&&g(Error("Tried to modify a read-only Uri"))}q.zb=function(a){this.p=a;this.v&&this.v.zb(a);return this};function Hc(a,b){var c=new sc(m,j);tc(c,"http");uc(c,"web.houyi.baofeng.net");a&&wc(c,a);b&&xc(c,b);return c}
function zc(a,b){return x(a)?encodeURI(a).replace(b,Ic):m}function Ic(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Ac=/[#\/\?@]/g,Cc=/[\#\?:]/g,Bc=/[\#\?]/g,Ec=/[\#\?@]/g,Dc=/#/g;function yc(a,b,c){this.l=a||m;this.p=!!c}
function Jc(a){if(!a.c&&(a.c=new pc,a.a=0,a.l))for(var b=a.l.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=m,f=m;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=Kc(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}q=yc.prototype;q.c=m;q.a=m;q.add=function(a,b){Jc(this);this.l=m;a=Kc(this,a);var c=this.c.get(a);c||this.c.set(a,c=[]);c.push(b);this.a++;return this};
q.remove=function(a){Jc(this);a=Kc(this,a);return this.c.O(a)?(this.l=m,this.a-=this.c.get(a).length,this.c.remove(a)):p};q.clear=function(){this.c=this.l=m;this.a=0};q.O=function(a){Jc(this);a=Kc(this,a);return this.c.O(a)};q.T=function(){Jc(this);for(var a=this.c.w(),b=this.c.T(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};q.w=function(a){Jc(this);var b=[];if(a)this.O(a)&&(b=ab(b,this.c.get(Kc(this,a))));else{a=this.c.w();for(var c=0;c<a.length;c++)b=ab(b,a[c])}return b};
q.set=function(a,b){Jc(this);this.l=m;a=Kc(this,a);this.O(a)&&(this.a-=this.c.get(a).length);this.c.set(a,[b]);this.a++;return this};q.get=function(a,b){var c=a?this.w(a):[];return 0<c.length?String(c[0]):b};function Gc(a,b,c){a.remove(b);0<c.length&&(a.l=m,a.c.set(Kc(a,b),bb(c)),a.a+=c.length)}
q.toString=function(){if(this.l)return this.l;if(!this.c)return"";for(var a=[],b=this.c.T(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.w(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}return this.l=a.join("&")};q.C=function(){var a=new yc;a.l=this.l;this.c&&(a.c=this.c.C(),a.a=this.a);return a};function Kc(a,b){var c=String(b);a.p&&(c=c.toLowerCase());return c}
q.zb=function(a){if(a&&!this.p){Jc(this);this.l=m;var b=this.c,c=function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),Gc(this,c,a))};if("function"==typeof b.forEach)b.forEach(c,this);else if(v(b)||x(b))I(b,c,this);else{var d;if("function"==typeof b.T)d=b.T();else if("function"!=typeof b.w)if(v(b)||x(b)){d=[];for(var e=b.length,f=0;f<e;f++)d.push(f)}else d=Sa(b);else d=j;b=oc(b);e=b.length;for(f=0;f<e;f++)c.call(this,b[f],d&&d[f])}}this.p=a};function Lc(a){this.s=a}var Mc=/\s*;\s*/;q=Lc.prototype;q.set=function(a,b,c,d,e,f){/[;=\s]/.test(a)&&g(Error('Invalid cookie name "'+a+'"'));/[;\r\n]/.test(b)&&g(Error('Invalid cookie value "'+b+'"'));t(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(na()+1E3*c)).toUTCString();this.s.cookie=a+"="+b+e+d+c+f};
q.get=function(a,b){for(var c=a+"=",d=(this.s.cookie||"").split(Mc),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};q.remove=function(a,b,c){var d=this.O(a);this.set(a,"",0,b,c);return d};q.T=function(){return Nc(this).keys};q.w=function(){return Nc(this).gd};q.O=function(a){return t(this.get(a))};q.clear=function(){for(var a=Nc(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
function Nc(a){a=(a.s.cookie||"").split(Mc);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,gd:c}};/*
 {@link www.baofeng.com}
*/
new sc(r.location.href);var Y=new gc,Oc=m;function Pc(a,b,c,d){var e=[];e.push("_trackEvent");e.push(a);e.push(b);c!=m&&e.push(c);d!=m&&e.push(d);try{r._hmt.push(e),r.ga&&r.ga("send","event",a,b)}catch(f){}}U(Y,"log",function(a){var b=Qc[a.data.key].name,c=Qc[a.data.key].infor[a.data.value-1];a.data.other?Pc(b,c,m,a.data.other):Pc(b,c)});
U(Y,"log",function(a){if(t(Qc[a.data.key].bfinfo)&&t(r.baofeng.eventLog)){var b=Qc[a.data.key].bfinfo[a.data.value-1];t(b)&&b!=m&&(t(a.data.other)&&(b.value&&(b.value=a.data.other),b.key&&(b[b.key]=a.data.other)),b.category=a.data.key,r.baofeng.eventLog(b))}});function Rc(a){R.call(this);this.ua={};this.ta={};this.aa=new cc(this);this.B=a}B(Rc,gc);var Sc=[C?"readystatechange":"load","abort","error"];Rc.prototype.start=function(){var a=this.ua;I(Sa(a),function(b){var c=a[b];if(c&&(delete a[b],!this.Ha)){var d;d=this.B?kb(this.B).Ib("img"):new Image;var e=this.aa,f=this.Zb,h=Sc;u(h)||(dc[0]=h,h=dc);for(var l=0;l<h.length;l++){var n=U(d,h[l],f||e,p,e.aa||e);e.b.push(n)}this.ta[b]=d;d.id=b;d.src=c}},this)};
Rc.prototype.Zb=function(a){var b=a.currentTarget;if(b){if("readystatechange"==a.type)if("complete"==b.readyState)a.type="load";else return;"undefined"==typeof b.naturalWidth&&("load"==a.type?(b.naturalWidth=b.width,b.naturalHeight=b.height):(b.naturalWidth=0,b.naturalHeight=0));this.dispatchEvent({type:a.type,target:b});if(!this.Ha&&(a=b.id,delete this.ua[a],b=this.ta[a]))delete this.ta[a],ec(this.aa,b,Sc,this.Zb),Ta(this.ta)&&Ta(this.ua)&&this.dispatchEvent("complete")}};
Rc.prototype.n=function(){delete this.ua;delete this.ta;var a=this.aa;a&&"function"==typeof a.na&&a.na();Rc.H.n.call(this)};/*
 {@link www.baofeng.com}
*/
function Tc(){this.Xc="data-qusrc";this.Dc="data-ersrc";this.Rc="data-level";this.Uc="data-none";this.ca=[];this.Kb=[];this.rb=p;this.hc=m;this.index=0;this.Ga=200;this.Mc=this.Kc=p;this.Zc="http://box.bfimg.com";this.Ub=0;this.exp=RegExp(this.Zc);this.W={Eb:"queue",eb:"erup",Fb:"switch"};this.fd=["http://box1.bfimg.com","http://box2.bfimg.com","http://box3.bfimg.com","http://box4.bfimg.com","http://box5.bfimg.com"]}B(Tc,V);q=Tc.prototype;q.start=function(){W(this,document)};
q.Da=function(){for(var a=Uc(),b=a.y+a.height,c=m,d=[],e=this.ca.length-1;-1<e;e--)if(c=this.ca[e],c.top<=b&&c.top+c.height>=a.y)switch(c.type){case this.W.eb:this.ca.splice(e,1);c.Qc?(this.rb=k,c.X.src=c.src):d.push(c);break;case this.W.Eb:this.ca.splice(e,1);Vc(this,c.X);break;case this.W.Fb:c.pb||(c.pb=k)}else c.pb&&c.type==this.W.Fb&&(c.pb=p,c.md.pd());d.length&&(this.rb?(this.Kb.push(d),this.rb=p,setTimeout(z(this.Vb,this),1E3)):this.Vb(d))};
q.Vb=function(a){a=a||this.Kb.shift();for(var b=m,c=0,d=a.length;c<d;c++)b=a[c],b.X.onerror=function(){this.src=b.url;this.onerror=m;C&&(this.onreadystatechange=m);this.onload=m},C?b.X.onreadystatechange=function(){if("complete"==this.readyState||"loaded"==this.readyState)this.onreadystatechange=this.onerror=m}:b.X.onload=function(){this.onload=this.onerror=m},b.X.src=b.src;a.length=0;a=m};
function Vc(a,b){var c=new Rc,d=Wc(a,a.W.Eb,a.Xc,b);U(c,"complete",function(){for(var a in d)d[a].X.src=d[a].src;c.n();$b(c,"complete");$b(c,"error");d.length=0;c=d=m});U(c,"error",function(a){d.splice(a.target.id,1)});for(var e in d){var f=d[e].src;(f=x(f)?f:f.src)&&(c.ua[e]=f)}c.start()}q.ec=function(a){var b;this.Kc?(clearTimeout(this.hc),this.hc=setTimeout(z(this.Da,this),this.Ga)):(b=Uc().y,"scroll"==a.type&&50>=Math.abs(b-this.Ub)||(this.Ub=b,this.Da()))};
q.Ac=function(a){a=Wc(this,this.W.eb,this.Uc,a.element);Array.prototype.push.apply(this.ca,a);this.Da()};q.U=function(a){var b=a.getBoundingClientRect(),c=Jb(a),d=a.ownerDocument;a=d.body;var e=d.documentElement,d=b.top+(self.pageYOffset||e.scrollTop||a.scrollTop)-(e.clientTop||a.clientTop||0),b=b.left+(self.pageXOffset||e.scrollLeft||a.scrollLeft)-(e.clientLeft||a.clientLeft||0);return{top:0>d?0:d,left:b,width:c.width,height:c.height}};
function Uc(){var a=rb(document),b;b=window.document;b="CSS1Compat"==b.compatMode?b.documentElement:b.body;b=new db(b.clientWidth,b.clientHeight);return{x:a.x,y:a.y,width:b.width,height:b.height}}function Wc(a,b,c,d){var e=[],f=m,h=m,l=m,n=m,w=m;d=d||document;d=O("img",m,d);for(var s=0,A=d.length;s<A;s++)l=d[s],w=l.getAttribute("src"),f=l.getAttribute(c),n=l.getAttribute(a.Rc),f&&(a.Mc&&(f=Xc(a,f)),h=a.U(d[s]),h.src=f,h.url=w,h.X=l,h.Qc=n,h.type=b,e.push(h));return e}
function Xc(a,b){a.index++;return b.replace(a.exp,function(){return a.fd[a.index%5]})}q.P=function(a){a=Wc(this,this.W.eb,this.Dc,a);Array.prototype.push.apply(this.ca,a);this.Da()};q.o=function(){U(r,"scroll",z(this.ec,this));U(r,"resize",z(this.ec,this));U(Y,"Add_Display",z(this.Ac,this))};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function Yc(a,b){this.ha=[];this.nd=a;this.yc=b||m}q=Yc.prototype;q.$=p;q.ra=p;q.hb=p;q.sc=p;q.gc=p;q.uc=0;q.Hb=function(a,b){this.hb=p;Zc(this,a,b)};function Zc(a,b,c){a.$=k;a.xb=c;a.ra=!b;$c(a)}function ad(a){a.$&&(a.gc||g(new bd(a)),a.gc=p)}function cd(a){return Ya(a.ha,function(a){return fa(a[1])})}
function $c(a){a.Cb&&(a.$&&cd(a))&&(r.clearTimeout(a.Cb),delete a.Cb);a.B&&(a.B.uc--,delete a.B);for(var b=a.xb,c=p,d=p;a.ha.length&&!a.hb;){var e=a.ha.shift(),f=e[0],h=e[1],e=e[2];if(f=a.ra?h:f)try{var l=f.call(e||a.yc,b);t(l)&&(a.ra=a.ra&&(l==b||l instanceof Error),a.xb=b=l);b instanceof Yc&&(d=k,a.hb=k)}catch(n){b=n,a.ra=k,cd(a)||(c=k)}}a.xb=b;d&&(d=b,l=z(a.Hb,a,k),f=z(a.Hb,a,p),d.ha.push([l,f,j]),d.$&&$c(d),b.sc=k);c&&(a.Cb=r.setTimeout(function(){g(b)},0))}
function bd(a){G.call(this);this.jd=a}B(bd,G);bd.prototype.message="Deferred has already fired";bd.prototype.name="AlreadyCalledError";function dd(){if(this&&this.dc){var a=this.dc;a&&"SCRIPT"==a.tagName&&ed(a,k,this.ia)}}function ed(a,b,c){c!=m&&r.clearTimeout(c);a.onload=ca;a.onerror=ca;a.onreadystatechange=ca;b&&window.setTimeout(function(){vb(a)},0)}function fd(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);G.call(this,c);this.code=a}B(fd,G);function gd(a){this.u={id:0,cb:m,name:m,dd:0,Nc:p,Bc:0};Va(this.u,a);this.$b=0}gd.prototype.pa=function(){return this.u.id};gd.prototype.Ob=function(){return t(this.u.cb)?this.u.cb:p};gd.prototype.toString=function(){var a=this.Ob(),b=this.pa();(!t(a)||!a)&&g(Error("storm need wid"));(!t(b)||!b)&&g(Error("storm need id"));var c=["storm://"],d=[];c.push(9<a?a:"0"+a);c.push(this.$b);c.push("0000");c.push(b);d.push(c.join(""));return d.join("||")};
function id(a){gd.call(this,{id:a.vid,name:a.vname,dd:a.update_time,Nc:a.ispay,Bc:a.dzone,ld:a.flash});this.$b=1;this.Yc(a)}B(id,gd);id.prototype.Yc=function(a){t(a.v_sub_title)&&(this.u.qd=a.v_sub_title);t(a.video_time)&&(this.u.time=a.video_time);t(a.location)&&(this.u.location=a.location);t(a.publish_date)&&(this.u.od=a.publish_date);this.u.cb="wid"in a?a.wid:0};id.prototype.Mb=function(){var a=this.u.pc;return a?a:0};function jd(a,b){function c(a){e.push(a)}var d={id:a,format:b},e=[],f=new yc,h=["Consultation/web.php"],l;for(l in h)c.call(j,h[l]);Qa(d,function(a,b){f.set(b,a)});f.set("_random","false");return new Hc(e.join("/"),f)};function kd(a,b){this.ed=new sc(a);this.vc=b?b:"callback";this.ia=5E3}var ld=0;
kd.prototype.send=function(a,b,c,d){var e=a||m,f=d||"_"+(ld++).toString(36)+na().toString(36);r._callbacks_||(r._callbacks_={});a=this.ed.C();if(e)for(var h in e)(!e.hasOwnProperty||e.hasOwnProperty(h))&&Fc(a,h,e[h]);b&&(r._callbacks_[f]=function(a){md(f,k);b.apply(j,arguments)},Fc(a,this.vc,"_callbacks_."+f));var l=a.toString(),n={timeout:this.ia,wc:k};h=n.document||document;var w=document.createElement("SCRIPT");a={dc:w,ia:j};var s=new Yc(dd,a),A=m;d=n.timeout!=m?n.timeout:5E3;0<d&&(A=window.setTimeout(function(){ed(w,
k);var a=new fd(1,"Timeout reached for loading script "+l);ad(s);Zc(s,p,a)},d),a.ia=A);w.onload=w.onreadystatechange=function(){if(!w.readyState||"loaded"==w.readyState||"complete"==w.readyState)ed(w,n.wc||p,A),ad(s),Zc(s,k,m)};w.onerror=function(){ed(w,k,A);var a=new fd(0,"Error while loading script "+l);ad(s);Zc(s,p,a)};ob(w,{type:"text/javascript",charset:"UTF-8",src:l});a=h.getElementsByTagName("HEAD");(!a||0==a.length?h.documentElement:a[0]).appendChild(w);s.ha.push([m,function(){md(f,p);c&&
c(e)},j]);s.$&&$c(s);return{ob:f,zc:s}};function md(a,b){r._callbacks_[a]&&(b?delete r._callbacks_[a]:r._callbacks_[a]=ca)};/*
 {@link www.baofeng.com}
*/
function Z(){this.M={mc:"Event_Billing",OPEN:"Event_Open",ya:"Event_Complete",nc:"Event_Error"};this.Sb=p;this.Ba="";this.Fc="json";this.height=this.width=0;this.kc;this.rd=m}B(Z,V);Z.TIMEOUT=8E3;function nd(a,b,c,d){b&&("number"==typeof c&&"number"==typeof d)&&(a.width=c,a.height=d,a.Ba=b)}
Z.prototype.qc=function(a){this.Sb=a.url?k:p;this.dispatchEvent({type:this.M.mc,target:this});if(this.Sb){var b=document.createElement("iframe");b.width=this.width;b.height=this.height;b.scrolling="no";b.frameBorder="no";b.align="center";b.marginHeight="0";b.marginWidth="0";b.src=a.url;U(b,"load",function(){this.dispatchEvent({type:this.M.ya})},p,this);this.kc.appendChild(b)}};Z.prototype.error=function(a){this.dispatchEvent({type:this.M.nc,target:this,error:a})};
Z.prototype.P=function(a){this.kc=a;if(this.Ba&&this.width&&this.height){var b=z(this.qc,this),c=z(this.error,this);a=Z.TIMEOUT;var d=new jd(this.Ba,this.Fc),d=new kd(d),e=p;a&&(d.ia=a);a=d.send(m,function(a){e=k;b(a)},function(){c("\u8bf7\u6c42\u540e\u7fbf\u7cfb\u7edf\u5f02\u5e38")});C&&(a=a.zc,a.ha.push([function(){e||c&&c("\u8bf7\u6c42\u540e\u7fbf\u7cfb\u7edf\u5f02\u5e38")},m,j]),a.$&&$c(a));(new Image).src='http://log.houyi.baofeng.net/logger.php?ltype=wadaction&msg={"id":"'+this.Ba+'","adpid":"2"}'}else this.error("\u4f20\u5165\u5e7f\u544a\u9700\u6c42\u53c2\u6570\u4e0d\u5b8c\u6574\u3002")};
Z.prototype.o=function(){this.dispatchEvent({type:this.M.OPEN,target:this})};function od(){if((this.id=this.pa())&&0<this.id.length&&1240<=r.screen.width)this.left=ub('<div class="ad-bar-l" style="display: none;"><div class="ad-bar-close"><a href="javascript:void(0)">\u5173\u95ed</a></div></div>'),r.document.body.appendChild(this.left),this.Ra=new Z,nd(this.Ra,this.id,120,270),W(this.Ra,this.left),U(this.Ra,this.Ra.M.ya,this.Pc,p,this),this.right=ub('<div class="ad-bar-r" style="display: none;"><div class="ad-bar-close"><a href="javascript:void(0)">\u5173\u95ed</a></div></div>'),
r.document.body.appendChild(this.right),this.$a=new Z,nd(this.$a,this.id,120,270),W(this.$a,this.right),U(this.$a,this.$a.M.ya,this.$c,p,this),U(r,"resize",this.wb,p,this),"hddl"==this.id&&(K(this.left,"ad-bar-bottom"),K(this.right,"ad-bar-bottom"))}od.prototype.pa=function(){return r.ad_dl_id};od.prototype.Pc=function(){this.wb();U(this.left,"click",function(a){"A"===a.target.nodeName&&vb(this.left)},p,this);setTimeout(z(function(){Q(this.left,k)},this),500)};
od.prototype.$c=function(){this.wb();U(this.right,"click",function(a){"A"===a.target.nodeName&&vb(this.right)},p,this);setTimeout(z(function(){Q(this.right,k);var a=document,b={type:"showRightBannerAd",target:document},c=S;"showRightBannerAd"in c&&(c=c.showRightBannerAd,p in c&&ac(c[p],a,"showRightBannerAd",p,b))},this),500)};
od.prototype.wb=function(){var a=Hb(r.document.body);1240<a.width?(Cb(this.left,{left:(a.width-1220)/2+"px"}),Cb(this.right,{right:(a.width-1220)/2+"px"})):(Cb(this.left,{left:"10px"}),Cb(this.right,{right:"10px"}))};new od;function pd(){this.Aa=new Z;this.element=ub('<div class="ad-pop-wrap" style="display: none;"><div class="ad-pop-close"><a href="javascript:void(0)">\u5173\u95ed</a></div></div>');r.document.body.appendChild(this.element);nd(this.Aa,"hdtips",300,250);W(this.Aa,this.element);U(this.Aa,this.Aa.M.ya,this.bd,p,this)}pd.prototype.bd=function(){U(this.element,"click",function(a){"A"===a.target.nodeName&&vb(this.element)},p,this);setTimeout(z(function(){Q(this.element,k)},this),500)};new pd;function rd(){};function sd(){}B(sd,rd);sd.prototype.clear=function(){var a;a=this.ka(k);if(v(a))a=bb(a);else{a=nc(a);var b=[],c=function(a){b.push(a)};if(v(a))try{I(a,c,j)}catch(d){d!==lc&&g(d)}else{a=nc(a);try{for(;;)c.call(j,a.next())}catch(e){e!==lc&&g(e)}}a=b}var f=this;I(a,function(a){f.remove(a)})};function td(a){this.r=a}B(td,sd);q=td.prototype;q.set=function(a,b){try{this.r.setItem(a,b)}catch(c){0==this.r.length&&g("Storage mechanism: Storage disabled"),g("Storage mechanism: Quota exceeded")}};q.get=function(a){a=this.r.getItem(a);!x(a)&&a!==m&&g("Storage mechanism: Invalid value was encountered");return a};q.remove=function(a){this.r.removeItem(a)};
q.ka=function(a){var b=0,c=this.r,d=new mc;d.next=function(){b>=c.length&&g(lc);var d=c.key(b++);if(a)return d;d=c.getItem(d);x(d)||g("Storage mechanism: Invalid value was encountered");return d};return d};q.clear=function(){this.r.clear()};q.key=function(a){return this.r.key(a)};function ud(){var a=m;try{a=window.localStorage||m}catch(b){}this.r=a}B(ud,td);function vd(){var a=m;try{a=window.sessionStorage||m}catch(b){}this.r=a}B(vd,td);function wd(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))}function xd(a){return yd(new zd(j),a)}function zd(a){this.Ya=a}function yd(a,b){var c=[];Ad(a,b,c);return c.join("")}
function Ad(a,b,c){switch(typeof b){case "string":Bd(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if(u(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Ad(a,a.Ya?a.Ya.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),Bd(f,c),c.push(":"),
Ad(a,a.Ya?a.Ya.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}}var Cd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Dd=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Bd(a,b){b.push('"',a.replace(Dd,function(a){if(a in Cd)return Cd[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Cd[a]=e+b.toString(16)}),'"')};function Ed(a){this.wa=a;this.fc=new zd}q=Ed.prototype;q.wa=m;q.fc=m;q.set=function(a,b){t(b)?this.wa.set(a,yd(this.fc,b)):this.wa.remove(a)};q.get=function(a){a=this.wa.get(a);if(a!==m)try{return wd(a)}catch(b){g("Storage: Invalid value was encountered")}};q.remove=function(a){this.wa.remove(a)};function Fd(a){Ed.call(this,a)}B(Fd,Ed);function Gd(a){this.data=a}Fd.prototype.set=function(a,b){Fd.H.set.call(this,a,!t(b)||b instanceof Gd?b:new Gd(b))};Fd.prototype.get=function(a){var b;a=Fd.H.get.call(this,a);!t(a)||a instanceof Object?b=a:g("Storage: Invalid value was encountered");b?(b=b.data,t(b)||g("Storage: Invalid value was encountered")):b=j;return b};function Hd(a){if(Id)return Id;a=a?new vd:new ud;this.cookie=new Lc(r.document);var b;if(a.r)try{a.r.setItem("__sak","1"),a.r.removeItem("__sak"),b=k}catch(c){b=p}else b=p;b?(this.D=new Fd(a),this.qb=k):this.D=this.cookie;Id=this}var Id;Hd.prototype.set=function(a,b){a&&this.D.set.apply(this.D,J(arguments,0))};Hd.prototype.get=function(a){if(a)return this.D.get.apply(this.D,J(arguments,0))};
Hd.prototype.clear=function(){this.qb&&this.D.remove.apply(this.D,J(arguments,0));this.cookie.set.apply(this.cookie,J(arguments,0))};Hd.prototype.remove=function(a){a&&this.D.remove.apply(this.D,J(arguments,0))};function Jd(a){this.tb=a||15;this.key="bfViewRecords";this.z=7776E3;this.path="/";this.domain=".baofeng.com";this.f=Id?Id:new Hd(j);if(this.f.qb){a=0;for(var b=Kd(this.f.cookie.get(this.key));a<b.length;a++)this.add(b[a])}}da(Jd);function Ld(a){var b="",c;for(c in a)b+=c+"="+encodeURIComponent(a[c])+"&";return b=b.substring(0,b.length-1)}q=Jd.prototype;q.list=function(){return Kd(this.f.get(this.key))};q.F=function(){return this.f.get(this.key)};
q.map=function(){for(var a=this.list(),b={},c=0,d=a.length;c<d;c++)b[a[c].id]=a[c];return b};function Kd(a){var b=[];a=a||"";if(0===a.length)return b;a=a.split(",");for(var c=0,d=a.length;c<d;c++){for(var e={},f=a[c].split("&"),h=0,l=f.length;h<l;h++){var n=f[h].split("=");e[n[0]]=2==n.length?decodeURIComponent(n[1]):m}b.push(e)}return b}q.nb=function(a){for(var b=0,c=this.list();b<c.length;b++)if(c[b].id==a)return c[b];return m};
q.add=function(a){for(var b=this.list(),c="",d=p,e=0,f=b.length;e<f;e++)b[e].id==a.id?d=k:c+=Ld(b[e])+",";b.length>=this.tb&&d===p&&(c=c.substring(c.indexOf(",")+1));c+=Ld(a);this.f.set(this.key,c,this.z,this.path,this.domain);d||this.i("Event_Record","ADD",a.id)};q.mb=function(a){for(var b=this.list(),c=p,d="",e=0,f=b.length;e<f;e++)b[e].id==a?c=k:d+=Ld(b[e])+",";c&&(d=d.substr(0,d.length-1),this.f.set(this.key,d,this.z,this.path,this.domain),this.i("Event_Record","DEL",a))};
q.remove=function(){this.f.clear(this.key,"",this.z,this.path,this.domain)};q.clear=function(){this.f.clear(this.key,"",this.z,this.path,this.domain);this.i("Event_Record","DEL","")};q.i=function(a,b,c){Y.dispatchEvent({type:a,kind:b,id:c})};function Md(a,b){this.anchor=a;this.h=b;this.fb="expd";this.N=[]}B(Md,V);q=Md.prototype;q.yb=aa("anchor");q.za=function(a){this.N.push(a)};q.o=function(){U(this.anchor,"mouseover",z(this.show,this,k));U(this.anchor,"mouseout",z(this.m,this,50));U(this.h,"mouseover",z(this.show,this));U(this.h,"mouseout",z(this.m,this,50))};q.show=function(){this.e&&(clearTimeout(this.e),this.e=m);for(var a=0,b=this.N.length;a<b;a++)Q(this.N[a],p);Q(this.h,k);K(this.anchor,this.fb)};
q.m=function(a){this.e&&(clearTimeout(this.e),this.e=m);a&&0<a?this.e=setTimeout(z(this.m,this),a):(Q(this.h,p),M(this.anchor,this.fb))};var Qc={active:{name:"\u64ad\u653e\u63a7\u4ef6\u76f8\u5173",infor:"\u6709\u7f51\u9875\u64ad\u653e\u7ec4\u4ef6 \u65e0\u7f51\u9875\u64ad\u653e\u7ec4\u4ef6 \u6709\u5c0f\u5305 \u65e0\u5c0f\u5305 \u7406\u8bba\u5f39\u51fa\u9ec4\u6761\u6570 \u4e2d\u5305\u5c1d\u8bd5\u4e0b\u8f7d \u4e2d\u5305\u5f00\u59cb\u4e0b\u8f7d \u4e2d\u5305\u4e0b\u8f7d\u5931\u8d25 \u4e2d\u5305\u4e0b\u8f7d\u6210\u529f \u4e2d\u5305\u5b89\u88c5\u6210\u529f \u4e2d\u5305\u5b89\u88c5\u5931\u8d25 \u64ad\u653e\u5668\u4e0b\u65b9\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570clickonce\u4e0b\u8f7d \u64ad\u653e\u5668\u4e2d\u592e\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570clickonce\u4e0b\u8f7d \u64ad\u653e\u5668\u5e95\u90e8\u6587\u5b57\u94fe\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570clickonce\u4e0b\u8f7d \u975eie\u64ad\u653e\u5668\u4e0b\u65b9\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570 \u975eIE\u64ad\u653e\u5668\u5e95\u90e8\u6587\u5b57\u94fe\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570 \u64ad\u653e\u5668\u4e0b\u65b9\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570GUI\u4e0b\u8f7d \u64ad\u653e\u5668\u4e2d\u592e\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570GUI\u4e0b\u8f7d \u64ad\u653e\u5668\u5e95\u90e8\u6587\u5b57\u94fe\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570GUI\u4e0b\u8f7d".split(" "),
bfinfo:[{pagesstate:1},{pagesstate:2},{lbstate:1},{lbstate:2},{yellowpop:1},{mbtry:1},{mbbegin:1},{mbfail:1,value:1},{mbsuccess:1},{mbsetup:1},{mbsetup:1,value:1},{linkdownload:2},{setupdownload:2},{linkdownload:2},m,m,{linkdownload:1},{setupdownload:1},{linkdownload:1}]},webplayer:{name:"\u64ad\u653e\u76f8\u5173",infor:"onPlayerOpen onPlayerPlay onPlayerPause OnPlayerPlayStart onPlayerFinish onPlayerOpenFail onPlayerClose onPlayerStop".split(" ")},flashplayer:{name:"flash\u64ad\u653e\u76f8\u5173",
infor:"\u5f00\u59cb\u64ad\u653eclickonce\u4e0b\u8f7d \u5c1d\u8bd5\u64ad\u653e \u64ad\u653e\u6210\u529f \u7f13\u51b2\u65f6\u95f4 \u9519\u8bef \u64ad\u653e\u6682\u505c \u5931\u8d25FLASH\u7684\u4e0b\u8f7d\u6309\u94aeclickonce\u4e0b\u8f7d \u64ad\u653e\u5b8c\u6210 flash\u52a0\u8f7d\u8d85\u65f6\u5931\u8d25 flash\u52a0\u8f7d\u8d85\u65f6\u5931\u8d25 \u5931\u8d25FLASH\u7684\u4e0b\u8f7d\u6309\u94aeGUI\u4e0b\u8f7d \u5f00\u59cb\u64ad\u653eGUI\u4e0b\u8f7d \u89c6\u9891cid \u7248\u672c\u53f7 flash\u89c2\u770b\u65f6\u957f \u5361\u987f\u6b21\u6570 flash\u64ad\u653e\u5668\u7248\u672c\u53f7".split(" "),
bfinfo:[{playdownload:2},{flshtry:1},{flashsuccess:1,key:"flashsuccess"},{flashloadtime:1,key:"flashloadtime"},{flasherr:1,key:"flasherr"},m,{faildownload:2},m,m,m,{faildownload:1},{playdownload:1},{flashiid:1,key:"flashiid"},{flashver:1,key:"flashver"},{flashtime:1,key:"flashtime"},{flashbuffrtempty:1,key:"flashbuffrtempty"}]},houyi:{name:"\u540e\u7fbf\u5e7f\u544a",infor:"\u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u603b\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u6210\u529f \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u5931\u8d25 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u6210\u529f\u6709\u5e7f\u544a \u64ad\u653e\u5668\u53f3\u4fa7\u5e7f\u544a\u88ab\u52a8\u5c55\u73b0\u6b21\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u5e7f\u544a\u4e3b\u52a8\u5c55\u73b0\u6b21\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u5c1d\u8bd5\u8bf7\u6c42\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u6210\u529f\u65e0\u5e7f\u544aURL".split(" "),
bfinfo:[m,{hyrequest:1},m,{hyadrequest:1},{addisplay:2},{addisplay:1},m,{hyadrequest:0,value:0}]},b3:{name:"B3\u5224\u65ad",infor:"B3\u5c1d\u8bd5\u8bf7\u6c42\u603b\u6570 B3\u8bf7\u6c42\u6210\u529f\u6570 B3\u8bf7\u6c42\u5931\u8d25\u6570 B3\u5224\u65ad\u6b63\u7247\u53ef\u64ad B3\u5224\u65ad\u6b63\u7247\u4e0d\u53ef\u64ad\u64ad\u7247\u82b1 \u64ad\u653e\u9884\u544a\u7247 B3\u5224\u65ad\u5f71\u7247\u8d44\u6e90\u4e0d\u5b58\u5728".split(" "),bfinfo:[{b3request:1,value:0},{b3state:1,value:0},{b3state:2,value:0},
{b3judge:1,value:0},{b3judge:2,value:0},m,{b3fail:1,value:0}]},noIE:{name:"\u975eIE\u6d4f\u89c8\u5668",infor:["\u4f7f\u7528ie\u6d4f\u89c8\u5668\u6dfb\u52a0\u6536\u85cf","\u4f7f\u7528\u975eie\u6d4f\u89c8\u5668\u6dfb\u52a0\u6536\u85cf","IE\u6d4f\u89c8\u5668","\u975eIE\u6d4f\u89c8\u5668"],bfinfo:[{exfav:0},{exfav:1}]},other:{name:"\u76f8\u5173\u63a5\u53e3",infor:"\u8bc4\u8bba\u8bf7\u6c42\u603b\u6570 \u8bc4\u8bba\u6210\u529f\u5c55\u73b0\u6570 \u8bc4\u8bba\u8bf7\u6c42\u5931\u8d25\u6570 MINFO\u8bf7\u6c42\u603b\u6570 MINFO\u8bf7\u6c42\u6210\u529f MINFO\u8bf7\u6c42\u5931\u8d25".split(" "),
bfinfo:[{comrequest:1},{comstate:1},{comstate:2},{minforequest:1},{minfostate:1},{minfostate:2}]},buttonClick:{name:"\u6309\u94ae\u70b9\u51fb",infor:"\u89c2\u770b\u8bb0\u5f55\u6d6e\u5c42\u5c55\u73b0\u6b21\u6570 \u89c2\u770b\u8bb0\u5f55\u70b9\u51fb\u6570 \u6dfb\u52a0\u5feb\u6377\u65b9\u5f0f\u6309\u94ae\u70b9\u51fb\u6570 \u5267\u96c6\u6309\u94ae\u70b9\u51fb\u6570 \u5267\u96c6\u533a\u95f4\u70b9\u51fb\u6570 \u5267\u96c6\u683c\u5f0f\u5207\u6362\u70b9\u51fb\u6570 \u5267\u96c6\u5c55\u5f00\u70b9\u51fb\u6570 \u5267\u96c6\u6536\u8d77\u70b9\u51fb\u6570 \u64ad\u653e\u5668\u4e0b\u65b9\u76f8\u5173\u63a8\u8350\u70b9\u51fb\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u76f8\u5173\u63a8\u8350\u70b9\u51fb\u6570".split(" ")},
tyg:{name:"\u4f53\u9a8c\u9986",infor:["\u4f53\u9a8c\u99863D\u5f71\u7247\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570","\u4f53\u9a8c\u9986\u5de6\u773c\u5f71\u7247\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570","\u4f53\u9a8c\u9986\u5b89\u88c5\u66b4\u98ce\u7ec4\u4ef6\u70b9\u51fb\u6570clickOnce","\u4f53\u9a8c\u9986\u540e\u64ad\u63a8\u8350\u70b9\u51fb\u6570","\u4f53\u9a8c\u9986\u5b89\u88c5\u66b4\u98ce\u7ec4\u4ef6\u70b9\u51fb\u6570GUI"],bfinfo:[m,m,{testsetup:2},m,{testsetup:1}]},jizhi:{name:"\u6781\u81f4\u529f\u80fd\u6309\u94ae\u4f7f\u7528",
infor:["3D\u6309\u94ae\u70b9\u51fb\u6570","\u5de6\u773c\u6309\u94ae\u70b9\u51fb\u6570","\u53f3\u8033\u6309\u94ae\u70b9\u51fb\u6570","IE\u4e0d\u652f\u6301\u6781\u81f4\u529f\u80fd","\u975eIE\u4e0d\u652f\u6301\u6781\u81f4\u529f\u80fd"],bfinfo:[{acmestate:1},{acmestate:2},{acmestate:3},{acmestate:4},{acmestate:5}]},search:{name:"\u641c\u7d22\u76f8\u5173\u62a5\u6570",infor:["\u70b9\u51fb\u641c\u7d22\u6309\u94ae","\u5c1d\u8bd5\u641c\u7d22"],bfinfo:[{tsearch:1},{tsearch:1}]},detail:{name:"\u8be6\u60c5\u9875\u76f8\u5173\u6570",
infor:["\u8be6\u60c5\u9875\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570","\u8be6\u60c5\u9875\u5408\u4f5c\u65b9\u89c6\u9891\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570"],bfinfo:[{playstate:1},{playstate:2}]},movie:{name:"\u5f71\u7247\u64ad\u653e",infor:["\u901a\u8fc7\u5ba2\u6237\u7aef\u64ad\u653e","\u901a\u8fc7\u7f51\u9875\u64ad\u653e"],bfinfo:[{playstate:2},{playstate:1}]},micvideo:{name:"\u5fae\u89c6\u9891\u9996\u9875",infor:["\u4eca\u65e5\u5173\u6ce8","\u5a31\u4e50\u661f\u95fb","\u7f51\u7edc\u70ed\u8bae",
"\u5c4c\u4e1d\u5b85\u7537","\u7206\u7b11\u63a8\u8350"],bfinfo:[{"\u4eca\u65e5\u5173\u6ce8":2},{"\u5a31\u4e50\u661f\u95fb":2},{"\u7f51\u7edc\u70ed\u8bae":2},{"\u5c4c\u4e1d\u5b85\u7537":2},{"\u7206\u7b11\u63a8\u8350":2}]},baiduvip:{name:"\u767e\u5ea6VIP",infor:["\u767e\u5ea6VIP\u7528\u6237"],bfinfo:[{baiduvip:1}]}};function Nd(){this.N=[]}B(Nd,V);q=Nd.prototype;q.yb=aa("anchor");q.za=function(a){this.N.push(a)};q.P=function(a){this.h=a;this.Jc=P("innerBox",this.h);this.Wb=P("menuHolder",this.Jc);this.Pb=O("iframe",j,this.Wb)[0];this.Na=P("frame",this.Wb);this.xc=P("empty",this.Na);this.Va=P("his-none",this.Na);this.Sa=P("his-cont",this.Na);this.list=O("ul",j,this.Na)[0]};
q.o=function(){U(this.h,"mouseover",z(this.show,this));U(this.h,"mouseout",z(this.m,this,50));U(this.anchor,"mouseover",z(this.show,this,k));U(this.anchor,"mouseout",z(this.m,this,50));U(this.xc,"click",z(this.clear,this));U(this.list,"click",z(this.Hc,this))};q.log=function(a,b,c){Y.dispatchEvent({type:"log",data:{key:a,value:b,other:c}})};
q.show=function(a){this.e?(clearTimeout(this.e),this.e=m):this.log("buttonClick",1);for(var b=0,c=this.N.length;b<c;b++)Q(this.N[0],p);Q(this.h,k);K(this.anchor,"expd");if(a===k)if(a=this.ja.list().reverse(),0>=a.length)Q(this.Va,k),Q(this.Sa,p);else{Q(this.Va,p);Q(this.Sa,k);var d="",e=0,f=a.length;for(template='<li  id="${recordId}"><a title=${title} class="his-reco">${recordName}</a><a class="continueButton">\u7ee7\u7eed\u89c2\u770b</a><span class="closed"></span></li>';e<f;e++){b=a[e];c=b.name;
recordId=b.id;if(!b.type||!("5"===b.type||"1"===b.type))"undefined"!==typeof b.loc&&"null"!=b.loc?c+=" \u7b2c"+b.loc+"\u671f":"undefined"!==typeof b.drama&&"null"!=b.drama&&(c+=" \u7b2c"+b.drama+"\u96c6");d+=template.replace("${title}",c).replace("${recordName}",c).replace("${recordId}","record-"+recordId)}this.list.innerHTML=d;this.gb()}};q.sa=function(a){console.log(a.target)};q.m=function(a){a&&0<a?this.e=setTimeout(z(this.m,this),a):(Q(this.h,p),M(this.anchor,"expd"))};
q.gb=function(){for(var a=0,b=this.list.children.length;a<b;a++){var c=this.list.children[a];U(c,"mouseover",z(this.ma,this));U(c,"mouseout",z(this.ma,this))}};q.ma=function(a){var b=a.currentTarget;"mouseover"==a.type&&this.R(a,b)?b.className="cur":"mouseout"==a.type&&this.R(a,b)&&(b.className="")};
q.R=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement||k;else if("mouseout"==c)c=a.relatedTarget||a.toElement||k;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};q.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};
q.Hc=function(a){a.preventDefault();a=a.target;var b;if("continueButton"===a.className||"his-reco"===a.className){b=this.ja.nb(a.parentNode.id.split("-")[1]);var c="/play/"+b.id%500+"/play-"+b.id;"5"===(b.type||"-1")?(c="",b.wid&&"13"!=b.wid&&(c="-"+b.wid),c="/micv/"+b.id%500+"/micv-"+b.id+c+"-vid-"+b.vid+".html"):("undefined"!==typeof b.drama&&"null"!=b.drama&&(c+="-drama-"+b.drama),"undefined"!==typeof b.format&&"null"!=b.format&&(c+="-format-"+b.format),"undefined"!==typeof b.trailer&&"null"!=
b.trailer&&(c+="-trailer-"+b.trailer),c+=".html");b=c;Q(this.h,p);r.open(b,"_blank");this.log("buttonClick",2)}"closed"==a.className&&(b=this.ja.nb(a.parentNode.id.split("-")[1]),(b=b.id)&&this.ja.mb(b),0==this.ja.list().length&&(Q(this.Sa,p),Q(this.Va,k)),a.parentNode.parentNode.removeChild(a.parentNode))};q.clear=function(){this.ja.clear();Q(this.Sa,p);Q(this.Va,k)};function Od(a){a=a||{};var b=this.g={Ja:"hd-load-text-on",Ga:50},c;for(c in a)b[c]=a[c];(!this.g.anchor||!this.g.content)&&this.dispatchEvent({type:"error",message:"hd.component.Popup params must contains anchor and content"})}B(Od,V);
Od.prototype.o=function(){try{U(this.g.anchor,"mouseover",this.show,p,this),U(this.g.anchor,"mouseout",z(this.m,this,this.g.Ga)),U(this.g.content,"mouseover",this.show,p,this),U(this.g.content,"mouseout",z(this.m,this,this.g.Ga))}catch(a){this.dispatchEvent({type:"error",message:"enterDocument method error"})}};Od.prototype.show=function(){this.e&&(clearTimeout(this.e),this.e=m);this.g.Ja&&K(this.g.anchor,this.g.Ja);Q(this.g.content,k);this.dispatchEvent("show")};
Od.prototype.m=function(a){this.e&&(clearTimeout(this.e),this.e=m);a&&0<a?this.e=setTimeout(z(this.m,this),a):(this.g.Ja&&M(this.g.anchor,this.g.Ja),Q(this.g.content,p),this.dispatchEvent("hide"))};function Pd(a,b){Y.dispatchEvent({type:"log",data:{key:"movie",value:a,other:b}})};var Qd=m,Rd=D||E||Ca||"function"==typeof r.atob;
function Sd(a){var b;if(Rd)b=r.btoa(a);else{b=[];for(var c=0,d=0;d<a.length;d++){for(var e=a.charCodeAt(d);255<e;)b[c++]=e&255,e>>=8;b[c++]=e}v(b)||g(Error("encodeByteArray takes an array as a parameter"));if(!Qd){Qd={};for(a=0;65>a;a++)Qd[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}a=Qd;c=[];for(d=0;d<b.length;d+=3){var f=b[d],h=(e=d+1<b.length)?b[d+1]:0,l=d+2<b.length,n=l?b[d+2]:0,w=f>>2,f=(f&3)<<4|h>>4,h=(h&15)<<2|n>>6,n=n&63;l||(n=64,e||(h=64));c.push(a[w],
a[f],a[h],a[n])}b=c.join("")}return b};function Td(){this.ab="\u8bf7\u8f93\u5165\u5f71\u7247\u540d\u3001\u5173\u952e\u5b57";this.Tb=r.static_keyword||""}B(Td,V);q=Td.prototype;q.P=function(a){this.h=a;this.form=O("form",j,this.h)[0];a=O("input",j,this.form);this.input=a[0];this.button=a[1];this.j=O("div",j,this.h)[1];this.Pb=O("iframe",j,this.j)[0];this.Xa=O("div",j,this.j)[0]};q.log=function(a,b,c){Y.dispatchEvent({type:"log",data:{key:a,value:b,other:c}})};
q.o=function(){var a=this;U(this.input,"mouseup",function(){a.log("search",2)});U(this.input,"focus",z(this.Ec,this));U(this.input,"blur",z(this.tc,this));U(this.input,"keyup",z(this.Oc,this));U(this.button,"mouseover",function(){K(this.button,"hover")},p,this);U(this.button,"mouseout",function(){M(this.button,"hover")},p,this);U(this.button,"mousedown",function(){K(this.button,"act")},p,this);U(this.button,"mouseup",function(){M(this.button,"act")},p,this);U(this.button,"focus",function(){this.button.blur()},
p,this);U(this.form,"submit",function(){a.log("search",1);var b=P("selected",this.j);Ud(this,b);setTimeout(z(function(){this.input.blur()},this),100)},p,this);U(this.j,"click",function(a){a=a.target;"A"===a.nodeName&&(Q(this.j,p),Ud(this,a))},p,this);var b=this.ab;if(this.Tb)b=this.Tb;else{var c=[],d=P("hotWords",this.h);if(d){for(var d=wb(d),e=0,f=d.length;e<f;e++)c.push(Ab(d[e]));0<c.length&&(b=c[Math.floor(Math.random()*c.length)])}}this.ab=b;this.input.value=this.ab};
q.Ec=function(){this.input.value="";K(this.input,"focus");return p};q.tc=function(){M(this.input,"focus");""===this.input.value&&(this.input.value=this.ab);setTimeout(z(function(){Q(this.j,p);var a=this.Xa;if("textContent"in a)a.textContent="";else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=""}else{for(var b;b=a.firstChild;)a.removeChild(b);a.appendChild(mb(a).createTextNode(""))}},this),500)};
q.Oc=function(a){a=a.keyCode;var b=this.input.value;if(0>=b.length)Q(this.j,p);else if(("38"==a||"40"==a)&&"none"!=this.Xa.style.display){var c=wb(this.Xa),d=c.length;if(0<d)if("none"!=this.j.style.display===p)Q(this.j,k);else{for(var e=-1,d=c.length,f=0;f<d;f++){var h=c[f];Za(gb(h),"selected")&&(e=f);M(h,"selected")}e="38"==a?e-1:e+1;0>e&&(e=d-1);e>d-1&&(e=0);K(c[e],"selected")}}else{var l=z(function(a){var c=this.input.value;if(c===b)if(0<c.length&&0<a.length){for(var c="",d=["\u7535\u5f71","\u7535\u89c6\u5267",
"\u52a8\u6f2b","\u7efc\u827a"],e=0,f=a.length;e<f;e++){var h=a[e],l=h.name,pb="\u7535\u5f71",ga=parseInt(h.channel);isNaN(ga)===p&&(1<ga&&5>ga)&&(pb=d[ga-1]);c+='<a href="javascript:void(0);" onclick="return false;">'+l+"<span>("+pb+")</span></a>";if(0===e&&"\u7535\u5f71"!==pb&&"undefined"!==typeof h.drama){var ga=h.id,ee=h.wid,fe=h.aid,ge=h.vid,qd=h.drama;(h=h.sub_title)||(h=qd);c+='<a href="javascript:void(0);" onclick="return false;" class="search-suggest-detail"';c+=' m-id="'+ga+'"';c+=' m-wid="'+
ee+'"';c+=' m-aId="'+fe+'"';c+=' m-vId="'+ge+'"';c+=' m-drama="'+qd+'"';c="\u7efc\u827a"===pb?c+(">\u6700\u65b0\u4e00\u671f("+h+")</a>"):c+(">\u6700\u65b0\u4e00\u96c6("+h+")</a>");c+='<a href="javascript:void(0);" onclick="return false;" class="search-suggest-info" m-id="'+ga+'">'+l+"\u8be6\u60c5</a>";f=Math.min(f,6)}}0<c.length?(this.Xa.innerHTML=c,Q(this.j,k),c=Hb(this.j).height,a=this.Pb.style,"number"==typeof c&&(c=Math.round(c)+"px"),a.height=c):Q(this.j,p)}else Q(this.j,p)},this);a="http://search.hd.baofeng.com/prompt.php?query=${keyword}&start=0&limit=8".replace("${keyword}",
encodeURIComponent(b));a=new kd(a);a.ia=8E3;a.send(m,function(a){a?l(a.results):l(m)},function(){l(m)})}};
function Ud(a,b){if(b)if(Za(gb(b),"search-suggest-detail")){var c=b.getAttribute("m-id"),d=b.getAttribute("m-wid"),e=b.getAttribute("m-aid"),f=b.getAttribute("m-vid"),h=b.getAttribute("m-drama");if("13"==d){var l=c;Pd(2,l);l="/play/"+l%500+"/play-"+l;h&&(l+="-drama-"+h);r.open(l+".html","_blank")}else{h=new id({id:f,cb:d});h.u.pc=Number(e);var n="";ha(h)?(Pd(1,h.Ob()),n=h.toString(),h.Mb&&(h=h.Mb())&&0!==h&&(n+="||aid="+h)):n=h;h=function(){var a=document.createElement("iframe");Q(a,p);ob(a,{src:n});
document.body.appendChild(a)};e=function(){alert("\u672c\u7247\u9700\u8981\u4f7f\u7528\u66b4\u98ce\u5ba2\u6237\u7aef\u64ad\u653e\uff0c\u5982\u679c\u60a8\u5df2\u5b89\u88c5\uff0c\u60a8\u5c06\u4f7f\u7528\u5ba2\u6237\u7aef\u64ad\u653e\uff0c\u5982\u679c\u6ca1\u6709\uff0c\u8bf7\u5230\u5b98\u7f51www.baofeng.com\u4e0b\u8f7d\u3002")};if(C)try{l=new ActiveXObject("StormAxPlayer.Player"),/8\d$/.test(l.Version)?e():setTimeout(h,100)}catch(w){e()}else setTimeout(h,100),setTimeout(e,200)}}else Za(gb(b),"search-suggest-info")?
(c=b.getAttribute("m-id"),r.open("/detail/"+c%500+"/detail-"+c+".html","_blank")):(l=Ab(b),l=l.substring(0,l.lastIndexOf("(")),a.search(l));else a.search()}q.search=function(a){"undefined"===typeof a&&(a=this.input.value);a=encodeURIComponent(oa(a));if(0<a.length){Q(this.j,p);var b="_blank";0<=r.location.href.indexOf("q_")&&(b="_self");r.open("/q_"+Sd(a),b)}};/*
 {@link www.baofeng.com}
*/
function Vd(){this.name=this.id=m;this.oa=0;this.title=this.q=this.element=m;this.La="";this.va=k;this.bb=[" fv-add"," shadow-cut"];this.Ka=""}B(Vd,V);q=Vd.prototype;q.R=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement;else if("mouseout"==c)c=a.relatedTarget||a.toElement;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};q.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};
q.start=function(a){var b=this;this.element=a;this.q=P("fv-add-no",a);this.id=a.getAttribute("data-id");this.Ka=a.getAttribute("data-farther")||"";this.id&&this.q&&(this.La=a.className.replace(/fv-cut|shadow-cut/gi,function(a){"fv-cut"==a&&(b.bb[1]=" fv-cut");return""}),W(this,a))};
q.ub=function(a){var b;switch(a.type){case "mouseover":Wd(this,a.target,1);this.va&&(this.va=p,this.element.className=this.La+this.bb[0]);break;case "mouseout":Wd(this,a.target,0);!this.va&&this.R(a,this.element)&&(this.va=k,this.element.className=this.La+this.bb[1]);break;case "click":a=a.target,a==this.q?(this.oa?(a={type:"Event_Collect",kind:"DEL",id:this.id},b=0):(a={type:"Event_Collect",kind:"ADD",data:{id:this.id,name:this.name,element:this.q}},b=1),Xd(this,b),this.dispatchEvent(a)):"IMG"==
a.tagName.toUpperCase()&&"A"==a.parentNode.tagName.toUpperCase()&&(this.va=k,this.element.className=this.La+this.bb[1])}};function Wd(a,b,c){!a.oa&&b==a.q&&(a.q.className=c?"fv-add-Keep "+a.Ka:"fv-add-no")}function Xd(a,b){a.oa=b;a.oa?(a.q.title="\u53d6\u6d88\u6536\u85cf",a.Ka&&(a.q.innerHTML="\u5df2\u6536\u85cf"),a.q.className="fv-add-Keep"):(a.q.title="\u6536\u85cf",a.Ka&&(a.q.innerHTML="\u6536\u85cf"),a.q.className="fv-add-no")}q.P=function(a){this.name=a.getAttribute("data-name")};
q.o=function(){U(this.element,"mouseout",z(this.ub,this));U(this.element,"mouseover",z(this.ub,this));U(this.element,"click",z(this.ub,this))};function Yd(a){this.tb=a||15;this.key="bfCollects";this.z=7776E3;this.path="/";this.domain=".baofeng.com";this.f=Id?Id:new Hd(j);if(this.f.qb){var b=this.f.cookie.get(this.key)||"[]";a=0;for(b=wd(b);a<b.length;a++)this.add(b[a])}}da(Yd);q=Yd.prototype;q.list=function(){var a=this.f.get(this.key)||"[]";return wd(a)};q.F=function(){return this.f.get(this.key)};q.map=function(){for(var a=this.list(),b={},c=0,d=a.length;c<d;c++)b[a[c].id]=a[c];return b};
q.nb=function(a){for(var b=0,c=this.list();b<c.length;b++)if(c[b].id==a)return c[b];return m};q.add=function(a){var b=this.list(),c=0;b.length>=this.tb&&(c=b.shift().id);b.push(a);this.f.set(this.key,xd(b),this.z,this.path,this.domain);return c};function Zd(a,b,c){for(var d=a.list(),e=p,f=0,h=d.length;f<h;f++)if(d[f].id==b){e=k;d[f].lb=c;break}e&&a.f.set(a.key,xd(d),a.z,a.path,a.domain)}
q.mb=function(a){for(var b=this.list(),c=p,d=0,e=b.length;d<e;d++)if(b[d].id==a){b.splice(d,1);c=k;break}c&&this.f.set(this.key,xd(b),this.z,this.path,this.domain)};q.clear=function(){this.f.clear(this.key,"",this.z,this.path,this.domain)};q.i=function(a,b,c){Y.dispatchEvent({type:a,kind:b,id:c})};function $d(a){a&&(this.Cc=parseInt(this.U(a).left),this.kd=parseInt(this.U(a).top))}$d.prototype.kb=function(a,b,c){switch(arguments.length){case 2:if("object"==typeof b)for(var d in b)"opacity"==d?(a.style.filter="alpha(opacity="+b[d]+")",a.style[d]=b[d]/100):a.style[d]=b[d];else return a.currentStyle?a.currentStyle[b]:getComputedStyle(a,document)[b];break;case 3:"opacity"==b?(a.style.filter="alpha(opacity="+c+")",a.style[b]=c/100):a.style[b]=c}};
$d.prototype.U=function(a){var b=a.getBoundingClientRect(),c=Jb(a),d=a.ownerDocument;a=d.body;var e=d.documentElement,d=b.top+(self.pageYOffset||e.scrollTop||a.scrollTop)-(e.clientTop||a.clientTop||0),b=b.left+(self.pageXOffset||e.scrollLeft||a.scrollLeft)-(e.clientLeft||a.clientLeft||0);return{top:0>d?0:d,left:b,width:c.width,height:c.height}};function $(){this.time=this.bc=this.Gb=m;this.A={};this.d=Yd.qa();this.fa=Jd.qa();ae(this);this.ib=this.d.F();this.vb=this.fa.F();this.Ma=sb("div",{id:"fly"});Q(this.Ma,p);document.body.appendChild(this.Ma);this.jc=N("viewFavoriteButton");this.i("Event_Collect","UP",this.d.list());this.rc=new $d(this.jc)}B($,V);
$.prototype.Db=function(a){switch(a.kind){case "ADD":Q(this.Ma,k);var b=this.rc,c=this.Ma,d=a.data.element,e=this.jc,f=b.U(d).left,d=b.U(d).top,e=Math.max(parseInt(b.U(e).left),b.Cc),h=document.documentElement.scrollTop||document.body.scrollTop,l=30/Math.tan(Math.atan2(h-d,e-f)),d=d-30;b.kb(c,"left",f-l+"px");b.kb(c,"top",d+"px");var n={left:e-l,top:h-30},w=function(){Q(c,p)};clearInterval(c.e);var s=b.kb;c.e=setInterval(function(){var a=k,b,d;for(d in n){b="opacity"==d?100*parseFloat(s(c,d)):Math.round(parseInt(s(c,
d)));var e=(n[d]-b)/12,e=0<e?Math.ceil(e):Math.floor(e);"opacity"==d?s(c,d,b+e):s(c,d,b+e+"px");20<Math.abs(n[d]-b)&&(a=p)}a==k&&(clearInterval(c.e),w&&w())},30);a=a.data;b=this.fa.list();a={id:a.id,name:a.name,lb:0};f=0;for(d=b.length;f<d;f++)b[f].id==a.id&&(a.lb=1);b=this.d.add(a);be(this.A[a.id],1);b&&be(this.A[b],0);this.i("Event_Collect","UP",this.d.list());break;case "DEL":if(a=a.id)this.d.mb(a),be(this.A[a],0);else for(b in this.d.clear(),this.A)be(this.A[b],0);this.i("Event_Collect","UP",
this.d.list());break;case "UP":this.ib=this.d.F(),this.vb=this.fa.F()}};$.prototype.oc=function(a){var b=a.id;switch(a.kind){case "ADD":b&&(Zd(this.d,a.id,1),this.i("Event_Collect","UP",this.d.list()));break;case "DEL":if(b)Zd(this.d,a.id,0);else{a=this.d;for(var b=a.list(),c=0,d=b.length;c<d;c++)b[c].lb=0;a.f.set(a.key,xd(b),a.z,a.path,a.domain)}ae(this);this.i("Event_Collect","UP",this.d.list())}};
$.prototype.ic=function(){var a=p,b=this.d.F(),c=this.fa.F(),d;clearTimeout(this.time);if(this.ib!=b){var a=k,b=this.d.map(),e;for(e in this.A)d=this.A[e],b[e]?be(d,1):be(d,0);this.ib=this.d.F()}this.vb!=c&&(a=k,ae(this),this.vb=this.fa.F());a&&this.i("Event_Collect","UP",this.d.list());this.time=setTimeout(z(this.ic,this),1E3)};function be(a,b){var c;if(a)for(var d=0,e=a.length;d<e;d++)(c=a[d])&&c.oa!=b&&Xd(c,b)}
function ae(a){var b=a.d.list(),c,d;a.bc=a.fa.map();for(var e=0,f=b.length;e<f;e++)c=b[e].id,d=0,a.bc[c]&&(d=1),Zd(a.d,c,d)}$.prototype.i=function(a,b,c){Y.dispatchEvent({type:a,kind:b,data:c})};$.V=function(){var a=new $;U(Y,"Event_Record",z(a.oc,a));U(Y,"Event_Collect",z(a.Db,a));var b,c=nb("js-collect");a.Gb=a.d.map();for(var d=0;d<c.length;d++)b=new Vd,b.start(c[d]),a.A[b.id]?a.A[b.id].push(b):a.A[b.id]=[b],a.Gb[b.id]&&Xd(b,1),U(b,"Event_Collect",z(a.Db,a));a.time=setTimeout(z(a.ic,a),1E3)};
ba("baofeng.menu.init",$.V);function ce(){this.Fa=[];this.Ta="";this.Qa=0;this.Bb=this.anchor=this.Z=this.list=this.defaultView=this.jb=this.sb=m;this.cd='<li id="fav-{id}"><a title={title} class="his-reco" href="javascript:void(0);">{name}</a><a href="javascript:void(0);" class="{view} state">{lb}</a><span class="closed">\u5173\u95ed</span></li>'}B(ce,V);q=ce.prototype;q.P=function(a){this.Z=a;this.jb=P("his-cont");this.list=O("ul",j,this.jb)[0];this.sb=N("favoriteR");this.defaultView=P("his-none")};
q.o=function(){U(this.Z,"click",z(this.Gc,this));U(Y,"Event_Collect",z(this.Vc,this));U(this.anchor,"mouseover",z(this.sa,this));U(this.anchor,"mouseout",z(this.sa,this));U(this.Z,"mouseover",z(this.sa,this));U(this.Z,"mouseout",z(this.sa,this))};q.sa=function(a){this.Bb&&clearTimeout(this.Bb);"mouseover"==a.type?this.show():this.Bb=setTimeout(z(this.m,this),80)};q.show=function(){for(var a=0;a<this.Fa.length;a++)Q(this.Fa[a],p);Q(this.Z,k)};q.m=function(){Q(this.Z,p)};
q.Gc=function(a){var b=a.target.nodeName;if("SPAN"==b&&"closed"==a.target.className){var c=a.target.parentNode.id.replace("fav-","");this.i("Event_Collect","DEL",c)}if("A"==b&&(-1!=a.target.className.indexOf("empty")&&this.i("Event_Collect","DEL",""),-1!=a.target.className.indexOf("his-reco")||-1!=a.target.className.indexOf("state")))c=a.target.parentNode.id.replace("fav-",""),r.open("/play/"+c%500+"/play-"+c+".html","_blank")};
q.Vc=function(a){var b=a.data;"UP"==a.kind&&(this.cc(b),Q(this.sb,0<this.Qa?k:p),this.sb.innerHTML=this.Qa+"",this.list.innerHTML=this.Ta,Q(this.defaultView,0==this.list.children.length?k:p),Q(this.jb,0==this.list.children.length?p:k),this.gb())};q.gb=function(){for(var a=0,b=this.list.children.length;a<b;a++){var c=this.list.children[a];U(c,"mouseover",z(this.ma,this));U(c,"mouseout",z(this.ma,this))}};
q.ma=function(a){var b=a.currentTarget;"mouseover"==a.type&&this.R(a,b)?b.className="cur":"mouseout"==a.type&&this.R(a,b)&&(b.className="")};q.R=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement;else if("mouseout"==c)c=a.relatedTarget||a.toElement;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};q.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};
q.i=function(a,b,c){Y.dispatchEvent({type:a,kind:b,id:c})};q.cc=function(a){this.Ta="";this.Qa=0;for(var b=a.length-1;0<=b;b--){var c=a[b],d=this.cd,e;for(e in c){var f=c[e];"lb"==e&&(d=d.replace("{view}",1==f?"old":"new"),f=1==f?"\u5df2\u770b":"\u672a\u89c2\u770b");d=d.replace("{"+e+"}",f)}d=d.replace("{title}",c.name);this.Ta+=d;0==c.lb&&this.Qa++}};function de(a){try{var b;if(!Oc&&!("Win64"==Da||-1!=za().indexOf("Trident")&&/11\.(.)*/.test(Ha))){var c,d=r.navigator.plugins;if(d&&0<d.length)for(var e=0;e<d.length;e++){if(d[e][0].type.match("application/baofengwebplayer-plugin")){c=document.createElement("embed");c.type="application/baofengwebplayer-plugin";c.width="1";c.height="1";document.body.appendChild(c);Oc=c;break}}else try{Oc=new ActiveXObject("StormAxPlayer.Player")}catch(f){}}b=Oc;if(b)var h=b.GetUserId();else g(Error());if(t(h)&&"undefined"!=
h&&(h=h.substr(1).substr(0,h.length-2),t(h)&&"undefined"!=h)){var l=new Lc(r.document);l.set("uid",h,7776E3,"/",".baofeng.com")}}catch(n){l=new Lc(r.document),h=l.get("uid"),t(h)&&("undefined"!=h&&""!=h)&&l.get("uid")}W(new Td,N("searchPane"));b=new ce;b.anchor=N("viewFavoriteButton");c=N("searchRecommend");xb(c)&&b.Fa.push(c);c=N("viewRecordPane");xb(c)&&b.Fa.push(c);W(b,N("viewFavoritePanel"));b=new Nd;c=Jd.qa();b.ja=c;b.yb(N("viewRecordButton"));b.za(N("searchRecommend"));b.za(N("viewFavoritePanel"));
W(b,N("viewRecordPane"));b=P("play-nave-guide");var w=P("play-nave-list");xb(b)&&xb(w)&&(c=new Md,c.yb(b),c.h=w,c.fb="play-nave-guide-on",c.za(N("searchRecommend")),c.o());b=P("hd-load-text");c=P("hd-load-con");xb(b)&&xb(c)&&(new Od({anchor:b,content:c,expandAnchorClass:"hd-load-text-on"})).o();$.V();if(a&&42<a){var s=P("play-page"),A=N("viewRecordPane"),L=N("searchRecommend");U(r,"scroll",function(){var a=r.document.documentElement.scrollTop||r.document.body.scrollTop;42<a&&650>a?(xb(w)&&Q(w,p),
Q(A,p),Q(L,p),Q(s,p)):Q(s,k)},p,this)}}ba("baofeng.header.init",de);ba("hd.ListPage",function(){de();for(var a=nb("fold"),b=0,c=a.length;b<c;b++){var d=a[b];U(d,"mouseover",function(){K(this,"unfold")},p,d);U(d,"mouseout",function(){M(this,"unfold")},p,d)}(new Tc).start()});})();
