(function(){var f=void 0,j=!0,l=null,p=!1,q,r=this;
function aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function s(a){return a!==f}function ba(a){var b=aa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function t(a){return"string"==typeof a}function ca(a){var b=typeof a;return"object"==b&&a!=l||"function"==b}var v="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ga(a,b,c){ga=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return ga.apply(l,arguments)}var ha=Date.now||function(){return+new Date};
function ia(a,b){function c(){}c.prototype=b.prototype;a.ma=b.prototype;a.prototype=new c};function ja(a,b){var c=String(a).toLowerCase(),d=String(b).toLowerCase();return c<d?-1:c==d?0:1}function w(a){a=s(f)?a.toFixed(f):String(a);var b=a.indexOf(".");-1==b&&(b=a.length);b=Math.max(0,2-b);return Array(b+1).join("0")+a};var x,ka,la,ma,na;function oa(){return r.navigator?r.navigator.userAgent:l}na=ma=la=ka=x=p;var y;if(y=oa()){var pa=r.navigator;x=0==y.indexOf("Opera");ka=!x&&-1!=y.indexOf("MSIE");ma=(la=!x&&-1!=y.indexOf("WebKit"))&&-1!=y.indexOf("Mobile");na=!x&&!la&&"Gecko"==pa.product}var qa=x,z=ka,C=na,D=la,ra=ma,sa=r.navigator,ta=-1!=(sa&&sa.platform||"").indexOf("Mac");function ua(){var a=r.document;return a?a.documentMode:f}var E;
a:{var va="",F;if(qa&&r.opera)var wa=r.opera.version,va="function"==typeof wa?wa():wa;else if(C?F=/rv\:([^\);]+)(\)|;)/:z?F=/MSIE\s+([^\);]+)(\)|;)/:D&&(F=/WebKit\/(\S+)/),F)var xa=F.exec(oa()),va=xa?xa[1]:"";if(z){var ya=ua();if(ya>parseFloat(va)){E=String(ya);break a}}E=va}var za={};
function G(a){var b;if(!(b=za[a])){b=0;for(var c=String(E).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),g=0;0==b&&g<e;g++){var h=c[g]||"",n=d[g]||"",k=RegExp("(\\d*)(\\D*)","g"),A=RegExp("(\\d*)(\\D*)","g");do{var m=k.exec(h)||["","",""],u=A.exec(n)||["","",""];if(0==m[0].length&&0==u[0].length)break;b=((0==m[1].length?0:parseInt(m[1],10))<(0==u[1].length?0:parseInt(u[1],10))?-1:(0==m[1].length?0:parseInt(m[1],
10))>(0==u[1].length?0:parseInt(u[1],10))?1:0)||((0==m[2].length)<(0==u[2].length)?-1:(0==m[2].length)>(0==u[2].length)?1:0)||(m[2]<u[2]?-1:m[2]>u[2]?1:0)}while(0==b)}b=za[a]=0<=b}return b}var Aa=r.document,Ba=!Aa||!z?f:ua()||("CSS1Compat"==Aa.compatMode?parseInt(E,10):5);var Ca=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Da(a,b){for(var c in a)b.call(f,a[c],c,a)}function Ea(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Fa(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var H=Array.prototype,Ga=H.indexOf?function(a,b,c){return H.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(t(a))return!t(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ha=H.forEach?function(a,b,c){H.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};function Ia(a){return H.concat.apply(H,arguments)}
function Ja(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Ka(a){if("function"==typeof a.h)return a.h();if(t(a))return a.split("");if(ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ea(a)};function La(a,b){this.i={};this.e=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof La?(c=a.m(),d=a.h()):(c=Fa(a),d=Ea(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}}q=La.prototype;q.b=0;q.S=0;q.h=function(){Ma(this);for(var a=[],b=0;b<this.e.length;b++)a.push(this.i[this.e[b]]);return a};q.m=function(){Ma(this);return this.e.concat()};q.l=function(a){return I(this.i,a)};
q.remove=function(a){return I(this.i,a)?(delete this.i[a],this.b--,this.S++,this.e.length>2*this.b&&Ma(this),j):p};function Ma(a){if(a.b!=a.e.length){for(var b=0,c=0;b<a.e.length;){var d=a.e[b];I(a.i,d)&&(a.e[c++]=d);b++}a.e.length=c}if(a.b!=a.e.length){for(var e={},c=b=0;b<a.e.length;)d=a.e[b],I(e,d)||(a.e[c++]=d,e[d]=1),b++;a.e.length=c}}q.get=function(a,b){return I(this.i,a)?this.i[a]:b};q.set=function(a,b){I(this.i,a)||(this.b++,this.e.push(a),this.S++);this.i[a]=b};q.p=function(){return new La(this)};
function I(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function J(a,b){var c;if(a instanceof J)this.g=s(b)?b:a.g,Na(this,a.s),c=a.D,K(this),this.D=c,c=a.q,K(this),this.q=c,Oa(this,a.B),c=a.r,K(this),this.r=c,Pa(this,a.j.p()),c=a.w,K(this),this.w=c;else if(a&&(c=String(a).match(Ca))){this.g=!!b;Na(this,c[1]||"",j);var d=c[2]||"";K(this);this.D=L(d);d=c[3]||"";K(this);this.q=L(d);Oa(this,c[4]);d=c[5]||"";K(this);this.r=L(d);Pa(this,c[6]||"",j);c=c[7]||"";K(this);this.w=L(c)}else this.g=!!b,this.j=new M(l,0,this.g)}q=J.prototype;q.s="";q.D="";q.q="";
q.B=l;q.r="";q.w="";q.da=p;q.g=p;q.toString=function(){var a=[],b=this.s;b&&a.push(N(b,Qa),":");if(b=this.q){a.push("//");var c=this.D;c&&a.push(N(c,Qa),"@");a.push(encodeURIComponent(String(b)));b=this.B;b!=l&&a.push(":",String(b))}if(b=this.r)this.q&&"/"!=b.charAt(0)&&a.push("/"),a.push(N(b,"/"==b.charAt(0)?Ra:Sa));(b=this.j.toString())&&a.push("?",b);(b=this.w)&&a.push("#",N(b,Ta));return a.join("")};q.p=function(){return new J(this)};
function Na(a,b,c){K(a);a.s=c?L(b):b;a.s&&(a.s=a.s.replace(/:$/,""))}function Oa(a,b){K(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.B=b}else a.B=l}function Pa(a,b,c){K(a);b instanceof M?(a.j=b,a.j.I(a.g)):(c||(b=N(b,Ua)),a.j=new M(b,0,a.g))}function K(a){if(a.da)throw Error("Tried to modify a read-only Uri");}q.I=function(a){this.g=a;this.j&&this.j.I(a);return this};function L(a){return a?decodeURIComponent(a):""}
function N(a,b){return t(a)?encodeURI(a).replace(b,Va):l}function Va(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Qa=/[#\/\?@]/g,Sa=/[\#\?:]/g,Ra=/[\#\?]/g,Ua=/[\#\?@]/g,Ta=/#/g;function M(a,b,c){this.f=a||l;this.g=!!c}
function O(a){if(!a.c&&(a.c=new La,a.b=0,a.f))for(var b=a.f.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=l,g=l;0<=d?(e=b[c].substring(0,d),g=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=P(a,e);a.add(e,g?decodeURIComponent(g.replace(/\+/g," ")):"")}}q=M.prototype;q.c=l;q.b=l;q.add=function(a,b){O(this);this.f=l;a=P(this,a);var c=this.c.get(a);c||this.c.set(a,c=[]);c.push(b);this.b++;return this};
q.remove=function(a){O(this);a=P(this,a);return this.c.l(a)?(this.f=l,this.b-=this.c.get(a).length,this.c.remove(a)):p};q.l=function(a){O(this);a=P(this,a);return this.c.l(a)};q.m=function(){O(this);for(var a=this.c.h(),b=this.c.m(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};q.h=function(a){O(this);var b=[];if(a)this.l(a)&&(b=Ia(b,this.c.get(P(this,a))));else{a=this.c.h();for(var c=0;c<a.length;c++)b=Ia(b,a[c])}return b};
q.set=function(a,b){O(this);this.f=l;a=P(this,a);this.l(a)&&(this.b-=this.c.get(a).length);this.c.set(a,[b]);this.b++;return this};q.get=function(a,b){var c=a?this.h(a):[];return 0<c.length?String(c[0]):b};q.toString=function(){if(this.f)return this.f;if(!this.c)return"";for(var a=[],b=this.c.m(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.h(d),g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="="+encodeURIComponent(String(d[g])));a.push(h)}return this.f=a.join("&")};
q.p=function(){var a=new M;a.f=this.f;this.c&&(a.c=this.c.p(),a.b=this.b);return a};function P(a,b){var c=String(b);a.g&&(c=c.toLowerCase());return c}
q.I=function(a){if(a&&!this.g){O(this);this.f=l;var b=this.c,c=function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),this.remove(c),0<a.length&&(this.f=l,this.c.set(P(this,c),Ja(a)),this.b+=a.length))};if("function"==typeof b.forEach)b.forEach(c,this);else if(ba(b)||t(b))Ha(b,c,this);else{var d;if("function"==typeof b.m)d=b.m();else if("function"!=typeof b.h)if(ba(b)||t(b)){d=[];for(var e=b.length,g=0;g<e;g++)d.push(g)}else d=Fa(b);else d=f;b=Ka(b);e=b.length;for(g=0;g<e;g++)c.call(this,b[g],
d&&d[g])}}this.g=a};function Q(a,b){this.type=a;this.currentTarget=this.target=b}Q.prototype.H=p;Q.prototype.defaultPrevented=p;Q.prototype.ja=j;Q.prototype.preventDefault=function(){this.defaultPrevented=j;this.ja=p};var Wa=0;function Xa(){}q=Xa.prototype;q.key=0;q.o=p;q.t=p;q.z=function(a,b,c,d,e,g){if("function"==aa(a))this.O=j;else if(a&&a.handleEvent&&"function"==aa(a.handleEvent))this.O=p;else throw Error("Invalid listener argument");this.n=a;this.Q=b;this.src=c;this.type=d;this.capture=!!e;this.M=g;this.t=p;this.key=++Wa;this.o=p};q.handleEvent=function(a){return this.O?this.n.call(this.M||this.src,a):this.n.handleEvent.call(this.n,a)};var Ya=!z||z&&9<=Ba,Za=z&&!G("9");!D||G("528");C&&G("1.9b")||z&&G("8")||qa&&G("9.5")||D&&G("528");C&&!G("8")||z&&G("9");function $a(a){$a[" "](a);return a}$a[" "]=function(){};function R(a,b){a&&this.z(a,b)}ia(R,Q);q=R.prototype;q.target=l;q.relatedTarget=l;q.offsetX=0;q.offsetY=0;q.clientX=0;q.clientY=0;q.screenX=0;q.screenY=0;q.button=0;q.keyCode=0;q.charCode=0;q.ctrlKey=p;q.altKey=p;q.shiftKey=p;q.metaKey=p;q.ha=p;q.K=l;
q.z=function(a,b){var c=this.type=a.type;Q.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(C){var e;a:{try{$a(d.nodeName);e=j;break a}catch(g){}e=p}e||(d=l)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=D||a.offsetX!==f?a.offsetX:a.layerX;this.offsetY=D||a.offsetY!==f?a.offsetY:a.layerY;this.clientX=a.clientX!==f?a.clientX:a.pageX;this.clientY=a.clientY!==f?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.ha=ta?a.metaKey:a.ctrlKey;this.state=a.state;this.K=a;a.defaultPrevented&&this.preventDefault();delete this.H};
q.preventDefault=function(){R.ma.preventDefault.call(this);var a=this.K;if(a.preventDefault)a.preventDefault();else if(a.returnValue=p,Za)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var ab={},S={},T={},U={};
function bb(a,b,c,d,e){if("array"==aa(b))for(var g=0;g<b.length;g++)bb(a,b[g],c,d,e);else{a:{if(!b)throw Error("Invalid event type");d=!!d;var h=S;b in h||(h[b]={b:0,k:0});h=h[b];d in h||(h[d]={b:0,k:0},h.b++);var h=h[d],g=a[v]||(a[v]=++da),n;h.k++;if(h[g]){n=h[g];for(var k=0;k<n.length;k++)if(h=n[k],h.n==c&&h.M==e){if(h.o)break;n[k].t=p;a=n[k];break a}}else n=h[g]=[],h.b++;var A=cb,m=Ya?function(a){return A.call(m.src,m.n,a)}:function(a){a=A.call(m.src,m.n,a);if(!a)return a},k=m,h=new Xa;h.z(c,k,
a,b,d,e);h.t=p;k.src=a;k.n=h;n.push(h);T[g]||(T[g]=[]);T[g].push(h);a.addEventListener?(a==r||!a.$)&&a.addEventListener(b,k,d):a.attachEvent(b in U?U[b]:U[b]="on"+b,k);a=h}ab[a.key]=a}}function db(a,b,c,d){if(!d.A&&d.P){for(var e=0,g=0;e<d.length;e++)d[e].o?d[e].Q.src=l:(e!=g&&(d[g]=d[e]),g++);d.length=g;d.P=p;0==g&&(delete S[a][b][c],S[a][b].b--,0==S[a][b].b&&(delete S[a][b],S[a].b--),0==S[a].b&&delete S[a])}}
function eb(a,b,c,d,e){var g=1;b=b[v]||(b[v]=++da);if(a[b]){var h=--a.k,n=a[b];n.A?n.A++:n.A=1;try{for(var k=n.length,A=0;A<k;A++){var m=n[A];m&&!m.o&&(g&=fb(m,e)!==p)}}finally{a.k=Math.max(h,a.k),n.A--,db(c,d,b,n)}}return Boolean(g)}
function fb(a,b){if(a.t){var c=a.key,d=ab[c];if(d&&!d.o){var e=d.src,g=d.type,h=d.Q,n=d.capture;e.removeEventListener?(e==r||!e.$)&&e.removeEventListener(g,h,n):e.detachEvent&&e.detachEvent(g in U?U[g]:U[g]="on"+g,h);e=e[v]||(e[v]=++da);if(T[e]){var h=T[e],k=Ga(h,d);0<=k&&H.splice.call(h,k,1);0==h.length&&delete T[e]}d.o=j;if(d=S[g][n][e])d.P=j,db(g,n,e,d);delete ab[c]}}return a.handleEvent(b)}
function cb(a,b){if(a.o)return j;var c=a.type,d=S;if(!(c in d))return j;var d=d[c],e,g;if(!Ya){var h;if(!(h=b))a:{h=["window","event"];for(var n=r;e=h.shift();)if(n[e]!=l)n=n[e];else{h=l;break a}h=n}e=h;h=j in d;n=p in d;if(h){if(0>e.keyCode||e.returnValue!=f)return j;a:{var k=p;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(A){k=j}if(k||e.returnValue==f)e.returnValue=j}}k=new R;k.z(e,this);e=j;try{if(h){for(var m=[],u=k.currentTarget;u;u=u.parentNode)m.push(u);g=d[j];g.k=g.b;for(var B=m.length-1;!k.H&&
0<=B&&g.k;B--)k.currentTarget=m[B],e&=eb(g,m[B],c,j,k);if(n){g=d[p];g.k=g.b;for(B=0;!k.H&&B<m.length&&g.k;B++)k.currentTarget=m[B],e&=eb(g,m[B],c,p,k)}}else e=fb(a,k)}finally{m&&(m.length=0)}return e}c=new R(b,this);return e=fb(a,c)};var gb={ta:["BC","AD"],sa:["Before Christ","Anno Domini"],va:"JFMAMJJASOND".split(""),Ca:"JFMAMJJASOND".split(""),ua:"January February March April May June July August September October November December".split(" "),Ba:"January February March April May June July August September October November December".split(" "),ya:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),Ea:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),Ia:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
Ga:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Aa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),Fa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),wa:"SMTWTFS".split(""),Da:"SMTWTFS".split(""),za:["Q1","Q2","Q3","Q4"],xa:["1st quarter","2nd quarter","3rd quarter","4th quarter"],qa:["AM","PM"],ra:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],Ha:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],T:6,Ja:[5,6],U:5};function V(a,b,c){"number"==typeof a?(this.a=new Date(a,b||0,c||1),hb(this,c||1)):ca(a)?(this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate()),hb(this,a.getDate())):(this.a=new Date(ha()),this.a.setHours(0),this.a.setMinutes(0),this.a.setSeconds(0),this.a.setMilliseconds(0))}q=V.prototype;q.u=gb.T;q.v=gb.U;q.p=function(){var a=new V(this.a);a.u=this.u;a.v=this.v;return a};q.getFullYear=function(){return this.a.getFullYear()};q.getYear=function(){return this.getFullYear()};q.getMonth=function(){return this.a.getMonth()};
q.getDate=function(){return this.a.getDate()};q.getTime=function(){return this.a.getTime()};q.getUTCHours=function(){return this.a.getUTCHours()};q.getTimezoneOffset=function(){return this.a.getTimezoneOffset()};function ib(a){a=a.getTimezoneOffset();if(0==a)a="Z";else{var b=Math.abs(a)/60,c=Math.floor(b),b=60*(b-c);a=(0<a?"-":"+")+w(c)+":"+w(b)}return a}q.set=function(a){this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate())};q.setFullYear=function(a){this.a.setFullYear(a)};q.setMonth=function(a){this.a.setMonth(a)};
q.setDate=function(a){this.a.setDate(a)};
q.add=function(a){if(a.pa||a.fa){var b=this.getMonth()+a.fa+12*a.pa,c=this.getYear()+Math.floor(b/12),b=b%12;0>b&&(b+=12);var d;a:{switch(b){case 1:d=0==c%4&&(0!=c%100||0==c%400)?29:28;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.aa&&(a=new Date((new Date(this.getYear(),this.getMonth(),this.getDate(),12)).getTime()+864E5*a.aa),this.setDate(1),this.setFullYear(a.getFullYear()),this.setMonth(a.getMonth()),
this.setDate(a.getDate()),hb(this,a.getDate()))};q.C=function(a,b){return[this.getFullYear(),w(this.getMonth()+1),w(this.getDate())].join(a?"-":"")+(b?ib(this):"")};q.toString=function(){return this.C()};function hb(a,b){a.getDate()!=b&&a.a.setUTCHours(a.a.getUTCHours()+(a.getDate()<b?1:-1))}q.valueOf=function(){return this.a.valueOf()};function W(a,b,c,d,e,g,h){this.a="number"==typeof a?new Date(a,b||0,c||1,d||0,e||0,g||0,h||0):new Date(a?a.getTime():ha())}ia(W,V);q=W.prototype;q.getHours=function(){return this.a.getHours()};
q.getMinutes=function(){return this.a.getMinutes()};q.getSeconds=function(){return this.a.getSeconds()};q.getUTCHours=function(){return this.a.getUTCHours()};q.setHours=function(a){this.a.setHours(a)};q.setMinutes=function(a){this.a.setMinutes(a)};q.setSeconds=function(a){this.a.setSeconds(a)};q.setMilliseconds=function(a){this.a.setMilliseconds(a)};q.setUTCHours=function(a){this.a.setUTCHours(a)};
q.add=function(a){V.prototype.add.call(this,a);a.ca&&this.setHours(this.a.getHours()+a.ca);a.ea&&this.setMinutes(this.a.getMinutes()+a.ea);a.ka&&this.setSeconds(this.a.getSeconds()+a.ka)};q.C=function(a,b){var c=V.prototype.C.call(this,a);return a?c+" "+w(this.getHours())+":"+w(this.getMinutes())+":"+w(this.getSeconds())+(b?ib(this):""):c+"T"+w(this.getHours())+w(this.getMinutes())+w(this.getSeconds())+(b?ib(this):"")};q.toString=function(){return this.C()};
q.p=function(){var a=new W(this.a);a.u=this.u;a.v=this.v;return a};function jb(a){this.F=a}var kb=/\s*;\s*/;q=jb.prototype;q.set=function(a,b,c,d,e,g){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');s(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";g=g?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(ha()+1E3*c)).toUTCString();this.F.cookie=a+"="+b+e+d+c+g};
q.get=function(a,b){for(var c=a+"=",d=(this.F.cookie||"").split(kb),e=0,g;g=d[e];e++){if(0==g.lastIndexOf(c,0))return g.substr(c.length);if(g==a)return""}return b};q.remove=function(a,b,c){var d=this.l(a);this.set(a,"",0,b,c);return d};q.m=function(){return lb(this).keys};q.h=function(){return lb(this).na};q.l=function(a){return s(this.get(a))};
function lb(a){a=(a.F.cookie||"").split(kb);for(var b=[],c=[],d,e,g=0;e=a[g];g++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,na:c}};!C&&!z||z&&z&&9<=Ba||C&&G("1.9.1");var mb=z&&!G("9"),nb=z||qa||D;function ob(a){if(nb)return a.parentElement;a=a.parentNode;return ca(a)&&1==a.nodeType?a:l}var pb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},qb={IMG:" ",BR:"\n"};function rb(a,b,c){if(!(a.nodeName in pb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in qb)b.push(qb[a.nodeName]);else for(a=a.firstChild;a;)rb(a,b,c),a=a.nextSibling};function X(){this.uri=new J(r.location.href);this.cookie=new jb(r.document);this.ia=new J("http://pvlog.hd.baofeng.com/logger.php");this.J=new J("http://clicklog.hd.baofeng.com/logger.php");this.ba=new J("http://eventlog.hd.baofeng.com/logger.php");this.G="bf_leave_log";var a=this.cookie.get(this.G,"");0<a.length&&(this.log(a),this.cookie.set(this.G,"",10,"/"));a=r.uid;t(a)===p&&(a="");this.uid=a;a=r.pid;t(a)===p&&(a="hdbf");this.ga=a;this.Y=this.uri.q;a=this.cookie.get("cid","");0>=a.length&&(a=
(new W).getTime(),this.cookie.set("cid",a,63072E4,"/"));this.Z=a;this.V=this.cookie.get("bali","");this.X=0<this.uri.j.toString().length?this.uri.r+"?"+L(this.uri.j.toString()):this.uri.r;this.la=this.cookie.get("sid","");this.d=new M;Da({ltype:"bfpv",uid:this.uid,pid:this.ga,chid:this.Y,cid:this.Z,bid:this.V,channel:this.X,msg:""},ga(function(a,c){this.d.add(c,a)},this));this.R("firsttime");bb(r,"unload",ga(this.R,this,"lasttime"),p);bb(r,"load",this.oa,p,this)}
X.L=function(){return X.N?X.N:X.N=new X};q=X.prototype;q.R=function(a){var b=r.document.referrer,b={browsertype:ra?"2":"1",browser:z?"IE"+E.substring(0,E.indexOf(".")):C?"GECKO":D?"WEBKIT":qa?"OPERA":D?"SAFARI":"OTHER",sid:this.la,refer:"string"===typeof b?b:""};b[a]=this.getTime();this.d.set("ltype","bfpv");this.d.set("msg",sb(b));this.d.set("t",(new W).getTime());this.log(this.ia.toString()+"?"+L(this.d.toString()))};
function sb(a){var b=[];Da(a,function(a,d){b.push('"'+d+'":"'+a+'"')});return"{"+b.join(",")+"}"}q.getTime=function(){var a=new W;return a.getHours()+":"+a.getMinutes()+":"+a.getSeconds()};q.oa=function(){bb(r.document.body,"click",this.W,p,this)};
q.W=function(a){for(a=a.target;a!==r.document.body&&a!==l;){if("A"===a.nodeName){var b=a;a:{for(a=b;a!==r.document.body&&a!==l;){var c=a.getAttribute("areacode");if(t(c)){a=c;break a}a=ob(a)}a=""}for(var c=b,d=0,e=c;e!==r.document.body&&e!==l;){var g=e.getAttribute("areacode");if(t(g)){e!==c&&(d=f,d=document,e=e||d,e=e.querySelectorAll&&e.querySelector?e.querySelectorAll("A"):d=e.getElementsByTagName("A"),e=Ja(e),d=Ga(e,c));break}e=ob(e)}c=d;a:{e=b;d="";d=e.getAttribute("title");if(!t(d)){if("INPUT"===
e.nodeName&&(d=e.getAttribute("value"),t(d))){e=d;break a}d=f;mb&&"innerText"in e?d=e.innerText.replace(/(\r\n|\r|\n)/g,"\n"):(d=[],rb(e,d,j),d=d.join(""));d=d.replace(/ \xAD /g," ").replace(/\xAD/g,"");d=d.replace(/\u200B/g,"");mb||(d=d.replace(/ +/g," "));" "!=d&&(d=d.replace(/^\s*/,""))}e=d}d="click";if("A"===b.nodeName&&(g=b.getAttribute("href"),t(g))){var h=RegExp(" ".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),g=g.replace(h,"");0==ja("javascript:void(0)",g.substr(0,
18))===p&&0==ja("#",g.substr(0,1))===p&&(b=b.getAttribute("target"),d=t(b)&&("_blank"===b||"blank"===b)?"gotoblank":"gotoself")}b=d;0<a.length&&0<=c&&(a={areacode:a,areaid:c,title:e,type:b},"gotoself"===b?(this.d.set("msg",sb(a)),this.d.set("ltype","bfclick"),this.d.set("t",(new W).getTime()),this.cookie.set(this.G,this.J.toString()+"?"+L(this.d.toString()),60,"/")):this.click(a));break}a=ob(a)}};q.log=function(a){(new Image).src=a};
q.click=function(a){this.d.set("msg",sb(a));this.d.set("ltype","bfclick");this.d.set("t",(new W).getTime());this.log(this.J.toString()+"?"+L(this.d.toString()))};q.event=function(a){this.d.set("msg",sb(a));this.d.set("ltype","bfevent");this.d.set("t",(new W).getTime());this.log(this.ba.toString()+"?"+L(this.d.toString()))};function tb(a){X.L().event(a)}var Y=["baofeng","eventLog"],Z=r;!(Y[0]in Z)&&Z.execScript&&Z.execScript("var "+Y[0]);
for(var $;Y.length&&($=Y.shift());)!Y.length&&s(tb)?Z[$]=tb:Z=Z[$]?Z[$]:Z[$]={};X.L();})();
