(function(){var g=void 0,j=!0,k=null,p=!1,q,r=this;function aa(a,b){var c=a.split("."),d=r;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&s(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}
function t(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function s(a){return a!==g}function ba(a){var b=t(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"string"==typeof a}function ca(a){var b=typeof a;return"object"==b&&a!=k||"function"==b}var w="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function x(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return x.apply(k,arguments)}var y=Date.now||function(){return+new Date};
function ga(a,b){function c(){}c.prototype=b.prototype;a.sa=b.prototype;a.prototype=new c};function ha(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")}function z(a){a=s(g)?a.toFixed(g):String(a);var b=a.indexOf(".");-1==b&&(b=a.length);b=Math.max(0,2-b);return Array(b+1).join("0")+a};var A,ia,ja,ka,la;function ma(){return r.navigator?r.navigator.userAgent:k}la=ka=ja=ia=A=p;var D;if(D=ma()){var na=r.navigator;A=0==D.indexOf("Opera");ia=!A&&-1!=D.indexOf("MSIE");ka=(ja=!A&&-1!=D.indexOf("WebKit"))&&-1!=D.indexOf("Mobile");la=!A&&!ja&&"Gecko"==na.product}var oa=A,E=ia,F=la,G=ja,pa=ka,qa=r.navigator,ra=-1!=(qa&&qa.platform||"").indexOf("Mac");function sa(){var a=r.document;return a?a.documentMode:g}var H;
a:{var ta="",I;if(oa&&r.opera)var ua=r.opera.version,ta="function"==typeof ua?ua():ua;else if(F?I=/rv\:([^\);]+)(\)|;)/:E?I=/MSIE\s+([^\);]+)(\)|;)/:G&&(I=/WebKit\/(\S+)/),I)var va=I.exec(ma()),ta=va?va[1]:"";if(E){var wa=sa();if(wa>parseFloat(ta)){H=String(wa);break a}}H=ta}var xa={};
function J(a){var b;if(!(b=xa[a])){b=0;for(var c=String(H).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",n=d[f]||"",l=RegExp("(\\d*)(\\D*)","g"),B=RegExp("(\\d*)(\\D*)","g");do{var m=l.exec(h)||["","",""],u=B.exec(n)||["","",""];if(0==m[0].length&&0==u[0].length)break;b=((0==m[1].length?0:parseInt(m[1],10))<(0==u[1].length?0:parseInt(u[1],10))?-1:(0==m[1].length?0:parseInt(m[1],
10))>(0==u[1].length?0:parseInt(u[1],10))?1:0)||((0==m[2].length)<(0==u[2].length)?-1:(0==m[2].length)>(0==u[2].length)?1:0)||(m[2]<u[2]?-1:m[2]>u[2]?1:0)}while(0==b)}b=xa[a]=0<=b}return b}var ya=r.document,za=!ya||!E?g:sa()||("CSS1Compat"==ya.compatMode?parseInt(H,10):5);var Aa=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Ba(a,b){for(var c in a)b.call(g,a[c],c,a)}function Ca(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Da(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var K=Array.prototype,Ea=K.indexOf?function(a,b,c){return K.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:0>c?Math.max(0,a.length+c):c;if(v(a))return!v(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Fa=K.forEach?function(a,b,c){K.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};function Ga(a){return K.concat.apply(K,arguments)}
function Ha(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Ia(a){if("function"==typeof a.i)return a.i();if(v(a))return a.split("");if(ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ca(a)};function Ja(a,b){this.j={};this.e=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Ja?(c=a.n(),d=a.i()):(c=Da(a),d=Ca(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}}q=Ja.prototype;q.b=0;q.ba=0;q.i=function(){Ka(this);for(var a=[],b=0;b<this.e.length;b++)a.push(this.j[this.e[b]]);return a};q.n=function(){Ka(this);return this.e.concat()};q.l=function(a){return L(this.j,a)};
q.remove=function(a){return L(this.j,a)?(delete this.j[a],this.b--,this.ba++,this.e.length>2*this.b&&Ka(this),j):p};function Ka(a){if(a.b!=a.e.length){for(var b=0,c=0;b<a.e.length;){var d=a.e[b];L(a.j,d)&&(a.e[c++]=d);b++}a.e.length=c}if(a.b!=a.e.length){for(var e={},c=b=0;b<a.e.length;)d=a.e[b],L(e,d)||(a.e[c++]=d,e[d]=1),b++;a.e.length=c}}q.get=function(a,b){return L(this.j,a)?this.j[a]:b};q.set=function(a,b){L(this.j,a)||(this.b++,this.e.push(a),this.ba++);this.j[a]=b};q.q=function(){return new Ja(this)};
function L(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function M(a,b){var c;if(a instanceof M)this.g=s(b)?b:a.g,La(this,a.s),c=a.F,N(this),this.F=c,c=a.m,N(this),this.m=c,Ma(this,a.B),c=a.r,N(this),this.r=c,O(this,a.h.q()),c=a.w,N(this),this.w=c;else if(a&&(c=String(a).match(Aa))){this.g=!!b;La(this,c[1]||"",j);var d=c[2]||"";N(this);this.F=d?decodeURIComponent(d):"";d=c[3]||"";N(this);this.m=d?decodeURIComponent(d):"";Ma(this,c[4]);d=c[5]||"";N(this);this.r=d?decodeURIComponent(d):"";O(this,c[6]||"",j);c=c[7]||"";N(this);this.w=c?decodeURIComponent(c):
""}else this.g=!!b,this.h=new P(k,0,this.g)}q=M.prototype;q.s="";q.F="";q.m="";q.B=k;q.r="";q.w="";q.la=p;q.g=p;q.toString=function(){var a=[],b=this.s;b&&a.push(Q(b,Na),":");if(b=this.m){a.push("//");var c=this.F;c&&a.push(Q(c,Na),"@");a.push(encodeURIComponent(String(b)));b=this.B;b!=k&&a.push(":",String(b))}if(b=this.r)this.m&&"/"!=b.charAt(0)&&a.push("/"),a.push(Q(b,"/"==b.charAt(0)?Oa:Pa));(b=this.h.toString())&&a.push("?",b);(b=this.w)&&a.push("#",Q(b,Qa));return a.join("")};q.q=function(){return new M(this)};
function La(a,b,c){N(a);a.s=c?b?decodeURIComponent(b):"":b;a.s&&(a.s=a.s.replace(/:$/,""))}function Ma(a,b){N(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.B=b}else a.B=k}function O(a,b,c){N(a);b instanceof P?(a.h=b,a.h.N(a.g)):(c||(b=Q(b,Ra)),a.h=new P(b,0,a.g))}function N(a){if(a.la)throw Error("Tried to modify a read-only Uri");}q.N=function(a){this.g=a;this.h&&this.h.N(a);return this};function Q(a,b){return v(a)?encodeURI(a).replace(b,Sa):k}
function Sa(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Na=/[#\/\?@]/g,Pa=/[\#\?:]/g,Oa=/[\#\?]/g,Ra=/[\#\?@]/g,Qa=/#/g;function P(a,b,c){this.f=a||k;this.g=!!c}function R(a){if(!a.c&&(a.c=new Ja,a.b=0,a.f))for(var b=a.f.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=k,f=k;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=S(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}q=P.prototype;
q.c=k;q.b=k;q.add=function(a,b){R(this);this.f=k;a=S(this,a);var c=this.c.get(a);c||this.c.set(a,c=[]);c.push(b);this.b++;return this};q.remove=function(a){R(this);a=S(this,a);return this.c.l(a)?(this.f=k,this.b-=this.c.get(a).length,this.c.remove(a)):p};q.l=function(a){R(this);a=S(this,a);return this.c.l(a)};q.n=function(){R(this);for(var a=this.c.i(),b=this.c.n(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
q.i=function(a){R(this);var b=[];if(a)this.l(a)&&(b=Ga(b,this.c.get(S(this,a))));else{a=this.c.i();for(var c=0;c<a.length;c++)b=Ga(b,a[c])}return b};q.set=function(a,b){R(this);this.f=k;a=S(this,a);this.l(a)&&(this.b-=this.c.get(a).length);this.c.set(a,[b]);this.b++;return this};q.get=function(a,b){var c=a?this.i(a):[];return 0<c.length?String(c[0]):b};
q.toString=function(){if(this.f)return this.f;if(!this.c)return"";for(var a=[],b=this.c.n(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.i(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}return this.f=a.join("&")};q.q=function(){var a=new P;a.f=this.f;this.c&&(a.c=this.c.q(),a.b=this.b);return a};function S(a,b){var c=String(b);a.g&&(c=c.toLowerCase());return c}
q.N=function(a){if(a&&!this.g){R(this);this.f=k;var b=this.c,c=function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),this.remove(c),0<a.length&&(this.f=k,this.c.set(S(this,c),Ha(a)),this.b+=a.length))};if("function"==typeof b.forEach)b.forEach(c,this);else if(ba(b)||v(b))Fa(b,c,this);else{var d;if("function"==typeof b.n)d=b.n();else if("function"!=typeof b.i)if(ba(b)||v(b)){d=[];for(var e=b.length,f=0;f<e;f++)d.push(f)}else d=Da(b);else d=g;b=Ia(b);e=b.length;for(f=0;f<e;f++)c.call(this,b[f],
d&&d[f])}}this.g=a};function T(a,b){this.type=a;this.currentTarget=this.target=b}T.prototype.M=p;T.prototype.defaultPrevented=p;T.prototype.qa=j;T.prototype.preventDefault=function(){this.defaultPrevented=j;this.qa=p};var Ta=0;function Ua(){}q=Ua.prototype;q.key=0;q.p=p;q.t=p;q.z=function(a,b,c,d,e,f){if("function"==t(a))this.W=j;else if(a&&a.handleEvent&&"function"==t(a.handleEvent))this.W=p;else throw Error("Invalid listener argument");this.o=a;this.Y=b;this.src=c;this.type=d;this.capture=!!e;this.U=f;this.t=p;this.key=++Ta;this.p=p};q.handleEvent=function(a){return this.W?this.o.call(this.U||this.src,a):this.o.handleEvent.call(this.o,a)};var Va=!E||E&&9<=za,Wa=E&&!J("9");!G||J("528");F&&J("1.9b")||E&&J("8")||oa&&J("9.5")||G&&J("528");F&&!J("8")||E&&J("9");function Xa(a){Xa[" "](a);return a}Xa[" "]=function(){};function U(a,b){a&&this.z(a,b)}ga(U,T);q=U.prototype;q.target=k;q.relatedTarget=k;q.offsetX=0;q.offsetY=0;q.clientX=0;q.clientY=0;q.screenX=0;q.screenY=0;q.button=0;q.keyCode=0;q.charCode=0;q.ctrlKey=p;q.altKey=p;q.shiftKey=p;q.metaKey=p;q.pa=p;q.S=k;
q.z=function(a,b){var c=this.type=a.type;T.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(F){var e;a:{try{Xa(d.nodeName);e=j;break a}catch(f){}e=p}e||(d=k)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=G||a.offsetX!==g?a.offsetX:a.layerX;this.offsetY=G||a.offsetY!==g?a.offsetY:a.layerY;this.clientX=a.clientX!==g?a.clientX:a.pageX;this.clientY=a.clientY!==g?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pa=ra?a.metaKey:a.ctrlKey;this.state=a.state;this.S=a;a.defaultPrevented&&this.preventDefault();delete this.M};
q.preventDefault=function(){U.sa.preventDefault.call(this);var a=this.S;if(a.preventDefault)a.preventDefault();else if(a.returnValue=p,Wa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Ya={},V={},W={},X={};
function Za(a,b,c,d,e){if("array"==t(b))for(var f=0;f<b.length;f++)Za(a,b[f],c,d,e);else{a:{if(!b)throw Error("Invalid event type");d=!!d;var h=V;b in h||(h[b]={b:0,k:0});h=h[b];d in h||(h[d]={b:0,k:0},h.b++);var h=h[d],f=a[w]||(a[w]=++da),n;h.k++;if(h[f]){n=h[f];for(var l=0;l<n.length;l++)if(h=n[l],h.o==c&&h.U==e){if(h.p)break;n[l].t=p;a=n[l];break a}}else n=h[f]=[],h.b++;var B=$a,m=Va?function(a){return B.call(m.src,m.o,a)}:function(a){a=B.call(m.src,m.o,a);if(!a)return a},l=m,h=new Ua;h.z(c,l,
a,b,d,e);h.t=p;l.src=a;l.o=h;n.push(h);W[f]||(W[f]=[]);W[f].push(h);a.addEventListener?(a==r||!a.ia)&&a.addEventListener(b,l,d):a.attachEvent(b in X?X[b]:X[b]="on"+b,l);a=h}Ya[a.key]=a}}function ab(a,b,c,d){if(!d.A&&d.X){for(var e=0,f=0;e<d.length;e++)d[e].p?d[e].Y.src=k:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.X=p;0==f&&(delete V[a][b][c],V[a][b].b--,0==V[a][b].b&&(delete V[a][b],V[a].b--),0==V[a].b&&delete V[a])}}
function bb(a,b,c,d,e){var f=1;b=b[w]||(b[w]=++da);if(a[b]){var h=--a.k,n=a[b];n.A?n.A++:n.A=1;try{for(var l=n.length,B=0;B<l;B++){var m=n[B];m&&!m.p&&(f&=cb(m,e)!==p)}}finally{a.k=Math.max(h,a.k),n.A--,ab(c,d,b,n)}}return Boolean(f)}
function cb(a,b){if(a.t){var c=a.key,d=Ya[c];if(d&&!d.p){var e=d.src,f=d.type,h=d.Y,n=d.capture;e.removeEventListener?(e==r||!e.ia)&&e.removeEventListener(f,h,n):e.detachEvent&&e.detachEvent(f in X?X[f]:X[f]="on"+f,h);e=e[w]||(e[w]=++da);if(W[e]){var h=W[e],l=Ea(h,d);0<=l&&K.splice.call(h,l,1);0==h.length&&delete W[e]}d.p=j;if(d=V[f][n][e])d.X=j,ab(f,n,e,d);delete Ya[c]}}return a.handleEvent(b)}
function $a(a,b){if(a.p)return j;var c=a.type,d=V;if(!(c in d))return j;var d=d[c],e,f;if(!Va){var h;if(!(h=b))a:{h=["window","event"];for(var n=r;e=h.shift();)if(n[e]!=k)n=n[e];else{h=k;break a}h=n}e=h;h=j in d;n=p in d;if(h){if(0>e.keyCode||e.returnValue!=g)return j;a:{var l=p;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(B){l=j}if(l||e.returnValue==g)e.returnValue=j}}l=new U;l.z(e,this);e=j;try{if(h){for(var m=[],u=l.currentTarget;u;u=u.parentNode)m.push(u);f=d[j];f.k=f.b;for(var C=m.length-1;!l.M&&
0<=C&&f.k;C--)l.currentTarget=m[C],e&=bb(f,m[C],c,j,l);if(n){f=d[p];f.k=f.b;for(C=0;!l.M&&C<m.length&&f.k;C++)l.currentTarget=m[C],e&=bb(f,m[C],c,p,l)}}else e=cb(a,l)}finally{m&&(m.length=0)}return e}c=new U(b,this);return e=cb(a,c)};var db={Aa:["BC","AD"],za:["Before Christ","Anno Domini"],Ca:"JFMAMJJASOND".split(""),Ja:"JFMAMJJASOND".split(""),Ba:"January February March April May June July August September October November December".split(" "),Ia:"January February March April May June July August September October November December".split(" "),Fa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),La:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),Pa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
Na:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Ha:"Sun Mon Tue Wed Thu Fri Sat".split(" "),Ma:"Sun Mon Tue Wed Thu Fri Sat".split(" "),Da:"SMTWTFS".split(""),Ka:"SMTWTFS".split(""),Ga:["Q1","Q2","Q3","Q4"],Ea:["1st quarter","2nd quarter","3rd quarter","4th quarter"],xa:["AM","PM"],ya:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],Oa:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],da:6,Qa:[5,6],ea:5};function Y(a,b,c){"number"==typeof a?(this.a=new Date(a,b||0,c||1),eb(this,c||1)):ca(a)?(this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate()),eb(this,a.getDate())):(this.a=new Date(y()),this.a.setHours(0),this.a.setMinutes(0),this.a.setSeconds(0),this.a.setMilliseconds(0))}q=Y.prototype;q.u=db.da;q.v=db.ea;q.q=function(){var a=new Y(this.a);a.u=this.u;a.v=this.v;return a};q.getFullYear=function(){return this.a.getFullYear()};q.getYear=function(){return this.getFullYear()};q.getMonth=function(){return this.a.getMonth()};
q.getDate=function(){return this.a.getDate()};q.getTime=function(){return this.a.getTime()};q.getUTCHours=function(){return this.a.getUTCHours()};q.getTimezoneOffset=function(){return this.a.getTimezoneOffset()};function fb(a){a=a.getTimezoneOffset();if(0==a)a="Z";else{var b=Math.abs(a)/60,c=Math.floor(b),b=60*(b-c);a=(0<a?"-":"+")+z(c)+":"+z(b)}return a}q.set=function(a){this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate())};q.setFullYear=function(a){this.a.setFullYear(a)};q.setMonth=function(a){this.a.setMonth(a)};
q.setDate=function(a){this.a.setDate(a)};
q.add=function(a){if(a.va||a.na){var b=this.getMonth()+a.na+12*a.va,c=this.getYear()+Math.floor(b/12),b=b%12;0>b&&(b+=12);var d;a:{switch(b){case 1:d=0==c%4&&(0!=c%100||0==c%400)?29:28;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.ja&&(a=new Date((new Date(this.getYear(),this.getMonth(),this.getDate(),12)).getTime()+864E5*a.ja),this.setDate(1),this.setFullYear(a.getFullYear()),this.setMonth(a.getMonth()),
this.setDate(a.getDate()),eb(this,a.getDate()))};q.D=function(a,b){return[this.getFullYear(),z(this.getMonth()+1),z(this.getDate())].join(a?"-":"")+(b?fb(this):"")};q.toString=function(){return this.D()};function eb(a,b){a.getDate()!=b&&a.a.setUTCHours(a.a.getUTCHours()+(a.getDate()<b?1:-1))}q.valueOf=function(){return this.a.valueOf()};function Z(a,b,c,d,e,f,h){this.a="number"==typeof a?new Date(a,b||0,c||1,d||0,e||0,f||0,h||0):new Date(a?a.getTime():y())}ga(Z,Y);q=Z.prototype;q.getHours=function(){return this.a.getHours()};
q.getMinutes=function(){return this.a.getMinutes()};q.getSeconds=function(){return this.a.getSeconds()};q.getUTCHours=function(){return this.a.getUTCHours()};q.setHours=function(a){this.a.setHours(a)};q.setMinutes=function(a){this.a.setMinutes(a)};q.setSeconds=function(a){this.a.setSeconds(a)};q.setMilliseconds=function(a){this.a.setMilliseconds(a)};q.setUTCHours=function(a){this.a.setUTCHours(a)};
q.add=function(a){Y.prototype.add.call(this,a);a.ka&&this.setHours(this.a.getHours()+a.ka);a.ma&&this.setMinutes(this.a.getMinutes()+a.ma);a.ra&&this.setSeconds(this.a.getSeconds()+a.ra)};q.D=function(a,b){var c=Y.prototype.D.call(this,a);return a?c+" "+z(this.getHours())+":"+z(this.getMinutes())+":"+z(this.getSeconds())+(b?fb(this):""):c+"T"+z(this.getHours())+z(this.getMinutes())+z(this.getSeconds())+(b?fb(this):"")};q.toString=function(){return this.D()};
q.q=function(){var a=new Z(this.a);a.u=this.u;a.v=this.v;return a};function gb(a){var b=[];hb(new ib,a,b);return b.join("")}function ib(){this.C=g}
function hb(a,b,c){switch(typeof b){case "string":jb(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==k){c.push("null");break}if("array"==t(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],hb(a,a.C?a.C.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),jb(f,
c),c.push(":"),hb(a,a.C?a.C.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var kb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},lb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function jb(a,b){b.push('"',a.replace(lb,function(a){if(a in kb)return kb[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return kb[a]=e+b.toString(16)}),'"')};function mb(a){this.J=a}var nb=/\s*;\s*/;q=mb.prototype;q.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');s(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(y()+1E3*c)).toUTCString();this.J.cookie=a+"="+b+e+d+c+f};
q.get=function(a,b){for(var c=a+"=",d=(this.J.cookie||"").split(nb),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};q.remove=function(a,b,c){var d=this.l(a);this.set(a,"",0,b,c);return d};q.n=function(){return ob(this).keys};q.i=function(){return ob(this).ta};q.l=function(a){return s(this.get(a))};
function ob(a){a=(a.J.cookie||"").split(nb);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,ta:c}};!F&&!E||E&&E&&9<=za||F&&J("1.9.1");var pb=E&&!J("9"),qb=E||oa||G;function rb(a){if(qb)return a.parentElement;a=a.parentNode;return ca(a)&&1==a.nodeType?a:k}var sb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},tb={IMG:" ",BR:"\n"};function ub(a,b,c){if(!(a.nodeName in sb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in tb)b.push(tb[a.nodeName]);else for(a=a.firstChild;a;)ub(a,b,c),a=a.nextSibling};function $(){this.uri=new M(r.location.href);this.cookie=new mb(r.document);this.Z=new M("http://pvlog.hd.baofeng.com/logger.php");this.O=new M("http://58.83.217.230/v.gif");this.I=new M("http://clicklog.hd.baofeng.com/logger.php");this.G=new M("http://58.83.217.230/c.gif");this.R=new M("http://eventlog.hd.baofeng.com/logger.php");this.ca=new M("http://union.baofeng.com/flash_player");this.L="bf_leave_log";this.H="bf_check_leave_log";var a=this.cookie.get(this.L,"");0<a.length&&(this.log(a),this.cookie.set(this.L,
"",10,"/"));a=this.cookie.get(this.H,"");0<a.length&&(this.log(a),this.cookie.set(this.H,"",10,"/"));a=this.cookie.get("uid","");this.uid=36===a.length&&0<a.indexOf("-")||40===a.length?a:"";a=r.pid;v(a)===p&&(a="hdbf");this.oa=a;this.P=this.uri.m;a=this.cookie.get("cid","");if(0>=a.length||13===a.length)a=(new Z).getTime()+(Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^y()).toString(36)),this.cookie.set("cid",a,63072E4,"/");this.Q=a;this.fa=this.cookie.get("bali",
"");this.ha=0<this.uri.h.toString().length?this.uri.r+"?"+this.uri.h.toString():this.uri.r;a=this.cookie.get("sid","");0>=a.length&&(a=(new Z).getTime(),this.cookie.set("sid",a,-1,"/"));this.aa=a;var a=this.cookie.get("fid",""),b=this.uri.h;b&&(b=b.get("fid",""),0<b.length&&(a=b,this.cookie.set("fid",a,-1,"/")));if(0>=a.length){switch(this.uri.m){case "baofeng.com":a=1358;break;case "www.baofeng.com":a=1358;break;case "hd.baofeng.com":a=1191;break;case "a.hd.baofeng.com":a=1238;break;case "b.hd.baofeng.com":a=
1196;break;case "c.hd.baofeng.com":a=1308;break;case "d.hd.baofeng.com":a=1162;break;case "e.hd.baofeng.com":a=1310;break;case "f.hd.baofeng.com":a=1210;break;case "g.hd.baofeng.com":a=1317;break;case "share.hd.baofeng.com":a=1339;break;default:a=1191}this.cookie.set("fid",a,-1,"/")}this.T=a;a="";if(a=this.uri.h)a=a.get("zid",""),0<a.length&&this.cookie.set("zid",a,-1,"/");this.wa=this.cookie.get("zid","");this.d=new P;Ba({ltype:"bfpv",uid:this.uid,pid:this.oa,chid:this.P,cid:this.Q,bid:this.fa,fid:this.T,
channel:this.ha,msg:""},x(function(a,b){this.d.add(b,a)},this));O(this.Z,this.d);O(this.O,this.d);O(this.I,this.d);O(this.G,this.d);O(this.R,this.d);this.$("firsttime");Za(r,"unload",x(this.$,this,"lasttime"),p);Za(r,"load",this.ua,p,this)}$.K=function(){return $.V?$.V:$.V=new $};q=$.prototype;
q.$=function(a){var b={browsertype:pa?"2":"1",browser:vb(),sid:this.aa,refer:wb()};b[a]=this.getTime();this.d.set("ltype","bfpv");this.d.set("msg",gb(b));this.d.set("t",(new Z).getTime());this.log(this.Z.toString());this.log(this.O.toString())};function vb(){return E?"IE"+H.substring(0,H.indexOf(".")):F?"GECKO":G?"WEBKIT":oa?"OPERA":G?"SAFARI":"OTHER"}function wb(){var a=r.document.referrer;return v(a)&&0<a.length?a:""}q.getTime=function(){var a=new Z;return a.getHours()+":"+a.getMinutes()+":"+a.getSeconds()};
q.ua=function(){Za(r.document.body,"click",this.ga,p,this)};
q.ga=function(a){for(a=a.target;a!==r.document.body&&a!==k;){if("A"===a.nodeName){var b=a;a:{for(a=b;a!==r.document.body&&a!==k;){var c=a.getAttribute("areacode");if(v(c)&&0<c.length){a=c;break a}a=rb(a)}a=""}for(var c=b,d=0,e=c;e!==r.document.body&&e!==k;){var f=e.getAttribute("areacode");if(v(f)&&0<f.length){e!==c&&(d=g,d=document,e=e||d,e=e.querySelectorAll&&e.querySelector?e.querySelectorAll("A"):d=e.getElementsByTagName("A"),e=Ha(e),d=Ea(e,c));break}e=rb(e)}c=d;e=b;d="";d=e.getAttribute("title");
f=g;v(d)&&0<d.length?f=encodeURIComponent(d):(d=encodeURIComponent,f=g,pb&&"innerText"in e?f=e.innerText.replace(/(\r\n|\r|\n)/g,"\n"):(f=[],ub(e,f,j),f=f.join("")),f=f.replace(/ \xAD /g," ").replace(/\xAD/g,""),f=f.replace(/\u200B/g,""),pb||(f=f.replace(/ +/g," "))," "!=f&&(f=f.replace(/^\s*/,"")),f=d(f));e=f;d=b;b="click";if("A"===d.nodeName&&(f=d.getAttribute("href"),v(f)&&0<f.length)){var h=RegExp(ha(" "),"g"),f=f.replace(h,""),h=String(f.substr(0,18)).toLowerCase();if(0==("javascript:void(0)"<
h?-1:"javascript:void(0)"==h?0:1)===p)d=d.getAttribute("target"),v(d)&&("_blank"===d||"blank"===d)?b="gotoblank":0==f.lastIndexOf("#",0)===p&&(d=this.uri.toString(),-1!=d.indexOf("#")&&(d=d.substring(0,d.indexOf("#"))),d=RegExp(ha(d),""),f=f.replace(d,""),0==f.lastIndexOf("#",0)===p&&(b="gotoself"))}0<a.length&&0<=c&&(a={areacode:a,areaid:c,title:e,type:b},"gotoself"===b?(this.d.set("msg",gb(a)),this.d.set("ltype","bfclick"),this.d.set("t",(new Z).getTime()),this.cookie.set(this.L,this.I.toString(),
60,"/"),this.cookie.set(this.H,this.G.toString(),60,"/")):this.click(a));break}a=rb(a)}};q.log=function(a){(new Image).src=a};q.click=function(a){this.d.set("msg",gb(a));this.d.set("ltype","bfclick");this.d.set("t",(new Z).getTime());this.log(this.I.toString());this.log(this.G.toString())};q.event=function(a){a=a||{};a.browsertype=pa?"2":"1";a.browser=vb();a.sid=this.aa;a.refer=wb();this.d.set("msg",gb(a));this.d.set("ltype","bfevent");this.d.set("t",(new Z).getTime());this.log(this.R.toString())};
aa("baofeng.eventLog",function(a){$.K().event(a)});aa("baofeng.nsignLog",function(a){var b=$.K(),c=a;a={type:"",cid:"",mtime:"",uuid:b.Q,channel:b.P,zid:b.wa,fid:b.T,ver:"d3f",ts:(new Z).getTime()};var d,c=c||{},e;for(e in c)a[e]=c[e];a.sign="41a31dd879856996a857ca97ca3f4314ee6f0e28";d=new P;Ba(a,function(a,b){d.add(b,a)});O(b.ca,d);b.log(b.ca.toString())});$.K();})();
document.write ('');