(function(){function f(a){throw a;}var j=void 0,k=!0,l=null,n=!1;function aa(a){return function(b){this[a]=b}}var p,s=this;function ba(){}function ca(a){a.$a=function(){return a.dd?a.dd:a.dd=new a}}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return a!==j}function u(a){return"array"==da(a)}function v(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){return"string"==typeof a}function ea(a){return"number"==typeof a}function fa(a){return"function"==da(a)}function ga(a){var b=typeof a;return"object"==b&&a!=l||"function"==b}function y(a){return a[ha]||(a[ha]=++ia)}var ha="closure_uid_"+(1E9*Math.random()>>>0),ia=0;
function ja(a,b,c){return a.call.apply(a.bind,arguments)}function ka(a,b,c){a||f(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function z(a,b,c){z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja:ka;return z.apply(l,arguments)}var la=Date.now||function(){return+new Date};
function ma(a,b){var c=a.split("."),d=s;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&t(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function A(a,b){function c(){}c.prototype=b.prototype;a.r=b.prototype;a.prototype=new c};function na(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function oa(a){if(!pa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ra,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(sa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ta,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ua,"&quot;"));return a}var ra=/&/g,sa=/</g,ta=/>/g,ua=/\"/g,pa=/[&<>\"]/;var va,wa,xa,ya;function za(){return s.navigator?s.navigator.userAgent:l}ya=xa=wa=va=n;var Aa;if(Aa=za()){var Ba=s.navigator;va=0==Aa.indexOf("Opera");wa=!va&&-1!=Aa.indexOf("MSIE");xa=!va&&-1!=Aa.indexOf("WebKit");ya=!va&&!xa&&"Gecko"==Ba.product}var Ca=va,C=wa,D=ya,E=xa,Da,Ea=s.navigator;Da=Ea&&Ea.platform||"";var Fa=-1!=Da.indexOf("Mac");function Ga(){var a=s.document;return a?a.documentMode:j}var Ha;
a:{var Ia="",Ja;if(Ca&&s.opera)var Ka=s.opera.version,Ia="function"==typeof Ka?Ka():Ka;else if(D?Ja=/rv\:([^\);]+)(\)|;)/:C?Ja=/MSIE\s+([^\);]+)(\)|;)/:E&&(Ja=/WebKit\/(\S+)/),Ja)var La=Ja.exec(za()),Ia=La?La[1]:"";if(C){var Ma=Ga();if(Ma>parseFloat(Ia)){Ha=String(Ma);break a}}Ha=Ia}var Na={};
function F(a){var b;if(!(b=Na[a])){b=0;for(var c=na(String(Ha)).split("."),d=na(String(a)).split("."),e=Math.max(c.length,d.length),g=0;0==b&&g<e;g++){var h=c[g]||"",m=d[g]||"",q=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var r=q.exec(h)||["","",""],B=w.exec(m)||["","",""];if(0==r[0].length&&0==B[0].length)break;b=((0==r[1].length?0:parseInt(r[1],10))<(0==B[1].length?0:parseInt(B[1],10))?-1:(0==r[1].length?0:parseInt(r[1],10))>(0==B[1].length?0:parseInt(B[1],10))?1:0)||((0==r[2].length)<
(0==B[2].length)?-1:(0==r[2].length)>(0==B[2].length)?1:0)||(r[2]<B[2]?-1:r[2]>B[2]?1:0)}while(0==b)}b=Na[a]=0<=b}return b}var Oa=s.document,Pa=!Oa||!C?j:Ga()||("CSS1Compat"==Oa.compatMode?parseInt(Ha,10):5);function Qa(a){Error.captureStackTrace?Error.captureStackTrace(this,Qa):this.stack=Error().stack||"";a&&(this.message=String(a))}A(Qa,Error);Qa.prototype.name="CustomError";var Ra=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Sa(a,b){for(var c in a)b.call(j,a[c],c,a)}function Ta(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ua(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Va(a){for(var b in a)return n;return k}var Wa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Xa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<Wa.length;g++)c=Wa[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var G=Array.prototype,Ya=G.indexOf?function(a,b,c){return G.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(x(a))return!x(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},H=G.forEach?function(a,b,c){G.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},Za=G.filter?function(a,b,c){return G.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],g=0,h=x(a)?a.split(""):
a,m=0;m<d;m++)if(m in h){var q=h[m];b.call(c,q,m,a)&&(e[g++]=q)}return e},$a=G.some?function(a,b,c){return G.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&b.call(c,e[g],g,a))return k;return n};function ab(a,b){return 0<=Ya(a,b)}function bb(a,b){var c=Ya(a,b),d;(d=0<=c)&&G.splice.call(a,c,1);return d}function cb(a){return G.concat.apply(G,arguments)}function db(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function eb(a,b,c){return 2>=arguments.length?G.slice.call(a,b):G.slice.call(a,b,c)};var fb="StopIteration"in s?s.StopIteration:Error("StopIteration");function gb(){}gb.prototype.next=function(){f(fb)};gb.prototype.Ua=function(){return this};function hb(a){if(a instanceof gb)return a;if("function"==typeof a.Ua)return a.Ua(n);if(v(a)){var b=0,c=new gb;c.next=function(){for(;;){b>=a.length&&f(fb);if(b in a)return a[b++];b++}};return c}f(Error("Not implemented"))};function ib(a){if("function"==typeof a.Q)return a.Q();if(x(a))return a.split("");if(v(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ta(a)};function jb(a,b){this.K={};this.c=[];var c=arguments.length;if(1<c){c%2&&f(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof jb?(c=a.sa(),d=a.Q()):(c=Ua(a),d=Ta(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}}p=jb.prototype;p.a=0;p.qb=0;p.Q=function(){kb(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.K[this.c[b]]);return a};p.sa=function(){kb(this);return this.c.concat()};p.pa=function(a){return lb(this.K,a)};
p.clear=function(){this.K={};this.qb=this.a=this.c.length=0};p.remove=function(a){return lb(this.K,a)?(delete this.K[a],this.a--,this.qb++,this.c.length>2*this.a&&kb(this),k):n};function kb(a){if(a.a!=a.c.length){for(var b=0,c=0;b<a.c.length;){var d=a.c[b];lb(a.K,d)&&(a.c[c++]=d);b++}a.c.length=c}if(a.a!=a.c.length){for(var e={},c=b=0;b<a.c.length;)d=a.c[b],lb(e,d)||(a.c[c++]=d,e[d]=1),b++;a.c.length=c}}p.get=function(a,b){return lb(this.K,a)?this.K[a]:b};
p.set=function(a,b){lb(this.K,a)||(this.a++,this.c.push(a),this.qb++);this.K[a]=b};p.O=function(){return new jb(this)};p.Ua=function(a){kb(this);var b=0,c=this.c,d=this.K,e=this.qb,g=this,h=new gb;h.next=function(){for(;;){e!=g.qb&&f(Error("The map has changed since the iterator was created"));b>=c.length&&f(fb);var h=c[b++];return a?h:d[h]}};return h};function lb(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function mb(a,b){var c;if(a instanceof mb)this.F=t(b)?b:a.F,nb(this,a.na),c=a.Da,I(this),this.Da=c,ob(this,a.qa),pb(this,a.Ma),qb(this,a.la),rb(this,a.M.O()),c=a.ra,I(this),this.ra=c;else if(a&&(c=String(a).match(Ra))){this.F=!!b;nb(this,c[1]||"",k);var d=c[2]||"";I(this);this.Da=d?decodeURIComponent(d):"";ob(this,c[3]||"",k);pb(this,c[4]);qb(this,c[5]||"",k);rb(this,c[6]||"",k);c=c[7]||"";I(this);this.ra=c?decodeURIComponent(c):""}else this.F=!!b,this.M=new sb(l,0,this.F)}p=mb.prototype;p.na="";
p.Da="";p.qa="";p.Ma=l;p.la="";p.ra="";p.ne=n;p.F=n;p.toString=function(){var a=[],b=this.na;b&&a.push(tb(b,ub),":");if(b=this.qa){a.push("//");var c=this.Da;c&&a.push(tb(c,ub),"@");a.push(encodeURIComponent(String(b)));b=this.Ma;b!=l&&a.push(":",String(b))}if(b=this.la)this.qa&&"/"!=b.charAt(0)&&a.push("/"),a.push(tb(b,"/"==b.charAt(0)?vb:wb));(b=this.M.toString())&&a.push("?",b);(b=this.ra)&&a.push("#",tb(b,xb));return a.join("")};
p.zd=function(a){var b=this.O(),c=!!a.na;c?nb(b,a.na):c=!!a.Da;if(c){var d=a.Da;I(b);b.Da=d}else c=!!a.qa;c?ob(b,a.qa):c=a.Ma!=l;var e=a.la;if(c)pb(b,a.Ma);else if(c=!!a.la)if("/"!=e.charAt(0)&&(this.qa&&!this.la?e="/"+e:(d=b.la.lastIndexOf("/"),-1!=d&&(e=b.la.substr(0,d+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){for(var d=0==e.lastIndexOf("/",0),e=e.split("/"),g=[],h=0;h<e.length;){var m=e[h++];"."==m?d&&h==e.length&&g.push(""):".."==m?((1<g.length||1==g.length&&
""!=g[0])&&g.pop(),d&&h==e.length&&g.push("")):(g.push(m),d=k)}e=g.join("/")}c?qb(b,e):c=""!==a.M.toString();c?rb(b,a.M.toString()?decodeURIComponent(a.M.toString()):""):c=!!a.ra;c&&(a=a.ra,I(b),b.ra=a);return b};p.O=function(){return new mb(this)};function nb(a,b,c){I(a);a.na=c?b?decodeURIComponent(b):"":b;a.na&&(a.na=a.na.replace(/:$/,""))}function ob(a,b,c){I(a);a.qa=c?b?decodeURIComponent(b):"":b}
function pb(a,b){I(a);b?(b=Number(b),(isNaN(b)||0>b)&&f(Error("Bad port number "+b)),a.Ma=b):a.Ma=l}function qb(a,b,c){I(a);a.la=c?b?decodeURIComponent(b):"":b}function rb(a,b,c){I(a);b instanceof sb?(a.M=b,a.M.Cc(a.F)):(c||(b=tb(b,yb)),a.M=new sb(b,0,a.F))}function zb(a,b,c){I(a);u(c)||(c=[String(c)]);Ab(a.M,b,c)}function I(a){a.ne&&f(Error("Tried to modify a read-only Uri"))}p.Cc=function(a){this.F=a;this.M&&this.M.Cc(a);return this};
function Bb(a,b){var c=new mb(l,j);nb(c,"http");ob(c,"web.houyi.baofeng.net");a&&qb(c,a);b&&rb(c,b);return c}function tb(a,b){return x(a)?encodeURI(a).replace(b,Cb):l}function Cb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var ub=/[#\/\?@]/g,wb=/[\#\?:]/g,vb=/[\#\?]/g,yb=/[\#\?@]/g,xb=/#/g;function sb(a,b,c){this.A=a||l;this.F=!!c}
function Db(a){if(!a.d&&(a.d=new jb,a.a=0,a.A))for(var b=a.A.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=l,g=l;0<=d?(e=b[c].substring(0,d),g=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=Eb(a,e);a.add(e,g?decodeURIComponent(g.replace(/\+/g," ")):"")}}p=sb.prototype;p.d=l;p.a=l;p.add=function(a,b){Db(this);this.A=l;a=Eb(this,a);var c=this.d.get(a);c||this.d.set(a,c=[]);c.push(b);this.a++;return this};
p.remove=function(a){Db(this);a=Eb(this,a);return this.d.pa(a)?(this.A=l,this.a-=this.d.get(a).length,this.d.remove(a)):n};p.clear=function(){this.d=this.A=l;this.a=0};p.pa=function(a){Db(this);a=Eb(this,a);return this.d.pa(a)};p.sa=function(){Db(this);for(var a=this.d.Q(),b=this.d.sa(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};
p.Q=function(a){Db(this);var b=[];if(a)this.pa(a)&&(b=cb(b,this.d.get(Eb(this,a))));else{a=this.d.Q();for(var c=0;c<a.length;c++)b=cb(b,a[c])}return b};p.set=function(a,b){Db(this);this.A=l;a=Eb(this,a);this.pa(a)&&(this.a-=this.d.get(a).length);this.d.set(a,[b]);this.a++;return this};p.get=function(a,b){var c=a?this.Q(a):[];return 0<c.length?String(c[0]):b};function Ab(a,b,c){a.remove(b);0<c.length&&(a.A=l,a.d.set(Eb(a,b),db(c)),a.a+=c.length)}
p.toString=function(){if(this.A)return this.A;if(!this.d)return"";for(var a=[],b=this.d.sa(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.Q(d),g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="="+encodeURIComponent(String(d[g])));a.push(h)}return this.A=a.join("&")};p.O=function(){var a=new sb;a.A=this.A;this.d&&(a.d=this.d.O(),a.a=this.a);return a};function Eb(a,b){var c=String(b);a.F&&(c=c.toLowerCase());return c}
p.Cc=function(a){if(a&&!this.F){Db(this);this.A=l;var b=this.d,c=function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),Ab(this,c,a))};if("function"==typeof b.forEach)b.forEach(c,this);else if(v(b)||x(b))H(b,c,this);else{var d;if("function"==typeof b.sa)d=b.sa();else if("function"!=typeof b.Q)if(v(b)||x(b)){d=[];for(var e=b.length,g=0;g<e;g++)d.push(g)}else d=Ua(b);else d=j;b=ib(b);e=b.length;for(g=0;g<e;g++)c.call(this,b[g],d&&d[g])}}this.F=a};function Fb(a){this.B=a}var Gb=/\s*;\s*/;p=Fb.prototype;p.set=function(a,b,c,d,e,g){/[;=\s]/.test(a)&&f(Error('Invalid cookie name "'+a+'"'));/[;\r\n]/.test(b)&&f(Error('Invalid cookie value "'+b+'"'));t(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";g=g?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(la()+1E3*c)).toUTCString();this.B.cookie=a+"="+b+e+d+c+g};
p.get=function(a,b){for(var c=a+"=",d=(this.B.cookie||"").split(Gb),e=0,g;g=d[e];e++){if(0==g.lastIndexOf(c,0))return g.substr(c.length);if(g==a)return""}return b};p.remove=function(a,b,c){var d=this.pa(a);this.set(a,"",0,b,c);return d};p.sa=function(){return Hb(this).keys};p.Q=function(){return Hb(this).Ne};p.pa=function(a){return t(this.get(a))};p.clear=function(){for(var a=Hb(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
function Hb(a){a=(a.B.cookie||"").split(Gb);for(var b=[],c=[],d,e,g=0;e=a[g];g++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,Ne:c}};function J(){0!=Ib&&(this.Se=Error().stack,Jb[y(this)]=this)}var Ib=0,Jb={};J.prototype.Ab=n;J.prototype.Ga=function(){if(!this.Ab&&(this.Ab=k,this.g(),0!=Ib)){var a=y(this);delete Jb[a]}};J.prototype.g=function(){if(this.td)for(;this.td.length;)this.td.shift()()};var Kb={};function K(a,b){this.type=a;this.currentTarget=this.target=b}p=K.prototype;p.g=function(){};p.Ga=function(){};p.Na=n;p.defaultPrevented=n;p.Tb=k;p.preventDefault=function(){this.defaultPrevented=k;this.Tb=n};var Mb=0;function Nb(){}p=Nb.prototype;p.key=0;p.ma=n;p.vb=n;p.ua=function(a,b,c,d,e,g){fa(a)?this.ed=k:a&&a.handleEvent&&fa(a.handleEvent)?this.ed=n:f(Error("Invalid listener argument"));this.da=a;this.xd=b;this.src=c;this.type=d;this.capture=!!e;this.Hb=g;this.vb=n;this.key=++Mb;this.ma=n};p.handleEvent=function(a){return this.ed?this.da.call(this.Hb||this.src,a):this.da.handleEvent.call(this.da,a)};var Ob=!C||C&&9<=Pa,Pb=C&&!F("9");!E||F("528");D&&F("1.9b")||C&&F("8")||Ca&&F("9.5")||E&&F("528");D&&!F("8")||C&&F("9");function Qb(a){Qb[" "](a);return a}Qb[" "]=ba;function Rb(a,b){a&&this.ua(a,b)}A(Rb,K);p=Rb.prototype;p.target=l;p.relatedTarget=l;p.offsetX=0;p.offsetY=0;p.clientX=0;p.clientY=0;p.screenX=0;p.screenY=0;p.button=0;p.keyCode=0;p.charCode=0;p.ctrlKey=n;p.altKey=n;p.shiftKey=n;p.metaKey=n;p.Be=n;p.Vc=l;
p.ua=function(a,b){var c=this.type=a.type;K.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(D){var e;a:{try{Qb(d.nodeName);e=k;break a}catch(g){}e=n}e||(d=l)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=E||a.offsetX!==j?a.offsetX:a.layerX;this.offsetY=E||a.offsetY!==j?a.offsetY:a.layerY;this.clientX=a.clientX!==j?a.clientX:a.pageX;this.clientY=a.clientY!==j?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Be=Fa?a.metaKey:a.ctrlKey;this.state=a.state;this.Vc=a;a.defaultPrevented&&this.preventDefault();delete this.Na};
p.preventDefault=function(){Rb.r.preventDefault.call(this);var a=this.Vc;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,Pb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};p.g=function(){};var Sb={},L={},M={},Tb={};
function O(a,b,c,d,e){if(u(b)){for(var g=0;g<b.length;g++)O(a,b[g],c,d,e);return l}a:{b||f(Error("Invalid event type"));d=!!d;var h=L;b in h||(h[b]={a:0,v:0});h=h[b];d in h||(h[d]={a:0,v:0},h.a++);var h=h[d],g=y(a),m;h.v++;if(h[g]){m=h[g];for(var q=0;q<m.length;q++)if(h=m[q],h.da==c&&h.Hb==e){if(h.ma)break;m[q].vb=n;a=m[q];break a}}else m=h[g]=[],h.a++;var w=Ub,r=Ob?function(a){return w.call(r.src,r.da,a)}:function(a){a=w.call(r.src,r.da,a);if(!a)return a},q=r,h=new Nb;h.ua(c,q,a,b,d,e);h.vb=n;q.src=
a;q.da=h;m.push(h);M[g]||(M[g]=[]);M[g].push(h);a.addEventListener?(a==s||!a.Tc)&&a.addEventListener(b,q,d):a.attachEvent(b in Tb?Tb[b]:Tb[b]="on"+b,q);a=h}b=a.key;Sb[b]=a;return b}function Vb(a,b,c,d,e){if(u(b))for(var g=0;g<b.length;g++)Vb(a,b[g],c,d,e);else if(d=!!d,a=Wb(a,b,d))for(g=0;g<a.length;g++)if(a[g].da==c&&a[g].capture==d&&a[g].Hb==e){Xb(a[g].key);break}}
function Xb(a){var b=Sb[a];if(!b||b.ma)return n;var c=b.src,d=b.type,e=b.xd,g=b.capture;c.removeEventListener?(c==s||!c.Tc)&&c.removeEventListener(d,e,g):c.detachEvent&&c.detachEvent(d in Tb?Tb[d]:Tb[d]="on"+d,e);c=y(c);M[c]&&(e=M[c],bb(e,b),0==e.length&&delete M[c]);b.ma=k;if(b=L[d][g][c])b.qd=k,Yb(d,g,c,b);delete Sb[a];return k}
function Yb(a,b,c,d){if(!d.Mb&&d.qd){for(var e=0,g=0;e<d.length;e++)d[e].ma?d[e].xd.src=l:(e!=g&&(d[g]=d[e]),g++);d.length=g;d.qd=n;0==g&&(delete L[a][b][c],L[a][b].a--,0==L[a][b].a&&(delete L[a][b],L[a].a--),0==L[a].a&&delete L[a])}}function Zb(a,b){var c=0,d=b==l;if(a!=l){var e=y(a);if(M[e])for(var e=M[e],g=e.length-1;0<=g;g--){var h=e[g];if(d||b==h.type)Xb(h.key),c++}}else Sa(Sb,function(a,b){Xb(b);c++})}function Wb(a,b,c){var d=L;return b in d&&(d=d[b],c in d&&(d=d[c],a=y(a),d[a]))?d[a]:l}
function $b(a,b,c,d,e){var g=1;b=y(b);if(a[b]){var h=--a.v,m=a[b];m.Mb?m.Mb++:m.Mb=1;try{for(var q=m.length,w=0;w<q;w++){var r=m[w];r&&!r.ma&&(g&=ac(r,e)!==n)}}finally{a.v=Math.max(h,a.v),m.Mb--,Yb(c,d,b,m)}}return Boolean(g)}function ac(a,b){a.vb&&Xb(a.key);return a.handleEvent(b)}
function Ub(a,b){if(a.ma)return k;var c=a.type,d=L;if(!(c in d))return k;var d=d[c],e,g;if(!Ob){var h;if(!(h=b))a:{h=["window","event"];for(var m=s;e=h.shift();)if(m[e]!=l)m=m[e];else{h=l;break a}h=m}e=h;h=k in d;m=n in d;if(h){if(0>e.keyCode||e.returnValue!=j)return k;a:{var q=n;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(w){q=k}if(q||e.returnValue==j)e.returnValue=k}}q=new Rb;q.ua(e,this);e=k;try{if(h){for(var r=[],B=q.currentTarget;B;B=B.parentNode)r.push(B);g=d[k];g.v=g.a;for(var N=r.length-
1;!q.Na&&0<=N&&g.v;N--)q.currentTarget=r[N],e&=$b(g,r[N],c,k,q);if(m){g=d[n];g.v=g.a;for(N=0;!q.Na&&N<r.length&&g.v;N++)q.currentTarget=r[N],e&=$b(g,r[N],c,n,q)}}else e=ac(a,q)}finally{r&&(r.length=0)}return e}c=new Rb(b,this);return e=ac(a,c)};function bc(){J.call(this)}A(bc,J);p=bc.prototype;p.Tc=k;p.Pb=l;p.Dc=aa("Pb");p.addEventListener=function(a,b,c,d){O(this,a,b,c,d)};p.removeEventListener=function(a,b,c,d){Vb(this,a,b,c,d)};
p.dispatchEvent=function(a){var b=a.type||a,c=L;if(b in c){if(x(a))a=new K(a,this);else if(a instanceof K)a.target=a.target||this;else{var d=a;a=new K(b,this);Xa(a,d)}var d=1,e,c=c[b],b=k in c,g;if(b){e=[];for(g=this;g;g=g.Pb)e.push(g);g=c[k];g.v=g.a;for(var h=e.length-1;!a.Na&&0<=h&&g.v;h--)a.currentTarget=e[h],d&=$b(g,e[h],a.type,k,a)&&a.Tb!=n}if(n in c)if(g=c[n],g.v=g.a,b)for(h=0;!a.Na&&h<e.length&&g.v;h++)a.currentTarget=e[h],d&=$b(g,e[h],a.type,n,a)&&a.Tb!=n;else for(e=this;!a.Na&&e&&g.v;e=e.Pb)a.currentTarget=
e,d&=$b(g,e,a.type,n,a)&&a.Tb!=n;a=Boolean(d)}else a=k;return a};p.g=function(){bc.r.g.call(this);Zb(this);this.Pb=l};/*
 {@link www.baofeng.com}
*/
new mb(s.location.href);var P=new bc,cc=l;function dc(a,b,c,d){var e=[];e.push("_trackEvent");e.push(a);e.push(b);c!=l&&e.push(c);d!=l&&e.push(d);try{s._hmt.push(e),s.ga&&s.ga("send","event",a,b)}catch(g){}}O(P,"log",function(a){var b=ec[a.data.key].name,c=ec[a.data.key].infor[a.data.value-1];a.data.other?dc(b,c,l,a.data.other):dc(b,c)});
O(P,"log",function(a){if(t(ec[a.data.key].bfinfo)&&t(s.baofeng.eventLog)){var b=ec[a.data.key].bfinfo[a.data.value-1];t(b)&&b!=l&&(t(a.data.other)&&(b.value&&(b.value=a.data.other),b.key&&(b[b.key]=a.data.other)),b.category=a.data.key,s.baofeng.eventLog(b))}});function fc(a,b){this.x=t(a)?a:0;this.y=t(b)?b:0}p=fc.prototype;p.O=function(){return new fc(this.x,this.y)};p.toString=function(){return"("+this.x+", "+this.y+")"};p.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};p.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};p.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function gc(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}p=gc.prototype;p.O=function(){return new gc(this.top,this.right,this.bottom,this.left)};p.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};p.contains=function(a){return!this||!a?n:a instanceof gc?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};
p.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};p.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};p.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function hc(a,b){this.width=a;this.height=b}p=hc.prototype;p.O=function(){return new hc(this.width,this.height)};p.toString=function(){return"("+this.width+" x "+this.height+")"};p.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};p.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};p.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function ic(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}p=ic.prototype;p.O=function(){return new ic(this.left,this.top,this.width,this.height)};p.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};p.contains=function(a){return a instanceof ic?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
p.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};p.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};p.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var jc;function kc(a){a=a.className;return x(a)&&a.match(/\S+/g)||[]}function Q(a,b){for(var c=kc(a),d=eb(arguments,1),e=c.length+d.length,g=c,h=0;h<d.length;h++)ab(g,d[h])||g.push(d[h]);a.className=c.join(" ");return c.length==e}function lc(a,b){var c=kc(a),d=eb(arguments,1),c=Za(c,function(a){return!ab(d,a)});a.className=c.join(" ")};var mc=!C||C&&9<=Pa,nc=!D&&!C||C&&C&&9<=Pa||D&&F("1.9.1"),oc=C&&!F("9");function pc(a){return a?new qc(rc(a)):jc||(jc=new qc)}function R(a){return x(a)?document.getElementById(a):a}function sc(a,b){var c=b||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):S("*",a,b)}function T(a,b){var c=b||document,d=l;return(d=c.querySelectorAll&&c.querySelector?c.querySelector("."+a):sc(a,b)[0])||l}
function S(a,b,c){var d=document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,g=0,h;h=c[g];g++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(g=e=0;h=c[g];g++)a=h.className,"function"==typeof a.split&&ab(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c}
function tc(a,b){Sa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in uc?a.setAttribute(uc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var uc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function vc(a){var b=!E&&"CSS1Compat"==a.compatMode?a.documentElement:a.body;a=a.parentWindow||a.defaultView;return new fc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}function wc(a,b,c){return xc(document,arguments)}
function xc(a,b){var c=b[0],d=b[1];if(!mc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',oa(d.name),'"');if(d.type){c.push(' type="',oa(d.type),'"');var e={};Xa(e,d);delete e.type;d=e}c.push(">");c=c.join("")}var g=a.createElement(c);d&&(x(d)?g.className=d:u(d)?Q.apply(l,[g].concat(d)):tc(g,d));if(2<b.length){d=function(b){b&&g.appendChild(x(b)?a.createTextNode(b):b)};for(c=2;c<b.length;c++)if(e=b[c],v(e)&&!(ga(e)&&0<e.nodeType)){var h=H,m;a:{if((m=e)&&"number"==typeof m.length){if(ga(m)){m=
"function"==typeof m.item||"string"==typeof m.item;break a}if(fa(m)){m="function"==typeof m.item;break a}}m=n}h(m?db(e):e,d)}else d(e)}return g}function yc(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function zc(a){return nc&&a.children!=j?a.children:Za(a.childNodes,function(a){return 1==a.nodeType})}function Ac(a){return ga(a)&&1==a.nodeType}function rc(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var Bc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Cc={IMG:" ",BR:"\n"};
function Dc(a){if(oc&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Ec(a,b,k);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");oc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Ec(a,b,c){if(!(a.nodeName in Bc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Cc)b.push(Cc[a.nodeName]);else for(a=a.firstChild;a;)Ec(a,b,c),a=a.nextSibling}function qc(a){this.B=a||s.document||document}p=qc.prototype;p.$c=function(a){return x(a)?this.B.getElementById(a):a};p.Sc=function(a,b,c){return xc(this.B,arguments)};p.createElement=function(a){return this.B.createElement(a)};p.createTextNode=function(a){return this.B.createTextNode(String(a))};
p.appendChild=function(a,b){a.appendChild(b)};p.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function Fc(a,b){var c=rc(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,l))?c[b]||c.getPropertyValue(b)||"":""}function Gc(a,b){return Fc(a,b)||(a.currentStyle?a.currentStyle[b]:l)||a.style&&a.style[b]}function Hc(a){var b=a.getBoundingClientRect();C&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Ic(a){if(C&&!(C&&8<=Pa))return a.offsetParent;var b=rc(a),c=Gc(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Gc(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return l}
function Jc(a){if("none"!=Gc(a,"display"))return Kc(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Kc(a);b.display=c;b.position=e;b.visibility=d;return a}function Kc(a){var b=a.offsetWidth,c=a.offsetHeight,d=E&&!b&&!c;return(!t(b)||d)&&a.getBoundingClientRect?(a=Hc(a),new hc(a.right-a.left,a.bottom-a.top)):new hc(b,c)}
function Lc(a){var b,c=rc(a),d=Gc(a,"position"),e=D&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),g=new fc(0,0),h;b=c?rc(c):document;if(h=C)if(h=!(C&&9<=Pa))h="CSS1Compat"!=pc(b).B.compatMode;h=h?b.body:b.documentElement;if(a!=h)if(a.getBoundingClientRect)b=Hc(a),c=pc(c),c=vc(c.B),g.x=b.left+c.x,g.y=b.top+c.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),c=c.getBoxObjectFor(h),g.x=b.screenX-c.screenX,g.y=b.screenY-c.screenY;
else{b=a;do{g.x+=b.offsetLeft;g.y+=b.offsetTop;b!=a&&(g.x+=b.clientLeft||0,g.y+=b.clientTop||0);if(E&&"fixed"==Gc(b,"position")){g.x+=c.body.scrollLeft;g.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(Ca||E&&"absolute"==d)g.y-=c.body.offsetTop;for(b=a;(b=Ic(b))&&b!=c.body&&b!=h;)if(g.x-=b.scrollLeft,!Ca||"TR"!=b.tagName)g.y-=b.scrollTop}a=Jc(a);return new ic(g.x,g.y,a.width,a.height)}function U(a,b){a.style.display=b?"":"none"}
function Mc(a,b){var c=a.currentStyle?a.currentStyle[b]:l,d;if(c)if(/^\d+px?$/.test(c))d=parseInt(c,10);else{d=a.style.left;var e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=d;a.runtimeStyle.left=e;d=c}else d=0;return d}
function Nc(a){if(C){var b=Mc(a,"marginLeft"),c=Mc(a,"marginRight"),d=Mc(a,"marginTop");a=Mc(a,"marginBottom");return new gc(d,c,a,b)}b=Fc(a,"marginLeft");c=Fc(a,"marginRight");d=Fc(a,"marginTop");a=Fc(a,"marginBottom");return new gc(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))};function Oc(a){J.call(this);this.aa=a;this.c=[]}A(Oc,J);var Pc=[];function Qc(a,b,c,d,e,g){if(u(c))for(var h=0;h<c.length;h++)Qc(a,b,c[h],d,e,g);else{a:{d=d||a;g=g||a.aa||a;e=!!e;if(b=Wb(b,c,e))for(c=0;c<b.length;c++)if(!b[c].ma&&b[c].da==d&&b[c].capture==e&&b[c].Hb==g){b=b[c];break a}b=l}b&&(b=b.key,Xb(b),bb(a.c,b))}}Oc.prototype.g=function(){Oc.r.g.call(this);H(this.c,Xb);this.c.length=0};Oc.prototype.handleEvent=function(){f(Error("EventHandler.handleEvent not implemented"))};function Rc(){}ca(Rc);Rc.prototype.xe=0;Rc.$a();function V(a){J.call(this);this.Xa=a||pc();this.Aa=Sc}A(V,bc);V.prototype.je=Rc.$a();var Sc=l;p=V.prototype;p.S=l;p.ta=n;p.Z=l;p.Aa=l;p.ve=l;p.V=l;p.yb=l;p.Va=l;p.Jd=n;p.ic=function(){return this.S||(this.S=":"+(this.je.xe++).toString(36))};p.$c=function(){return this.Z};p.Dc=function(a){this.V&&this.V!=a&&f(Error("Method not supported"));V.r.Dc.call(this,a)};p.Sc=function(){this.Z=this.Xa.createElement("div")};
function W(a,b){a.ta&&f(Error("Component already rendered"));if(b){a.Jd=k;if(!a.Xa||a.Xa.B!=rc(b))a.Xa=pc(b);a.P(b);a.q()}else f(Error("Invalid element to decorate"))}p.P=aa("Z");p.q=function(){this.ta=k;Tc(this,function(a){!a.ta&&a.$c()&&a.q()})};function Uc(a){Tc(a,function(a){a.ta&&Uc(a)});if(a.Gb){var b=a.Gb;H(b.c,Xb);b.c.length=0}a.ta=n}
p.g=function(){this.ta&&Uc(this);this.Gb&&(this.Gb.Ga(),delete this.Gb);Tc(this,function(a){a.Ga()});!this.Jd&&this.Z&&yc(this.Z);this.V=this.ve=this.Z=this.Va=this.yb=l;V.r.g.call(this)};p.gd=function(){this.Aa==l&&(this.Aa="rtl"==Gc(this.ta?this.Z:this.Xa.B.body,"direction"));return this.Aa};function Tc(a,b){a.yb&&H(a.yb,b,j)}
p.removeChild=function(a,b){if(a){var c=x(a)?a:a.ic();a=this.Va&&c?(c in this.Va?this.Va[c]:j)||l:l;if(c&&a){var d=this.Va;c in d&&delete d[c];bb(this.yb,a);b&&(Uc(a),a.Z&&yc(a.Z));c=a;c==l&&f(Error("Unable to set parent component"));c.V=l;V.r.Dc.call(c,l)}}a||f(Error("Child is not in parent component"));return a};/*
 {@link www.baofeng.com}
*/
function Vc(){this.Hd=this.Id=this.n=this.ca=l;this.Lc="menu";this.Kc="content";this.Ea="active";this.l="click";this.ea=[];this.R=[];this.Ra=l;this.index=0;this.classList=[];this.ba=k}A(Vc,V);function Wc(a,b){var c=db(b.children),d=l,e;for(e in c)d=c[e],d.ad=function(){return this},1==d.nodeType&&a.ea.push(c[e])}
Vc.prototype.kd=function(a){var b=this;a.target!=this.ca&&("mouseover"==this.l?"mouseout"==a.type&&this.ba?clearTimeout(this.Ra):this.ba?this.Ra=setTimeout(function(){Xc(b,a.target,n)},200):Xc(this,a.target,n):Xc(this,a.target,n))};Vc.prototype.Fe=function(a){a=a.index;t(a)&&(ea(a)&&0<=a&&a<this.ea.length)&&Xc(this,this.R[a],k)};
function Xc(a,b,c){b!=a.ca&&(b.className=a.Ea+" "+a.classList[b.index],b.qc.style.display="block",a.dispatchEvent({type:"Event_UpPage",target:a,index:b.index,Re:c}),a.ca.className=""+a.classList[a.ca.index],a.ca.qc.style.display="none",a.ca=b,b.kc&&(b.kc=n,P.dispatchEvent({type:"Add_Display",element:b.qc})))}
Vc.prototype.P=function(a){var b=l;this.n=a;this.Id=sc(this.Lc,this.n)[0];this.Hd=sc(this.Kc,this.n)[0];this.R=db(this.Id.children);a=document.createDocumentFragment();for(var c=0,d=this.ea.length;c<d;c++){b=this.ea[c].ad();-1==this.R[c].className.indexOf(this.Ea)?(b.style.display="none",this.R[c].kc=k):(this.index=c,this.ca=this.R[c],this.ca.index=c,this.ca.kc=n);this.R[c].qc=b;var e=this.R[c].index=c,g=this.R[c].className;RegExp(this.Ea).test(g)&&(g=g.substr(this.Ea.length));this.classList[e]=g;
this.classList[c]||(this.classList[c]="");a.appendChild(b)}this.Hd.appendChild(a)};Vc.prototype.q=function(){for(var a=0,b=this.ea.length;a<b;a++)O(this.R[a],this.l,z(this.kd,this)),"mouseover"==this.l&&O(this.R[a],"mouseout",z(this.kd,this));0!=this.ea.length&&(O(this,"Event_SetIndex",z(this.Fe,this)),this.dispatchEvent({type:"Event_Open",target:this}))};function Yc(a,b,c){J.call(this);this.tc=a;this.le=b||0;this.aa=c;this.Ud=z(this.be,this)}A(Yc,J);p=Yc.prototype;p.S=0;p.g=function(){Yc.r.g.call(this);this.stop();delete this.tc;delete this.aa};p.start=function(a){this.stop();var b=this.Ud;a=t(a)?a:this.le;fa(b)||(b&&"function"==typeof b.handleEvent?b=z(b.handleEvent,b):f(Error("Invalid listener argument")));this.S=2147483647<a?-1:s.setTimeout(b,a||0)};p.stop=function(){0!=this.S&&s.clearTimeout(this.S);this.S=0};
p.be=function(){this.S=0;this.tc&&this.tc.call(this.aa)};var Zc={},$c=l;function ad(a){a=y(a);delete Zc[a];Va(Zc)&&$c&&$c.stop()}function bd(){$c||($c=new Yc(function(){var a=la();Sa(Zc,function(c){cd(c,a)});Va(Zc)||bd()},20));var a=$c;0!=a.S||a.start()};function X(){J.call(this);this.e=Y;this.Ya=this.startTime=l}A(X,bc);var Y=0;X.prototype.Ob=function(){this.z("begin")};X.prototype.La=function(){this.z("end")};X.prototype.z=function(a){this.dispatchEvent(a)};function dd(a,b,c,d){X.call(this);(!u(a)||!u(b))&&f(Error("Start and end parameters must be arrays"));a.length!=b.length&&f(Error("Start and end points must be the same length"));this.nb=a;this.de=b;this.duration=c;this.Pc=d;this.coords=[];this.Me=n}A(dd,X);p=dd.prototype;p.Yc=0;p.H=0;p.sc=l;
p.play=function(a){if(a||this.e==Y)this.H=0,this.coords=this.nb;else if(1==this.e)return n;ad(this);this.startTime=a=la();-1==this.e&&(this.startTime-=this.duration*this.H);this.Ya=this.startTime+this.duration;this.sc=this.startTime;this.H||this.Ob();this.z("play");-1==this.e&&this.z("resume");this.e=1;var b=y(this);b in Zc||(Zc[b]=this);bd();cd(this,a);return k};p.stop=function(a){ad(this);this.e=Y;a&&(this.H=1);ed(this,this.H);this.z("stop");this.La()};
p.g=function(){this.e==Y||this.stop(n);this.z("destroy");dd.r.g.call(this)};function cd(a,b){a.H=(b-a.startTime)/(a.Ya-a.startTime);1<=a.H&&(a.H=1);a.Yc=1E3/(b-a.sc);a.sc=b;ed(a,a.H);1==a.H?(a.e=Y,ad(a),a.z("finish"),a.La()):1==a.e&&a.xc()}function ed(a,b){fa(a.Pc)&&(b=a.Pc(b));a.coords=Array(a.nb.length);for(var c=0;c<a.nb.length;c++)a.coords[c]=(a.de[c]-a.nb[c])*b+a.nb[c]}p.xc=function(){this.z("animate")};p.z=function(a){this.dispatchEvent(new fd(a,this))};
function fd(a,b){K.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.ef=b.coords[2];this.duration=b.duration;this.H=b.H;this.Xe=b.Yc;this.state=b.e;this.Qe=b}A(fd,K);function Z(a,b,c,d,e){dd.call(this,b,c,d,e);this.element=a}A(Z,dd);p=Z.prototype;p.pb=ba;p.gd=function(){t(this.Aa)||(this.Aa="rtl"==Gc(this.element,"direction"));return this.Aa};p.xc=function(){this.pb();Z.r.xc.call(this)};p.La=function(){this.pb();Z.r.La.call(this)};p.Ob=function(){this.pb();Z.r.Ob.call(this)};function gd(a,b,c,d,e){(2!=b.length||2!=c.length)&&f(Error("Start and end points must be 2D"));Z.apply(this,arguments)}A(gd,Z);
gd.prototype.pb=function(){var a=this.Me&&this.gd()?"right":"left";this.element.style[a]=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};function id(a,b,c,d,e){ea(b)&&(b=[b]);ea(c)&&(c=[c]);Z.call(this,a,b,c,d,e);(1!=b.length||1!=c.length)&&f(Error("Start and end points must be 1D"))}A(id,Z);
id.prototype.pb=function(){var a=this.coords[0],b=this.element.style;"opacity"in b?b.opacity=a:"MozOpacity"in b?b.MozOpacity=a:"filter"in b&&(b.filter=""===a?"":"alpha(opacity="+100*a+")")};id.prototype.show=function(){this.element.style.display=""};id.prototype.t=function(){this.element.style.display="none"};function jd(){X.call(this);this.p=[]}A(jd,X);jd.prototype.add=function(a){ab(this.p,a)||(this.p.push(a),O(a,"finish",this.sd,n,this))};jd.prototype.remove=function(a){bb(this.p,a)&&Vb(a,"finish",this.sd,n,this)};jd.prototype.g=function(){H(this.p,function(a){a.Ga()});this.p.length=0;jd.r.g.call(this)};function kd(){jd.call(this);this.J=0}A(kd,jd);
kd.prototype.play=function(a){if(0==this.p.length)return n;if(a||this.e==Y)this.J<this.p.length&&this.p[this.J].e!=Y&&this.p[this.J].stop(n),this.J=0,this.Ob();else if(1==this.e)return n;this.z("play");-1==this.e&&this.z("resume");this.startTime=la();this.Ya=l;this.e=1;this.p[this.J].play(a);return k};
kd.prototype.stop=function(a){this.e=Y;this.Ya=la();if(a)for(a=this.J;a<this.p.length;++a){var b=this.p[a];b.e==Y&&b.play();b.e==Y||b.stop(k)}else this.J<this.p.length&&this.p[this.J].stop(n);this.z("stop");this.La()};kd.prototype.sd=function(){1==this.e&&(this.J++,this.J<this.p.length?this.p[this.J].play():(this.Ya=la(),this.e=Y,this.z("finish"),this.La()))};var ld={bf:k};C&&F(8);function md(a){return a&&a.Xd&&a.Xd===ld?a.content:String(a).replace(nd,od)}var pd={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function od(a){return pd[a]}var nd=/[\x00\x22\x26\x27\x3c\x3e]/g;function qd(a){J.call(this);this.eb={};this.cb={};this.aa=new Oc(this);this.V=a}A(qd,bc);var rd=[C?"readystatechange":"load","abort","error"];qd.prototype.start=function(){var a=this.eb;H(Ua(a),function(b){var c=a[b];if(c&&(delete a[b],!this.Ab)){var d;d=this.V?pc(this.V).Sc("img"):new Image;var e=this.aa,g=this.ud,h=rd;u(h)||(Pc[0]=h,h=Pc);for(var m=0;m<h.length;m++){var q=O(d,h[m],g||e,n,e.aa||e);e.c.push(q)}this.cb[b]=d;d.id=b;d.src=c}},this)};
qd.prototype.ud=function(a){var b=a.currentTarget;if(b){if("readystatechange"==a.type)if("complete"==b.readyState)a.type="load";else return;"undefined"==typeof b.naturalWidth&&("load"==a.type?(b.naturalWidth=b.width,b.naturalHeight=b.height):(b.naturalWidth=0,b.naturalHeight=0));this.dispatchEvent({type:a.type,target:b});if(!this.Ab&&(a=b.id,delete this.eb[a],b=this.cb[a]))delete this.cb[a],Qc(this.aa,b,rd,this.ud),Va(this.cb)&&Va(this.eb)&&this.dispatchEvent("complete")}};
qd.prototype.g=function(){delete this.eb;delete this.cb;var a=this.aa;a&&"function"==typeof a.Ga&&a.Ga();qd.r.g.call(this)};var sd=l,td=D||E||Ca||"function"==typeof s.atob;
function ud(a){var b;if(td)b=s.btoa(a);else{b=[];for(var c=0,d=0;d<a.length;d++){for(var e=a.charCodeAt(d);255<e;)b[c++]=e&255,e>>=8;b[c++]=e}v(b)||f(Error("encodeByteArray takes an array as a parameter"));if(!sd){sd={};for(a=0;65>a;a++)sd[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}a=sd;c=[];for(d=0;d<b.length;d+=3){var g=b[d],h=(e=d+1<b.length)?b[d+1]:0,m=d+2<b.length,q=m?b[d+2]:0,w=g>>2,g=(g&3)<<4|h>>4,h=(h&15)<<2|q>>6,q=q&63;m||(q=64,e||(h=64));c.push(a[w],
a[g],a[h],a[q])}b=c.join("")}return b};function vd(a){return 1-Math.pow(1-a,3)};function wd(){this.Fc=l;this.links=[];this.xa=this.fa=this.mb=this.ob=this.w=this.Ic=this.Hc=this.b=this.j=this.i=this.X=l;this.ka=this.index=0;this.ha=[];this.Jb="change-pic-l";this.Qb="change-pic-r";this.xb="change-pic-list";this.te="linksVideo";this.hb="art-pic-big";this.time=6E3;this.Ie=300;this.Ba=6;this.Ec=this.page=0;this.lc=this.Ia=k;this.Wb=this.Ge;this.W=new kd;this.l={OPEN:"Event_Open",rb:"Event_Error",Ta:"Event_Switch"};this.yc="q_"}A(wd,V);
function xd(a,b){var c=l,d=a.ha[b];a.ob.className="";for(var e=0,g=a.links.length;e<g;e++)c=a.links[e],c.href=d.href,c.title=d.title,1==e&&(c.innerHTML=a.Wb(d));a.n.style.backgroundColor=d.color;a.Fc.style.backgroundImage=d.hd?"":"url("+d.wd+")";a.X[b].className="cur";a.ob=a.X[b];a.index++;a.page=Math.ceil(a.index/a.Ba)-1;a.dispatchEvent({type:"click",gc:a});a.index>=a.X.length&&(a.index=0);a.W.e==Y||a.W.stop();a.W.g();a.W.add(new id(a.Fc,0,1,2E3,vd));a.W.play()}p=wd.prototype;
p.Ge=function(a){return a.title?'<em class="icon-view"></em><span class="tip">'+md(a.title)+"</span><span>"+md(a.value)+"</span>":""};p.He=function(a){return a.value?'<em class="icon-view-cart"></em>'+md(a.value):""};function yd(a,b,c,d){var e="";if(a&&b)return e=a.getAttribute(b)||d||"",c&&(e=c(e)),e}p.$d=function(a){return a.replace(/(^\s+)|(\s+$)/g,"")};
function zd(a,b,c){var d=[],e=l,g=l,h=l;if(!b)return d;h=b.split("|");b=0;for(var m=h.length;b<m;b++)e={},c?(e.value=h[b],e.href=a.yc+ud(encodeURIComponent(h[b]))):(g=h[b].split("="),e.value=g[0],e.href=g[1]),d.push(e);return d}
p.wa=function(a){switch(a.gc||a.currentTarget){case this.i:0<this.page&&(this.page--,this.b.style.left=-this.page*this.ka+"px",Ad(this,this.page*this.Ba));break;case this.j:this.page<this.Ec&&(this.page++,this.b.style.left=-(this.page*this.ka)+"px",Ad(this,this.page*this.Ba));break;case this:this.b.style.left=-(this.page*this.ka)+"px"}this.i.fd=0==this.page?n:k;this.j.fd=this.page==this.Ec?n:k;this.Fa({target:this.i,type:Kb.Ld});this.Fa({target:this.j,type:Kb.Ld})};
p.D=function(a){var b=Lc(a);a=Nc(a);b.height+=a.top+a.bottom;b.width+=a.left+a.right;return b};p.we=function(){var a=this.ha[this.index];a.ia?this.Zb():Bd(this,a,this.Zb,this.index)};p.Zb=function(a){this.Ia&&this.lc&&(clearTimeout(this.Hc),this.Ca());a&&"error"==a.type&&(this.ha[a.index].hd=k);this.ha[this.index].ia=k;xd(this,this.index)};p.ze=function(a){a&&"error"==a.type&&(this.ha[a.index].hd=k);this.ha[a.index].ia=k;a.index==this.index&&xd(this,this.index)};
function Bd(a,b,c,d){var e=new Image;e.index=d;C?e.onreadystatechange=function(){if("complete"==this.readyState||"loaded"==this.readyState)c.call(a,{type:"load",index:this.index}),this.onreadystatechange=l}:e.onload=function(){c.call(a,{type:"load",index:this.index})};e.onerror=function(){c.call(a,{type:"error",index:this.index})};e.src=b.wd}p.Ca=function(){var a=this;this.Hc=setTimeout(function(){a.dispatchEvent({type:a.l.Ta})},this.time)};
function Ad(a,b){var c=a.ha[b];a.ob.className="";a.X[b].className="cur";a.ob=a.X[b];a.index=b;c.ia?a.Zb():Bd(a,c,a.ze,a.index)}p.fb=function(a){var b=a.target,c=this;if("mouseover"==a.type){if("SPAN"==b.nodeName.toUpperCase()||"IMG"==b.nodeName.toUpperCase())clearTimeout(this.Hc),clearTimeout(this.Ic),this.lc=n,this.Ic=setTimeout(function(){Ad(c,b.index)},this.Ie)}else"mouseout"==a.type&&this.C(a,this.w)&&(clearTimeout(this.Ic),this.lc=k,this.Ca())};
p.Fa=function(a){var b=a.target;a=a.type;var c="change-pic-",c=b==this.i?c+"l":c+"r";b.fd&&(c="mouseover"==a?c+"02":c+"03");b.className=c};p.C=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement;else if("mouseout"==c)c=a.relatedTarget||a.toElement;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};p.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};p.start=function(a){W(this,R(a))};
p.P=function(a){this.n=a;this.b=T(this.xb,this.n);this.w=this.b.parentNode;this.links=sc(this.te,this.n);this.Fc=R("switchB");var b=a=l,c=S("a",l,this.b),d=S("img",l,this.b);this.X=S("span",l,this.b);this.xa=this.b.children;this.mb=this.xa[0];this.fa=this.D(this.mb);this.Ec=Math.ceil(this.xa.length/this.Ba)-1;this.ka=this.fa.width*this.Ba;for(var e=0,g=c.length;e<g;e++)b=c[e],a={},a.wd=yd(b,"data-pic",l,l),a.value=yd(b,"data-value",l,l),a.color=yd(b,"data-color",this.$d,l),a.title=yd(b,"title",l,
l),a.href=yd(b,"data-href",l,"http://hd.baofeng.com"),a.status=yd(b,"data-status",l,l),a.Xc=yd(b,"data-format",l,l),a.Ze=zd(this,b.getAttribute("data-type")),a.Ue=zd(this,b.getAttribute("data-director"),this.yc),a.Pe=zd(this,b.getAttribute("data-actor"),this.yc),a.index=e,this.ha.push(a),d[e].index=this.X[e].index=e;this.X=c;this.i=T(this.Jb,this.n);this.j=T(this.Qb,this.n);this.ob=this.X[0]};
p.q=function(){this.X.length<=this.Ba?(this.i.style.display="none",this.j.style.display="none",this.hb&&Q(this.w,this.hb)):this.i&&this.j&&(this.i.style.display="block",this.j.style.display="block",O(this.i,"click",z(this.wa,this)),O(this.j,"click",z(this.wa,this)),O(this.i,"mouseout",z(this.Fa,this)),O(this.j,"mouseout",z(this.Fa,this)),O(this.i,"mouseover",z(this.Fa,this)),O(this.j,"mouseover",z(this.Fa,this)));this.b&&(O(this.w,"mouseout",z(this.fb,this)),O(this.w,"mouseover",z(this.fb,this)));
this.dispatchEvent({type:this.l.OPEN,target:this});this.Ia&&(O(this,this.l.Ta,z(this.we,this)),O(this,"click",z(this.wa,this)),xd(this,0),this.Ca())};ma("baofeng.component.FocusMap",wd);wd.prototype.start=wd.prototype.start;/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function Cd(a,b){this.Pa=[];this.$e=a;this.Yd=b||l}p=Cd.prototype;p.Ha=n;p.ab=n;p.cc=n;p.Qd=n;p.Dd=n;p.Sd=0;p.Rc=function(a,b){this.cc=n;Dd(this,a,b)};function Dd(a,b,c){a.Ha=k;a.Ac=c;a.ab=!b;Ed(a)}function Fd(a){a.Ha&&(a.Dd||f(new Gd(a)),a.Dd=n)}function Hd(a){return $a(a.Pa,function(a){return fa(a[1])})}
function Ed(a){a.Jc&&(a.Ha&&Hd(a))&&(s.clearTimeout(a.Jc),delete a.Jc);a.V&&(a.V.Sd--,delete a.V);for(var b=a.Ac,c=n,d=n;a.Pa.length&&!a.cc;){var e=a.Pa.shift(),g=e[0],h=e[1],e=e[2];if(g=a.ab?h:g)try{var m=g.call(e||a.Yd,b);t(m)&&(a.ab=a.ab&&(m==b||m instanceof Error),a.Ac=b=m);b instanceof Cd&&(d=k,a.cc=k)}catch(q){b=q,a.ab=k,Hd(a)||(c=k)}}a.Ac=b;d&&(d=b,m=z(a.Rc,a,k),g=z(a.Rc,a,n),d.Pa.push([m,g,j]),d.Ha&&Ed(d),b.Qd=k);c&&(a.Jc=s.setTimeout(function(){f(b)},0))}
function Gd(a){Qa.call(this);this.Te=a}A(Gd,Qa);Gd.prototype.message="Deferred has already fired";Gd.prototype.name="AlreadyCalledError";function Id(){if(this&&this.Ad){var a=this.Ad;a&&"SCRIPT"==a.tagName&&Jd(a,k,this.Qa)}}function Jd(a,b,c){c!=l&&s.clearTimeout(c);a.onload=ba;a.onerror=ba;a.onreadystatechange=ba;b&&window.setTimeout(function(){yc(a)},0)}function Kd(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);Qa.call(this,c);this.code=a}A(Kd,Qa);function Ld(a){this.L={id:0,Xb:l,name:l,Je:0,pe:n,ce:0};Xa(this.L,a);this.vd=0}Ld.prototype.ic=function(){return this.L.id};Ld.prototype.bd=function(){return t(this.L.Xb)?this.L.Xb:n};Ld.prototype.toString=function(){var a=this.bd(),b=this.ic();(!t(a)||!a)&&f(Error("storm need wid"));(!t(b)||!b)&&f(Error("storm need id"));var c=["storm://"],d=[];c.push(9<a?a:"0"+a);c.push(this.vd);c.push("0000");c.push(b);d.push(c.join(""));return d.join("||")};
function Md(a){Ld.call(this,{id:a.vid,name:a.vname,Je:a.update_time,pe:a.ispay,ce:a.dzone,We:a.flash});this.vd=1;this.De(a)}A(Md,Ld);Md.prototype.De=function(a){t(a.v_sub_title)&&(this.L.cf=a.v_sub_title);t(a.video_time)&&(this.L.time=a.video_time);t(a.location)&&(this.L.location=a.location);t(a.publish_date)&&(this.L.af=a.publish_date);this.L.Xb="wid"in a?a.wid:0};Md.prototype.Zc=function(){var a=this.L.Nd;return a?a:0};function Nd(a,b){function c(a){e.push(a)}var d={id:a,format:b},e=[],g=new sb,h=["Consultation/web.php"],m;for(m in h)c.call(j,h[m]);Sa(d,function(a,b){g.set(b,a)});g.set("_random","false");return new Bb(e.join("/"),g)};function Od(a,b){this.Ke=new mb(a);this.Td=b?b:"callback";this.Qa=5E3}var Pd=0;
Od.prototype.send=function(a,b,c,d){var e=a||l,g=d||"_"+(Pd++).toString(36)+la().toString(36);s._callbacks_||(s._callbacks_={});a=this.Ke.O();if(e)for(var h in e)(!e.hasOwnProperty||e.hasOwnProperty(h))&&zb(a,h,e[h]);b&&(s._callbacks_[g]=function(a){Qd(g,k);b.apply(j,arguments)},zb(a,this.Td,"_callbacks_."+g));var m=a.toString(),q={timeout:this.Qa,Vd:k};h=q.document||document;var w=document.createElement("SCRIPT");a={Ad:w,Qa:j};var r=new Cd(Id,a),B=l;d=q.timeout!=l?q.timeout:5E3;0<d&&(B=window.setTimeout(function(){Jd(w,
k);var a=new Kd(1,"Timeout reached for loading script "+m);Fd(r);Dd(r,n,a)},d),a.Qa=B);w.onload=w.onreadystatechange=function(){if(!w.readyState||"loaded"==w.readyState||"complete"==w.readyState)Jd(w,q.Vd||n,B),Fd(r),Dd(r,k,l)};w.onerror=function(){Jd(w,k,B);var a=new Kd(0,"Error while loading script "+m);Fd(r);Dd(r,n,a)};tc(w,{type:"text/javascript",charset:"UTF-8",src:m});a=h.getElementsByTagName("HEAD");(!a||0==a.length?h.documentElement:a[0]).appendChild(w);r.Pa.push([l,function(){Qd(g,n);c&&
c(e)},j]);r.Ha&&Ed(r);return{S:g,Zd:r}};function Qd(a,b){s._callbacks_[a]&&(b?delete s._callbacks_[a]:s._callbacks_[a]=ba)};/*
 {@link www.baofeng.com}
*/
function Rd(){this.l={Mc:"Event_Billing",OPEN:"Event_Open",Kd:"Event_Complete",rb:"Event_Error"};this.oc=n;this.ub="";this.Xc="json";this.height=this.width=0;this.n;this.Oe=l}A(Rd,V);Rd.TIMEOUT=8E3;p=Rd.prototype;
p.Od=function(a){this.oc=a.url?k:n;this.dispatchEvent({type:this.l.Mc,target:this});if(this.oc){var b=document.createElement("iframe");b.width=this.width;b.height=this.height;b.scrolling="no";b.frameBorder="no";b.align="center";b.marginHeight="0";b.marginWidth="0";b.src=a.url;O(b,"load",function(){this.dispatchEvent({type:this.l.Kd})},n,this);this.n.appendChild(b)}};p.ad=function(){return this.Oe};p.error=function(a){this.dispatchEvent({type:this.l.rb,target:this,error:a})};
p.P=function(a){this.n=a;if(this.ub&&this.width&&this.height){var b=z(this.Od,this),c=z(this.error,this);a=Rd.TIMEOUT;var d=new Nd(this.ub,this.Xc),d=new Od(d),e=n;a&&(d.Qa=a);a=d.send(l,function(a){e=k;b(a)},function(){c("\u8bf7\u6c42\u540e\u7fbf\u7cfb\u7edf\u5f02\u5e38")});C&&(a=a.Zd,a.Pa.push([function(){e||c&&c("\u8bf7\u6c42\u540e\u7fbf\u7cfb\u7edf\u5f02\u5e38")},l,j]),a.Ha&&Ed(a));(new Image).src='http://log.houyi.baofeng.net/logger.php?ltype=wadaction&msg={"id":"'+this.ub+'","adpid":"2"}'}else this.error("\u4f20\u5165\u5e7f\u544a\u9700\u6c42\u53c2\u6570\u4e0d\u5b8c\u6574\u3002")};
p.q=function(){this.dispatchEvent({type:this.l.OPEN,target:this})};new function(){if((this.tb=s.ads)&&0<this.tb.length)for(var a=0,b=this.tb.length;a<b;a++){var c=this.tb[a],d=R(c.element);if(d){var e=new Rd,g=e,h=c.id,m=c.width,c=c.height;h&&(ea(m)&&ea(c))&&(g.width=m,g.height=c,g.ub=h);W(e,d);O(e,e.l.Mc,z(function(a,b){b.target.oc&&U(a,k)},this,d))}}};/*
 {@link www.baofeng.com}
*/
function Sd(){this.l={OPEN:"Event_Open",rb:"Event_Error"};this.jd=k;this.time=3E3;this.pd=1200;this.jb=2;this.wc="left";this.Ka="width";this.za="offsetLeft";this.rd="offsetWidth";this.fa=l;this.ka=0;this.j=this.i=this.ja=l;this.Jb="left_scroll";this.Qb="right_scroll";this.hb="mic-video-little";this.Ia=k;this.mb=this.xa=this.Ra=l;this.xb="items";this.gb=k;this.n=this.w=this.b=this.df=l;this.kb=0;this.show=6;this.W=new kd}A(Sd,V);p=Sd.prototype;
p.D=function(a){var b=Lc(a);a=Nc(a);b.height+=a.top+a.bottom;b.width+=a.left+a.right;return b};
p.wa=function(a){var b=0;a=a.gc||a.currentTarget;if(this.W.e==Y){this.Ia&&(clearTimeout(this.Ra),this.Ca());switch(a){case this.i:if(this.gb==k)0<=this.b[this.za]&&(this.b.style[this.wc]=-this.kb/2+"px");else if(0<this.b[this.za])return;b=this.ka;break;case this.j:if(this.gb==k)this.b[this.za]<=-this.kb/2&&(this.b.style[this.wc]="0px");else if(this.kb+this.b[this.za]-this.w[this.rd]<this.fa[this.Ka])return;b=-this.ka}this.W.g();this.W.add(new gd(this.b,[this.b[this.za],0],[this.b[this.za]+b,0],this.pd,
vd));this.W.play()}};p.fb=function(a){"mouseover"==a.type&&this.C(a,this.w)?window.clearTimeout(this.Ra):"mouseout"==a.type&&this.C(a,this.w)&&this.Ca()};p.C=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement;else if("mouseout"==c)c=a.relatedTarget||a.toElement;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};p.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};
p.Ca=function(){var a=this;this.Ra=setTimeout(function(){a.dispatchEvent({type:"click",gc:a.j})},this.time)};
p.P=function(a){var b=0;this.n=a;this.b=T(this.xb,this.n);this.w=this.b.parentNode;this.i=T(this.Jb,this.n);this.j=T(this.Qb,this.n);b=this.b.children.length;0!=b%this.jb&&(this.jb=1);b>this.jb?("top"==this.wc&&(this.Ka="height",this.za="offsetTop",this.rd="offsetHeight"),this.gb==k&&(this.b.innerHTML+=this.b.innerHTML),this.xa=this.b.children,this.mb=this.xa[0],this.fa=this.D(this.mb),0==this.fa[this.Ka]&&(this.fa=this.D(this.ja)),this.kb=this.xa.length*this.fa[this.Ka],this.b.style[this.Ka]=this.kb+
"px",this.ka=this.fa[this.Ka]*this.jb):this.jd=n;this.gb==n&&(b<=this.show?(this.i.style.display="none",this.j.style.display="none",this.hb&&Q(this.w,this.hb)):(this.i.style.display="block",this.j.style.display="block"))};
p.q=function(){this.jd?(this.i&&this.j&&(O(this.i,"click",z(this.wa,this)),O(this.j,"click",z(this.wa,this))),this.b&&(O(this.w,"mouseout",z(this.fb,this)),O(this.w,"mouseover",z(this.fb,this))),this.Ia&&(O(this,"click",z(this.wa,this)),this.Ca())):this.dispatchEvent({type:this.l.rb,target:this,error:"\u6eda\u52a8\u5bf9\u8c61\u4e0d\u662f\u79fb\u52a8\u5bf9\u8c61\u7684\u6574\u6570\u500d\uff0c\u65e0\u6cd5\u65e0\u7f1d\u6eda\u52a8\u3002"})};/*
 {@link www.baofeng.com}
*/
function Ud(){this.Ce="data-qusrc";this.fe="data-ersrc";this.se="data-level";this.ye="data-none";this.Ja=[];this.Uc=[];this.pc=n;this.Ed=l;this.index=0;this.ia=200;this.oe=this.me=n;this.Ee="http://box.bfimg.com";this.md=0;this.exp=RegExp(this.Ee);this.va={Oc:"queue",Yb:"erup",Ta:"switch"};this.Le=["http://box1.bfimg.com","http://box2.bfimg.com","http://box3.bfimg.com","http://box4.bfimg.com","http://box5.bfimg.com"]}A(Ud,V);p=Ud.prototype;p.start=function(){W(this,document)};
p.wb=function(){for(var a=Vd(),b=a.y+a.height,c=l,d=[],e=this.Ja.length-1;-1<e;e--)if(c=this.Ja[e],c.top<=b&&c.top+c.height>=a.y)switch(c.type){case this.va.Yb:this.Ja.splice(e,1);c.re?(this.pc=k,c.ya.src=c.src):d.push(c);break;case this.va.Oc:this.Ja.splice(e,1);Wd(this,c.ya);break;case this.va.Ta:c.mc||(c.mc=k)}else c.mc&&c.type==this.va.Ta&&(c.mc=n,c.Ye.ea.push(j));d.length&&(this.pc?(this.Uc.push(d),this.pc=n,setTimeout(z(this.nd,this),1E3)):this.nd(d))};
p.nd=function(a){a=a||this.Uc.shift();for(var b=l,c=0,d=a.length;c<d;c++)b=a[c],b.ya.onerror=function(){this.src=b.url;this.onerror=l;C&&(this.onreadystatechange=l);this.onload=l},C?b.ya.onreadystatechange=function(){if("complete"==this.readyState||"loaded"==this.readyState)this.onreadystatechange=this.onerror=l}:b.ya.onload=function(){this.onload=this.onerror=l},b.ya.src=b.src;a.length=0;a=l};
function Wd(a,b){var c=new qd,d=Xd(a,a.va.Oc,a.Ce,b);O(c,"complete",function(){for(var a in d)d[a].ya.src=d[a].src;c.g();Zb(c,"complete");Zb(c,"error");d.length=0;c=d=l});O(c,"error",function(a){d.splice(a.target.id,1)});for(var e in d){var g=d[e].src;(g=x(g)?g:g.src)&&(c.eb[e]=g)}c.start()}p.Bd=function(a){var b;this.me?(clearTimeout(this.Ed),this.Ed=setTimeout(z(this.wb,this),this.ia)):(b=Vd().y,"scroll"==a.type&&50>=Math.abs(b-this.md)||(this.md=b,this.wb()))};
p.ae=function(a){a=Xd(this,this.va.Yb,this.ye,a.element);Array.prototype.push.apply(this.Ja,a);this.wb()};p.D=function(a){var b=a.getBoundingClientRect(),c=Lc(a),d=a.ownerDocument;a=d.body;var e=d.documentElement,d=b.top+(self.pageYOffset||e.scrollTop||a.scrollTop)-(e.clientTop||a.clientTop||0),b=b.left+(self.pageXOffset||e.scrollLeft||a.scrollLeft)-(e.clientLeft||a.clientLeft||0);return{top:0>d?0:d,left:b,width:c.width,height:c.height}};
function Vd(){var a=vc(document),b;b=window.document;b="CSS1Compat"==b.compatMode?b.documentElement:b.body;b=new hc(b.clientWidth,b.clientHeight);return{x:a.x,y:a.y,width:b.width,height:b.height}}function Xd(a,b,c,d){var e=[],g=l,h=l,m=l,q=l,w=l;d=d||document;d=S("img",l,d);for(var r=0,B=d.length;r<B;r++)m=d[r],w=m.getAttribute("src"),g=m.getAttribute(c),q=m.getAttribute(a.se),g&&(a.oe&&(g=Yd(a,g)),h=a.D(d[r]),h.src=g,h.url=w,h.ya=m,h.re=q,h.type=b,e.push(h));return e}
function Yd(a,b){a.index++;return b.replace(a.exp,function(){return a.Le[a.index%5]})}p.P=function(a){a=Xd(this,this.va.Yb,this.fe,a);Array.prototype.push.apply(this.Ja,a);this.wb()};p.q=function(){O(s,"scroll",z(this.Bd,this));O(s,"resize",z(this.Bd,this));O(P,"Add_Display",z(this.ae,this))};function Zd(){};function $d(){}A($d,Zd);$d.prototype.clear=function(){var a;a=this.Ua(k);if(v(a))a=db(a);else{a=hb(a);var b=[],c=function(a){b.push(a)};if(v(a))try{H(a,c,j)}catch(d){d!==fb&&f(d)}else{a=hb(a);try{for(;;)c.call(j,a.next())}catch(e){e!==fb&&f(e)}}a=b}var g=this;H(a,function(a){g.remove(a)})};function ae(a){this.I=a}A(ae,$d);p=ae.prototype;p.set=function(a,b){try{this.I.setItem(a,b)}catch(c){0==this.I.length&&f("Storage mechanism: Storage disabled"),f("Storage mechanism: Quota exceeded")}};p.get=function(a){a=this.I.getItem(a);!x(a)&&a!==l&&f("Storage mechanism: Invalid value was encountered");return a};p.remove=function(a){this.I.removeItem(a)};
p.Ua=function(a){var b=0,c=this.I,d=new gb;d.next=function(){b>=c.length&&f(fb);var d=c.key(b++);if(a)return d;d=c.getItem(d);x(d)||f("Storage mechanism: Invalid value was encountered");return d};return d};p.clear=function(){this.I.clear()};p.key=function(a){return this.I.key(a)};function be(){var a=l;try{a=window.localStorage||l}catch(b){}this.I=a}A(be,ae);function ce(){var a=l;try{a=window.sessionStorage||l}catch(b){}this.I=a}A(ce,ae);function de(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}f(Error("Invalid JSON string: "+a))}function ee(a){return fe(new ge(j),a)}function ge(a){this.Sb=a}function fe(a,b){var c=[];he(a,b,c);return c.join("")}
function he(a,b,c){switch(typeof b){case "string":ie(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if(u(b)){var d=b.length;c.push("[");for(var e="",g=0;g<d;g++)c.push(e),e=b[g],he(a,a.Sb?a.Sb.call(b,String(g),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(e=b[g],"function"!=typeof e&&(c.push(d),ie(g,c),c.push(":"),
he(a,a.Sb?a.Sb.call(b,g,e):e,c),d=","));c.push("}");break;case "function":break;default:f(Error("Unknown type: "+typeof b))}}var je={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},ke=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function ie(a,b){b.push('"',a.replace(ke,function(a){if(a in je)return je[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return je[a]=e+b.toString(16)}),'"')};function le(a){this.ib=a;this.Cd=new ge}p=le.prototype;p.ib=l;p.Cd=l;p.set=function(a,b){t(b)?this.ib.set(a,fe(this.Cd,b)):this.ib.remove(a)};p.get=function(a){a=this.ib.get(a);if(a!==l)try{return de(a)}catch(b){f("Storage: Invalid value was encountered")}};p.remove=function(a){this.ib.remove(a)};function me(a){le.call(this,a)}A(me,le);function ne(a){this.data=a}me.prototype.set=function(a,b){me.r.set.call(this,a,!t(b)||b instanceof ne?b:new ne(b))};me.prototype.get=function(a){var b;a=me.r.get.call(this,a);!t(a)||a instanceof Object?b=a:f("Storage: Invalid value was encountered");b?(b=b.data,t(b)||f("Storage: Invalid value was encountered")):b=j;return b};function oe(a){if(pe)return pe;a=a?new ce:new be;this.cookie=new Fb(s.document);var b;if(a.I)try{a.I.setItem("__sak","1"),a.I.removeItem("__sak"),b=k}catch(c){b=n}else b=n;b?(this.Y=new me(a),this.nc=k):this.Y=this.cookie;pe=this}var pe;oe.prototype.set=function(a,b){a&&this.Y.set.apply(this.Y,eb(arguments,0))};oe.prototype.get=function(a){if(a)return this.Y.get.apply(this.Y,eb(arguments,0))};
oe.prototype.clear=function(){this.nc&&this.Y.remove.apply(this.Y,eb(arguments,0));this.cookie.set.apply(this.cookie,eb(arguments,0))};oe.prototype.remove=function(a){a&&this.Y.remove.apply(this.Y,eb(arguments,0))};function qe(a){this.uc=a||15;this.key="bfViewRecords";this.T=7776E3;this.path="/";this.domain=".baofeng.com";this.k=pe?pe:new oe(j);if(this.k.nc){a=0;for(var b=re(this.k.cookie.get(this.key));a<b.length;a++)this.add(b[a])}}ca(qe);function se(a){var b="",c;for(c in a)b+=c+"="+encodeURIComponent(a[c])+"&";return b=b.substring(0,b.length-1)}p=qe.prototype;p.list=function(){return re(this.k.get(this.key))};p.$=function(){return this.k.get(this.key)};
p.map=function(){for(var a=this.list(),b={},c=0,d=a.length;c<d;c++)b[a[c].id]=a[c];return b};function re(a){var b=[];a=a||"";if(0===a.length)return b;a=a.split(",");for(var c=0,d=a.length;c<d;c++){for(var e={},g=a[c].split("&"),h=0,m=g.length;h<m;h++){var q=g[h].split("=");e[q[0]]=2==q.length?decodeURIComponent(q[1]):l}b.push(e)}return b}p.jc=function(a){for(var b=0,c=this.list();b<c.length;b++)if(c[b].id==a)return c[b];return l};
p.add=function(a){for(var b=this.list(),c="",d=n,e=0,g=b.length;e<g;e++)b[e].id==a.id?d=k:c+=se(b[e])+",";b.length>=this.uc&&d===n&&(c=c.substring(c.indexOf(",")+1));c+=se(a);this.k.set(this.key,c,this.T,this.path,this.domain);d||this.s("Event_Record","ADD",a.id)};p.hc=function(a){for(var b=this.list(),c=n,d="",e=0,g=b.length;e<g;e++)b[e].id==a?c=k:d+=se(b[e])+",";c&&(d=d.substr(0,d.length-1),this.k.set(this.key,d,this.T,this.path,this.domain),this.s("Event_Record","DEL",a))};
p.remove=function(){this.k.clear(this.key,"",this.T,this.path,this.domain)};p.clear=function(){this.k.clear(this.key,"",this.T,this.path,this.domain);this.s("Event_Record","DEL","")};p.s=function(a,b,c){P.dispatchEvent({type:a,kind:b,id:c})};function te(a,b){this.anchor=a;this.o=b;this.$b="expd";this.oa=[]}A(te,V);p=te.prototype;p.Bc=aa("anchor");p.sb=function(a){this.oa.push(a)};p.q=function(){O(this.anchor,"mouseover",z(this.show,this,k));O(this.anchor,"mouseout",z(this.t,this,50));O(this.o,"mouseover",z(this.show,this));O(this.o,"mouseout",z(this.t,this,50))};p.show=function(){this.h&&(clearTimeout(this.h),this.h=l);for(var a=0,b=this.oa.length;a<b;a++)U(this.oa[a],n);U(this.o,k);Q(this.anchor,this.$b)};
p.t=function(a){this.h&&(clearTimeout(this.h),this.h=l);a&&0<a?this.h=setTimeout(z(this.t,this),a):(U(this.o,n),lc(this.anchor,this.$b))};var ec={active:{name:"\u64ad\u653e\u63a7\u4ef6\u76f8\u5173",infor:"\u6709\u7f51\u9875\u64ad\u653e\u7ec4\u4ef6 \u65e0\u7f51\u9875\u64ad\u653e\u7ec4\u4ef6 \u6709\u5c0f\u5305 \u65e0\u5c0f\u5305 \u7406\u8bba\u5f39\u51fa\u9ec4\u6761\u6570 \u4e2d\u5305\u5c1d\u8bd5\u4e0b\u8f7d \u4e2d\u5305\u5f00\u59cb\u4e0b\u8f7d \u4e2d\u5305\u4e0b\u8f7d\u5931\u8d25 \u4e2d\u5305\u4e0b\u8f7d\u6210\u529f \u4e2d\u5305\u5b89\u88c5\u6210\u529f \u4e2d\u5305\u5b89\u88c5\u5931\u8d25 \u64ad\u653e\u5668\u4e0b\u65b9\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570clickonce\u4e0b\u8f7d \u64ad\u653e\u5668\u4e2d\u592e\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570clickonce\u4e0b\u8f7d \u64ad\u653e\u5668\u5e95\u90e8\u6587\u5b57\u94fe\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570clickonce\u4e0b\u8f7d \u975eie\u64ad\u653e\u5668\u4e0b\u65b9\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570 \u975eIE\u64ad\u653e\u5668\u5e95\u90e8\u6587\u5b57\u94fe\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570 \u64ad\u653e\u5668\u4e0b\u65b9\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570GUI\u4e0b\u8f7d \u64ad\u653e\u5668\u4e2d\u592e\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570GUI\u4e0b\u8f7d \u64ad\u653e\u5668\u5e95\u90e8\u6587\u5b57\u94fe\u4e00\u952e\u5b89\u88c5\u70b9\u51fb\u6570GUI\u4e0b\u8f7d".split(" "),
bfinfo:[{pagesstate:1},{pagesstate:2},{lbstate:1},{lbstate:2},{yellowpop:1},{mbtry:1},{mbbegin:1},{mbfail:1,value:1},{mbsuccess:1},{mbsetup:1},{mbsetup:1,value:1},{linkdownload:2},{setupdownload:2},{linkdownload:2},l,l,{linkdownload:1},{setupdownload:1},{linkdownload:1}]},webplayer:{name:"\u64ad\u653e\u76f8\u5173",infor:"onPlayerOpen onPlayerPlay onPlayerPause OnPlayerPlayStart onPlayerFinish onPlayerOpenFail onPlayerClose onPlayerStop".split(" ")},flashplayer:{name:"flash\u64ad\u653e\u76f8\u5173",
infor:"\u5f00\u59cb\u64ad\u653eclickonce\u4e0b\u8f7d \u5c1d\u8bd5\u64ad\u653e \u64ad\u653e\u6210\u529f \u7f13\u51b2\u65f6\u95f4 \u9519\u8bef \u64ad\u653e\u6682\u505c \u5931\u8d25FLASH\u7684\u4e0b\u8f7d\u6309\u94aeclickonce\u4e0b\u8f7d \u64ad\u653e\u5b8c\u6210 flash\u52a0\u8f7d\u8d85\u65f6\u5931\u8d25 flash\u52a0\u8f7d\u8d85\u65f6\u5931\u8d25 \u5931\u8d25FLASH\u7684\u4e0b\u8f7d\u6309\u94aeGUI\u4e0b\u8f7d \u5f00\u59cb\u64ad\u653eGUI\u4e0b\u8f7d \u89c6\u9891cid \u7248\u672c\u53f7 flash\u89c2\u770b\u65f6\u957f \u5361\u987f\u6b21\u6570 flash\u64ad\u653e\u5668\u7248\u672c\u53f7".split(" "),
bfinfo:[{playdownload:2},{flshtry:1},{flashsuccess:1,key:"flashsuccess"},{flashloadtime:1,key:"flashloadtime"},{flasherr:1,key:"flasherr"},l,{faildownload:2},l,l,l,{faildownload:1},{playdownload:1},{flashiid:1,key:"flashiid"},{flashver:1,key:"flashver"},{flashtime:1,key:"flashtime"},{flashbuffrtempty:1,key:"flashbuffrtempty"}]},houyi:{name:"\u540e\u7fbf\u5e7f\u544a",infor:"\u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u603b\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u6210\u529f \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u5931\u8d25 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u6210\u529f\u6709\u5e7f\u544a \u64ad\u653e\u5668\u53f3\u4fa7\u5e7f\u544a\u88ab\u52a8\u5c55\u73b0\u6b21\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u5e7f\u544a\u4e3b\u52a8\u5c55\u73b0\u6b21\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u5c1d\u8bd5\u8bf7\u6c42\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u540e\u7fbf\u8bf7\u6c42\u6210\u529f\u65e0\u5e7f\u544aURL".split(" "),
bfinfo:[l,{hyrequest:1},l,{hyadrequest:1},{addisplay:2},{addisplay:1},l,{hyadrequest:0,value:0}]},b3:{name:"B3\u5224\u65ad",infor:"B3\u5c1d\u8bd5\u8bf7\u6c42\u603b\u6570 B3\u8bf7\u6c42\u6210\u529f\u6570 B3\u8bf7\u6c42\u5931\u8d25\u6570 B3\u5224\u65ad\u6b63\u7247\u53ef\u64ad B3\u5224\u65ad\u6b63\u7247\u4e0d\u53ef\u64ad\u64ad\u7247\u82b1 \u64ad\u653e\u9884\u544a\u7247 B3\u5224\u65ad\u5f71\u7247\u8d44\u6e90\u4e0d\u5b58\u5728".split(" "),bfinfo:[{b3request:1,value:0},{b3state:1,value:0},{b3state:2,value:0},
{b3judge:1,value:0},{b3judge:2,value:0},l,{b3fail:1,value:0}]},noIE:{name:"\u975eIE\u6d4f\u89c8\u5668",infor:["\u4f7f\u7528ie\u6d4f\u89c8\u5668\u6dfb\u52a0\u6536\u85cf","\u4f7f\u7528\u975eie\u6d4f\u89c8\u5668\u6dfb\u52a0\u6536\u85cf","IE\u6d4f\u89c8\u5668","\u975eIE\u6d4f\u89c8\u5668"],bfinfo:[{exfav:0},{exfav:1}]},other:{name:"\u76f8\u5173\u63a5\u53e3",infor:"\u8bc4\u8bba\u8bf7\u6c42\u603b\u6570 \u8bc4\u8bba\u6210\u529f\u5c55\u73b0\u6570 \u8bc4\u8bba\u8bf7\u6c42\u5931\u8d25\u6570 MINFO\u8bf7\u6c42\u603b\u6570 MINFO\u8bf7\u6c42\u6210\u529f MINFO\u8bf7\u6c42\u5931\u8d25".split(" "),
bfinfo:[{comrequest:1},{comstate:1},{comstate:2},{minforequest:1},{minfostate:1},{minfostate:2}]},buttonClick:{name:"\u6309\u94ae\u70b9\u51fb",infor:"\u89c2\u770b\u8bb0\u5f55\u6d6e\u5c42\u5c55\u73b0\u6b21\u6570 \u89c2\u770b\u8bb0\u5f55\u70b9\u51fb\u6570 \u6dfb\u52a0\u5feb\u6377\u65b9\u5f0f\u6309\u94ae\u70b9\u51fb\u6570 \u5267\u96c6\u6309\u94ae\u70b9\u51fb\u6570 \u5267\u96c6\u533a\u95f4\u70b9\u51fb\u6570 \u5267\u96c6\u683c\u5f0f\u5207\u6362\u70b9\u51fb\u6570 \u5267\u96c6\u5c55\u5f00\u70b9\u51fb\u6570 \u5267\u96c6\u6536\u8d77\u70b9\u51fb\u6570 \u64ad\u653e\u5668\u4e0b\u65b9\u76f8\u5173\u63a8\u8350\u70b9\u51fb\u6570 \u64ad\u653e\u5668\u53f3\u4fa7\u76f8\u5173\u63a8\u8350\u70b9\u51fb\u6570".split(" ")},
tyg:{name:"\u4f53\u9a8c\u9986",infor:["\u4f53\u9a8c\u99863D\u5f71\u7247\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570","\u4f53\u9a8c\u9986\u5de6\u773c\u5f71\u7247\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570","\u4f53\u9a8c\u9986\u5b89\u88c5\u66b4\u98ce\u7ec4\u4ef6\u70b9\u51fb\u6570clickOnce","\u4f53\u9a8c\u9986\u540e\u64ad\u63a8\u8350\u70b9\u51fb\u6570","\u4f53\u9a8c\u9986\u5b89\u88c5\u66b4\u98ce\u7ec4\u4ef6\u70b9\u51fb\u6570GUI"],bfinfo:[l,l,{testsetup:2},l,{testsetup:1}]},jizhi:{name:"\u6781\u81f4\u529f\u80fd\u6309\u94ae\u4f7f\u7528",
infor:["3D\u6309\u94ae\u70b9\u51fb\u6570","\u5de6\u773c\u6309\u94ae\u70b9\u51fb\u6570","\u53f3\u8033\u6309\u94ae\u70b9\u51fb\u6570","IE\u4e0d\u652f\u6301\u6781\u81f4\u529f\u80fd","\u975eIE\u4e0d\u652f\u6301\u6781\u81f4\u529f\u80fd"],bfinfo:[{acmestate:1},{acmestate:2},{acmestate:3},{acmestate:4},{acmestate:5}]},search:{name:"\u641c\u7d22\u76f8\u5173\u62a5\u6570",infor:["\u70b9\u51fb\u641c\u7d22\u6309\u94ae","\u5c1d\u8bd5\u641c\u7d22"],bfinfo:[{tsearch:1},{tsearch:1}]},detail:{name:"\u8be6\u60c5\u9875\u76f8\u5173\u6570",
infor:["\u8be6\u60c5\u9875\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570","\u8be6\u60c5\u9875\u5408\u4f5c\u65b9\u89c6\u9891\u64ad\u653e\u6309\u94ae\u70b9\u51fb\u6570"],bfinfo:[{playstate:1},{playstate:2}]},movie:{name:"\u5f71\u7247\u64ad\u653e",infor:["\u901a\u8fc7\u5ba2\u6237\u7aef\u64ad\u653e","\u901a\u8fc7\u7f51\u9875\u64ad\u653e"],bfinfo:[{playstate:2},{playstate:1}]},micvideo:{name:"\u5fae\u89c6\u9891\u9996\u9875",infor:["\u4eca\u65e5\u5173\u6ce8","\u5a31\u4e50\u661f\u95fb","\u7f51\u7edc\u70ed\u8bae",
"\u5c4c\u4e1d\u5b85\u7537","\u7206\u7b11\u63a8\u8350"],bfinfo:[{"\u4eca\u65e5\u5173\u6ce8":2},{"\u5a31\u4e50\u661f\u95fb":2},{"\u7f51\u7edc\u70ed\u8bae":2},{"\u5c4c\u4e1d\u5b85\u7537":2},{"\u7206\u7b11\u63a8\u8350":2}]},baiduvip:{name:"\u767e\u5ea6VIP",infor:["\u767e\u5ea6VIP\u7528\u6237"],bfinfo:[{baiduvip:1}]}};function ue(){this.oa=[]}A(ue,V);p=ue.prototype;p.Bc=aa("anchor");p.sb=function(a){this.oa.push(a)};p.P=function(a){this.o=a;this.ke=T("innerBox",this.o);this.od=T("menuHolder",this.ke);this.cd=S("iframe",j,this.od)[0];this.Fb=T("frame",this.od);this.Wd=T("empty",this.Fb);this.Nb=T("his-none",this.Fb);this.Kb=T("his-cont",this.Fb);this.list=S("ul",j,this.Fb)[0]};
p.q=function(){O(this.o,"mouseover",z(this.show,this));O(this.o,"mouseout",z(this.t,this,50));O(this.anchor,"mouseover",z(this.show,this,k));O(this.anchor,"mouseout",z(this.t,this,50));O(this.Wd,"click",z(this.clear,this));O(this.list,"click",z(this.ie,this))};p.log=function(a,b,c){P.dispatchEvent({type:"log",data:{key:a,value:b,other:c}})};
p.show=function(a){this.h?(clearTimeout(this.h),this.h=l):this.log("buttonClick",1);for(var b=0,c=this.oa.length;b<c;b++)U(this.oa[0],n);U(this.o,k);Q(this.anchor,"expd");if(a===k)if(a=this.Sa.list().reverse(),0>=a.length)U(this.Nb,k),U(this.Kb,n);else{U(this.Nb,n);U(this.Kb,k);var d="",e=0,g=a.length;for(template='<li  id="${recordId}"><a title=${title} class="his-reco">${recordName}</a><a class="continueButton">\u7ee7\u7eed\u89c2\u770b</a><span class="closed"></span></li>';e<g;e++){b=a[e];c=b.name;
recordId=b.id;if(!b.type||!("5"===b.type||"1"===b.type))"undefined"!==typeof b.loc&&"null"!=b.loc?c+=" \u7b2c"+b.loc+"\u671f":"undefined"!==typeof b.drama&&"null"!=b.drama&&(c+=" \u7b2c"+b.drama+"\u96c6");d+=template.replace("${title}",c).replace("${recordName}",c).replace("${recordId}","record-"+recordId)}this.list.innerHTML=d;this.bc()}};p.bb=function(a){console.log(a.target)};p.t=function(a){a&&0<a?this.h=setTimeout(z(this.t,this),a):(U(this.o,n),lc(this.anchor,"expd"))};
p.bc=function(){for(var a=0,b=this.list.children.length;a<b;a++){var c=this.list.children[a];O(c,"mouseover",z(this.Wa,this));O(c,"mouseout",z(this.Wa,this))}};p.Wa=function(a){var b=a.currentTarget;"mouseover"==a.type&&this.C(a,b)?b.className="cur":"mouseout"==a.type&&this.C(a,b)&&(b.className="")};
p.C=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement||k;else if("mouseout"==c)c=a.relatedTarget||a.toElement||k;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};p.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};
p.ie=function(a){a.preventDefault();a=a.target;var b;if("continueButton"===a.className||"his-reco"===a.className){b=this.Sa.jc(a.parentNode.id.split("-")[1]);var c="/play/"+b.id%500+"/play-"+b.id;"5"===(b.type||"-1")?(c="",b.wid&&"13"!=b.wid&&(c="-"+b.wid),c="/micv/"+b.id%500+"/micv-"+b.id+c+"-vid-"+b.vid+".html"):("undefined"!==typeof b.drama&&"null"!=b.drama&&(c+="-drama-"+b.drama),"undefined"!==typeof b.format&&"null"!=b.format&&(c+="-format-"+b.format),"undefined"!==typeof b.trailer&&"null"!=
b.trailer&&(c+="-trailer-"+b.trailer),c+=".html");b=c;U(this.o,n);s.open(b,"_blank");this.log("buttonClick",2)}"closed"==a.className&&(b=this.Sa.jc(a.parentNode.id.split("-")[1]),(b=b.id)&&this.Sa.hc(b),0==this.Sa.list().length&&(U(this.Kb,n),U(this.Nb,k)),a.parentNode.parentNode.removeChild(a.parentNode))};p.clear=function(){this.Sa.clear();U(this.Kb,n);U(this.Nb,k)};function ve(a){a=a||{};var b=this.m={Bb:"hd-load-text-on",ia:50},c;for(c in a)b[c]=a[c];(!this.m.anchor||!this.m.content)&&this.dispatchEvent({type:"error",message:"hd.component.Popup params must contains anchor and content"})}A(ve,V);
ve.prototype.q=function(){try{O(this.m.anchor,"mouseover",this.show,n,this),O(this.m.anchor,"mouseout",z(this.t,this,this.m.ia)),O(this.m.content,"mouseover",this.show,n,this),O(this.m.content,"mouseout",z(this.t,this,this.m.ia))}catch(a){this.dispatchEvent({type:"error",message:"enterDocument method error"})}};ve.prototype.show=function(){this.h&&(clearTimeout(this.h),this.h=l);this.m.Bb&&Q(this.m.anchor,this.m.Bb);U(this.m.content,k);this.dispatchEvent("show")};
ve.prototype.t=function(a){this.h&&(clearTimeout(this.h),this.h=l);a&&0<a?this.h=setTimeout(z(this.t,this),a):(this.m.Bb&&lc(this.m.anchor,this.m.Bb),U(this.m.content,n),this.dispatchEvent("hide"))};function we(a,b){P.dispatchEvent({type:"log",data:{key:"movie",value:a,other:b}})};function xe(){this.Ub="\u8bf7\u8f93\u5165\u5f71\u7247\u540d\u3001\u5173\u952e\u5b57";this.ld=s.static_keyword||""}A(xe,V);p=xe.prototype;p.P=function(a){this.o=a;this.form=S("form",j,this.o)[0];a=S("input",j,this.form);this.input=a[0];this.button=a[1];this.u=S("div",j,this.o)[1];this.cd=S("iframe",j,this.u)[0];this.Rb=S("div",j,this.u)[0]};p.log=function(a,b,c){P.dispatchEvent({type:"log",data:{key:a,value:b,other:c}})};
p.q=function(){var a=this;O(this.input,"mouseup",function(){a.log("search",2)});O(this.input,"focus",z(this.ge,this));O(this.input,"blur",z(this.Rd,this));O(this.input,"keyup",z(this.qe,this));O(this.button,"mouseover",function(){Q(this.button,"hover")},n,this);O(this.button,"mouseout",function(){lc(this.button,"hover")},n,this);O(this.button,"mousedown",function(){Q(this.button,"act")},n,this);O(this.button,"mouseup",function(){lc(this.button,"act")},n,this);O(this.button,"focus",function(){this.button.blur()},
n,this);O(this.form,"submit",function(){a.log("search",1);var b=T("selected",this.u);ye(this,b);setTimeout(z(function(){this.input.blur()},this),100)},n,this);O(this.u,"click",function(a){a=a.target;"A"===a.nodeName&&(U(this.u,n),ye(this,a))},n,this);var b=this.Ub;if(this.ld)b=this.ld;else{var c=[],d=T("hotWords",this.o);if(d){for(var d=zc(d),e=0,g=d.length;e<g;e++)c.push(Dc(d[e]));0<c.length&&(b=c[Math.floor(Math.random()*c.length)])}}this.Ub=b;this.input.value=this.Ub};
p.ge=function(){this.input.value="";Q(this.input,"focus");return n};p.Rd=function(){lc(this.input,"focus");""===this.input.value&&(this.input.value=this.Ub);setTimeout(z(function(){U(this.u,n);var a=this.Rb;if("textContent"in a)a.textContent="";else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=""}else{for(var b;b=a.firstChild;)a.removeChild(b);a.appendChild(rc(a).createTextNode(""))}},this),500)};
p.qe=function(a){a=a.keyCode;var b=this.input.value;if(0>=b.length)U(this.u,n);else if(("38"==a||"40"==a)&&"none"!=this.Rb.style.display){var c=zc(this.Rb),d=c.length;if(0<d)if("none"!=this.u.style.display===n)U(this.u,k);else{for(var e=-1,d=c.length,g=0;g<d;g++){var h=c[g];ab(kc(h),"selected")&&(e=g);lc(h,"selected")}e="38"==a?e-1:e+1;0>e&&(e=d-1);e>d-1&&(e=0);Q(c[e],"selected")}}else{var m=z(function(a){var c=this.input.value;if(c===b)if(0<c.length&&0<a.length){for(var c="",d=["\u7535\u5f71","\u7535\u89c6\u5267",
"\u52a8\u6f2b","\u7efc\u827a"],e=0,g=a.length;e<g;e++){var h=a[e],m=h.name,Lb="\u7535\u5f71",qa=parseInt(h.channel);isNaN(qa)===n&&(1<qa&&5>qa)&&(Lb=d[qa-1]);c+='<a href="javascript:void(0);" onclick="return false;">'+m+"<span>("+Lb+")</span></a>";if(0===e&&"\u7535\u5f71"!==Lb&&"undefined"!==typeof h.drama){var qa=h.id,Ke=h.wid,Le=h.aid,Me=h.vid,Td=h.drama;(h=h.sub_title)||(h=Td);c+='<a href="javascript:void(0);" onclick="return false;" class="search-suggest-detail"';c+=' m-id="'+qa+'"';c+=' m-wid="'+
Ke+'"';c+=' m-aId="'+Le+'"';c+=' m-vId="'+Me+'"';c+=' m-drama="'+Td+'"';c="\u7efc\u827a"===Lb?c+(">\u6700\u65b0\u4e00\u671f("+h+")</a>"):c+(">\u6700\u65b0\u4e00\u96c6("+h+")</a>");c+='<a href="javascript:void(0);" onclick="return false;" class="search-suggest-info" m-id="'+qa+'">'+m+"\u8be6\u60c5</a>";g=Math.min(g,6)}}0<c.length?(this.Rb.innerHTML=c,U(this.u,k),c=Jc(this.u).height,a=this.cd.style,"number"==typeof c&&(c=Math.round(c)+"px"),a.height=c):U(this.u,n)}else U(this.u,n)},this);a="http://search.hd.baofeng.com/prompt.php?query=${keyword}&start=0&limit=8".replace("${keyword}",
encodeURIComponent(b));a=new Od(a);a.Qa=8E3;a.send(l,function(a){a?m(a.results):m(l)},function(){m(l)})}};
function ye(a,b){if(b)if(ab(kc(b),"search-suggest-detail")){var c=b.getAttribute("m-id"),d=b.getAttribute("m-wid"),e=b.getAttribute("m-aid"),g=b.getAttribute("m-vid"),h=b.getAttribute("m-drama");if("13"==d){var m=c;we(2,m);m="/play/"+m%500+"/play-"+m;h&&(m+="-drama-"+h);s.open(m+".html","_blank")}else{h=new Md({id:g,Xb:d});h.L.Nd=Number(e);var q="";ga(h)?(we(1,h.bd()),q=h.toString(),h.Zc&&(h=h.Zc())&&0!==h&&(q+="||aid="+h)):q=h;h=function(){var a=document.createElement("iframe");U(a,n);tc(a,{src:q});
document.body.appendChild(a)};e=function(){alert("\u672c\u7247\u9700\u8981\u4f7f\u7528\u66b4\u98ce\u5ba2\u6237\u7aef\u64ad\u653e\uff0c\u5982\u679c\u60a8\u5df2\u5b89\u88c5\uff0c\u60a8\u5c06\u4f7f\u7528\u5ba2\u6237\u7aef\u64ad\u653e\uff0c\u5982\u679c\u6ca1\u6709\uff0c\u8bf7\u5230\u5b98\u7f51www.baofeng.com\u4e0b\u8f7d\u3002")};if(C)try{m=new ActiveXObject("StormAxPlayer.Player"),/8\d$/.test(m.Version)?e():setTimeout(h,100)}catch(w){e()}else setTimeout(h,100),setTimeout(e,200)}}else ab(kc(b),"search-suggest-info")?
(c=b.getAttribute("m-id"),s.open("/detail/"+c%500+"/detail-"+c+".html","_blank")):(m=Dc(b),m=m.substring(0,m.lastIndexOf("(")),a.search(m));else a.search()}p.search=function(a){"undefined"===typeof a&&(a=this.input.value);a=encodeURIComponent(na(a));if(0<a.length){U(this.u,n);var b="_blank";0<=s.location.href.indexOf("q_")&&(b="_self");s.open("/q_"+ud(a),b)}};/*
 {@link www.baofeng.com}
*/
function ze(){this.name=this.id=l;this.Za=0;this.title=this.G=this.element=l;this.Db="";this.ba=k;this.Vb=[" fv-add"," shadow-cut"];this.Cb=""}A(ze,V);p=ze.prototype;p.C=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement;else if("mouseout"==c)c=a.relatedTarget||a.toElement;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};p.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};
p.start=function(a){var b=this;this.element=a;this.G=T("fv-add-no",a);this.id=a.getAttribute("data-id");this.Cb=a.getAttribute("data-farther")||"";this.id&&this.G&&(this.Db=a.className.replace(/fv-cut|shadow-cut/gi,function(a){"fv-cut"==a&&(b.Vb[1]=" fv-cut");return""}),W(this,a))};
p.vc=function(a){var b;switch(a.type){case "mouseover":Ae(this,a.target,1);this.ba&&(this.ba=n,this.element.className=this.Db+this.Vb[0]);break;case "mouseout":Ae(this,a.target,0);!this.ba&&this.C(a,this.element)&&(this.ba=k,this.element.className=this.Db+this.Vb[1]);break;case "click":a=a.target,a==this.G?(this.Za?(a={type:"Event_Collect",kind:"DEL",id:this.id},b=0):(a={type:"Event_Collect",kind:"ADD",data:{id:this.id,name:this.name,element:this.G}},b=1),Be(this,b),this.dispatchEvent(a)):"IMG"==
a.tagName.toUpperCase()&&"A"==a.parentNode.tagName.toUpperCase()&&(this.ba=k,this.element.className=this.Db+this.Vb[1])}};function Ae(a,b,c){!a.Za&&b==a.G&&(a.G.className=c?"fv-add-Keep "+a.Cb:"fv-add-no")}function Be(a,b){a.Za=b;a.Za?(a.G.title="\u53d6\u6d88\u6536\u85cf",a.Cb&&(a.G.innerHTML="\u5df2\u6536\u85cf"),a.G.className="fv-add-Keep"):(a.G.title="\u6536\u85cf",a.Cb&&(a.G.innerHTML="\u6536\u85cf"),a.G.className="fv-add-no")}p.P=function(a){this.name=a.getAttribute("data-name")};
p.q=function(){O(this.element,"mouseout",z(this.vc,this));O(this.element,"mouseover",z(this.vc,this));O(this.element,"click",z(this.vc,this))};function Ce(a){this.uc=a||15;this.key="bfCollects";this.T=7776E3;this.path="/";this.domain=".baofeng.com";this.k=pe?pe:new oe(j);if(this.k.nc){var b=this.k.cookie.get(this.key)||"[]";a=0;for(b=de(b);a<b.length;a++)this.add(b[a])}}ca(Ce);p=Ce.prototype;p.list=function(){var a=this.k.get(this.key)||"[]";return de(a)};p.$=function(){return this.k.get(this.key)};p.map=function(){for(var a=this.list(),b={},c=0,d=a.length;c<d;c++)b[a[c].id]=a[c];return b};
p.jc=function(a){for(var b=0,c=this.list();b<c.length;b++)if(c[b].id==a)return c[b];return l};p.add=function(a){var b=this.list(),c=0;b.length>=this.uc&&(c=b.shift().id);b.push(a);this.k.set(this.key,ee(b),this.T,this.path,this.domain);return c};function De(a,b,c){for(var d=a.list(),e=n,g=0,h=d.length;g<h;g++)if(d[g].id==b){e=k;d[g].lb=c;break}e&&a.k.set(a.key,ee(d),a.T,a.path,a.domain)}
p.hc=function(a){for(var b=this.list(),c=n,d=0,e=b.length;d<e;d++)if(b[d].id==a){b.splice(d,1);c=k;break}c&&this.k.set(this.key,ee(b),this.T,this.path,this.domain)};p.clear=function(){this.k.clear(this.key,"",this.T,this.path,this.domain)};p.s=function(a,b,c){P.dispatchEvent({type:a,kind:b,id:c})};function Ee(a){a&&(this.ee=parseInt(this.D(a).left),this.Ve=parseInt(this.D(a).top))}Ee.prototype.fc=function(a,b,c){switch(arguments.length){case 2:if("object"==typeof b)for(var d in b)"opacity"==d?(a.style.filter="alpha(opacity="+b[d]+")",a.style[d]=b[d]/100):a.style[d]=b[d];else return a.currentStyle?a.currentStyle[b]:getComputedStyle(a,document)[b];break;case 3:"opacity"==b?(a.style.filter="alpha(opacity="+c+")",a.style[b]=c/100):a.style[b]=c}};
Ee.prototype.D=function(a){var b=a.getBoundingClientRect(),c=Lc(a),d=a.ownerDocument;a=d.body;var e=d.documentElement,d=b.top+(self.pageYOffset||e.scrollTop||a.scrollTop)-(e.clientTop||a.clientTop||0),b=b.left+(self.pageXOffset||e.scrollLeft||a.scrollLeft)-(e.clientLeft||a.clientLeft||0);return{top:0>d?0:d,left:b,width:c.width,height:c.height}};function $(){this.time=this.yd=this.Qc=l;this.U={};this.f=Ce.$a();this.Oa=qe.$a();Fe(this);this.dc=this.f.$();this.zc=this.Oa.$();this.Eb=wc("div",{id:"fly"});U(this.Eb,n);document.body.appendChild(this.Eb);this.Gd=R("viewFavoriteButton");this.s("Event_Collect","UP",this.f.list());this.Pd=new Ee(this.Gd)}A($,V);
$.prototype.Nc=function(a){switch(a.kind){case "ADD":U(this.Eb,k);var b=this.Pd,c=this.Eb,d=a.data.element,e=this.Gd,g=b.D(d).left,d=b.D(d).top,e=Math.max(parseInt(b.D(e).left),b.ee),h=document.documentElement.scrollTop||document.body.scrollTop,m=30/Math.tan(Math.atan2(h-d,e-g)),d=d-30;b.fc(c,"left",g-m+"px");b.fc(c,"top",d+"px");var q={left:e-m,top:h-30},w=function(){U(c,n)};clearInterval(c.h);var r=b.fc;c.h=setInterval(function(){var a=k,b,d;for(d in q){b="opacity"==d?100*parseFloat(r(c,d)):Math.round(parseInt(r(c,
d)));var e=(q[d]-b)/12,e=0<e?Math.ceil(e):Math.floor(e);"opacity"==d?r(c,d,b+e):r(c,d,b+e+"px");20<Math.abs(q[d]-b)&&(a=n)}a==k&&(clearInterval(c.h),w&&w())},30);a=a.data;b=this.Oa.list();a={id:a.id,name:a.name,lb:0};g=0;for(d=b.length;g<d;g++)b[g].id==a.id&&(a.lb=1);b=this.f.add(a);Ge(this.U[a.id],1);b&&Ge(this.U[b],0);this.s("Event_Collect","UP",this.f.list());break;case "DEL":if(a=a.id)this.f.hc(a),Ge(this.U[a],0);else for(b in this.f.clear(),this.U)Ge(this.U[b],0);this.s("Event_Collect","UP",
this.f.list());break;case "UP":this.dc=this.f.$(),this.zc=this.Oa.$()}};$.prototype.Md=function(a){var b=a.id;switch(a.kind){case "ADD":b&&(De(this.f,a.id,1),this.s("Event_Collect","UP",this.f.list()));break;case "DEL":if(b)De(this.f,a.id,0);else{a=this.f;for(var b=a.list(),c=0,d=b.length;c<d;c++)b[c].lb=0;a.k.set(a.key,ee(b),a.T,a.path,a.domain)}Fe(this);this.s("Event_Collect","UP",this.f.list())}};
$.prototype.Fd=function(){var a=n,b=this.f.$(),c=this.Oa.$(),d;clearTimeout(this.time);if(this.dc!=b){var a=k,b=this.f.map(),e;for(e in this.U)d=this.U[e],b[e]?Ge(d,1):Ge(d,0);this.dc=this.f.$()}this.zc!=c&&(a=k,Fe(this),this.zc=this.Oa.$());a&&this.s("Event_Collect","UP",this.f.list());this.time=setTimeout(z(this.Fd,this),1E3)};function Ge(a,b){var c;if(a)for(var d=0,e=a.length;d<e;d++)(c=a[d])&&c.Za!=b&&Be(c,b)}
function Fe(a){var b=a.f.list(),c,d;a.yd=a.Oa.map();for(var e=0,g=b.length;e<g;e++)c=b[e].id,d=0,a.yd[c]&&(d=1),De(a.f,c,d)}$.prototype.s=function(a,b,c){P.dispatchEvent({type:a,kind:b,data:c})};$.ua=function(){var a=new $;O(P,"Event_Record",z(a.Md,a));O(P,"Event_Collect",z(a.Nc,a));var b,c=sc("js-collect");a.Qc=a.f.map();for(var d=0;d<c.length;d++)b=new ze,b.start(c[d]),a.U[b.id]?a.U[b.id].push(b):a.U[b.id]=[b],a.Qc[b.id]&&Be(b,1),O(b,"Event_Collect",z(a.Nc,a));a.time=setTimeout(z(a.Fd,a),1E3)};
ma("baofeng.menu.init",$.ua);function He(){this.zb=[];this.Lb="";this.Ib=0;this.Gc=this.anchor=this.ja=this.list=this.defaultView=this.ec=this.rc=l;this.Wb='<li id="fav-{id}"><a title={title} class="his-reco" href="javascript:void(0);">{name}</a><a href="javascript:void(0);" class="{view} state">{lb}</a><span class="closed">\u5173\u95ed</span></li>'}A(He,V);p=He.prototype;p.P=function(a){this.ja=a;this.ec=T("his-cont");this.list=S("ul",j,this.ec)[0];this.rc=R("favoriteR");this.defaultView=T("his-none")};
p.q=function(){O(this.ja,"click",z(this.he,this));O(P,"Event_Collect",z(this.Ae,this));O(this.anchor,"mouseover",z(this.bb,this));O(this.anchor,"mouseout",z(this.bb,this));O(this.ja,"mouseover",z(this.bb,this));O(this.ja,"mouseout",z(this.bb,this))};p.bb=function(a){this.Gc&&clearTimeout(this.Gc);"mouseover"==a.type?this.show():this.Gc=setTimeout(z(this.t,this),80)};p.show=function(){for(var a=0;a<this.zb.length;a++)U(this.zb[a],n);U(this.ja,k)};p.t=function(){U(this.ja,n)};
p.he=function(a){var b=a.target.nodeName;if("SPAN"==b&&"closed"==a.target.className){var c=a.target.parentNode.id.replace("fav-","");this.s("Event_Collect","DEL",c)}if("A"==b&&(-1!=a.target.className.indexOf("empty")&&this.s("Event_Collect","DEL",""),-1!=a.target.className.indexOf("his-reco")||-1!=a.target.className.indexOf("state")))c=a.target.parentNode.id.replace("fav-",""),s.open("/play/"+c%500+"/play-"+c+".html","_blank")};
p.Ae=function(a){var b=a.data;"UP"==a.kind&&(this.zd(b),U(this.rc,0<this.Ib?k:n),this.rc.innerHTML=this.Ib+"",this.list.innerHTML=this.Lb,U(this.defaultView,0==this.list.children.length?k:n),U(this.ec,0==this.list.children.length?n:k),this.bc())};p.bc=function(){for(var a=0,b=this.list.children.length;a<b;a++){var c=this.list.children[a];O(c,"mouseover",z(this.Wa,this));O(c,"mouseout",z(this.Wa,this))}};
p.Wa=function(a){var b=a.currentTarget;"mouseover"==a.type&&this.C(a,b)?b.className="cur":"mouseout"==a.type&&this.C(a,b)&&(b.className="")};p.C=function(a,b){var c;c=a.type.toLowerCase();if("mouseover"==c)c=a.relatedTarget||a.fromElement;else if("mouseout"==c)c=a.relatedTarget||a.toElement;else return k;return c&&"xul"!=c.prefix&&!this.contains(b,c)&&c!==b};p.contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};
p.s=function(a,b,c){P.dispatchEvent({type:a,kind:b,id:c})};p.zd=function(a){this.Lb="";this.Ib=0;for(var b=a.length-1;0<=b;b--){var c=a[b],d=this.Wb,e;for(e in c){var g=c[e];"lb"==e&&(d=d.replace("{view}",1==g?"old":"new"),g=1==g?"\u5df2\u770b":"\u672a\u89c2\u770b");d=d.replace("{"+e+"}",g)}d=d.replace("{title}",c.name);this.Lb+=d;0==c.lb&&this.Ib++}};function Ie(a){try{var b;if(!cc&&!("Win64"==Da||-1!=za().indexOf("Trident")&&/11\.(.)*/.test(Ha))){var c,d=s.navigator.plugins;if(d&&0<d.length)for(var e=0;e<d.length;e++){if(d[e][0].type.match("application/baofengwebplayer-plugin")){c=document.createElement("embed");c.type="application/baofengwebplayer-plugin";c.width="1";c.height="1";document.body.appendChild(c);cc=c;break}}else try{cc=new ActiveXObject("StormAxPlayer.Player")}catch(g){}}b=cc;if(b)var h=b.GetUserId();else f(Error());if(t(h)&&"undefined"!=
h&&(h=h.substr(1).substr(0,h.length-2),t(h)&&"undefined"!=h)){var m=new Fb(s.document);m.set("uid",h,7776E3,"/",".baofeng.com")}}catch(q){m=new Fb(s.document),h=m.get("uid"),t(h)&&("undefined"!=h&&""!=h)&&m.get("uid")}W(new xe,R("searchPane"));b=new He;b.anchor=R("viewFavoriteButton");c=R("searchRecommend");Ac(c)&&b.zb.push(c);c=R("viewRecordPane");Ac(c)&&b.zb.push(c);W(b,R("viewFavoritePanel"));b=new ue;c=qe.$a();b.Sa=c;b.Bc(R("viewRecordButton"));b.sb(R("searchRecommend"));b.sb(R("viewFavoritePanel"));
W(b,R("viewRecordPane"));b=T("play-nave-guide");var w=T("play-nave-list");Ac(b)&&Ac(w)&&(c=new te,c.Bc(b),c.o=w,c.$b="play-nave-guide-on",c.sb(R("searchRecommend")),c.q());b=T("hd-load-text");c=T("hd-load-con");Ac(b)&&Ac(c)&&(new ve({anchor:b,content:c,expandAnchorClass:"hd-load-text-on"})).q();$.ua();if(a&&42<a){var r=T("play-page"),B=R("viewRecordPane"),N=R("searchRecommend");O(s,"scroll",function(){var a=s.document.documentElement.scrollTop||s.document.body.scrollTop;42<a&&650>a?(Ac(w)&&U(w,n),
U(B,n),U(N,n),U(r,n)):U(r,k)},n,this)}}ma("baofeng.header.init",Ie);function Je(a,b){var c=l,d=l;a.ac[b]&&(d=a.N.ea[b],c=new Sd,c.Jb="play-arrow-l",c.Qb="play-arrow-r",c.xb="art-poster-roll-list",c.jb=1,c.time=9E3,c.pd=400,c.Ia=n,c.gb=n,W(c,d),a.ac[b]=n)}
ma("hd.man",function(a,b){this.N=this.map=l;this.ac=[];Ie();if(this.Wc=R("FocusMap"))this.map=new wd,this.map.Ba=b,this.map.Wb=this.map.He,W(this.map,this.Wc);var c=new Vc,d=R("week"),e=(new Date).getDay();c.Lc="week-resource-menu";c.Kc="week-tab-con";c.Ea="cur";c.ba=n;c.l="mouseover";Wc(c,T("week-tab-con",d));W(c,d);c.dispatchEvent({type:"Event_SetIndex",index:e});if("zYi"==a){var g=this,c=T("hot-resource");this.N=new Vc;this.N.Lc="mic-video-menu";this.N.Kc="mic-video-topic";this.N.Ea="cur";this.N.l=
"mouseover";Wc(this.N,T("mic-video-topic",c));W(this.N,c);for(c=0;c<this.N.ea.length;c++)this.ac.push(k);Je(this,0);O(this.N,"Event_UpPage",function(a){Je(g,a.index)})}this.ue=new Ud;this.ue.start()});})();
