//www.hc128.cn
function changeButtn(){if(navigator.userAgent.match(/android/i)){var a=$("p.pBottom");a.attr("noplay")&&a.html('<span class="sBtn"><a href="http://app.2345.cn/appmovie/2345ysxq.apk" class="downloadBtn">\u5ba2\u6237\u7aef\u89c2\u770b</a></span>')}}changeButtn();
function showDownLoad(){if(void 0!=$.cookie){if($.cookie("showdownload"))return!1;var a=window.location.href;if(a.match(/from=daohang/i)||a.match(/\/\d+(\.html)?/i)||a.match(/zy_\d+/i)||a.match(/juqing/i)||a.match(/feedback/i)||a.match(/search\.php/i)||a.match(/\/login/i))return!1;navigator.userAgent.match(/android/i)&&$.ajax({url:"http://dianying.v.lyaoyu.cn/moviecore/server/mversion/index.php?ctl=guide&callId=?"})}}showDownLoad();
function setGuideInfo(a,b,c){$(".downLoadPopB")[0]&&(a&&$(".downLoadPopB .blueBtn").attr("href",a),b&&$(".downLoadPopB").css("background-image","url(http://img.lyaoyu.cn"+b+")"),c&&$(".downLoadPopB").css("background-color",c),$(".downLoadPopB").show(),$("body").css("overflow","hidden"),$.cookie("showdownload",1,{path:"/",domain:"v.lyaoyu.cn",secure:!1}))}
function forget(a){$(a).hasClass("iCheckedIcon")?($(a).removeClass("iCheckedIcon"),a=new Date,a.setTime(a.getTime()-1),$.cookie("showdownload","",{expires:a,path:"/",domain:"v.lyaoyu.cn"})):($(a).addClass("iCheckedIcon"),$.cookie("showdownload",1,{path:"/",domain:"v.lyaoyu.cn",secure:!1}))}function jump(){closeDownLoad()}function closeDownLoad(){$(".downLoadPopB").hide().remove();$("body").scroll(0,0);$("body").css("overflow","")}
function toggleIntro(){var a=$(".pIntroTxt").html();$(".pIntroTxt").html($("#hidden_intro").val());$("#hidden_intro").val(a)}
var userLogedFav=!1,PLAYHREF="",shoucang={opt:{},init:function(a,b,c){document.domain="v.lyaoyu.cn";this.opt._channel=a;this.opt._id=b;this.opt._title=escape(c);this.bindFavBtn();a&&b&&this.dealFav("readFav")},showTips:function(){if($(".aCollectBtn .emTips")[0])if($.cookie("shoucang_tips_hide"))$(".aCollectBtn .emTips").hide();else{$(".aCollectBtn .emTips").show();var a=[];a.expires=365;a.path="/";a.domain="v.lyaoyu.cn";$.cookie("shoucang_tips_hide","1",a)}},bindAddToplayFav:function(){var a=this;
$(".aPlayBtn").click(function(){a.dealPlayFav(this)})},bindAddEpisodePlayFav:function(){var a=this;$(".ulNumList li a").each(function(b,c){$(c).click(function(){a.dealPlayFav(c)})})},dealPlayFav:function(a){PLAYHREF=$(a).attr("data-href");if($.cookie("uid")&&$.cookie("passid")&&$(a).attr("data-id")&&$(a).attr("data-api")&&$(a).attr("data-type")){var b=$(a).attr("data-id"),c=$(a).attr("data-api"),d=$(a).attr("data-type");a=$(a).attr("data-episode");$.ajax({url:"http://v.lyaoyu.cn/moviecore/server/mversion/user/index.php?act=addHistory&callId=?",
data:{id:b,type:d,api:c,epiId:a,callback:"shoucang.playFavCallback"}});return!1}PLAYHREF&&(location.href=PLAYHREF)},playFavCallback:function(a){PLAYHREF&&(location.href=PLAYHREF);return!0},dealUserFav:function(a){var b=this;switch(a){case "clickFav":b.opt._act="addCollect";break;case "cancelFav":b.opt._act="delCollect";break;case "readFav":b.opt._act="isCollect"}var b=this,c=b.opt._channel?b.opt._channel:0;if(c){"clickFav"!=a&&"cancelFav"!=a||_dct_("m_detail_"+c+"_shoucang");switch(c){case "dy":c=
1;break;case "tv":c=2;break;case "dm":c=3;break;case "zy":c=4}$.ajax({url:"http://v.lyaoyu.cn/moviecore/server/mversion/user/index.php?channel=collect&act="+b.opt._act+"&callId=?",data:{id:b.opt._id,type:c,callback:"shoucang.favCallback"}})}},favCallback:function(a){if(!a)return alert("\u670d\u52a1\u5668\u6682\u65f6\u672a\u54cd\u5e94\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5");if(1===parseInt(a.code)){a="collectBtn";var b="collectBtnCur";$("."+a)[0]||(a="favoriteBtn",b="cur");switch(this.opt._act){case "addCollect":$("."+
a).addClass(b);$("."+a).html('<i class="iIcon"></i>\u5df2\u6536\u85cf');break;case "delCollect":$("."+a).removeClass(b);$("."+a).html('<i class="iIcon"></i>\u6536\u85cf');break;case "isCollect":$("."+a).addClass(b),$("."+a).html('<i class="iIcon"></i>\u5df2\u6536\u85cf')}}else 2===parseInt(a.code)&&"isCollect"!==this.opt._act&&alert("\u64cd\u4f5c\u5931\u8d25\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5")},dealFav:function(a,b,c,d){var e=this.opt._channel||b;if(b&&!$.cookie("name_ie"))!$(".loginPop")[0]||navigator.userAgent.match(/android 2\.3/i)||
navigator.userAgent.match(/android\/2\.3/i)?confirm("\u60a8\u8fd8\u672a\u767b\u5f55\uff0c\u662f\u5426\u9a6c\u4e0a\u767b\u5f55\uff1f")&&(location.href="m.v.lyaoyu.cnlogin/"):this.showLogin();else{if($.cookie("name_ie")&&-1!=="dy,tv,zy,dm".indexOf(e)&&-1!=="clickFav,cancelFav,readFav".indexOf(a))return this.dealUserFav(a);b=this.opt._id||c;d=this.opt._title||d;c=this.opt._src||"";var f=$("#favIframe");f[0]||($('<iframe id="favIframe">').appendTo(document.head).hide(),f=$("#favIframe"));c||(c="m.v.lyaoyu.cnstorageHead.html?",
a&&(c+="action="+a),e&&b&&(c=c+("&key="+e+"_"+b)+("&fav="+e+"_"+b)),d&&(c+="&title="+d));f.attr({src:c});a&&f.ready(function(){setTimeout(function(){f[0].parentNode.removeChild(f[0])},500)})}},showLogin:function(){isCrossLogin=!0;muser.showMsg("","");window.scroll(0,0);$("#mask_box").show();$(".loginPop").show()},bindFavBtn:function(){var a=this,b="collectBtn";$("."+b)[0]||(b="favoriteBtn");$("."+b).click(function(){var b=$(this).attr("type"),d=$(this).attr("class");b&&(d.match(/cur/)||d.match(/collectBtnCur/)?
a.dealFav("cancelFav",!0):a.dealFav("clickFav",!0))})}};$(".tabNav").delegate("li","click",function(a){$(".tabNav li").find("span").removeClass("cur");$(this).find("span").addClass("cur");a=$(this).index();$("div.tabCon").hide().eq(a).show()});
if($("#juji")[0]){var isShow=function(){var a=$("#juji").width();document.documentElement.clientWidth<a?($("#juji2").removeClass("numListWid"),$("#juji2").addClass("numListWid")):$("#juji2").removeClass("numListWid")},width=$("#juji").width()+30;$("#juji2 .conBox ").css({width:width});var indexMenu2=new iScroll("juji2",{hScroll:!0,vScroll:!1,bounce:!1,momentum:!0});$(window).on("resize",function(){$("#juji2 .conBox ").css({width:""});var a=$("#juji").width()+30;$("#juji2 .conBox ").css({width:a});
indexMenu2.refresh();isShow()});isShow();$(function(){$(window).scroll(function(){var a=$(".numListBox").offset().top,b=$(this).scrollTop();b>a&&!$("#juji2").hasClass("fixBox")?$("#juji2").addClass("fixBox"):b<a&&$("#juji2").hasClass("fixBox")&&$("#juji2").removeClass("fixBox")})})}function clickCur(a){$(a).removeClass("cur");$(a).parent().siblings().find("a").addClass("cur")}
function historyBack(){var a=getDelCookie();a?window.location.href=a:(a=document.referrer)&&(0==a.indexOf("action")||a.indexOf(".v.lyaoyu.cn/m/"))?history.back():window.location.href="m.v.lyaoyu.cn"}getDelCookie();
function getDelCookie(){var a="";if(0<document.cookie.length){var b=document.cookie.indexOf("m_list_referer=");-1!=b&&(b+=15,a=document.cookie.indexOf(";",b),-1==a&&(a=document.cookie.length),a=unescape(document.cookie.substring(b,a)))}b=window.location.href;-1===b.indexOf("/m/detail/")&&-1===b.indexOf("/m/zy_")&&-1===b.indexOf("/m/dm/")&&(b=new Date,b.setTime(b.getTime()-1E4),document.cookie="m_list_referer=0;expires="+b.toGMTString()+";path=/;domain=.v.lyaoyu.cn;");return a}
function _dct_(a){var b;b="http://union2.50bang.org/web/ajax35?uId2=SPTNPQRLSX&r="+encodeURIComponent(document.referrer);b+="&fBL="+screen.width+"*"+screen.height;b+="&lO="+encodeURIComponent(a);$.ajax({type:"get",url:b});return!0}function resizeImgCommon(a){a=a||"resize_list";var b=$("#"+a).width();height=$("#"+a).height();b=parseInt(.31999*b);height=parseInt(b/195*260);$("#"+a+" img").css({width:b,height:height});"resize_list"==a&&$("#"+a+" a").css({width:b,height:height})}
$("#resize_list").length&&(resizeImgCommon(),$(window).on("resize",function(){resizeImgCommon()}));
if($("#nav_menu")[0]){width=$(".subNav p").width()+30;$("#nav_menu .con").css({width:width});var indexMenu=new iScroll("nav_menu",{hScroll:!0,vScroll:!1,bounce:!0,momentum:!0});$(window).on("resize",function(){$("#nav_menu .con").css({width:""});var a=$(".subNav p").width()+30;$("#nav_menu .con").css({width:a});indexMenu.refresh()});if($("#nav_menu a.cur")[0]){var screenWidth=$(".headerbar").width(),left=$("#nav_menu a.cur").offset().left,scrollLeft=parseInt(screenWidth-left);30>scrollLeft&&indexMenu.scrollTo(-screenWidth)}}
$(".aSearch")[0]&&$(".aSearch").click(function(a){$("#index_menu_box").hide();$(".index_menu_top").hide();$(".ulHotList").hide();$(".loginPop").hide();$(".headRight a").removeClass("cur");"none"==$("#search_box").css("display")?($("html,body").css({"overflow-y":"hidden"}),$(".aSearch").addClass("cur"),$("#mask_box").show(),$("#search_box").show(),$("#hot_word_box").show(),$(".searchTxt").focus()):(searchM.addCurClass(),$("html,body").css({"overflow-y":""}),$("#hot_word_box").hide(),$("#search_box").hide(),
$("#mask_box").hide())});
$(".aNav")[0]&&$(".aNav").click(function(){$(".searchForm")[0]||$("#search_box").hide();$(".ulHotList")[0]&&$(".ulHotList").hide();$(".loginPop").hide();$(".headRight a").removeClass("cur");if($(".index_menu_top")[0])if($("#mask_box").hide(),"none"==$(".index_menu_top").css("display")){$(".index_menu_top").show();$("#nav_menu .con").css({width:""});var a=$(".subNav p").width()+30;$("#nav_menu .con").css({width:a});indexMenu.refresh()}else searchM.addCurClass(),$(".index_menu_top").hide();else"none"==
$("#index_menu_box").css("display")?($("html,body").css({"overflow-y":"hidden"}),$(".aNav").addClass("cur"),$("#mask_box").show(),$("#index_menu_box").show()):(searchM.addCurClass(),$("html,body").css({"overflow-y":"auto"}),$("#index_menu_box").hide(),$("#mask_box").hide())});
if($("#search_menu")[0]){width=$(".searchNav p").width()+30;$("#search_menu .con").css({width:width});var searchMenu=new iScroll("search_menu",{hScroll:!0,vScroll:!1,bounce:!0,momentum:!0});$(window).on("resize",function(){$("#search_menu .con").css({width:""});var a=$(".searchNav p").width()+30;$("#search_menu .con").css({width:a});searchMenu.refresh()});if($("#search_menu a.cur")[0]){var screenWidth=$(".headerbar").width(),leftWidth=$("#search_menu a.cur").offset().left,aWidth=$("#search_menu a.cur").width(),
scrollLeft=parseInt(screenWidth-leftWidth-aWidth);5>scrollLeft&&searchMenu.scrollTo(-screenWidth)}}
var searchM={isScrolled:0,curIndex:!1,init:function(){if($("#search_box")){var a=this;a.getHotWord();a.getHistory();a.dealInput();a.searchPage();a.addHistory();a.getCurIndex();a.hideAll();$(".searchBtn")[0]&&$(".searchBtn").click(function(){a.submitSearch()})}},getCurIndex:function(){var a=this;$(".headRight")[0]&&$(".headRight a").each(function(){-1!==$(this).attr("class").indexOf("cur")&&(a.curIndex=$(this).index())})},addCurClass:function(){this.curIndex&&$($(".headRight a")[this.curIndex]).addClass("cur")},
hideAll:function(){var a=this;$("#search_main")[0]&&$(document).click(function(a){"search_box"!=a.target.id&&"search_form"!=a.target.id&&"searchTxt"!=a.target.className&&"clearSearchBtn"!=a.target.parentNode.className&&$("#search_history_list").hide()});$("#mask_box").click(function(){$(".headRight a").removeClass("cur");$("#hot_word_box").hide();!$("#search_main")[0]&&$("#search_box").hide();$("#mask_box").hide();$(".loginPop").hide();$("#index_menu_box").hide();$(".index_menu_top").hide();$("html,body").css({"overflow-y":""});
a.addCurClass()})},submitSearch:function(){var a=$(".searchTxt").val();return""!=a.replace(/\s*/g,"")&&"\u8bf7\u8f93\u5165\u5f71\u7247\u6216\u6f14\u5458..."!=a?($("#search_form").submit(),!0):!1},dealInput:function(){var a=$(".searchTxt");""!=a.val()&&("\u8bf7\u8f93\u5165\u5f71\u7247\u6216\u6f14\u5458..."==a.val()?a.addClass("searchTxtBlur"):$(".clearSearchBtn").show());a.focus(function(){"\u8bf7\u8f93\u5165\u5f71\u7247\u6216\u6f14\u5458..."==a.val()&&($(this).val(""),$(this).removeClass("searchTxtBlur"),
$(".clearSearchBtn").hide());""!=$(".ulHotList").html()&&($("#hot_word_box").hide(),$(".ulHotList").show())}).blur(function(){""==a.val()&&($(this).val("\u8bf7\u8f93\u5165\u5f71\u7247\u6216\u6f14\u5458..."),$(this).addClass("searchTxtBlur"))});$(window).keyup(function(){""!=a.val()?$(".clearSearchBtn").show():$(".clearSearchBtn").hide()});$(".clearSearchBtn").click(function(){$(".searchTxt").val("");$(this).hide();$(".searchTxt").focus()})},dealHistory:function(a,b,c){var d="historyIframe_"+a,e=$("#"+
d);e[0]||($('<iframe id="'+d+'">').appendTo(document.head),e=$("#"+d));a="m.v.lyaoyu.cnstorageHead.html?action=search_"+a;b&&(a+="&key="+b);c&&(a+="&keyword="+escape(c));e.attr({src:a});e.ready(function(){setTimeout(function(){e[0].parentNode.removeChild(e[0])},500)})},addHistory:function(){if($(".searchTxt")[0]){var a=$(".searchTxt").val();if(""!=a.replace(/\s*/g,"")&&"\u8bf7\u8f93\u5165\u5f71\u7247\u6216\u6f14\u5458..."!=a){var b=(new Date).getTime(),a=this.html2Escape(a);this.dealHistory("add",
b,a)}}},getHistory:function(){document.domain="v.lyaoyu.cn";this.dealHistory("list")},bindHistoryEvent:function(){$("#search_history_list a").click(function(){"aClearBtn"!=$(this).attr("class")&&"aCloseBtn"!=$(this).attr("class")&&($(".searchTxt").removeClass("searchTxtBlur"),$(".searchTxt").val($(this).attr("data-keyword")),$("#search_form").submit());$(".ulHotList").hide()});$(".aCloseBtn").click(function(){$(".ulHotList").hide();$("#hot_word_box")[0]&&$("#hot_word_box").show()});$(".aClearBtn").click(function(){$(".ulHotList").hide();
$(".ulHotList").html("");searchM.dealHistory("clear")})},getHotWord:function(){if(!$(".searchForm")[0]&&"undefined"!=typeof hotword_mobile)if(hotword_mobile&&hotword_mobile.length){if(""==$("#hot_word_box").html()){var a=['<span class="sTit">\u70ed\u641c\u8bcd</span>'],b;for(b in hotword_mobile)a.push('<a href="'+hotword_mobile[b].url+'" target="_blank" title="'+hotword_mobile[b].title+'" style="color:'+hotword_mobile[b].color+';">'+hotword_mobile[b].title+"</a>");$("#hot_word_box").html(a.join(""))}$("#hot_word_box").show()}else $("#hot_word_box").hide()},
searchPage:function(){$("#search_main")[0]&&this.bindScroll()},bindScroll:function(){var a=this;$(window).scroll(function(){var b=parseInt($("#page_more").attr("data-total")),c=parseInt($("#page_more").attr("data-page")),d=$(this).scrollTop();30>=$(".wrapper").height()-d-$(document).height()&&!a.isScrolled&&b>=c&&a.nextPage()})},nextPage:function(a){a=$("#page_more");var b=this;b.isScrolled=1;var c=$(a).attr("data-page");if(!c)return!1;$("#loading_more").show();var d=a.attr("data-url");$.ajax({url:d,
data:{page:c,is_ajax:1},type:"get",charset:"gb2312",success:function(e){if(e){var d=eval("("+e+")");e=b.createHtml(d.list);d=d.page_num;$("#loading_more").hide();$("#data_list").append(e);e=parseInt(c)+1;e<=d&&($(a).attr("data-page",e),b.isScrolled=0)}}})},createHtml:function(a){if(a){var b=[],c;for(c in a){var d="m_so_pic_";b.push('<li><div class="pic">');"\u7535\u89c6\u5267"==a[c].cntype?d+="tv":"\u7535\u5f71"==a[c].cntype?d+="dy":"\u7efc\u827a\u8282\u76ee"==a[c].cntype?d+="zy":"\u52a8\u6f2b"==
a[c].cntype&&(d+="dm");b.push('<a href="'+a[c].detail_surl+'" onclick="_dct_(\''+d+'\');" target="_self" rel="nofollow">');b.push('<img src="'+a[c].img+'" onerror="nofind(this);" alt="">');b.push('<span class="sStyle">'+a[c].cntype.replace("\u8282\u76ee","")+"</span>");"\u7535\u5f71"==a[c].cntype&&b.push('<span class="sDes">'+a[c].duration+"</span>");b.push("</a></div>");b.push('<div class="txt');a[c].play_link&&a[c].play_link.list||b.push(" txtHeight");b.push('"><span class="sTit">'+a[c].title2+
"</span>");"\u7535\u89c6\u5267"==a[c].cntype?b.push(this.tvHtml(a,c)):"\u7535\u5f71"==a[c].cntype?b.push(this.dyHtml(a,c)):"\u7efc\u827a\u8282\u76ee"==a[c].cntype?b.push(this.zyHtml(a,c)):"\u52a8\u6f2b"==a[c].cntype&&b.push(this.dmHtml(a,c));b.push("</div></li>")}return b.join("")}},tvHtml:function(a,b){var c=[];a[b].actor&&c.push('<span class="sDes"><em class="emTit">\u4e3b\u6f14\uff1a</em>'+a[b].actor+"</span>");c.push('<span class="sDes">'+a[b].latests+"</span>\r\n");if(a[b].play_link&&a[b].play_link.list){c.push('<p class="playList clearfix">');
var d=a[b].play_link.list,e;for(e in d)c.push('<span><a href="'+d[e]+'"'),7<a[b].play_link.num&&3==e?(c.push(" onclick=\"_dct_('m_so_all_tv');\" "),c.push(' target="_self"')):(a[b].click_code&&(a[b].click_from?c.push(" onclick=\"_dct_('"+a[b].click_code+"_"+(parseInt(e)+1)+"');_dct_('"+a[b].click_from+"');\""):c.push(" onclick=\"_dct_('"+a[b].click_code+"_"+(parseInt(e)+1)+"');\"")),c.push(' target="_blank"')),c.push(' rel="nofollow">'),7<a[b].play_link.num&&3==e?c.push("..."):c.push(parseInt(e)+
1),parseInt(a[b].play_link.count)-1==e&&c.push('<i class="iNew"></i>'),c.push("</a></span>");7<a[b].play_link.num&&c.push('<span><a href="'+a[b].detail_surl+'" onclick="_dct_(\'m_so_all_tv\');" target="_self">\u5168\u90e8</a></span>');c.push("</p>")}else c.push('<p class="pBottom"><span class="sBtn"><a href="javascript:void(0);" class="aPlayBtn noPlayBtn" rel="nofollow">\u6682\u65e0\u64ad\u653e\u6e90</a></span></p>');return c.join("")},dyHtml:function(a,b){var c=[];a[b].actor&&c.push('<span class="sDes"><em class="emTit">\u4e3b\u6f14\uff1a</em>'+
a[b].actor+"</span>");a[b].score&&c.push('<span class="sDes"><em class="emTit">\u8bc4\u5206\uff1a</em>'+a[b].score+"\u5206</span>");c.push('<p class="pBottom">');c.push('<span class="sBtn">');c.push("<a ");a[b].play_link?(c.push('href="'+a[b].play_link.replace("Attp://","http://")+'" '),a[b].click_code&&(a[b].click_from?c.push("onclick=\"_dct_('"+a[b].click_code+"');_dct_('"+a[b].click_from+"');\" "):c.push("onclick=\"_dct_('"+a[b].click_code+"');\" "))):c.push('href="javascript:void(0);" ');c.push('target="_self" ');
a[b].play_link?a[b].is_preview?c.push('class="aPlayBtn comingBtn" '):c.push('class="aPlayBtn" '):c.push('class="aPlayBtn noPlayBtn" ');c.push('rel="nofollow">');a[b].play_link?a[b].is_preview?c.push("\u9884\u544a\u7247"):c.push("\u7acb\u5373\u64ad\u653e"):c.push("\u6682\u65e0\u64ad\u653e\u6e90");c.push("</a></span></p>");return c.join("")},zyHtml:function(a,b){var c=[];c.push('<span class="sDes">\u66f4\u65b0\u81f3'+a[b].latests+"</span>");if(a[b].play_link&&a[b].play_link.list){c.push('<p class="playList playListTwo clearfix">');
var d=a[b].play_link.list,e;for(e in d)c.push('<span><a href="'+d[e].url+'"'),a[b].click_code&&(a[b].click_from?c.push(" onclick=\"_dct_('"+a[b].click_code+"_"+(parseInt(e)+1)+"');_dct_('"+a[b].click_from+"');\""):c.push(" onclick=\"_dct_('"+a[b].click_code+"_"+(parseInt(e)+1)+"');\"")),c.push(' target="_blank" rel="nofollow">'),c.push(d[e].issue),d[e].is_new&&c.push('<i class="iNew"></i>'),c.push("</a></span>");3<a[b].play_link.num&&c.push('<span><a href="'+a[b].detail_surl+'" onclick="_dct_(\'m_so_all_zy\');" target="_self">\u5168\u90e8</a></span>');
c.push("</p>")}else c.push('<p class="pBottom"><span class="sBtn"><a href="javascript:void(0);" class="aPlayBtn noPlayBtn" rel="nofollow">\u6682\u65e0\u64ad\u653e\u6e90</a></span></p>');return c.join("")},dmHtml:function(a,b){var c=[];c.push('<span class="sDes">'+a[b].latests+"</span>");if(a[b].play_link&&a[b].play_link.list){c.push('<p class="playList clearfix">');var d=a[b].play_link.list,e;for(e in d){c.push('<span><a href="'+d[e]+'"');var f=0;7<a[b].play_link.num&&3==e&&(f=1);a[b].click_code&&
(f?c.push(" onclick=\"_dct_('m_so_all_dm');\" "):a[b].click_from?c.push(" onclick=\"_dct_('"+a[b].click_code+"_"+(parseInt(e)+1)+"');_dct_('"+a[b].click_from+"');\""):c.push(" onclick=\"_dct_('"+a[b].click_code+"_"+(parseInt(e)+1)+"');\""));c.push(' target="_blank" rel="nofollow">');f?c.push("..."):c.push(parseInt(e)+1);c.push("</a></span>")}7<a[b].play_link.num&&c.push('<span><a href="'+a[b].detail_surl+'" onclick="_dct_(\'m_so_all_dm\');" target="_self">\u5168\u90e8</a></span>');c.push("</p>")}else c.push('<p class="pBottom"><span class="sBtn"><a href="javascript:void(0);" class="aPlayBtn noPlayBtn" rel="nofollow">\u6682\u65e0\u64ad\u653e\u6e90</a></span></p>');
return c.join("")},html2Escape:function(a){return a.replace(/[<>&"]/g,function(a){return{"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;"}[a]})}};searchM.init();$(window).scroll(function(){100<$(this).scrollTop()?$(".fixedBtnList").show():$(".fixedBtnList").hide()});$(".aFeedBack").click(function(){var a=escape(window.location.href),a=$(this).attr("href")+"?from="+a;$(this).attr("href",a)});
var topDownload={init:function(){navigator.userAgent.match(/android/i)&&($(".appDownLoad").show(),this.bindClose())},bindClose:function(){$("#closeTopDownload").click(function(){$(".appDownLoad").hide()})}};$(".appDownLoad")[0]&&topDownload.init();